// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: adjudication_rules.sql

package db

import (
	"context"
	"encoding/json"

	uuid "github.com/google/uuid"
)

const createAdjudicationRule = `-- name: CreateAdjudicationRule :one
INSERT INTO adjudication_rules (name, rule_type, parameters, priority, is_active)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, rule_type, parameters, priority, is_active, created_at, updated_at
`

type CreateAdjudicationRuleParams struct {
	Name       string          `json:"name"`
	RuleType   string          `json:"rule_type"`
	Parameters json.RawMessage `json:"parameters"`
	Priority   int32           `json:"priority"`
	IsActive   bool            `json:"is_active"`
}

func (q *Queries) CreateAdjudicationRule(ctx context.Context, arg CreateAdjudicationRuleParams) (AdjudicationRule, error) {
	row := q.db.QueryRow(ctx, createAdjudicationRule,
		arg.Name,
		arg.RuleType,
		arg.Parameters,
		arg.Priority,
		arg.IsActive,
	)
	var i AdjudicationRule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RuleType,
		&i.Parameters,
		&i.Priority,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAdjudicationRule = `-- name: DeleteAdjudicationRule :exec
DELETE FROM adjudication_rules WHERE id = $1
`

func (q *Queries) DeleteAdjudicationRule(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAdjudicationRule, id)
	return err
}

const getAdjudicationRuleByID = `-- name: GetAdjudicationRuleByID :one
SELECT id, name, rule_type, parameters, priority, is_active, created_at, updated_at FROM adjudication_rules WHERE id = $1
`

func (q *Queries) GetAdjudicationRuleByID(ctx context.Context, id uuid.UUID) (AdjudicationRule, error) {
	row := q.db.QueryRow(ctx, getAdjudicationRuleByID, id)
	var i AdjudicationRule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RuleType,
		&i.Parameters,
		&i.Priority,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveAdjudicationRules = `-- name: ListActiveAdjudicationRules :many
SELECT id, name, rule_type, parameters, priority, is_active, created_at, updated_at FROM adjudication_rules WHERE is_active = TRUE ORDER BY priority ASC
`

func (q *Queries) ListActiveAdjudicationRules(ctx context.Context) ([]AdjudicationRule, error) {
	rows, err := q.db.Query(ctx, listActiveAdjudicationRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdjudicationRule{}
	for rows.Next() {
		var i AdjudicationRule
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.RuleType,
			&i.Parameters,
			&i.Priority,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdjudicationRules = `-- name: ListAdjudicationRules :many
SELECT id, name, rule_type, parameters, priority, is_active, created_at, updated_at FROM adjudication_rules ORDER BY priority ASC LIMIT $1 OFFSET $2
`

type ListAdjudicationRulesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAdjudicationRules(ctx context.Context, arg ListAdjudicationRulesParams) ([]AdjudicationRule, error) {
	rows, err := q.db.Query(ctx, listAdjudicationRules, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdjudicationRule{}
	for rows.Next() {
		var i AdjudicationRule
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.RuleType,
			&i.Parameters,
			&i.Priority,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAdjudicationRule = `-- name: UpdateAdjudicationRule :one
UPDATE adjudication_rules
SET name = $2, rule_type = $3, parameters = $4, priority = $5, is_active = $6, updated_at = NOW()
WHERE id = $1
RETURNING id, name, rule_type, parameters, priority, is_active, created_at, updated_at
`

type UpdateAdjudicationRuleParams struct {
	ID         uuid.UUID       `json:"id"`
	Name       string          `json:"name"`
	RuleType   string          `json:"rule_type"`
	Parameters json.RawMessage `json:"parameters"`
	Priority   int32           `json:"priority"`
	IsActive   bool            `json:"is_active"`
}

func (q *Queries) UpdateAdjudicationRule(ctx context.Context, arg UpdateAdjudicationRuleParams) (AdjudicationRule, error) {
	row := q.db.QueryRow(ctx, updateAdjudicationRule,
		arg.ID,
		arg.Name,
		arg.RuleType,
		arg.Parameters,
		arg.Priority,
		arg.IsActive,
	)
	var i AdjudicationRule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RuleType,
		&i.Parameters,
		&i.Priority,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
