// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: analytics.sql

package db

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const getApprovalRate = `-- name: GetApprovalRate :one
SELECT (
    CASE WHEN COUNT(*) > 0
        THEN (COUNT(CASE WHEN status IN ('APPROVED', 'PAID') THEN 1 END) * 100 / COUNT(*))
        ELSE 0
    END
)::bigint as approval_rate
FROM claims
WHERE status NOT IN ('RECEIVED', 'VALIDATED')
  AND created_at >= $1 AND created_at <= $2
`

type GetApprovalRateParams struct {
	StartDate time.Time `json:"start_date"`
	EndDate   time.Time `json:"end_date"`
}

func (q *Queries) GetApprovalRate(ctx context.Context, arg GetApprovalRateParams) (int64, error) {
	row := q.db.QueryRow(ctx, getApprovalRate, arg.StartDate, arg.EndDate)
	var approval_rate int64
	err := row.Scan(&approval_rate)
	return approval_rate, err
}

const getAverageTAT = `-- name: GetAverageTAT :one
SELECT
    COALESCE(AVG(EXTRACT(EPOCH FROM (updated_at - created_at)) / 3600), 0) as avg_tat_hours
FROM claims
WHERE status IN ('APPROVED', 'REJECTED', 'PAID')
  AND created_at >= $1 AND created_at <= $2
`

type GetAverageTATParams struct {
	StartDate time.Time `json:"start_date"`
	EndDate   time.Time `json:"end_date"`
}

func (q *Queries) GetAverageTAT(ctx context.Context, arg GetAverageTATParams) (interface{}, error) {
	row := q.db.QueryRow(ctx, getAverageTAT, arg.StartDate, arg.EndDate)
	var avg_tat_hours interface{}
	err := row.Scan(&avg_tat_hours)
	return avg_tat_hours, err
}

const getClaimsVolume = `-- name: GetClaimsVolume :one
SELECT
    COUNT(*) as total_claims,
    COUNT(CASE WHEN status = 'APPROVED' THEN 1 END) as approved_claims,
    COUNT(CASE WHEN status = 'REJECTED' THEN 1 END) as rejected_claims,
    COUNT(CASE WHEN status = 'MANUAL_REVIEW' THEN 1 END) as manual_review_claims,
    COUNT(CASE WHEN status IN ('PAID', 'PART_PAID') THEN 1 END) as paid_claims
FROM claims
WHERE created_at >= $1 AND created_at <= $2
`

type GetClaimsVolumeParams struct {
	StartDate time.Time `json:"start_date"`
	EndDate   time.Time `json:"end_date"`
}

type GetClaimsVolumeRow struct {
	TotalClaims        int64 `json:"total_claims"`
	ApprovedClaims     int64 `json:"approved_claims"`
	RejectedClaims     int64 `json:"rejected_claims"`
	ManualReviewClaims int64 `json:"manual_review_claims"`
	PaidClaims         int64 `json:"paid_claims"`
}

func (q *Queries) GetClaimsVolume(ctx context.Context, arg GetClaimsVolumeParams) (GetClaimsVolumeRow, error) {
	row := q.db.QueryRow(ctx, getClaimsVolume, arg.StartDate, arg.EndDate)
	var i GetClaimsVolumeRow
	err := row.Scan(
		&i.TotalClaims,
		&i.ApprovedClaims,
		&i.RejectedClaims,
		&i.ManualReviewClaims,
		&i.PaidClaims,
	)
	return i, err
}

const getDocumentStats = `-- name: GetDocumentStats :one
SELECT
    COUNT(*) as total_documents,
    COUNT(CASE WHEN status = 'ACTIVE' THEN 1 END) as active_documents,
    COUNT(CASE WHEN status = 'PENDING_UPLOAD' THEN 1 END) as pending_documents,
    COUNT(CASE WHEN status = 'UPLOAD_FAILED' THEN 1 END) as failed_documents
FROM documents
WHERE deleted_at IS NULL
  AND created_at >= $1 AND created_at <= $2
`

type GetDocumentStatsParams struct {
	StartDate time.Time `json:"start_date"`
	EndDate   time.Time `json:"end_date"`
}

type GetDocumentStatsRow struct {
	TotalDocuments   int64 `json:"total_documents"`
	ActiveDocuments  int64 `json:"active_documents"`
	PendingDocuments int64 `json:"pending_documents"`
	FailedDocuments  int64 `json:"failed_documents"`
}

func (q *Queries) GetDocumentStats(ctx context.Context, arg GetDocumentStatsParams) (GetDocumentStatsRow, error) {
	row := q.db.QueryRow(ctx, getDocumentStats, arg.StartDate, arg.EndDate)
	var i GetDocumentStatsRow
	err := row.Scan(
		&i.TotalDocuments,
		&i.ActiveDocuments,
		&i.PendingDocuments,
		&i.FailedDocuments,
	)
	return i, err
}

const getFraudRate = `-- name: GetFraudRate :one
SELECT (
    CASE WHEN COUNT(DISTINCT c.id) > 0
        THEN (COUNT(DISTINCT ff.claim_id) * 100 / COUNT(DISTINCT c.id))
        ELSE 0
    END
)::bigint as fraud_rate
FROM claims c
LEFT JOIN fraud_flags ff ON ff.claim_id = c.id
WHERE c.created_at >= $1 AND c.created_at <= $2
`

type GetFraudRateParams struct {
	StartDate time.Time `json:"start_date"`
	EndDate   time.Time `json:"end_date"`
}

func (q *Queries) GetFraudRate(ctx context.Context, arg GetFraudRateParams) (int64, error) {
	row := q.db.QueryRow(ctx, getFraudRate, arg.StartDate, arg.EndDate)
	var fraud_rate int64
	err := row.Scan(&fraud_rate)
	return fraud_rate, err
}

const getLossRatio = `-- name: GetLossRatio :one
SELECT COALESCE(
    (SELECT CASE WHEN p.premium_total > 0
        THEN (c.claims_total * 100 / p.premium_total)::bigint
        ELSE 0 END
    FROM (
        SELECT COALESCE(SUM(COALESCE(NULLIF(cl.vetted_amount, 0), cl.approved_amount)), 0) as claims_total
        FROM claims cl WHERE cl.status IN ('APPROVED', 'PAID', 'PART_PAID', 'VETTED')
        AND cl.created_at >= $1 AND cl.created_at <= $2
    ) c,
    (
        SELECT COALESCE(SUM(pay.amount), 0) as premium_total
        FROM payments pay WHERE pay.type = 'PREMIUM' AND pay.status = 'CONFIRMED'
        AND pay.created_at >= $1 AND pay.created_at <= $2
    ) p),
0)::bigint as loss_ratio
`

type GetLossRatioParams struct {
	StartDate time.Time `json:"start_date"`
	EndDate   time.Time `json:"end_date"`
}

func (q *Queries) GetLossRatio(ctx context.Context, arg GetLossRatioParams) (int64, error) {
	row := q.db.QueryRow(ctx, getLossRatio, arg.StartDate, arg.EndDate)
	var loss_ratio int64
	err := row.Scan(&loss_ratio)
	return loss_ratio, err
}

const getTopProviders = `-- name: GetTopProviders :many
SELECT
    p.id,
    p.name,
    COUNT(c.id) as claim_count,
    COALESCE(SUM(c.total_amount), 0)::bigint as total_amount,
    COALESCE(SUM(c.approved_amount), 0)::bigint as total_approved
FROM providers p
LEFT JOIN claims c ON c.provider_id = p.id AND c.created_at >= $2 AND c.created_at <= $3
GROUP BY p.id, p.name
ORDER BY claim_count DESC
LIMIT $1
`

type GetTopProvidersParams struct {
	Limit     int32     `json:"limit"`
	StartDate time.Time `json:"start_date"`
	EndDate   time.Time `json:"end_date"`
}

type GetTopProvidersRow struct {
	ID            uuid.UUID `json:"id"`
	Name          string    `json:"name"`
	ClaimCount    int64     `json:"claim_count"`
	TotalAmount   int64     `json:"total_amount"`
	TotalApproved int64     `json:"total_approved"`
}

func (q *Queries) GetTopProviders(ctx context.Context, arg GetTopProvidersParams) ([]GetTopProvidersRow, error) {
	rows, err := q.db.Query(ctx, getTopProviders, arg.Limit, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTopProvidersRow{}
	for rows.Next() {
		var i GetTopProvidersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ClaimCount,
			&i.TotalAmount,
			&i.TotalApproved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalClaimsPaid = `-- name: GetTotalClaimsPaid :one
SELECT COALESCE(SUM(COALESCE(NULLIF(vetted_amount, 0), approved_amount)), 0)::bigint as total_paid
FROM claims
WHERE status IN ('PAID', 'PART_PAID')
  AND created_at >= $1 AND created_at <= $2
`

type GetTotalClaimsPaidParams struct {
	StartDate time.Time `json:"start_date"`
	EndDate   time.Time `json:"end_date"`
}

func (q *Queries) GetTotalClaimsPaid(ctx context.Context, arg GetTotalClaimsPaidParams) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalClaimsPaid, arg.StartDate, arg.EndDate)
	var total_paid int64
	err := row.Scan(&total_paid)
	return total_paid, err
}

const getTotalDocumentCount = `-- name: GetTotalDocumentCount :one
SELECT COUNT(*)::bigint as total_documents
FROM documents
WHERE status = 'ACTIVE' AND deleted_at IS NULL
  AND created_at >= $1 AND created_at <= $2
`

type GetTotalDocumentCountParams struct {
	StartDate time.Time `json:"start_date"`
	EndDate   time.Time `json:"end_date"`
}

func (q *Queries) GetTotalDocumentCount(ctx context.Context, arg GetTotalDocumentCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalDocumentCount, arg.StartDate, arg.EndDate)
	var total_documents int64
	err := row.Scan(&total_documents)
	return total_documents, err
}

const getTotalPremiumCollected = `-- name: GetTotalPremiumCollected :one
SELECT COALESCE(SUM(amount), 0)::bigint as total_premium
FROM payments
WHERE type = 'PREMIUM' AND status = 'CONFIRMED'
  AND created_at >= $1 AND created_at <= $2
`

type GetTotalPremiumCollectedParams struct {
	StartDate time.Time `json:"start_date"`
	EndDate   time.Time `json:"end_date"`
}

func (q *Queries) GetTotalPremiumCollected(ctx context.Context, arg GetTotalPremiumCollectedParams) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalPremiumCollected, arg.StartDate, arg.EndDate)
	var total_premium int64
	err := row.Scan(&total_premium)
	return total_premium, err
}
