// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: api_partner.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIPartner = `-- name: CreateAPIPartner :one
INSERT INTO api_partners (name, partner_type, api_key, api_secret_hash, provider_id, is_active, rate_limit_per_minute, allowed_claim_types, webhook_url, contact_email, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11) RETURNING id, name, partner_type, api_key, api_secret_hash, provider_id, is_active, rate_limit_per_minute, allowed_claim_types, webhook_url, contact_email, metadata, created_at, updated_at
`

type CreateAPIPartnerParams struct {
	Name               string      `json:"name"`
	PartnerType        string      `json:"partner_type"`
	ApiKey             string      `json:"api_key"`
	ApiSecretHash      string      `json:"api_secret_hash"`
	ProviderID         pgtype.UUID `json:"provider_id"`
	IsActive           bool        `json:"is_active"`
	RateLimitPerMinute int32       `json:"rate_limit_per_minute"`
	AllowedClaimTypes  []string    `json:"allowed_claim_types"`
	WebhookUrl         pgtype.Text `json:"webhook_url"`
	ContactEmail       pgtype.Text `json:"contact_email"`
	Metadata           []byte      `json:"metadata"`
}

func (q *Queries) CreateAPIPartner(ctx context.Context, arg CreateAPIPartnerParams) (ApiPartner, error) {
	row := q.db.QueryRow(ctx, createAPIPartner,
		arg.Name,
		arg.PartnerType,
		arg.ApiKey,
		arg.ApiSecretHash,
		arg.ProviderID,
		arg.IsActive,
		arg.RateLimitPerMinute,
		arg.AllowedClaimTypes,
		arg.WebhookUrl,
		arg.ContactEmail,
		arg.Metadata,
	)
	var i ApiPartner
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PartnerType,
		&i.ApiKey,
		&i.ApiSecretHash,
		&i.ProviderID,
		&i.IsActive,
		&i.RateLimitPerMinute,
		&i.AllowedClaimTypes,
		&i.WebhookUrl,
		&i.ContactEmail,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateAPIPartner = `-- name: DeactivateAPIPartner :exec
UPDATE api_partners SET is_active = false, updated_at = NOW() WHERE id = $1
`

func (q *Queries) DeactivateAPIPartner(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deactivateAPIPartner, id)
	return err
}

const getAPIPartnerByAPIKey = `-- name: GetAPIPartnerByAPIKey :one
SELECT id, name, partner_type, api_key, api_secret_hash, provider_id, is_active, rate_limit_per_minute, allowed_claim_types, webhook_url, contact_email, metadata, created_at, updated_at FROM api_partners WHERE api_key = $1
`

func (q *Queries) GetAPIPartnerByAPIKey(ctx context.Context, apiKey string) (ApiPartner, error) {
	row := q.db.QueryRow(ctx, getAPIPartnerByAPIKey, apiKey)
	var i ApiPartner
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PartnerType,
		&i.ApiKey,
		&i.ApiSecretHash,
		&i.ProviderID,
		&i.IsActive,
		&i.RateLimitPerMinute,
		&i.AllowedClaimTypes,
		&i.WebhookUrl,
		&i.ContactEmail,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAPIPartnerByID = `-- name: GetAPIPartnerByID :one
SELECT id, name, partner_type, api_key, api_secret_hash, provider_id, is_active, rate_limit_per_minute, allowed_claim_types, webhook_url, contact_email, metadata, created_at, updated_at FROM api_partners WHERE id = $1
`

func (q *Queries) GetAPIPartnerByID(ctx context.Context, id uuid.UUID) (ApiPartner, error) {
	row := q.db.QueryRow(ctx, getAPIPartnerByID, id)
	var i ApiPartner
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PartnerType,
		&i.ApiKey,
		&i.ApiSecretHash,
		&i.ProviderID,
		&i.IsActive,
		&i.RateLimitPerMinute,
		&i.AllowedClaimTypes,
		&i.WebhookUrl,
		&i.ContactEmail,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAPIPartners = `-- name: ListAPIPartners :many
SELECT id, name, partner_type, api_key, api_secret_hash, provider_id, is_active, rate_limit_per_minute, allowed_claim_types, webhook_url, contact_email, metadata, created_at, updated_at FROM api_partners ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListAPIPartnersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAPIPartners(ctx context.Context, arg ListAPIPartnersParams) ([]ApiPartner, error) {
	rows, err := q.db.Query(ctx, listAPIPartners, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiPartner{}
	for rows.Next() {
		var i ApiPartner
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PartnerType,
			&i.ApiKey,
			&i.ApiSecretHash,
			&i.ProviderID,
			&i.IsActive,
			&i.RateLimitPerMinute,
			&i.AllowedClaimTypes,
			&i.WebhookUrl,
			&i.ContactEmail,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAPIPartner = `-- name: UpdateAPIPartner :one
UPDATE api_partners SET
    name = $2,
    partner_type = $3,
    provider_id = $4,
    rate_limit_per_minute = $5,
    allowed_claim_types = $6,
    webhook_url = $7,
    contact_email = $8,
    metadata = $9,
    updated_at = NOW()
WHERE id = $1 RETURNING id, name, partner_type, api_key, api_secret_hash, provider_id, is_active, rate_limit_per_minute, allowed_claim_types, webhook_url, contact_email, metadata, created_at, updated_at
`

type UpdateAPIPartnerParams struct {
	ID                 uuid.UUID   `json:"id"`
	Name               string      `json:"name"`
	PartnerType        string      `json:"partner_type"`
	ProviderID         pgtype.UUID `json:"provider_id"`
	RateLimitPerMinute int32       `json:"rate_limit_per_minute"`
	AllowedClaimTypes  []string    `json:"allowed_claim_types"`
	WebhookUrl         pgtype.Text `json:"webhook_url"`
	ContactEmail       pgtype.Text `json:"contact_email"`
	Metadata           []byte      `json:"metadata"`
}

func (q *Queries) UpdateAPIPartner(ctx context.Context, arg UpdateAPIPartnerParams) (ApiPartner, error) {
	row := q.db.QueryRow(ctx, updateAPIPartner,
		arg.ID,
		arg.Name,
		arg.PartnerType,
		arg.ProviderID,
		arg.RateLimitPerMinute,
		arg.AllowedClaimTypes,
		arg.WebhookUrl,
		arg.ContactEmail,
		arg.Metadata,
	)
	var i ApiPartner
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PartnerType,
		&i.ApiKey,
		&i.ApiSecretHash,
		&i.ProviderID,
		&i.IsActive,
		&i.RateLimitPerMinute,
		&i.AllowedClaimTypes,
		&i.WebhookUrl,
		&i.ContactEmail,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAPIPartnerAPIKey = `-- name: UpdateAPIPartnerAPIKey :one
UPDATE api_partners SET api_key = $2, api_secret_hash = $3, updated_at = NOW() WHERE id = $1 RETURNING id, name, partner_type, api_key, api_secret_hash, provider_id, is_active, rate_limit_per_minute, allowed_claim_types, webhook_url, contact_email, metadata, created_at, updated_at
`

type UpdateAPIPartnerAPIKeyParams struct {
	ID            uuid.UUID `json:"id"`
	ApiKey        string    `json:"api_key"`
	ApiSecretHash string    `json:"api_secret_hash"`
}

func (q *Queries) UpdateAPIPartnerAPIKey(ctx context.Context, arg UpdateAPIPartnerAPIKeyParams) (ApiPartner, error) {
	row := q.db.QueryRow(ctx, updateAPIPartnerAPIKey, arg.ID, arg.ApiKey, arg.ApiSecretHash)
	var i ApiPartner
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PartnerType,
		&i.ApiKey,
		&i.ApiSecretHash,
		&i.ProviderID,
		&i.IsActive,
		&i.RateLimitPerMinute,
		&i.AllowedClaimTypes,
		&i.WebhookUrl,
		&i.ContactEmail,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
