// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: approval_limit.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createApprovalLimit = `-- name: CreateApprovalLimit :one
INSERT INTO approval_limits (role_name, max_discount_percentage, max_discount_amount, max_loading_percentage, max_loading_amount, escalation_role)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, role_name, max_discount_percentage, max_discount_amount, max_loading_percentage, max_loading_amount, escalation_role, is_active, created_at, updated_at
`

type CreateApprovalLimitParams struct {
	RoleName              string      `json:"role_name"`
	MaxDiscountPercentage int64       `json:"max_discount_percentage"`
	MaxDiscountAmount     int64       `json:"max_discount_amount"`
	MaxLoadingPercentage  int64       `json:"max_loading_percentage"`
	MaxLoadingAmount      int64       `json:"max_loading_amount"`
	EscalationRole        pgtype.Text `json:"escalation_role"`
}

func (q *Queries) CreateApprovalLimit(ctx context.Context, arg CreateApprovalLimitParams) (ApprovalLimit, error) {
	row := q.db.QueryRow(ctx, createApprovalLimit,
		arg.RoleName,
		arg.MaxDiscountPercentage,
		arg.MaxDiscountAmount,
		arg.MaxLoadingPercentage,
		arg.MaxLoadingAmount,
		arg.EscalationRole,
	)
	var i ApprovalLimit
	err := row.Scan(
		&i.ID,
		&i.RoleName,
		&i.MaxDiscountPercentage,
		&i.MaxDiscountAmount,
		&i.MaxLoadingPercentage,
		&i.MaxLoadingAmount,
		&i.EscalationRole,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteApprovalLimit = `-- name: DeleteApprovalLimit :exec
UPDATE approval_limits SET is_active = false, updated_at = NOW() WHERE id = $1
`

func (q *Queries) DeleteApprovalLimit(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteApprovalLimit, id)
	return err
}

const getApprovalLimitByRole = `-- name: GetApprovalLimitByRole :one
SELECT id, role_name, max_discount_percentage, max_discount_amount, max_loading_percentage, max_loading_amount, escalation_role, is_active, created_at, updated_at FROM approval_limits WHERE role_name = $1 AND is_active = true
`

func (q *Queries) GetApprovalLimitByRole(ctx context.Context, roleName string) (ApprovalLimit, error) {
	row := q.db.QueryRow(ctx, getApprovalLimitByRole, roleName)
	var i ApprovalLimit
	err := row.Scan(
		&i.ID,
		&i.RoleName,
		&i.MaxDiscountPercentage,
		&i.MaxDiscountAmount,
		&i.MaxLoadingPercentage,
		&i.MaxLoadingAmount,
		&i.EscalationRole,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listApprovalLimits = `-- name: ListApprovalLimits :many
SELECT id, role_name, max_discount_percentage, max_discount_amount, max_loading_percentage, max_loading_amount, escalation_role, is_active, created_at, updated_at FROM approval_limits WHERE is_active = true ORDER BY role_name
`

func (q *Queries) ListApprovalLimits(ctx context.Context) ([]ApprovalLimit, error) {
	rows, err := q.db.Query(ctx, listApprovalLimits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApprovalLimit{}
	for rows.Next() {
		var i ApprovalLimit
		if err := rows.Scan(
			&i.ID,
			&i.RoleName,
			&i.MaxDiscountPercentage,
			&i.MaxDiscountAmount,
			&i.MaxLoadingPercentage,
			&i.MaxLoadingAmount,
			&i.EscalationRole,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateApprovalLimit = `-- name: UpdateApprovalLimit :one
UPDATE approval_limits SET
    max_discount_percentage = COALESCE($2, max_discount_percentage),
    max_discount_amount = COALESCE($3, max_discount_amount),
    max_loading_percentage = COALESCE($4, max_loading_percentage),
    max_loading_amount = COALESCE($5, max_loading_amount),
    escalation_role = COALESCE(NULLIF($6, ''), escalation_role),
    updated_at = NOW()
WHERE id = $1 RETURNING id, role_name, max_discount_percentage, max_discount_amount, max_loading_percentage, max_loading_amount, escalation_role, is_active, created_at, updated_at
`

type UpdateApprovalLimitParams struct {
	ID                    uuid.UUID   `json:"id"`
	MaxDiscountPercentage int64       `json:"max_discount_percentage"`
	MaxDiscountAmount     int64       `json:"max_discount_amount"`
	MaxLoadingPercentage  int64       `json:"max_loading_percentage"`
	MaxLoadingAmount      int64       `json:"max_loading_amount"`
	Column6               interface{} `json:"column_6"`
}

func (q *Queries) UpdateApprovalLimit(ctx context.Context, arg UpdateApprovalLimitParams) (ApprovalLimit, error) {
	row := q.db.QueryRow(ctx, updateApprovalLimit,
		arg.ID,
		arg.MaxDiscountPercentage,
		arg.MaxDiscountAmount,
		arg.MaxLoadingPercentage,
		arg.MaxLoadingAmount,
		arg.Column6,
	)
	var i ApprovalLimit
	err := row.Scan(
		&i.ID,
		&i.RoleName,
		&i.MaxDiscountPercentage,
		&i.MaxDiscountAmount,
		&i.MaxLoadingPercentage,
		&i.MaxLoadingAmount,
		&i.EscalationRole,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
