// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: benefit.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createBenefit = `-- name: CreateBenefit :one
INSERT INTO benefits (plan_id, name, category, annual_limit, co_pay_type, co_pay_value, waiting_period_days, sub_limit_type, sub_limit_value, min_age, max_age, waiting_period_type, deductible_amount, is_optional, addon_premium)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15) RETURNING id, plan_id, name, category, annual_limit, co_pay_type, co_pay_value, waiting_period_days, sub_limit_type, sub_limit_value, min_age, max_age, waiting_period_type, created_at, updated_at, deductible_amount, parent_benefit_id, is_optional, addon_premium
`

type CreateBenefitParams struct {
	PlanID            uuid.UUID `json:"plan_id"`
	Name              string    `json:"name"`
	Category          string    `json:"category"`
	AnnualLimit       int64     `json:"annual_limit"`
	CoPayType         string    `json:"co_pay_type"`
	CoPayValue        int64     `json:"co_pay_value"`
	WaitingPeriodDays int32     `json:"waiting_period_days"`
	SubLimitType      string    `json:"sub_limit_type"`
	SubLimitValue     int64     `json:"sub_limit_value"`
	MinAge            int32     `json:"min_age"`
	MaxAge            int32     `json:"max_age"`
	WaitingPeriodType string    `json:"waiting_period_type"`
	DeductibleAmount  int64     `json:"deductible_amount"`
	IsOptional        bool      `json:"is_optional"`
	AddonPremium      int64     `json:"addon_premium"`
}

func (q *Queries) CreateBenefit(ctx context.Context, arg CreateBenefitParams) (Benefit, error) {
	row := q.db.QueryRow(ctx, createBenefit,
		arg.PlanID,
		arg.Name,
		arg.Category,
		arg.AnnualLimit,
		arg.CoPayType,
		arg.CoPayValue,
		arg.WaitingPeriodDays,
		arg.SubLimitType,
		arg.SubLimitValue,
		arg.MinAge,
		arg.MaxAge,
		arg.WaitingPeriodType,
		arg.DeductibleAmount,
		arg.IsOptional,
		arg.AddonPremium,
	)
	var i Benefit
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.Name,
		&i.Category,
		&i.AnnualLimit,
		&i.CoPayType,
		&i.CoPayValue,
		&i.WaitingPeriodDays,
		&i.SubLimitType,
		&i.SubLimitValue,
		&i.MinAge,
		&i.MaxAge,
		&i.WaitingPeriodType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeductibleAmount,
		&i.ParentBenefitID,
		&i.IsOptional,
		&i.AddonPremium,
	)
	return i, err
}

const createBenefitWithParent = `-- name: CreateBenefitWithParent :one
INSERT INTO benefits (plan_id, parent_benefit_id, name, category, annual_limit, co_pay_type, co_pay_value, waiting_period_days, sub_limit_type, sub_limit_value, min_age, max_age, waiting_period_type, deductible_amount, is_optional, addon_premium)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16) RETURNING id, plan_id, name, category, annual_limit, co_pay_type, co_pay_value, waiting_period_days, sub_limit_type, sub_limit_value, min_age, max_age, waiting_period_type, created_at, updated_at, deductible_amount, parent_benefit_id, is_optional, addon_premium
`

type CreateBenefitWithParentParams struct {
	PlanID            uuid.UUID   `json:"plan_id"`
	ParentBenefitID   pgtype.UUID `json:"parent_benefit_id"`
	Name              string      `json:"name"`
	Category          string      `json:"category"`
	AnnualLimit       int64       `json:"annual_limit"`
	CoPayType         string      `json:"co_pay_type"`
	CoPayValue        int64       `json:"co_pay_value"`
	WaitingPeriodDays int32       `json:"waiting_period_days"`
	SubLimitType      string      `json:"sub_limit_type"`
	SubLimitValue     int64       `json:"sub_limit_value"`
	MinAge            int32       `json:"min_age"`
	MaxAge            int32       `json:"max_age"`
	WaitingPeriodType string      `json:"waiting_period_type"`
	DeductibleAmount  int64       `json:"deductible_amount"`
	IsOptional        bool        `json:"is_optional"`
	AddonPremium      int64       `json:"addon_premium"`
}

func (q *Queries) CreateBenefitWithParent(ctx context.Context, arg CreateBenefitWithParentParams) (Benefit, error) {
	row := q.db.QueryRow(ctx, createBenefitWithParent,
		arg.PlanID,
		arg.ParentBenefitID,
		arg.Name,
		arg.Category,
		arg.AnnualLimit,
		arg.CoPayType,
		arg.CoPayValue,
		arg.WaitingPeriodDays,
		arg.SubLimitType,
		arg.SubLimitValue,
		arg.MinAge,
		arg.MaxAge,
		arg.WaitingPeriodType,
		arg.DeductibleAmount,
		arg.IsOptional,
		arg.AddonPremium,
	)
	var i Benefit
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.Name,
		&i.Category,
		&i.AnnualLimit,
		&i.CoPayType,
		&i.CoPayValue,
		&i.WaitingPeriodDays,
		&i.SubLimitType,
		&i.SubLimitValue,
		&i.MinAge,
		&i.MaxAge,
		&i.WaitingPeriodType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeductibleAmount,
		&i.ParentBenefitID,
		&i.IsOptional,
		&i.AddonPremium,
	)
	return i, err
}

const deleteBenefit = `-- name: DeleteBenefit :exec
DELETE FROM benefits WHERE id = $1
`

func (q *Queries) DeleteBenefit(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBenefit, id)
	return err
}

const getBenefitByID = `-- name: GetBenefitByID :one
SELECT id, plan_id, name, category, annual_limit, co_pay_type, co_pay_value, waiting_period_days, sub_limit_type, sub_limit_value, min_age, max_age, waiting_period_type, created_at, updated_at, deductible_amount, parent_benefit_id, is_optional, addon_premium FROM benefits WHERE id = $1
`

func (q *Queries) GetBenefitByID(ctx context.Context, id uuid.UUID) (Benefit, error) {
	row := q.db.QueryRow(ctx, getBenefitByID, id)
	var i Benefit
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.Name,
		&i.Category,
		&i.AnnualLimit,
		&i.CoPayType,
		&i.CoPayValue,
		&i.WaitingPeriodDays,
		&i.SubLimitType,
		&i.SubLimitValue,
		&i.MinAge,
		&i.MaxAge,
		&i.WaitingPeriodType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeductibleAmount,
		&i.ParentBenefitID,
		&i.IsOptional,
		&i.AddonPremium,
	)
	return i, err
}

const listBenefitsByCategory = `-- name: ListBenefitsByCategory :many
SELECT id, plan_id, name, category, annual_limit, co_pay_type, co_pay_value, waiting_period_days, sub_limit_type, sub_limit_value, min_age, max_age, waiting_period_type, created_at, updated_at, deductible_amount, parent_benefit_id, is_optional, addon_premium FROM benefits WHERE plan_id = $1 AND category = $2
`

type ListBenefitsByCategoryParams struct {
	PlanID   uuid.UUID `json:"plan_id"`
	Category string    `json:"category"`
}

func (q *Queries) ListBenefitsByCategory(ctx context.Context, arg ListBenefitsByCategoryParams) ([]Benefit, error) {
	rows, err := q.db.Query(ctx, listBenefitsByCategory, arg.PlanID, arg.Category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Benefit{}
	for rows.Next() {
		var i Benefit
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.Name,
			&i.Category,
			&i.AnnualLimit,
			&i.CoPayType,
			&i.CoPayValue,
			&i.WaitingPeriodDays,
			&i.SubLimitType,
			&i.SubLimitValue,
			&i.MinAge,
			&i.MaxAge,
			&i.WaitingPeriodType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeductibleAmount,
			&i.ParentBenefitID,
			&i.IsOptional,
			&i.AddonPremium,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBenefitsByPlan = `-- name: ListBenefitsByPlan :many
SELECT id, plan_id, name, category, annual_limit, co_pay_type, co_pay_value, waiting_period_days, sub_limit_type, sub_limit_value, min_age, max_age, waiting_period_type, created_at, updated_at, deductible_amount, parent_benefit_id, is_optional, addon_premium FROM benefits WHERE plan_id = $1 ORDER BY category, name
`

func (q *Queries) ListBenefitsByPlan(ctx context.Context, planID uuid.UUID) ([]Benefit, error) {
	rows, err := q.db.Query(ctx, listBenefitsByPlan, planID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Benefit{}
	for rows.Next() {
		var i Benefit
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.Name,
			&i.Category,
			&i.AnnualLimit,
			&i.CoPayType,
			&i.CoPayValue,
			&i.WaitingPeriodDays,
			&i.SubLimitType,
			&i.SubLimitValue,
			&i.MinAge,
			&i.MaxAge,
			&i.WaitingPeriodType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeductibleAmount,
			&i.ParentBenefitID,
			&i.IsOptional,
			&i.AddonPremium,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOptionalBenefitsByPlan = `-- name: ListOptionalBenefitsByPlan :many
SELECT id, plan_id, name, category, annual_limit, co_pay_type, co_pay_value, waiting_period_days, sub_limit_type, sub_limit_value, min_age, max_age, waiting_period_type, created_at, updated_at, deductible_amount, parent_benefit_id, is_optional, addon_premium FROM benefits WHERE plan_id = $1 AND is_optional = true ORDER BY category, name
`

func (q *Queries) ListOptionalBenefitsByPlan(ctx context.Context, planID uuid.UUID) ([]Benefit, error) {
	rows, err := q.db.Query(ctx, listOptionalBenefitsByPlan, planID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Benefit{}
	for rows.Next() {
		var i Benefit
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.Name,
			&i.Category,
			&i.AnnualLimit,
			&i.CoPayType,
			&i.CoPayValue,
			&i.WaitingPeriodDays,
			&i.SubLimitType,
			&i.SubLimitValue,
			&i.MinAge,
			&i.MaxAge,
			&i.WaitingPeriodType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeductibleAmount,
			&i.ParentBenefitID,
			&i.IsOptional,
			&i.AddonPremium,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubBenefits = `-- name: ListSubBenefits :many
SELECT id, plan_id, name, category, annual_limit, co_pay_type, co_pay_value, waiting_period_days, sub_limit_type, sub_limit_value, min_age, max_age, waiting_period_type, created_at, updated_at, deductible_amount, parent_benefit_id, is_optional, addon_premium FROM benefits WHERE parent_benefit_id = $1 ORDER BY name
`

func (q *Queries) ListSubBenefits(ctx context.Context, parentBenefitID pgtype.UUID) ([]Benefit, error) {
	rows, err := q.db.Query(ctx, listSubBenefits, parentBenefitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Benefit{}
	for rows.Next() {
		var i Benefit
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.Name,
			&i.Category,
			&i.AnnualLimit,
			&i.CoPayType,
			&i.CoPayValue,
			&i.WaitingPeriodDays,
			&i.SubLimitType,
			&i.SubLimitValue,
			&i.MinAge,
			&i.MaxAge,
			&i.WaitingPeriodType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeductibleAmount,
			&i.ParentBenefitID,
			&i.IsOptional,
			&i.AddonPremium,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBenefit = `-- name: UpdateBenefit :one
UPDATE benefits SET
    name = COALESCE($1, name),
    category = COALESCE($2, category),
    annual_limit = COALESCE($3, annual_limit),
    co_pay_type = COALESCE($4, co_pay_type),
    co_pay_value = COALESCE($5, co_pay_value),
    waiting_period_days = COALESCE($6, waiting_period_days),
    sub_limit_type = COALESCE($7, sub_limit_type),
    sub_limit_value = COALESCE($8, sub_limit_value),
    min_age = COALESCE($9, min_age),
    max_age = COALESCE($10, max_age),
    waiting_period_type = COALESCE($11, waiting_period_type),
    is_optional = COALESCE($12, is_optional),
    addon_premium = COALESCE($13, addon_premium),
    updated_at = NOW()
WHERE id = $14 RETURNING id, plan_id, name, category, annual_limit, co_pay_type, co_pay_value, waiting_period_days, sub_limit_type, sub_limit_value, min_age, max_age, waiting_period_type, created_at, updated_at, deductible_amount, parent_benefit_id, is_optional, addon_premium
`

type UpdateBenefitParams struct {
	Name              pgtype.Text `json:"name"`
	Category          pgtype.Text `json:"category"`
	AnnualLimit       pgtype.Int8 `json:"annual_limit"`
	CoPayType         pgtype.Text `json:"co_pay_type"`
	CoPayValue        pgtype.Int8 `json:"co_pay_value"`
	WaitingPeriodDays pgtype.Int4 `json:"waiting_period_days"`
	SubLimitType      pgtype.Text `json:"sub_limit_type"`
	SubLimitValue     pgtype.Int8 `json:"sub_limit_value"`
	MinAge            pgtype.Int4 `json:"min_age"`
	MaxAge            pgtype.Int4 `json:"max_age"`
	WaitingPeriodType pgtype.Text `json:"waiting_period_type"`
	IsOptional        pgtype.Bool `json:"is_optional"`
	AddonPremium      pgtype.Int8 `json:"addon_premium"`
	ID                uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateBenefit(ctx context.Context, arg UpdateBenefitParams) (Benefit, error) {
	row := q.db.QueryRow(ctx, updateBenefit,
		arg.Name,
		arg.Category,
		arg.AnnualLimit,
		arg.CoPayType,
		arg.CoPayValue,
		arg.WaitingPeriodDays,
		arg.SubLimitType,
		arg.SubLimitValue,
		arg.MinAge,
		arg.MaxAge,
		arg.WaitingPeriodType,
		arg.IsOptional,
		arg.AddonPremium,
		arg.ID,
	)
	var i Benefit
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.Name,
		&i.Category,
		&i.AnnualLimit,
		&i.CoPayType,
		&i.CoPayValue,
		&i.WaitingPeriodDays,
		&i.SubLimitType,
		&i.SubLimitValue,
		&i.MinAge,
		&i.MaxAge,
		&i.WaitingPeriodType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeductibleAmount,
		&i.ParentBenefitID,
		&i.IsOptional,
		&i.AddonPremium,
	)
	return i, err
}
