// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: bordereau.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countBordereaux = `-- name: CountBordereaux :one
SELECT COUNT(*) FROM bordereaux
`

func (q *Queries) CountBordereaux(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countBordereaux)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBordereau = `-- name: CreateBordereau :one
INSERT INTO bordereaux (bordereau_number, treaty_id, bordereau_type, period_start, period_end, total_gross, total_ceded, total_commission, item_count, status, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11) RETURNING id, bordereau_number, treaty_id, bordereau_type, period_start, period_end, total_gross, total_ceded, total_commission, item_count, status, created_by, created_at, updated_at
`

type CreateBordereauParams struct {
	BordereauNumber string      `json:"bordereau_number"`
	TreatyID        uuid.UUID   `json:"treaty_id"`
	BordereauType   string      `json:"bordereau_type"`
	PeriodStart     pgtype.Date `json:"period_start"`
	PeriodEnd       pgtype.Date `json:"period_end"`
	TotalGross      int64       `json:"total_gross"`
	TotalCeded      int64       `json:"total_ceded"`
	TotalCommission int64       `json:"total_commission"`
	ItemCount       int32       `json:"item_count"`
	Status          string      `json:"status"`
	CreatedBy       uuid.UUID   `json:"created_by"`
}

func (q *Queries) CreateBordereau(ctx context.Context, arg CreateBordereauParams) (Bordereaux, error) {
	row := q.db.QueryRow(ctx, createBordereau,
		arg.BordereauNumber,
		arg.TreatyID,
		arg.BordereauType,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.TotalGross,
		arg.TotalCeded,
		arg.TotalCommission,
		arg.ItemCount,
		arg.Status,
		arg.CreatedBy,
	)
	var i Bordereaux
	err := row.Scan(
		&i.ID,
		&i.BordereauNumber,
		&i.TreatyID,
		&i.BordereauType,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.TotalGross,
		&i.TotalCeded,
		&i.TotalCommission,
		&i.ItemCount,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBordereauByID = `-- name: GetBordereauByID :one
SELECT id, bordereau_number, treaty_id, bordereau_type, period_start, period_end, total_gross, total_ceded, total_commission, item_count, status, created_by, created_at, updated_at FROM bordereaux WHERE id = $1
`

func (q *Queries) GetBordereauByID(ctx context.Context, id uuid.UUID) (Bordereaux, error) {
	row := q.db.QueryRow(ctx, getBordereauByID, id)
	var i Bordereaux
	err := row.Scan(
		&i.ID,
		&i.BordereauNumber,
		&i.TreatyID,
		&i.BordereauType,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.TotalGross,
		&i.TotalCeded,
		&i.TotalCommission,
		&i.ItemCount,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBordereauByNumber = `-- name: GetBordereauByNumber :one
SELECT id, bordereau_number, treaty_id, bordereau_type, period_start, period_end, total_gross, total_ceded, total_commission, item_count, status, created_by, created_at, updated_at FROM bordereaux WHERE bordereau_number = $1
`

func (q *Queries) GetBordereauByNumber(ctx context.Context, bordereauNumber string) (Bordereaux, error) {
	row := q.db.QueryRow(ctx, getBordereauByNumber, bordereauNumber)
	var i Bordereaux
	err := row.Scan(
		&i.ID,
		&i.BordereauNumber,
		&i.TreatyID,
		&i.BordereauType,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.TotalGross,
		&i.TotalCeded,
		&i.TotalCommission,
		&i.ItemCount,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBordereauxByTreaty = `-- name: ListBordereauxByTreaty :many
SELECT id, bordereau_number, treaty_id, bordereau_type, period_start, period_end, total_gross, total_ceded, total_commission, item_count, status, created_by, created_at, updated_at FROM bordereaux WHERE treaty_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListBordereauxByTreatyParams struct {
	TreatyID uuid.UUID `json:"treaty_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListBordereauxByTreaty(ctx context.Context, arg ListBordereauxByTreatyParams) ([]Bordereaux, error) {
	rows, err := q.db.Query(ctx, listBordereauxByTreaty, arg.TreatyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Bordereaux{}
	for rows.Next() {
		var i Bordereaux
		if err := rows.Scan(
			&i.ID,
			&i.BordereauNumber,
			&i.TreatyID,
			&i.BordereauType,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.TotalGross,
			&i.TotalCeded,
			&i.TotalCommission,
			&i.ItemCount,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBordereau = `-- name: UpdateBordereau :one
UPDATE bordereaux SET
    total_gross = $2, total_ceded = $3, total_commission = $4,
    item_count = $5, updated_at = NOW()
WHERE id = $1 RETURNING id, bordereau_number, treaty_id, bordereau_type, period_start, period_end, total_gross, total_ceded, total_commission, item_count, status, created_by, created_at, updated_at
`

type UpdateBordereauParams struct {
	ID              uuid.UUID `json:"id"`
	TotalGross      int64     `json:"total_gross"`
	TotalCeded      int64     `json:"total_ceded"`
	TotalCommission int64     `json:"total_commission"`
	ItemCount       int32     `json:"item_count"`
}

func (q *Queries) UpdateBordereau(ctx context.Context, arg UpdateBordereauParams) (Bordereaux, error) {
	row := q.db.QueryRow(ctx, updateBordereau,
		arg.ID,
		arg.TotalGross,
		arg.TotalCeded,
		arg.TotalCommission,
		arg.ItemCount,
	)
	var i Bordereaux
	err := row.Scan(
		&i.ID,
		&i.BordereauNumber,
		&i.TreatyID,
		&i.BordereauType,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.TotalGross,
		&i.TotalCeded,
		&i.TotalCommission,
		&i.ItemCount,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBordereauStatus = `-- name: UpdateBordereauStatus :one
UPDATE bordereaux SET status = $2, updated_at = NOW() WHERE id = $1 RETURNING id, bordereau_number, treaty_id, bordereau_type, period_start, period_end, total_gross, total_ceded, total_commission, item_count, status, created_by, created_at, updated_at
`

type UpdateBordereauStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateBordereauStatus(ctx context.Context, arg UpdateBordereauStatusParams) (Bordereaux, error) {
	row := q.db.QueryRow(ctx, updateBordereauStatus, arg.ID, arg.Status)
	var i Bordereaux
	err := row.Scan(
		&i.ID,
		&i.BordereauNumber,
		&i.TreatyID,
		&i.BordereauType,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.TotalGross,
		&i.TotalCeded,
		&i.TotalCommission,
		&i.ItemCount,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
