// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: bordereau_item.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createBordereauItem = `-- name: CreateBordereauItem :one
INSERT INTO bordereau_items (bordereau_id, cession_id, recovery_id, policy_number, claim_number, gross_amount, ceded_amount, commission_amount)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING id, bordereau_id, cession_id, recovery_id, policy_number, claim_number, gross_amount, ceded_amount, commission_amount, created_at
`

type CreateBordereauItemParams struct {
	BordereauID      uuid.UUID   `json:"bordereau_id"`
	CessionID        pgtype.UUID `json:"cession_id"`
	RecoveryID       pgtype.UUID `json:"recovery_id"`
	PolicyNumber     pgtype.Text `json:"policy_number"`
	ClaimNumber      pgtype.Text `json:"claim_number"`
	GrossAmount      int64       `json:"gross_amount"`
	CededAmount      int64       `json:"ceded_amount"`
	CommissionAmount int64       `json:"commission_amount"`
}

func (q *Queries) CreateBordereauItem(ctx context.Context, arg CreateBordereauItemParams) (BordereauItem, error) {
	row := q.db.QueryRow(ctx, createBordereauItem,
		arg.BordereauID,
		arg.CessionID,
		arg.RecoveryID,
		arg.PolicyNumber,
		arg.ClaimNumber,
		arg.GrossAmount,
		arg.CededAmount,
		arg.CommissionAmount,
	)
	var i BordereauItem
	err := row.Scan(
		&i.ID,
		&i.BordereauID,
		&i.CessionID,
		&i.RecoveryID,
		&i.PolicyNumber,
		&i.ClaimNumber,
		&i.GrossAmount,
		&i.CededAmount,
		&i.CommissionAmount,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBordereauItemsByBordereau = `-- name: DeleteBordereauItemsByBordereau :exec
DELETE FROM bordereau_items WHERE bordereau_id = $1
`

func (q *Queries) DeleteBordereauItemsByBordereau(ctx context.Context, bordereauID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBordereauItemsByBordereau, bordereauID)
	return err
}

const listBordereauItemsByBordereau = `-- name: ListBordereauItemsByBordereau :many
SELECT id, bordereau_id, cession_id, recovery_id, policy_number, claim_number, gross_amount, ceded_amount, commission_amount, created_at FROM bordereau_items WHERE bordereau_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListBordereauItemsByBordereau(ctx context.Context, bordereauID uuid.UUID) ([]BordereauItem, error) {
	rows, err := q.db.Query(ctx, listBordereauItemsByBordereau, bordereauID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BordereauItem{}
	for rows.Next() {
		var i BordereauItem
		if err := rows.Scan(
			&i.ID,
			&i.BordereauID,
			&i.CessionID,
			&i.RecoveryID,
			&i.PolicyNumber,
			&i.ClaimNumber,
			&i.GrossAmount,
			&i.CededAmount,
			&i.CommissionAmount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
