// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: cession.sql

package db

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countCessions = `-- name: CountCessions :one
SELECT COUNT(*) FROM cessions
`

func (q *Queries) CountCessions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCessions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCession = `-- name: CreateCession :one
INSERT INTO cessions (cession_number, treaty_id, policy_id, treaty_layer_id, cession_type, gross_amount, ceded_amount, retained_amount, commission_amount, share_percentage, status, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12) RETURNING id, cession_number, treaty_id, policy_id, treaty_layer_id, cession_type, gross_amount, ceded_amount, retained_amount, commission_amount, share_percentage, status, created_by, created_at, updated_at
`

type CreateCessionParams struct {
	CessionNumber    string         `json:"cession_number"`
	TreatyID         uuid.UUID      `json:"treaty_id"`
	PolicyID         uuid.UUID      `json:"policy_id"`
	TreatyLayerID    pgtype.UUID    `json:"treaty_layer_id"`
	CessionType      string         `json:"cession_type"`
	GrossAmount      int64          `json:"gross_amount"`
	CededAmount      int64          `json:"ceded_amount"`
	RetainedAmount   int64          `json:"retained_amount"`
	CommissionAmount int64          `json:"commission_amount"`
	SharePercentage  pgtype.Numeric `json:"share_percentage"`
	Status           string         `json:"status"`
	CreatedBy        uuid.UUID      `json:"created_by"`
}

func (q *Queries) CreateCession(ctx context.Context, arg CreateCessionParams) (Cession, error) {
	row := q.db.QueryRow(ctx, createCession,
		arg.CessionNumber,
		arg.TreatyID,
		arg.PolicyID,
		arg.TreatyLayerID,
		arg.CessionType,
		arg.GrossAmount,
		arg.CededAmount,
		arg.RetainedAmount,
		arg.CommissionAmount,
		arg.SharePercentage,
		arg.Status,
		arg.CreatedBy,
	)
	var i Cession
	err := row.Scan(
		&i.ID,
		&i.CessionNumber,
		&i.TreatyID,
		&i.PolicyID,
		&i.TreatyLayerID,
		&i.CessionType,
		&i.GrossAmount,
		&i.CededAmount,
		&i.RetainedAmount,
		&i.CommissionAmount,
		&i.SharePercentage,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCessionByID = `-- name: GetCessionByID :one
SELECT id, cession_number, treaty_id, policy_id, treaty_layer_id, cession_type, gross_amount, ceded_amount, retained_amount, commission_amount, share_percentage, status, created_by, created_at, updated_at FROM cessions WHERE id = $1
`

func (q *Queries) GetCessionByID(ctx context.Context, id uuid.UUID) (Cession, error) {
	row := q.db.QueryRow(ctx, getCessionByID, id)
	var i Cession
	err := row.Scan(
		&i.ID,
		&i.CessionNumber,
		&i.TreatyID,
		&i.PolicyID,
		&i.TreatyLayerID,
		&i.CessionType,
		&i.GrossAmount,
		&i.CededAmount,
		&i.RetainedAmount,
		&i.CommissionAmount,
		&i.SharePercentage,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCessionByNumber = `-- name: GetCessionByNumber :one
SELECT id, cession_number, treaty_id, policy_id, treaty_layer_id, cession_type, gross_amount, ceded_amount, retained_amount, commission_amount, share_percentage, status, created_by, created_at, updated_at FROM cessions WHERE cession_number = $1
`

func (q *Queries) GetCessionByNumber(ctx context.Context, cessionNumber string) (Cession, error) {
	row := q.db.QueryRow(ctx, getCessionByNumber, cessionNumber)
	var i Cession
	err := row.Scan(
		&i.ID,
		&i.CessionNumber,
		&i.TreatyID,
		&i.PolicyID,
		&i.TreatyLayerID,
		&i.CessionType,
		&i.GrossAmount,
		&i.CededAmount,
		&i.RetainedAmount,
		&i.CommissionAmount,
		&i.SharePercentage,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTotalCededAmountAll = `-- name: GetTotalCededAmountAll :one
SELECT COALESCE(SUM(ceded_amount), 0)::bigint as total_ceded
FROM cessions WHERE status = 'BOOKED'
`

func (q *Queries) GetTotalCededAmountAll(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalCededAmountAll)
	var total_ceded int64
	err := row.Scan(&total_ceded)
	return total_ceded, err
}

const getTotalCededByTreaty = `-- name: GetTotalCededByTreaty :one
SELECT COALESCE(SUM(ceded_amount), 0)::bigint as total_ceded
FROM cessions WHERE treaty_id = $1 AND status = 'BOOKED'
`

func (q *Queries) GetTotalCededByTreaty(ctx context.Context, treatyID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalCededByTreaty, treatyID)
	var total_ceded int64
	err := row.Scan(&total_ceded)
	return total_ceded, err
}

const getTotalCededByTreatyAndPeriod = `-- name: GetTotalCededByTreatyAndPeriod :one
SELECT COALESCE(SUM(ceded_amount), 0)::bigint as total_ceded
FROM cessions WHERE treaty_id = $1 AND status = 'BOOKED' AND created_at >= $2 AND created_at <= $3
`

type GetTotalCededByTreatyAndPeriodParams struct {
	TreatyID    uuid.UUID `json:"treaty_id"`
	CreatedAt   time.Time `json:"created_at"`
	CreatedAt_2 time.Time `json:"created_at_2"`
}

func (q *Queries) GetTotalCededByTreatyAndPeriod(ctx context.Context, arg GetTotalCededByTreatyAndPeriodParams) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalCededByTreatyAndPeriod, arg.TreatyID, arg.CreatedAt, arg.CreatedAt_2)
	var total_ceded int64
	err := row.Scan(&total_ceded)
	return total_ceded, err
}

const getTotalGrossAmountAll = `-- name: GetTotalGrossAmountAll :one
SELECT COALESCE(SUM(gross_amount), 0)::bigint as total_gross
FROM cessions WHERE status = 'BOOKED'
`

func (q *Queries) GetTotalGrossAmountAll(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalGrossAmountAll)
	var total_gross int64
	err := row.Scan(&total_gross)
	return total_gross, err
}

const listBookedCessionsByTreatyAndPeriod = `-- name: ListBookedCessionsByTreatyAndPeriod :many
SELECT id, cession_number, treaty_id, policy_id, treaty_layer_id, cession_type, gross_amount, ceded_amount, retained_amount, commission_amount, share_percentage, status, created_by, created_at, updated_at FROM cessions
WHERE treaty_id = $1 AND status = 'BOOKED' AND created_at >= $2 AND created_at <= $3
ORDER BY created_at DESC
`

type ListBookedCessionsByTreatyAndPeriodParams struct {
	TreatyID    uuid.UUID `json:"treaty_id"`
	CreatedAt   time.Time `json:"created_at"`
	CreatedAt_2 time.Time `json:"created_at_2"`
}

func (q *Queries) ListBookedCessionsByTreatyAndPeriod(ctx context.Context, arg ListBookedCessionsByTreatyAndPeriodParams) ([]Cession, error) {
	rows, err := q.db.Query(ctx, listBookedCessionsByTreatyAndPeriod, arg.TreatyID, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Cession{}
	for rows.Next() {
		var i Cession
		if err := rows.Scan(
			&i.ID,
			&i.CessionNumber,
			&i.TreatyID,
			&i.PolicyID,
			&i.TreatyLayerID,
			&i.CessionType,
			&i.GrossAmount,
			&i.CededAmount,
			&i.RetainedAmount,
			&i.CommissionAmount,
			&i.SharePercentage,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCessionsByPolicy = `-- name: ListCessionsByPolicy :many
SELECT id, cession_number, treaty_id, policy_id, treaty_layer_id, cession_type, gross_amount, ceded_amount, retained_amount, commission_amount, share_percentage, status, created_by, created_at, updated_at FROM cessions WHERE policy_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListCessionsByPolicyParams struct {
	PolicyID uuid.UUID `json:"policy_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListCessionsByPolicy(ctx context.Context, arg ListCessionsByPolicyParams) ([]Cession, error) {
	rows, err := q.db.Query(ctx, listCessionsByPolicy, arg.PolicyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Cession{}
	for rows.Next() {
		var i Cession
		if err := rows.Scan(
			&i.ID,
			&i.CessionNumber,
			&i.TreatyID,
			&i.PolicyID,
			&i.TreatyLayerID,
			&i.CessionType,
			&i.GrossAmount,
			&i.CededAmount,
			&i.RetainedAmount,
			&i.CommissionAmount,
			&i.SharePercentage,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCessionsByTreaty = `-- name: ListCessionsByTreaty :many
SELECT id, cession_number, treaty_id, policy_id, treaty_layer_id, cession_type, gross_amount, ceded_amount, retained_amount, commission_amount, share_percentage, status, created_by, created_at, updated_at FROM cessions WHERE treaty_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListCessionsByTreatyParams struct {
	TreatyID uuid.UUID `json:"treaty_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListCessionsByTreaty(ctx context.Context, arg ListCessionsByTreatyParams) ([]Cession, error) {
	rows, err := q.db.Query(ctx, listCessionsByTreaty, arg.TreatyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Cession{}
	for rows.Next() {
		var i Cession
		if err := rows.Scan(
			&i.ID,
			&i.CessionNumber,
			&i.TreatyID,
			&i.PolicyID,
			&i.TreatyLayerID,
			&i.CessionType,
			&i.GrossAmount,
			&i.CededAmount,
			&i.RetainedAmount,
			&i.CommissionAmount,
			&i.SharePercentage,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCessionsByTreatyAndPeriod = `-- name: ListCessionsByTreatyAndPeriod :many
SELECT id, cession_number, treaty_id, policy_id, treaty_layer_id, cession_type, gross_amount, ceded_amount, retained_amount, commission_amount, share_percentage, status, created_by, created_at, updated_at FROM cessions
WHERE treaty_id = $1 AND created_at >= $2 AND created_at <= $3
ORDER BY created_at DESC LIMIT $4 OFFSET $5
`

type ListCessionsByTreatyAndPeriodParams struct {
	TreatyID    uuid.UUID `json:"treaty_id"`
	CreatedAt   time.Time `json:"created_at"`
	CreatedAt_2 time.Time `json:"created_at_2"`
	Limit       int32     `json:"limit"`
	Offset      int32     `json:"offset"`
}

func (q *Queries) ListCessionsByTreatyAndPeriod(ctx context.Context, arg ListCessionsByTreatyAndPeriodParams) ([]Cession, error) {
	rows, err := q.db.Query(ctx, listCessionsByTreatyAndPeriod,
		arg.TreatyID,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Cession{}
	for rows.Next() {
		var i Cession
		if err := rows.Scan(
			&i.ID,
			&i.CessionNumber,
			&i.TreatyID,
			&i.PolicyID,
			&i.TreatyLayerID,
			&i.CessionType,
			&i.GrossAmount,
			&i.CededAmount,
			&i.RetainedAmount,
			&i.CommissionAmount,
			&i.SharePercentage,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCessionStatus = `-- name: UpdateCessionStatus :one
UPDATE cessions SET status = $2, updated_at = NOW() WHERE id = $1 RETURNING id, cession_number, treaty_id, policy_id, treaty_layer_id, cession_type, gross_amount, ceded_amount, retained_amount, commission_amount, share_percentage, status, created_by, created_at, updated_at
`

type UpdateCessionStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateCessionStatus(ctx context.Context, arg UpdateCessionStatusParams) (Cession, error) {
	row := q.db.QueryRow(ctx, updateCessionStatus, arg.ID, arg.Status)
	var i Cession
	err := row.Scan(
		&i.ID,
		&i.CessionNumber,
		&i.TreatyID,
		&i.PolicyID,
		&i.TreatyLayerID,
		&i.CessionType,
		&i.GrossAmount,
		&i.CededAmount,
		&i.RetainedAmount,
		&i.CommissionAmount,
		&i.SharePercentage,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
