// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: claim_document.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
)

const createClaimDocument = `-- name: CreateClaimDocument :one
INSERT INTO claim_documents (claim_id, file_name, file_type, file_size, s3_key, uploaded_by)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, claim_id, file_name, file_type, file_size, s3_key, uploaded_by, is_deleted, created_at, updated_at
`

type CreateClaimDocumentParams struct {
	ClaimID    uuid.UUID `json:"claim_id"`
	FileName   string    `json:"file_name"`
	FileType   string    `json:"file_type"`
	FileSize   int64     `json:"file_size"`
	S3Key      string    `json:"s3_key"`
	UploadedBy uuid.UUID `json:"uploaded_by"`
}

func (q *Queries) CreateClaimDocument(ctx context.Context, arg CreateClaimDocumentParams) (ClaimDocument, error) {
	row := q.db.QueryRow(ctx, createClaimDocument,
		arg.ClaimID,
		arg.FileName,
		arg.FileType,
		arg.FileSize,
		arg.S3Key,
		arg.UploadedBy,
	)
	var i ClaimDocument
	err := row.Scan(
		&i.ID,
		&i.ClaimID,
		&i.FileName,
		&i.FileType,
		&i.FileSize,
		&i.S3Key,
		&i.UploadedBy,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClaimDocumentByID = `-- name: GetClaimDocumentByID :one
SELECT id, claim_id, file_name, file_type, file_size, s3_key, uploaded_by, is_deleted, created_at, updated_at FROM claim_documents WHERE id = $1 AND is_deleted = false
`

func (q *Queries) GetClaimDocumentByID(ctx context.Context, id uuid.UUID) (ClaimDocument, error) {
	row := q.db.QueryRow(ctx, getClaimDocumentByID, id)
	var i ClaimDocument
	err := row.Scan(
		&i.ID,
		&i.ClaimID,
		&i.FileName,
		&i.FileType,
		&i.FileSize,
		&i.S3Key,
		&i.UploadedBy,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listClaimDocumentsByClaim = `-- name: ListClaimDocumentsByClaim :many
SELECT id, claim_id, file_name, file_type, file_size, s3_key, uploaded_by, is_deleted, created_at, updated_at FROM claim_documents WHERE claim_id = $1 AND is_deleted = false ORDER BY created_at DESC
`

func (q *Queries) ListClaimDocumentsByClaim(ctx context.Context, claimID uuid.UUID) ([]ClaimDocument, error) {
	rows, err := q.db.Query(ctx, listClaimDocumentsByClaim, claimID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimDocument{}
	for rows.Next() {
		var i ClaimDocument
		if err := rows.Scan(
			&i.ID,
			&i.ClaimID,
			&i.FileName,
			&i.FileType,
			&i.FileSize,
			&i.S3Key,
			&i.UploadedBy,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteClaimDocument = `-- name: SoftDeleteClaimDocument :one
UPDATE claim_documents SET is_deleted = true, updated_at = NOW() WHERE id = $1 RETURNING id, claim_id, file_name, file_type, file_size, s3_key, uploaded_by, is_deleted, created_at, updated_at
`

func (q *Queries) SoftDeleteClaimDocument(ctx context.Context, id uuid.UUID) (ClaimDocument, error) {
	row := q.db.QueryRow(ctx, softDeleteClaimDocument, id)
	var i ClaimDocument
	err := row.Scan(
		&i.ID,
		&i.ClaimID,
		&i.FileName,
		&i.FileType,
		&i.FileSize,
		&i.S3Key,
		&i.UploadedBy,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
