// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: claim.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const completeDraftClaim = `-- name: CompleteDraftClaim :one
UPDATE claims SET is_draft = false, draft_completed_at = NOW(), updated_at = NOW() WHERE id = $1 AND is_draft = true RETURNING id, claim_number, policy_id, member_id, provider_id, preauth_id, status, total_amount, approved_amount, co_pay_amount, member_responsibility, diagnosis_codes, service_date, admission_date, discharge_date, notes, rejection_reason, created_by, created_at, updated_at, claim_type, vetted_amount, vetted_by, vetted_at, sla_breach_at, escalated_to, claim_source, idempotency_key, external_claim_id, source_metadata, is_draft, draft_completed_at
`

func (q *Queries) CompleteDraftClaim(ctx context.Context, id uuid.UUID) (Claim, error) {
	row := q.db.QueryRow(ctx, completeDraftClaim, id)
	var i Claim
	err := row.Scan(
		&i.ID,
		&i.ClaimNumber,
		&i.PolicyID,
		&i.MemberID,
		&i.ProviderID,
		&i.PreauthID,
		&i.Status,
		&i.TotalAmount,
		&i.ApprovedAmount,
		&i.CoPayAmount,
		&i.MemberResponsibility,
		&i.DiagnosisCodes,
		&i.ServiceDate,
		&i.AdmissionDate,
		&i.DischargeDate,
		&i.Notes,
		&i.RejectionReason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClaimType,
		&i.VettedAmount,
		&i.VettedBy,
		&i.VettedAt,
		&i.SlaBreachAt,
		&i.EscalatedTo,
		&i.ClaimSource,
		&i.IdempotencyKey,
		&i.ExternalClaimID,
		&i.SourceMetadata,
		&i.IsDraft,
		&i.DraftCompletedAt,
	)
	return i, err
}

const countClaims = `-- name: CountClaims :one
SELECT COUNT(*) FROM claims
`

func (q *Queries) CountClaims(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countClaims)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countClaimsByMemberThisMonth = `-- name: CountClaimsByMemberThisMonth :one
SELECT COUNT(*) FROM claims WHERE member_id = $1 AND created_at >= date_trunc('month', CURRENT_DATE) AND deleted_at IS NULL
`

func (q *Queries) CountClaimsByMemberThisMonth(ctx context.Context, memberID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countClaimsByMemberThisMonth, memberID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countClaimsByStatus = `-- name: CountClaimsByStatus :one
SELECT COUNT(*) FROM claims WHERE status = $1
`

func (q *Queries) CountClaimsByStatus(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRow(ctx, countClaimsByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countClaimsFiltered = `-- name: CountClaimsFiltered :one
SELECT COUNT(*) FROM claims
WHERE ($1::text = '' OR status = $1)
  AND ($2::timestamptz IS NULL OR created_at >= $2)
  AND ($3::timestamptz IS NULL OR created_at <= $3)
  AND ($4::text = '' OR (claim_number ILIKE '%' || $4 || '%' OR status ILIKE '%' || $4 || '%'))
`

type CountClaimsFilteredParams struct {
	StatusFilter string             `json:"status_filter"`
	DateFrom     pgtype.Timestamptz `json:"date_from"`
	DateTo       pgtype.Timestamptz `json:"date_to"`
	Search       string             `json:"search"`
}

func (q *Queries) CountClaimsFiltered(ctx context.Context, arg CountClaimsFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countClaimsFiltered,
		arg.StatusFilter,
		arg.DateFrom,
		arg.DateTo,
		arg.Search,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createClaim = `-- name: CreateClaim :one
INSERT INTO claims (claim_number, policy_id, member_id, provider_id, preauth_id, status, total_amount, diagnosis_codes, service_date, admission_date, discharge_date, notes, created_by, claim_type, sla_breach_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15) RETURNING id, claim_number, policy_id, member_id, provider_id, preauth_id, status, total_amount, approved_amount, co_pay_amount, member_responsibility, diagnosis_codes, service_date, admission_date, discharge_date, notes, rejection_reason, created_by, created_at, updated_at, claim_type, vetted_amount, vetted_by, vetted_at, sla_breach_at, escalated_to, claim_source, idempotency_key, external_claim_id, source_metadata, is_draft, draft_completed_at
`

type CreateClaimParams struct {
	ClaimNumber    string             `json:"claim_number"`
	PolicyID       uuid.UUID          `json:"policy_id"`
	MemberID       uuid.UUID          `json:"member_id"`
	ProviderID     uuid.UUID          `json:"provider_id"`
	PreauthID      pgtype.UUID        `json:"preauth_id"`
	Status         string             `json:"status"`
	TotalAmount    int64              `json:"total_amount"`
	DiagnosisCodes json.RawMessage    `json:"diagnosis_codes"`
	ServiceDate    time.Time          `json:"service_date"`
	AdmissionDate  pgtype.Timestamptz `json:"admission_date"`
	DischargeDate  pgtype.Timestamptz `json:"discharge_date"`
	Notes          string             `json:"notes"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	ClaimType      string             `json:"claim_type"`
	SlaBreachAt    pgtype.Timestamptz `json:"sla_breach_at"`
}

func (q *Queries) CreateClaim(ctx context.Context, arg CreateClaimParams) (Claim, error) {
	row := q.db.QueryRow(ctx, createClaim,
		arg.ClaimNumber,
		arg.PolicyID,
		arg.MemberID,
		arg.ProviderID,
		arg.PreauthID,
		arg.Status,
		arg.TotalAmount,
		arg.DiagnosisCodes,
		arg.ServiceDate,
		arg.AdmissionDate,
		arg.DischargeDate,
		arg.Notes,
		arg.CreatedBy,
		arg.ClaimType,
		arg.SlaBreachAt,
	)
	var i Claim
	err := row.Scan(
		&i.ID,
		&i.ClaimNumber,
		&i.PolicyID,
		&i.MemberID,
		&i.ProviderID,
		&i.PreauthID,
		&i.Status,
		&i.TotalAmount,
		&i.ApprovedAmount,
		&i.CoPayAmount,
		&i.MemberResponsibility,
		&i.DiagnosisCodes,
		&i.ServiceDate,
		&i.AdmissionDate,
		&i.DischargeDate,
		&i.Notes,
		&i.RejectionReason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClaimType,
		&i.VettedAmount,
		&i.VettedBy,
		&i.VettedAt,
		&i.SlaBreachAt,
		&i.EscalatedTo,
		&i.ClaimSource,
		&i.IdempotencyKey,
		&i.ExternalClaimID,
		&i.SourceMetadata,
		&i.IsDraft,
		&i.DraftCompletedAt,
	)
	return i, err
}

const createDraftClaim = `-- name: CreateDraftClaim :one
INSERT INTO claims (claim_number, policy_id, member_id, provider_id, preauth_id, status, total_amount, diagnosis_codes, service_date, admission_date, discharge_date, notes, created_by, claim_type, sla_breach_at, claim_source, is_draft)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, 'INTERNAL', true) RETURNING id, claim_number, policy_id, member_id, provider_id, preauth_id, status, total_amount, approved_amount, co_pay_amount, member_responsibility, diagnosis_codes, service_date, admission_date, discharge_date, notes, rejection_reason, created_by, created_at, updated_at, claim_type, vetted_amount, vetted_by, vetted_at, sla_breach_at, escalated_to, claim_source, idempotency_key, external_claim_id, source_metadata, is_draft, draft_completed_at
`

type CreateDraftClaimParams struct {
	ClaimNumber    string             `json:"claim_number"`
	PolicyID       uuid.UUID          `json:"policy_id"`
	MemberID       uuid.UUID          `json:"member_id"`
	ProviderID     uuid.UUID          `json:"provider_id"`
	PreauthID      pgtype.UUID        `json:"preauth_id"`
	Status         string             `json:"status"`
	TotalAmount    int64              `json:"total_amount"`
	DiagnosisCodes json.RawMessage    `json:"diagnosis_codes"`
	ServiceDate    time.Time          `json:"service_date"`
	AdmissionDate  pgtype.Timestamptz `json:"admission_date"`
	DischargeDate  pgtype.Timestamptz `json:"discharge_date"`
	Notes          string             `json:"notes"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	ClaimType      string             `json:"claim_type"`
	SlaBreachAt    pgtype.Timestamptz `json:"sla_breach_at"`
}

func (q *Queries) CreateDraftClaim(ctx context.Context, arg CreateDraftClaimParams) (Claim, error) {
	row := q.db.QueryRow(ctx, createDraftClaim,
		arg.ClaimNumber,
		arg.PolicyID,
		arg.MemberID,
		arg.ProviderID,
		arg.PreauthID,
		arg.Status,
		arg.TotalAmount,
		arg.DiagnosisCodes,
		arg.ServiceDate,
		arg.AdmissionDate,
		arg.DischargeDate,
		arg.Notes,
		arg.CreatedBy,
		arg.ClaimType,
		arg.SlaBreachAt,
	)
	var i Claim
	err := row.Scan(
		&i.ID,
		&i.ClaimNumber,
		&i.PolicyID,
		&i.MemberID,
		&i.ProviderID,
		&i.PreauthID,
		&i.Status,
		&i.TotalAmount,
		&i.ApprovedAmount,
		&i.CoPayAmount,
		&i.MemberResponsibility,
		&i.DiagnosisCodes,
		&i.ServiceDate,
		&i.AdmissionDate,
		&i.DischargeDate,
		&i.Notes,
		&i.RejectionReason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClaimType,
		&i.VettedAmount,
		&i.VettedBy,
		&i.VettedAt,
		&i.SlaBreachAt,
		&i.EscalatedTo,
		&i.ClaimSource,
		&i.IdempotencyKey,
		&i.ExternalClaimID,
		&i.SourceMetadata,
		&i.IsDraft,
		&i.DraftCompletedAt,
	)
	return i, err
}

const deleteDraftClaim = `-- name: DeleteDraftClaim :exec
DELETE FROM claims WHERE id = $1 AND is_draft = true
`

func (q *Queries) DeleteDraftClaim(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDraftClaim, id)
	return err
}

const findClaimByProviderAndDate = `-- name: FindClaimByProviderAndDate :one
SELECT id, claim_number, policy_id, member_id, provider_id, preauth_id, status, total_amount, approved_amount, co_pay_amount, member_responsibility, diagnosis_codes, service_date, admission_date, discharge_date, notes, rejection_reason, created_by, created_at, updated_at, claim_type, vetted_amount, vetted_by, vetted_at, sla_breach_at, escalated_to, claim_source, idempotency_key, external_claim_id, source_metadata, is_draft, draft_completed_at FROM claims
WHERE provider_id = $1
AND service_date = $2
AND ABS(total_amount - $3) < 100
AND status NOT IN ('REJECTED', 'CANCELLED')
ORDER BY created_at DESC
LIMIT 1
`

type FindClaimByProviderAndDateParams struct {
	ProviderID  uuid.UUID `json:"provider_id"`
	ServiceDate time.Time `json:"service_date"`
	TotalAmount int64     `json:"total_amount"`
}

func (q *Queries) FindClaimByProviderAndDate(ctx context.Context, arg FindClaimByProviderAndDateParams) (Claim, error) {
	row := q.db.QueryRow(ctx, findClaimByProviderAndDate, arg.ProviderID, arg.ServiceDate, arg.TotalAmount)
	var i Claim
	err := row.Scan(
		&i.ID,
		&i.ClaimNumber,
		&i.PolicyID,
		&i.MemberID,
		&i.ProviderID,
		&i.PreauthID,
		&i.Status,
		&i.TotalAmount,
		&i.ApprovedAmount,
		&i.CoPayAmount,
		&i.MemberResponsibility,
		&i.DiagnosisCodes,
		&i.ServiceDate,
		&i.AdmissionDate,
		&i.DischargeDate,
		&i.Notes,
		&i.RejectionReason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClaimType,
		&i.VettedAmount,
		&i.VettedBy,
		&i.VettedAt,
		&i.SlaBreachAt,
		&i.EscalatedTo,
		&i.ClaimSource,
		&i.IdempotencyKey,
		&i.ExternalClaimID,
		&i.SourceMetadata,
		&i.IsDraft,
		&i.DraftCompletedAt,
	)
	return i, err
}

const getApprovedAmountForBenefitThisYear = `-- name: GetApprovedAmountForBenefitThisYear :one
SELECT COALESCE(SUM(c.approved_amount), 0)::bigint as total_approved
FROM claims c
JOIN claim_line_items cli ON cli.claim_id = c.id
JOIN benefits b ON b.plan_id = (SELECT plan_id FROM policies WHERE id = c.policy_id)
WHERE c.member_id = $1
  AND c.status IN ('APPROVED', 'PAID')
  AND b.category = $2
  AND EXTRACT(YEAR FROM c.service_date) = EXTRACT(YEAR FROM NOW())
`

type GetApprovedAmountForBenefitThisYearParams struct {
	MemberID uuid.UUID `json:"member_id"`
	Category string    `json:"category"`
}

func (q *Queries) GetApprovedAmountForBenefitThisYear(ctx context.Context, arg GetApprovedAmountForBenefitThisYearParams) (int64, error) {
	row := q.db.QueryRow(ctx, getApprovedAmountForBenefitThisYear, arg.MemberID, arg.Category)
	var total_approved int64
	err := row.Scan(&total_approved)
	return total_approved, err
}

const getApprovedClaimsForRemittance = `-- name: GetApprovedClaimsForRemittance :many
SELECT id, claim_number, policy_id, member_id, provider_id, preauth_id, status, total_amount, approved_amount, co_pay_amount, member_responsibility, diagnosis_codes, service_date, admission_date, discharge_date, notes, rejection_reason, created_by, created_at, updated_at, claim_type, vetted_amount, vetted_by, vetted_at, sla_breach_at, escalated_to, claim_source, idempotency_key, external_claim_id, source_metadata, is_draft, draft_completed_at FROM claims WHERE status = 'APPROVED' AND provider_id = $1
`

func (q *Queries) GetApprovedClaimsForRemittance(ctx context.Context, providerID uuid.UUID) ([]Claim, error) {
	rows, err := q.db.Query(ctx, getApprovedClaimsForRemittance, providerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Claim{}
	for rows.Next() {
		var i Claim
		if err := rows.Scan(
			&i.ID,
			&i.ClaimNumber,
			&i.PolicyID,
			&i.MemberID,
			&i.ProviderID,
			&i.PreauthID,
			&i.Status,
			&i.TotalAmount,
			&i.ApprovedAmount,
			&i.CoPayAmount,
			&i.MemberResponsibility,
			&i.DiagnosisCodes,
			&i.ServiceDate,
			&i.AdmissionDate,
			&i.DischargeDate,
			&i.Notes,
			&i.RejectionReason,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClaimType,
			&i.VettedAmount,
			&i.VettedBy,
			&i.VettedAt,
			&i.SlaBreachAt,
			&i.EscalatedTo,
			&i.ClaimSource,
			&i.IdempotencyKey,
			&i.ExternalClaimID,
			&i.SourceMetadata,
			&i.IsDraft,
			&i.DraftCompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClaimByExternalClaimID = `-- name: GetClaimByExternalClaimID :one
SELECT id, claim_number, policy_id, member_id, provider_id, preauth_id, status, total_amount, approved_amount, co_pay_amount, member_responsibility, diagnosis_codes, service_date, admission_date, discharge_date, notes, rejection_reason, created_by, created_at, updated_at, claim_type, vetted_amount, vetted_by, vetted_at, sla_breach_at, escalated_to, claim_source, idempotency_key, external_claim_id, source_metadata, is_draft, draft_completed_at FROM claims WHERE external_claim_id = $1
`

func (q *Queries) GetClaimByExternalClaimID(ctx context.Context, externalClaimID pgtype.Text) (Claim, error) {
	row := q.db.QueryRow(ctx, getClaimByExternalClaimID, externalClaimID)
	var i Claim
	err := row.Scan(
		&i.ID,
		&i.ClaimNumber,
		&i.PolicyID,
		&i.MemberID,
		&i.ProviderID,
		&i.PreauthID,
		&i.Status,
		&i.TotalAmount,
		&i.ApprovedAmount,
		&i.CoPayAmount,
		&i.MemberResponsibility,
		&i.DiagnosisCodes,
		&i.ServiceDate,
		&i.AdmissionDate,
		&i.DischargeDate,
		&i.Notes,
		&i.RejectionReason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClaimType,
		&i.VettedAmount,
		&i.VettedBy,
		&i.VettedAt,
		&i.SlaBreachAt,
		&i.EscalatedTo,
		&i.ClaimSource,
		&i.IdempotencyKey,
		&i.ExternalClaimID,
		&i.SourceMetadata,
		&i.IsDraft,
		&i.DraftCompletedAt,
	)
	return i, err
}

const getClaimByID = `-- name: GetClaimByID :one
SELECT id, claim_number, policy_id, member_id, provider_id, preauth_id, status, total_amount, approved_amount, co_pay_amount, member_responsibility, diagnosis_codes, service_date, admission_date, discharge_date, notes, rejection_reason, created_by, created_at, updated_at, claim_type, vetted_amount, vetted_by, vetted_at, sla_breach_at, escalated_to, claim_source, idempotency_key, external_claim_id, source_metadata, is_draft, draft_completed_at FROM claims WHERE id = $1
`

func (q *Queries) GetClaimByID(ctx context.Context, id uuid.UUID) (Claim, error) {
	row := q.db.QueryRow(ctx, getClaimByID, id)
	var i Claim
	err := row.Scan(
		&i.ID,
		&i.ClaimNumber,
		&i.PolicyID,
		&i.MemberID,
		&i.ProviderID,
		&i.PreauthID,
		&i.Status,
		&i.TotalAmount,
		&i.ApprovedAmount,
		&i.CoPayAmount,
		&i.MemberResponsibility,
		&i.DiagnosisCodes,
		&i.ServiceDate,
		&i.AdmissionDate,
		&i.DischargeDate,
		&i.Notes,
		&i.RejectionReason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClaimType,
		&i.VettedAmount,
		&i.VettedBy,
		&i.VettedAt,
		&i.SlaBreachAt,
		&i.EscalatedTo,
		&i.ClaimSource,
		&i.IdempotencyKey,
		&i.ExternalClaimID,
		&i.SourceMetadata,
		&i.IsDraft,
		&i.DraftCompletedAt,
	)
	return i, err
}

const getClaimByIdempotencyKey = `-- name: GetClaimByIdempotencyKey :one
SELECT id, claim_number, policy_id, member_id, provider_id, preauth_id, status, total_amount, approved_amount, co_pay_amount, member_responsibility, diagnosis_codes, service_date, admission_date, discharge_date, notes, rejection_reason, created_by, created_at, updated_at, claim_type, vetted_amount, vetted_by, vetted_at, sla_breach_at, escalated_to, claim_source, idempotency_key, external_claim_id, source_metadata, is_draft, draft_completed_at FROM claims WHERE idempotency_key = $1
`

func (q *Queries) GetClaimByIdempotencyKey(ctx context.Context, idempotencyKey pgtype.Text) (Claim, error) {
	row := q.db.QueryRow(ctx, getClaimByIdempotencyKey, idempotencyKey)
	var i Claim
	err := row.Scan(
		&i.ID,
		&i.ClaimNumber,
		&i.PolicyID,
		&i.MemberID,
		&i.ProviderID,
		&i.PreauthID,
		&i.Status,
		&i.TotalAmount,
		&i.ApprovedAmount,
		&i.CoPayAmount,
		&i.MemberResponsibility,
		&i.DiagnosisCodes,
		&i.ServiceDate,
		&i.AdmissionDate,
		&i.DischargeDate,
		&i.Notes,
		&i.RejectionReason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClaimType,
		&i.VettedAmount,
		&i.VettedBy,
		&i.VettedAt,
		&i.SlaBreachAt,
		&i.EscalatedTo,
		&i.ClaimSource,
		&i.IdempotencyKey,
		&i.ExternalClaimID,
		&i.SourceMetadata,
		&i.IsDraft,
		&i.DraftCompletedAt,
	)
	return i, err
}

const getClaimByNumber = `-- name: GetClaimByNumber :one
SELECT id, claim_number, policy_id, member_id, provider_id, preauth_id, status, total_amount, approved_amount, co_pay_amount, member_responsibility, diagnosis_codes, service_date, admission_date, discharge_date, notes, rejection_reason, created_by, created_at, updated_at, claim_type, vetted_amount, vetted_by, vetted_at, sla_breach_at, escalated_to, claim_source, idempotency_key, external_claim_id, source_metadata, is_draft, draft_completed_at FROM claims WHERE claim_number = $1
`

func (q *Queries) GetClaimByNumber(ctx context.Context, claimNumber string) (Claim, error) {
	row := q.db.QueryRow(ctx, getClaimByNumber, claimNumber)
	var i Claim
	err := row.Scan(
		&i.ID,
		&i.ClaimNumber,
		&i.PolicyID,
		&i.MemberID,
		&i.ProviderID,
		&i.PreauthID,
		&i.Status,
		&i.TotalAmount,
		&i.ApprovedAmount,
		&i.CoPayAmount,
		&i.MemberResponsibility,
		&i.DiagnosisCodes,
		&i.ServiceDate,
		&i.AdmissionDate,
		&i.DischargeDate,
		&i.Notes,
		&i.RejectionReason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClaimType,
		&i.VettedAmount,
		&i.VettedBy,
		&i.VettedAt,
		&i.SlaBreachAt,
		&i.EscalatedTo,
		&i.ClaimSource,
		&i.IdempotencyKey,
		&i.ExternalClaimID,
		&i.SourceMetadata,
		&i.IsDraft,
		&i.DraftCompletedAt,
	)
	return i, err
}

const getClaimsForAdjudication = `-- name: GetClaimsForAdjudication :many
SELECT id, claim_number, policy_id, member_id, provider_id, preauth_id, status, total_amount, approved_amount, co_pay_amount, member_responsibility, diagnosis_codes, service_date, admission_date, discharge_date, notes, rejection_reason, created_by, created_at, updated_at, claim_type, vetted_amount, vetted_by, vetted_at, sla_breach_at, escalated_to, claim_source, idempotency_key, external_claim_id, source_metadata, is_draft, draft_completed_at FROM claims WHERE status = 'VALIDATED' ORDER BY created_at ASC LIMIT $1
`

func (q *Queries) GetClaimsForAdjudication(ctx context.Context, limit int32) ([]Claim, error) {
	rows, err := q.db.Query(ctx, getClaimsForAdjudication, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Claim{}
	for rows.Next() {
		var i Claim
		if err := rows.Scan(
			&i.ID,
			&i.ClaimNumber,
			&i.PolicyID,
			&i.MemberID,
			&i.ProviderID,
			&i.PreauthID,
			&i.Status,
			&i.TotalAmount,
			&i.ApprovedAmount,
			&i.CoPayAmount,
			&i.MemberResponsibility,
			&i.DiagnosisCodes,
			&i.ServiceDate,
			&i.AdmissionDate,
			&i.DischargeDate,
			&i.Notes,
			&i.RejectionReason,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClaimType,
			&i.VettedAmount,
			&i.VettedBy,
			&i.VettedAt,
			&i.SlaBreachAt,
			&i.EscalatedTo,
			&i.ClaimSource,
			&i.IdempotencyKey,
			&i.ExternalClaimID,
			&i.SourceMetadata,
			&i.IsDraft,
			&i.DraftCompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApproachingSLAClaims = `-- name: ListApproachingSLAClaims :many
SELECT id, claim_number, policy_id, member_id, provider_id, preauth_id, status, total_amount, approved_amount, co_pay_amount, member_responsibility, diagnosis_codes, service_date, admission_date, discharge_date, notes, rejection_reason, created_by, created_at, updated_at, claim_type, vetted_amount, vetted_by, vetted_at, sla_breach_at, escalated_to, claim_source, idempotency_key, external_claim_id, source_metadata, is_draft, draft_completed_at FROM claims
WHERE sla_breach_at IS NOT NULL
  AND sla_breach_at > NOW()
  AND sla_breach_at <= NOW() + INTERVAL '24 hours'
  AND status NOT IN ('PAID', 'REJECTED', 'VETTED', 'READY_FOR_PAYMENT')
ORDER BY sla_breach_at ASC
LIMIT $1 OFFSET $2
`

type ListApproachingSLAClaimsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListApproachingSLAClaims(ctx context.Context, arg ListApproachingSLAClaimsParams) ([]Claim, error) {
	rows, err := q.db.Query(ctx, listApproachingSLAClaims, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Claim{}
	for rows.Next() {
		var i Claim
		if err := rows.Scan(
			&i.ID,
			&i.ClaimNumber,
			&i.PolicyID,
			&i.MemberID,
			&i.ProviderID,
			&i.PreauthID,
			&i.Status,
			&i.TotalAmount,
			&i.ApprovedAmount,
			&i.CoPayAmount,
			&i.MemberResponsibility,
			&i.DiagnosisCodes,
			&i.ServiceDate,
			&i.AdmissionDate,
			&i.DischargeDate,
			&i.Notes,
			&i.RejectionReason,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClaimType,
			&i.VettedAmount,
			&i.VettedBy,
			&i.VettedAt,
			&i.SlaBreachAt,
			&i.EscalatedTo,
			&i.ClaimSource,
			&i.IdempotencyKey,
			&i.ExternalClaimID,
			&i.SourceMetadata,
			&i.IsDraft,
			&i.DraftCompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClaims = `-- name: ListClaims :many
SELECT id, claim_number, policy_id, member_id, provider_id, preauth_id, status, total_amount, approved_amount, co_pay_amount, member_responsibility, diagnosis_codes, service_date, admission_date, discharge_date, notes, rejection_reason, created_by, created_at, updated_at, claim_type, vetted_amount, vetted_by, vetted_at, sla_breach_at, escalated_to, claim_source, idempotency_key, external_claim_id, source_metadata, is_draft, draft_completed_at FROM claims ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListClaimsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListClaims(ctx context.Context, arg ListClaimsParams) ([]Claim, error) {
	rows, err := q.db.Query(ctx, listClaims, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Claim{}
	for rows.Next() {
		var i Claim
		if err := rows.Scan(
			&i.ID,
			&i.ClaimNumber,
			&i.PolicyID,
			&i.MemberID,
			&i.ProviderID,
			&i.PreauthID,
			&i.Status,
			&i.TotalAmount,
			&i.ApprovedAmount,
			&i.CoPayAmount,
			&i.MemberResponsibility,
			&i.DiagnosisCodes,
			&i.ServiceDate,
			&i.AdmissionDate,
			&i.DischargeDate,
			&i.Notes,
			&i.RejectionReason,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClaimType,
			&i.VettedAmount,
			&i.VettedBy,
			&i.VettedAt,
			&i.SlaBreachAt,
			&i.EscalatedTo,
			&i.ClaimSource,
			&i.IdempotencyKey,
			&i.ExternalClaimID,
			&i.SourceMetadata,
			&i.IsDraft,
			&i.DraftCompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClaimsByMember = `-- name: ListClaimsByMember :many
SELECT id, claim_number, policy_id, member_id, provider_id, preauth_id, status, total_amount, approved_amount, co_pay_amount, member_responsibility, diagnosis_codes, service_date, admission_date, discharge_date, notes, rejection_reason, created_by, created_at, updated_at, claim_type, vetted_amount, vetted_by, vetted_at, sla_breach_at, escalated_to, claim_source, idempotency_key, external_claim_id, source_metadata, is_draft, draft_completed_at FROM claims WHERE member_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListClaimsByMemberParams struct {
	MemberID uuid.UUID `json:"member_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListClaimsByMember(ctx context.Context, arg ListClaimsByMemberParams) ([]Claim, error) {
	rows, err := q.db.Query(ctx, listClaimsByMember, arg.MemberID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Claim{}
	for rows.Next() {
		var i Claim
		if err := rows.Scan(
			&i.ID,
			&i.ClaimNumber,
			&i.PolicyID,
			&i.MemberID,
			&i.ProviderID,
			&i.PreauthID,
			&i.Status,
			&i.TotalAmount,
			&i.ApprovedAmount,
			&i.CoPayAmount,
			&i.MemberResponsibility,
			&i.DiagnosisCodes,
			&i.ServiceDate,
			&i.AdmissionDate,
			&i.DischargeDate,
			&i.Notes,
			&i.RejectionReason,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClaimType,
			&i.VettedAmount,
			&i.VettedBy,
			&i.VettedAt,
			&i.SlaBreachAt,
			&i.EscalatedTo,
			&i.ClaimSource,
			&i.IdempotencyKey,
			&i.ExternalClaimID,
			&i.SourceMetadata,
			&i.IsDraft,
			&i.DraftCompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClaimsByPolicy = `-- name: ListClaimsByPolicy :many
SELECT id, claim_number, policy_id, member_id, provider_id, preauth_id, status, total_amount, approved_amount, co_pay_amount, member_responsibility, diagnosis_codes, service_date, admission_date, discharge_date, notes, rejection_reason, created_by, created_at, updated_at, claim_type, vetted_amount, vetted_by, vetted_at, sla_breach_at, escalated_to, claim_source, idempotency_key, external_claim_id, source_metadata, is_draft, draft_completed_at FROM claims WHERE policy_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListClaimsByPolicyParams struct {
	PolicyID uuid.UUID `json:"policy_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListClaimsByPolicy(ctx context.Context, arg ListClaimsByPolicyParams) ([]Claim, error) {
	rows, err := q.db.Query(ctx, listClaimsByPolicy, arg.PolicyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Claim{}
	for rows.Next() {
		var i Claim
		if err := rows.Scan(
			&i.ID,
			&i.ClaimNumber,
			&i.PolicyID,
			&i.MemberID,
			&i.ProviderID,
			&i.PreauthID,
			&i.Status,
			&i.TotalAmount,
			&i.ApprovedAmount,
			&i.CoPayAmount,
			&i.MemberResponsibility,
			&i.DiagnosisCodes,
			&i.ServiceDate,
			&i.AdmissionDate,
			&i.DischargeDate,
			&i.Notes,
			&i.RejectionReason,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClaimType,
			&i.VettedAmount,
			&i.VettedBy,
			&i.VettedAt,
			&i.SlaBreachAt,
			&i.EscalatedTo,
			&i.ClaimSource,
			&i.IdempotencyKey,
			&i.ExternalClaimID,
			&i.SourceMetadata,
			&i.IsDraft,
			&i.DraftCompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClaimsByProvider = `-- name: ListClaimsByProvider :many
SELECT id, claim_number, policy_id, member_id, provider_id, preauth_id, status, total_amount, approved_amount, co_pay_amount, member_responsibility, diagnosis_codes, service_date, admission_date, discharge_date, notes, rejection_reason, created_by, created_at, updated_at, claim_type, vetted_amount, vetted_by, vetted_at, sla_breach_at, escalated_to, claim_source, idempotency_key, external_claim_id, source_metadata, is_draft, draft_completed_at FROM claims WHERE provider_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListClaimsByProviderParams struct {
	ProviderID uuid.UUID `json:"provider_id"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

func (q *Queries) ListClaimsByProvider(ctx context.Context, arg ListClaimsByProviderParams) ([]Claim, error) {
	rows, err := q.db.Query(ctx, listClaimsByProvider, arg.ProviderID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Claim{}
	for rows.Next() {
		var i Claim
		if err := rows.Scan(
			&i.ID,
			&i.ClaimNumber,
			&i.PolicyID,
			&i.MemberID,
			&i.ProviderID,
			&i.PreauthID,
			&i.Status,
			&i.TotalAmount,
			&i.ApprovedAmount,
			&i.CoPayAmount,
			&i.MemberResponsibility,
			&i.DiagnosisCodes,
			&i.ServiceDate,
			&i.AdmissionDate,
			&i.DischargeDate,
			&i.Notes,
			&i.RejectionReason,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClaimType,
			&i.VettedAmount,
			&i.VettedBy,
			&i.VettedAt,
			&i.SlaBreachAt,
			&i.EscalatedTo,
			&i.ClaimSource,
			&i.IdempotencyKey,
			&i.ExternalClaimID,
			&i.SourceMetadata,
			&i.IsDraft,
			&i.DraftCompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClaimsByStatus = `-- name: ListClaimsByStatus :many
SELECT id, claim_number, policy_id, member_id, provider_id, preauth_id, status, total_amount, approved_amount, co_pay_amount, member_responsibility, diagnosis_codes, service_date, admission_date, discharge_date, notes, rejection_reason, created_by, created_at, updated_at, claim_type, vetted_amount, vetted_by, vetted_at, sla_breach_at, escalated_to, claim_source, idempotency_key, external_claim_id, source_metadata, is_draft, draft_completed_at FROM claims WHERE status = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListClaimsByStatusParams struct {
	Status string `json:"status"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListClaimsByStatus(ctx context.Context, arg ListClaimsByStatusParams) ([]Claim, error) {
	rows, err := q.db.Query(ctx, listClaimsByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Claim{}
	for rows.Next() {
		var i Claim
		if err := rows.Scan(
			&i.ID,
			&i.ClaimNumber,
			&i.PolicyID,
			&i.MemberID,
			&i.ProviderID,
			&i.PreauthID,
			&i.Status,
			&i.TotalAmount,
			&i.ApprovedAmount,
			&i.CoPayAmount,
			&i.MemberResponsibility,
			&i.DiagnosisCodes,
			&i.ServiceDate,
			&i.AdmissionDate,
			&i.DischargeDate,
			&i.Notes,
			&i.RejectionReason,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClaimType,
			&i.VettedAmount,
			&i.VettedBy,
			&i.VettedAt,
			&i.SlaBreachAt,
			&i.EscalatedTo,
			&i.ClaimSource,
			&i.IdempotencyKey,
			&i.ExternalClaimID,
			&i.SourceMetadata,
			&i.IsDraft,
			&i.DraftCompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClaimsFiltered = `-- name: ListClaimsFiltered :many
SELECT id, claim_number, policy_id, member_id, provider_id, preauth_id, status, total_amount, approved_amount, co_pay_amount, member_responsibility, diagnosis_codes, service_date, admission_date, discharge_date, notes, rejection_reason, created_by, created_at, updated_at, claim_type, vetted_amount, vetted_by, vetted_at, sla_breach_at, escalated_to, claim_source, idempotency_key, external_claim_id, source_metadata, is_draft, draft_completed_at FROM claims
WHERE ($1::text = '' OR status = $1)
  AND ($2::timestamptz IS NULL OR created_at >= $2)
  AND ($3::timestamptz IS NULL OR created_at <= $3)
  AND ($4::text = '' OR (claim_number ILIKE '%' || $4 || '%' OR status ILIKE '%' || $4 || '%'))
ORDER BY created_at DESC
LIMIT $6 OFFSET $5
`

type ListClaimsFilteredParams struct {
	StatusFilter string             `json:"status_filter"`
	DateFrom     pgtype.Timestamptz `json:"date_from"`
	DateTo       pgtype.Timestamptz `json:"date_to"`
	Search       string             `json:"search"`
	QueryOffset  int32              `json:"query_offset"`
	QueryLimit   int32              `json:"query_limit"`
}

func (q *Queries) ListClaimsFiltered(ctx context.Context, arg ListClaimsFilteredParams) ([]Claim, error) {
	rows, err := q.db.Query(ctx, listClaimsFiltered,
		arg.StatusFilter,
		arg.DateFrom,
		arg.DateTo,
		arg.Search,
		arg.QueryOffset,
		arg.QueryLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Claim{}
	for rows.Next() {
		var i Claim
		if err := rows.Scan(
			&i.ID,
			&i.ClaimNumber,
			&i.PolicyID,
			&i.MemberID,
			&i.ProviderID,
			&i.PreauthID,
			&i.Status,
			&i.TotalAmount,
			&i.ApprovedAmount,
			&i.CoPayAmount,
			&i.MemberResponsibility,
			&i.DiagnosisCodes,
			&i.ServiceDate,
			&i.AdmissionDate,
			&i.DischargeDate,
			&i.Notes,
			&i.RejectionReason,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClaimType,
			&i.VettedAmount,
			&i.VettedBy,
			&i.VettedAt,
			&i.SlaBreachAt,
			&i.EscalatedTo,
			&i.ClaimSource,
			&i.IdempotencyKey,
			&i.ExternalClaimID,
			&i.SourceMetadata,
			&i.IsDraft,
			&i.DraftCompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDraftClaims = `-- name: ListDraftClaims :many
SELECT id, claim_number, policy_id, member_id, provider_id, preauth_id, status, total_amount, approved_amount, co_pay_amount, member_responsibility, diagnosis_codes, service_date, admission_date, discharge_date, notes, rejection_reason, created_by, created_at, updated_at, claim_type, vetted_amount, vetted_by, vetted_at, sla_breach_at, escalated_to, claim_source, idempotency_key, external_claim_id, source_metadata, is_draft, draft_completed_at FROM claims WHERE is_draft = true AND created_by = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListDraftClaimsParams struct {
	CreatedBy pgtype.UUID `json:"created_by"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) ListDraftClaims(ctx context.Context, arg ListDraftClaimsParams) ([]Claim, error) {
	rows, err := q.db.Query(ctx, listDraftClaims, arg.CreatedBy, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Claim{}
	for rows.Next() {
		var i Claim
		if err := rows.Scan(
			&i.ID,
			&i.ClaimNumber,
			&i.PolicyID,
			&i.MemberID,
			&i.ProviderID,
			&i.PreauthID,
			&i.Status,
			&i.TotalAmount,
			&i.ApprovedAmount,
			&i.CoPayAmount,
			&i.MemberResponsibility,
			&i.DiagnosisCodes,
			&i.ServiceDate,
			&i.AdmissionDate,
			&i.DischargeDate,
			&i.Notes,
			&i.RejectionReason,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClaimType,
			&i.VettedAmount,
			&i.VettedBy,
			&i.VettedAt,
			&i.SlaBreachAt,
			&i.EscalatedTo,
			&i.ClaimSource,
			&i.IdempotencyKey,
			&i.ExternalClaimID,
			&i.SourceMetadata,
			&i.IsDraft,
			&i.DraftCompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSLABreachedClaims = `-- name: ListSLABreachedClaims :many
SELECT id, claim_number, policy_id, member_id, provider_id, preauth_id, status, total_amount, approved_amount, co_pay_amount, member_responsibility, diagnosis_codes, service_date, admission_date, discharge_date, notes, rejection_reason, created_by, created_at, updated_at, claim_type, vetted_amount, vetted_by, vetted_at, sla_breach_at, escalated_to, claim_source, idempotency_key, external_claim_id, source_metadata, is_draft, draft_completed_at FROM claims
WHERE sla_breach_at IS NOT NULL
  AND sla_breach_at < NOW()
  AND status NOT IN ('PAID', 'REJECTED')
ORDER BY sla_breach_at ASC
LIMIT $1 OFFSET $2
`

type ListSLABreachedClaimsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListSLABreachedClaims(ctx context.Context, arg ListSLABreachedClaimsParams) ([]Claim, error) {
	rows, err := q.db.Query(ctx, listSLABreachedClaims, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Claim{}
	for rows.Next() {
		var i Claim
		if err := rows.Scan(
			&i.ID,
			&i.ClaimNumber,
			&i.PolicyID,
			&i.MemberID,
			&i.ProviderID,
			&i.PreauthID,
			&i.Status,
			&i.TotalAmount,
			&i.ApprovedAmount,
			&i.CoPayAmount,
			&i.MemberResponsibility,
			&i.DiagnosisCodes,
			&i.ServiceDate,
			&i.AdmissionDate,
			&i.DischargeDate,
			&i.Notes,
			&i.RejectionReason,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClaimType,
			&i.VettedAmount,
			&i.VettedBy,
			&i.VettedAt,
			&i.SlaBreachAt,
			&i.EscalatedTo,
			&i.ClaimSource,
			&i.IdempotencyKey,
			&i.ExternalClaimID,
			&i.SourceMetadata,
			&i.IsDraft,
			&i.DraftCompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markClaimReadyForPayment = `-- name: MarkClaimReadyForPayment :one
UPDATE claims SET status = 'READY_FOR_PAYMENT', updated_at = NOW() WHERE id = $1 RETURNING id, claim_number, policy_id, member_id, provider_id, preauth_id, status, total_amount, approved_amount, co_pay_amount, member_responsibility, diagnosis_codes, service_date, admission_date, discharge_date, notes, rejection_reason, created_by, created_at, updated_at, claim_type, vetted_amount, vetted_by, vetted_at, sla_breach_at, escalated_to, claim_source, idempotency_key, external_claim_id, source_metadata, is_draft, draft_completed_at
`

func (q *Queries) MarkClaimReadyForPayment(ctx context.Context, id uuid.UUID) (Claim, error) {
	row := q.db.QueryRow(ctx, markClaimReadyForPayment, id)
	var i Claim
	err := row.Scan(
		&i.ID,
		&i.ClaimNumber,
		&i.PolicyID,
		&i.MemberID,
		&i.ProviderID,
		&i.PreauthID,
		&i.Status,
		&i.TotalAmount,
		&i.ApprovedAmount,
		&i.CoPayAmount,
		&i.MemberResponsibility,
		&i.DiagnosisCodes,
		&i.ServiceDate,
		&i.AdmissionDate,
		&i.DischargeDate,
		&i.Notes,
		&i.RejectionReason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClaimType,
		&i.VettedAmount,
		&i.VettedBy,
		&i.VettedAt,
		&i.SlaBreachAt,
		&i.EscalatedTo,
		&i.ClaimSource,
		&i.IdempotencyKey,
		&i.ExternalClaimID,
		&i.SourceMetadata,
		&i.IsDraft,
		&i.DraftCompletedAt,
	)
	return i, err
}

const setClaimEscalatedTo = `-- name: SetClaimEscalatedTo :exec
UPDATE claims SET escalated_to = $2, updated_at = now() WHERE id = $1
`

type SetClaimEscalatedToParams struct {
	ID          uuid.UUID   `json:"id"`
	EscalatedTo pgtype.Text `json:"escalated_to"`
}

func (q *Queries) SetClaimEscalatedTo(ctx context.Context, arg SetClaimEscalatedToParams) error {
	_, err := q.db.Exec(ctx, setClaimEscalatedTo, arg.ID, arg.EscalatedTo)
	return err
}

const updateClaimAmounts = `-- name: UpdateClaimAmounts :one
UPDATE claims SET
    approved_amount = $2,
    co_pay_amount = $3,
    member_responsibility = $4,
    updated_at = NOW()
WHERE id = $1 RETURNING id, claim_number, policy_id, member_id, provider_id, preauth_id, status, total_amount, approved_amount, co_pay_amount, member_responsibility, diagnosis_codes, service_date, admission_date, discharge_date, notes, rejection_reason, created_by, created_at, updated_at, claim_type, vetted_amount, vetted_by, vetted_at, sla_breach_at, escalated_to, claim_source, idempotency_key, external_claim_id, source_metadata, is_draft, draft_completed_at
`

type UpdateClaimAmountsParams struct {
	ID                   uuid.UUID `json:"id"`
	ApprovedAmount       int64     `json:"approved_amount"`
	CoPayAmount          int64     `json:"co_pay_amount"`
	MemberResponsibility int64     `json:"member_responsibility"`
}

func (q *Queries) UpdateClaimAmounts(ctx context.Context, arg UpdateClaimAmountsParams) (Claim, error) {
	row := q.db.QueryRow(ctx, updateClaimAmounts,
		arg.ID,
		arg.ApprovedAmount,
		arg.CoPayAmount,
		arg.MemberResponsibility,
	)
	var i Claim
	err := row.Scan(
		&i.ID,
		&i.ClaimNumber,
		&i.PolicyID,
		&i.MemberID,
		&i.ProviderID,
		&i.PreauthID,
		&i.Status,
		&i.TotalAmount,
		&i.ApprovedAmount,
		&i.CoPayAmount,
		&i.MemberResponsibility,
		&i.DiagnosisCodes,
		&i.ServiceDate,
		&i.AdmissionDate,
		&i.DischargeDate,
		&i.Notes,
		&i.RejectionReason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClaimType,
		&i.VettedAmount,
		&i.VettedBy,
		&i.VettedAt,
		&i.SlaBreachAt,
		&i.EscalatedTo,
		&i.ClaimSource,
		&i.IdempotencyKey,
		&i.ExternalClaimID,
		&i.SourceMetadata,
		&i.IsDraft,
		&i.DraftCompletedAt,
	)
	return i, err
}

const updateClaimRejection = `-- name: UpdateClaimRejection :one
UPDATE claims SET status = 'REJECTED', rejection_reason = $2, updated_at = NOW() WHERE id = $1 RETURNING id, claim_number, policy_id, member_id, provider_id, preauth_id, status, total_amount, approved_amount, co_pay_amount, member_responsibility, diagnosis_codes, service_date, admission_date, discharge_date, notes, rejection_reason, created_by, created_at, updated_at, claim_type, vetted_amount, vetted_by, vetted_at, sla_breach_at, escalated_to, claim_source, idempotency_key, external_claim_id, source_metadata, is_draft, draft_completed_at
`

type UpdateClaimRejectionParams struct {
	ID              uuid.UUID   `json:"id"`
	RejectionReason pgtype.Text `json:"rejection_reason"`
}

func (q *Queries) UpdateClaimRejection(ctx context.Context, arg UpdateClaimRejectionParams) (Claim, error) {
	row := q.db.QueryRow(ctx, updateClaimRejection, arg.ID, arg.RejectionReason)
	var i Claim
	err := row.Scan(
		&i.ID,
		&i.ClaimNumber,
		&i.PolicyID,
		&i.MemberID,
		&i.ProviderID,
		&i.PreauthID,
		&i.Status,
		&i.TotalAmount,
		&i.ApprovedAmount,
		&i.CoPayAmount,
		&i.MemberResponsibility,
		&i.DiagnosisCodes,
		&i.ServiceDate,
		&i.AdmissionDate,
		&i.DischargeDate,
		&i.Notes,
		&i.RejectionReason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClaimType,
		&i.VettedAmount,
		&i.VettedBy,
		&i.VettedAt,
		&i.SlaBreachAt,
		&i.EscalatedTo,
		&i.ClaimSource,
		&i.IdempotencyKey,
		&i.ExternalClaimID,
		&i.SourceMetadata,
		&i.IsDraft,
		&i.DraftCompletedAt,
	)
	return i, err
}

const updateClaimSource = `-- name: UpdateClaimSource :exec
UPDATE claims SET
    claim_source = $2,
    idempotency_key = $3,
    external_claim_id = $4,
    source_metadata = $5,
    updated_at = NOW()
WHERE id = $1
`

type UpdateClaimSourceParams struct {
	ID              uuid.UUID       `json:"id"`
	ClaimSource     string          `json:"claim_source"`
	IdempotencyKey  pgtype.Text     `json:"idempotency_key"`
	ExternalClaimID pgtype.Text     `json:"external_claim_id"`
	SourceMetadata  json.RawMessage `json:"source_metadata"`
}

func (q *Queries) UpdateClaimSource(ctx context.Context, arg UpdateClaimSourceParams) error {
	_, err := q.db.Exec(ctx, updateClaimSource,
		arg.ID,
		arg.ClaimSource,
		arg.IdempotencyKey,
		arg.ExternalClaimID,
		arg.SourceMetadata,
	)
	return err
}

const updateClaimStatus = `-- name: UpdateClaimStatus :one
UPDATE claims SET status = $2, updated_at = NOW() WHERE id = $1 RETURNING id, claim_number, policy_id, member_id, provider_id, preauth_id, status, total_amount, approved_amount, co_pay_amount, member_responsibility, diagnosis_codes, service_date, admission_date, discharge_date, notes, rejection_reason, created_by, created_at, updated_at, claim_type, vetted_amount, vetted_by, vetted_at, sla_breach_at, escalated_to, claim_source, idempotency_key, external_claim_id, source_metadata, is_draft, draft_completed_at
`

type UpdateClaimStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateClaimStatus(ctx context.Context, arg UpdateClaimStatusParams) (Claim, error) {
	row := q.db.QueryRow(ctx, updateClaimStatus, arg.ID, arg.Status)
	var i Claim
	err := row.Scan(
		&i.ID,
		&i.ClaimNumber,
		&i.PolicyID,
		&i.MemberID,
		&i.ProviderID,
		&i.PreauthID,
		&i.Status,
		&i.TotalAmount,
		&i.ApprovedAmount,
		&i.CoPayAmount,
		&i.MemberResponsibility,
		&i.DiagnosisCodes,
		&i.ServiceDate,
		&i.AdmissionDate,
		&i.DischargeDate,
		&i.Notes,
		&i.RejectionReason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClaimType,
		&i.VettedAmount,
		&i.VettedBy,
		&i.VettedAt,
		&i.SlaBreachAt,
		&i.EscalatedTo,
		&i.ClaimSource,
		&i.IdempotencyKey,
		&i.ExternalClaimID,
		&i.SourceMetadata,
		&i.IsDraft,
		&i.DraftCompletedAt,
	)
	return i, err
}

const updateDraftClaim = `-- name: UpdateDraftClaim :one
UPDATE claims SET
    policy_id = $2,
    member_id = $3,
    provider_id = $4,
    preauth_id = $5,
    diagnosis_codes = $6,
    service_date = $7,
    notes = $8,
    claim_type = $9,
    total_amount = $10,
    updated_at = NOW()
WHERE id = $1 AND is_draft = true RETURNING id, claim_number, policy_id, member_id, provider_id, preauth_id, status, total_amount, approved_amount, co_pay_amount, member_responsibility, diagnosis_codes, service_date, admission_date, discharge_date, notes, rejection_reason, created_by, created_at, updated_at, claim_type, vetted_amount, vetted_by, vetted_at, sla_breach_at, escalated_to, claim_source, idempotency_key, external_claim_id, source_metadata, is_draft, draft_completed_at
`

type UpdateDraftClaimParams struct {
	ID             uuid.UUID       `json:"id"`
	PolicyID       uuid.UUID       `json:"policy_id"`
	MemberID       uuid.UUID       `json:"member_id"`
	ProviderID     uuid.UUID       `json:"provider_id"`
	PreauthID      pgtype.UUID     `json:"preauth_id"`
	DiagnosisCodes json.RawMessage `json:"diagnosis_codes"`
	ServiceDate    time.Time       `json:"service_date"`
	Notes          string          `json:"notes"`
	ClaimType      string          `json:"claim_type"`
	TotalAmount    int64           `json:"total_amount"`
}

func (q *Queries) UpdateDraftClaim(ctx context.Context, arg UpdateDraftClaimParams) (Claim, error) {
	row := q.db.QueryRow(ctx, updateDraftClaim,
		arg.ID,
		arg.PolicyID,
		arg.MemberID,
		arg.ProviderID,
		arg.PreauthID,
		arg.DiagnosisCodes,
		arg.ServiceDate,
		arg.Notes,
		arg.ClaimType,
		arg.TotalAmount,
	)
	var i Claim
	err := row.Scan(
		&i.ID,
		&i.ClaimNumber,
		&i.PolicyID,
		&i.MemberID,
		&i.ProviderID,
		&i.PreauthID,
		&i.Status,
		&i.TotalAmount,
		&i.ApprovedAmount,
		&i.CoPayAmount,
		&i.MemberResponsibility,
		&i.DiagnosisCodes,
		&i.ServiceDate,
		&i.AdmissionDate,
		&i.DischargeDate,
		&i.Notes,
		&i.RejectionReason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClaimType,
		&i.VettedAmount,
		&i.VettedBy,
		&i.VettedAt,
		&i.SlaBreachAt,
		&i.EscalatedTo,
		&i.ClaimSource,
		&i.IdempotencyKey,
		&i.ExternalClaimID,
		&i.SourceMetadata,
		&i.IsDraft,
		&i.DraftCompletedAt,
	)
	return i, err
}

const vetClaim = `-- name: VetClaim :one
UPDATE claims SET
    vetted_amount = $2,
    vetted_by = $3,
    vetted_at = NOW(),
    status = $4,
    updated_at = NOW()
WHERE id = $1 RETURNING id, claim_number, policy_id, member_id, provider_id, preauth_id, status, total_amount, approved_amount, co_pay_amount, member_responsibility, diagnosis_codes, service_date, admission_date, discharge_date, notes, rejection_reason, created_by, created_at, updated_at, claim_type, vetted_amount, vetted_by, vetted_at, sla_breach_at, escalated_to, claim_source, idempotency_key, external_claim_id, source_metadata, is_draft, draft_completed_at
`

type VetClaimParams struct {
	ID           uuid.UUID   `json:"id"`
	VettedAmount pgtype.Int8 `json:"vetted_amount"`
	VettedBy     pgtype.UUID `json:"vetted_by"`
	Status       string      `json:"status"`
}

func (q *Queries) VetClaim(ctx context.Context, arg VetClaimParams) (Claim, error) {
	row := q.db.QueryRow(ctx, vetClaim,
		arg.ID,
		arg.VettedAmount,
		arg.VettedBy,
		arg.Status,
	)
	var i Claim
	err := row.Scan(
		&i.ID,
		&i.ClaimNumber,
		&i.PolicyID,
		&i.MemberID,
		&i.ProviderID,
		&i.PreauthID,
		&i.Status,
		&i.TotalAmount,
		&i.ApprovedAmount,
		&i.CoPayAmount,
		&i.MemberResponsibility,
		&i.DiagnosisCodes,
		&i.ServiceDate,
		&i.AdmissionDate,
		&i.DischargeDate,
		&i.Notes,
		&i.RejectionReason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClaimType,
		&i.VettedAmount,
		&i.VettedBy,
		&i.VettedAt,
		&i.SlaBreachAt,
		&i.EscalatedTo,
		&i.ClaimSource,
		&i.IdempotencyKey,
		&i.ExternalClaimID,
		&i.SourceMetadata,
		&i.IsDraft,
		&i.DraftCompletedAt,
	)
	return i, err
}
