// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: claim_line_item.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createClaimLineItem = `-- name: CreateClaimLineItem :one
INSERT INTO claim_line_items (claim_id, procedure_code, procedure_name, diagnosis_code, quantity, unit_price, total_price)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, claim_id, procedure_code, procedure_name, diagnosis_code, quantity, unit_price, total_price, approved_amount, created_at, updated_at
`

type CreateClaimLineItemParams struct {
	ClaimID       uuid.UUID   `json:"claim_id"`
	ProcedureCode string      `json:"procedure_code"`
	ProcedureName string      `json:"procedure_name"`
	DiagnosisCode pgtype.Text `json:"diagnosis_code"`
	Quantity      int32       `json:"quantity"`
	UnitPrice     int64       `json:"unit_price"`
	TotalPrice    int64       `json:"total_price"`
}

func (q *Queries) CreateClaimLineItem(ctx context.Context, arg CreateClaimLineItemParams) (ClaimLineItem, error) {
	row := q.db.QueryRow(ctx, createClaimLineItem,
		arg.ClaimID,
		arg.ProcedureCode,
		arg.ProcedureName,
		arg.DiagnosisCode,
		arg.Quantity,
		arg.UnitPrice,
		arg.TotalPrice,
	)
	var i ClaimLineItem
	err := row.Scan(
		&i.ID,
		&i.ClaimID,
		&i.ProcedureCode,
		&i.ProcedureName,
		&i.DiagnosisCode,
		&i.Quantity,
		&i.UnitPrice,
		&i.TotalPrice,
		&i.ApprovedAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteClaimLineItem = `-- name: DeleteClaimLineItem :exec
DELETE FROM claim_line_items WHERE id = $1
`

func (q *Queries) DeleteClaimLineItem(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteClaimLineItem, id)
	return err
}

const getClaimLineItemByID = `-- name: GetClaimLineItemByID :one
SELECT id, claim_id, procedure_code, procedure_name, diagnosis_code, quantity, unit_price, total_price, approved_amount, created_at, updated_at FROM claim_line_items WHERE id = $1
`

func (q *Queries) GetClaimLineItemByID(ctx context.Context, id uuid.UUID) (ClaimLineItem, error) {
	row := q.db.QueryRow(ctx, getClaimLineItemByID, id)
	var i ClaimLineItem
	err := row.Scan(
		&i.ID,
		&i.ClaimID,
		&i.ProcedureCode,
		&i.ProcedureName,
		&i.DiagnosisCode,
		&i.Quantity,
		&i.UnitPrice,
		&i.TotalPrice,
		&i.ApprovedAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listClaimLineItems = `-- name: ListClaimLineItems :many
SELECT id, claim_id, procedure_code, procedure_name, diagnosis_code, quantity, unit_price, total_price, approved_amount, created_at, updated_at FROM claim_line_items WHERE claim_id = $1 ORDER BY created_at
`

func (q *Queries) ListClaimLineItems(ctx context.Context, claimID uuid.UUID) ([]ClaimLineItem, error) {
	rows, err := q.db.Query(ctx, listClaimLineItems, claimID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimLineItem{}
	for rows.Next() {
		var i ClaimLineItem
		if err := rows.Scan(
			&i.ID,
			&i.ClaimID,
			&i.ProcedureCode,
			&i.ProcedureName,
			&i.DiagnosisCode,
			&i.Quantity,
			&i.UnitPrice,
			&i.TotalPrice,
			&i.ApprovedAmount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClaimLineItemApprovedAmount = `-- name: UpdateClaimLineItemApprovedAmount :one
UPDATE claim_line_items SET approved_amount = $2, updated_at = NOW() WHERE id = $1 RETURNING id, claim_id, procedure_code, procedure_name, diagnosis_code, quantity, unit_price, total_price, approved_amount, created_at, updated_at
`

type UpdateClaimLineItemApprovedAmountParams struct {
	ID             uuid.UUID `json:"id"`
	ApprovedAmount int64     `json:"approved_amount"`
}

func (q *Queries) UpdateClaimLineItemApprovedAmount(ctx context.Context, arg UpdateClaimLineItemApprovedAmountParams) (ClaimLineItem, error) {
	row := q.db.QueryRow(ctx, updateClaimLineItemApprovedAmount, arg.ID, arg.ApprovedAmount)
	var i ClaimLineItem
	err := row.Scan(
		&i.ID,
		&i.ClaimID,
		&i.ProcedureCode,
		&i.ProcedureName,
		&i.DiagnosisCode,
		&i.Quantity,
		&i.UnitPrice,
		&i.TotalPrice,
		&i.ApprovedAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
