// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: commissions.sql

package db

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCommissionPayment = `-- name: CreateCommissionPayment :one
INSERT INTO commission_payments (policy_id, intermediary_id, commission_rule_id, amount, currency, status, period_start, period_end, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, policy_id, intermediary_id, commission_rule_id, amount, currency, status, period_start, period_end, paid_at, created_by, created_at, updated_at
`

type CreateCommissionPaymentParams struct {
	PolicyID         uuid.UUID   `json:"policy_id"`
	IntermediaryID   uuid.UUID   `json:"intermediary_id"`
	CommissionRuleID uuid.UUID   `json:"commission_rule_id"`
	Amount           int64       `json:"amount"`
	Currency         string      `json:"currency"`
	Status           string      `json:"status"`
	PeriodStart      time.Time   `json:"period_start"`
	PeriodEnd        time.Time   `json:"period_end"`
	CreatedBy        pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateCommissionPayment(ctx context.Context, arg CreateCommissionPaymentParams) (CommissionPayment, error) {
	row := q.db.QueryRow(ctx, createCommissionPayment,
		arg.PolicyID,
		arg.IntermediaryID,
		arg.CommissionRuleID,
		arg.Amount,
		arg.Currency,
		arg.Status,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.CreatedBy,
	)
	var i CommissionPayment
	err := row.Scan(
		&i.ID,
		&i.PolicyID,
		&i.IntermediaryID,
		&i.CommissionRuleID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.PaidAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCommissionRule = `-- name: CreateCommissionRule :one
INSERT INTO commission_rules (plan_id, intermediary_id, rate_pct, flat_amount, effective_from, effective_to, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, plan_id, intermediary_id, rate_pct, flat_amount, effective_from, effective_to, created_by, created_at, updated_at
`

type CreateCommissionRuleParams struct {
	PlanID         uuid.UUID          `json:"plan_id"`
	IntermediaryID uuid.UUID          `json:"intermediary_id"`
	RatePct        pgtype.Numeric     `json:"rate_pct"`
	FlatAmount     int64              `json:"flat_amount"`
	EffectiveFrom  time.Time          `json:"effective_from"`
	EffectiveTo    pgtype.Timestamptz `json:"effective_to"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
}

func (q *Queries) CreateCommissionRule(ctx context.Context, arg CreateCommissionRuleParams) (CommissionRule, error) {
	row := q.db.QueryRow(ctx, createCommissionRule,
		arg.PlanID,
		arg.IntermediaryID,
		arg.RatePct,
		arg.FlatAmount,
		arg.EffectiveFrom,
		arg.EffectiveTo,
		arg.CreatedBy,
	)
	var i CommissionRule
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.IntermediaryID,
		&i.RatePct,
		&i.FlatAmount,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCommissionRuleByID = `-- name: GetCommissionRuleByID :one
SELECT id, plan_id, intermediary_id, rate_pct, flat_amount, effective_from, effective_to, created_by, created_at, updated_at FROM commission_rules WHERE id = $1
`

func (q *Queries) GetCommissionRuleByID(ctx context.Context, id uuid.UUID) (CommissionRule, error) {
	row := q.db.QueryRow(ctx, getCommissionRuleByID, id)
	var i CommissionRule
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.IntermediaryID,
		&i.RatePct,
		&i.FlatAmount,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCommissionPayments = `-- name: ListCommissionPayments :many
SELECT id, policy_id, intermediary_id, commission_rule_id, amount, currency, status, period_start, period_end, paid_at, created_by, created_at, updated_at FROM commission_payments ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListCommissionPaymentsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListCommissionPayments(ctx context.Context, arg ListCommissionPaymentsParams) ([]CommissionPayment, error) {
	rows, err := q.db.Query(ctx, listCommissionPayments, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CommissionPayment{}
	for rows.Next() {
		var i CommissionPayment
		if err := rows.Scan(
			&i.ID,
			&i.PolicyID,
			&i.IntermediaryID,
			&i.CommissionRuleID,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.PaidAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommissionPaymentsByIntermediary = `-- name: ListCommissionPaymentsByIntermediary :many
SELECT id, policy_id, intermediary_id, commission_rule_id, amount, currency, status, period_start, period_end, paid_at, created_by, created_at, updated_at FROM commission_payments WHERE intermediary_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListCommissionPaymentsByIntermediaryParams struct {
	IntermediaryID uuid.UUID `json:"intermediary_id"`
	Limit          int32     `json:"limit"`
	Offset         int32     `json:"offset"`
}

func (q *Queries) ListCommissionPaymentsByIntermediary(ctx context.Context, arg ListCommissionPaymentsByIntermediaryParams) ([]CommissionPayment, error) {
	rows, err := q.db.Query(ctx, listCommissionPaymentsByIntermediary, arg.IntermediaryID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CommissionPayment{}
	for rows.Next() {
		var i CommissionPayment
		if err := rows.Scan(
			&i.ID,
			&i.PolicyID,
			&i.IntermediaryID,
			&i.CommissionRuleID,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.PaidAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommissionRulesByPlan = `-- name: ListCommissionRulesByPlan :many
SELECT id, plan_id, intermediary_id, rate_pct, flat_amount, effective_from, effective_to, created_by, created_at, updated_at FROM commission_rules WHERE plan_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListCommissionRulesByPlan(ctx context.Context, planID uuid.UUID) ([]CommissionRule, error) {
	rows, err := q.db.Query(ctx, listCommissionRulesByPlan, planID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CommissionRule{}
	for rows.Next() {
		var i CommissionRule
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.IntermediaryID,
			&i.RatePct,
			&i.FlatAmount,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCommissionPaymentStatus = `-- name: UpdateCommissionPaymentStatus :one
UPDATE commission_payments SET status = $2, updated_at = NOW() WHERE id = $1 RETURNING id, policy_id, intermediary_id, commission_rule_id, amount, currency, status, period_start, period_end, paid_at, created_by, created_at, updated_at
`

type UpdateCommissionPaymentStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateCommissionPaymentStatus(ctx context.Context, arg UpdateCommissionPaymentStatusParams) (CommissionPayment, error) {
	row := q.db.QueryRow(ctx, updateCommissionPaymentStatus, arg.ID, arg.Status)
	var i CommissionPayment
	err := row.Scan(
		&i.ID,
		&i.PolicyID,
		&i.IntermediaryID,
		&i.CommissionRuleID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.PaidAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
