// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: contract.sql

package db

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createContract = `-- name: CreateContract :one
INSERT INTO contracts (provider_id, start_date, end_date, terms, status, created_by)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, provider_id, start_date, end_date, terms, status, created_by, created_at, updated_at
`

type CreateContractParams struct {
	ProviderID uuid.UUID   `json:"provider_id"`
	StartDate  time.Time   `json:"start_date"`
	EndDate    time.Time   `json:"end_date"`
	Terms      string      `json:"terms"`
	Status     string      `json:"status"`
	CreatedBy  pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateContract(ctx context.Context, arg CreateContractParams) (Contract, error) {
	row := q.db.QueryRow(ctx, createContract,
		arg.ProviderID,
		arg.StartDate,
		arg.EndDate,
		arg.Terms,
		arg.Status,
		arg.CreatedBy,
	)
	var i Contract
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.StartDate,
		&i.EndDate,
		&i.Terms,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveContractByProvider = `-- name: GetActiveContractByProvider :one
SELECT id, provider_id, start_date, end_date, terms, status, created_by, created_at, updated_at FROM contracts WHERE provider_id = $1 AND status = 'ACTIVE' ORDER BY start_date DESC LIMIT 1
`

func (q *Queries) GetActiveContractByProvider(ctx context.Context, providerID uuid.UUID) (Contract, error) {
	row := q.db.QueryRow(ctx, getActiveContractByProvider, providerID)
	var i Contract
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.StartDate,
		&i.EndDate,
		&i.Terms,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContractByID = `-- name: GetContractByID :one
SELECT id, provider_id, start_date, end_date, terms, status, created_by, created_at, updated_at FROM contracts WHERE id = $1
`

func (q *Queries) GetContractByID(ctx context.Context, id uuid.UUID) (Contract, error) {
	row := q.db.QueryRow(ctx, getContractByID, id)
	var i Contract
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.StartDate,
		&i.EndDate,
		&i.Terms,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listContractsByProvider = `-- name: ListContractsByProvider :many
SELECT id, provider_id, start_date, end_date, terms, status, created_by, created_at, updated_at FROM contracts WHERE provider_id = $1 ORDER BY start_date DESC
`

func (q *Queries) ListContractsByProvider(ctx context.Context, providerID uuid.UUID) ([]Contract, error) {
	rows, err := q.db.Query(ctx, listContractsByProvider, providerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Contract{}
	for rows.Next() {
		var i Contract
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.StartDate,
			&i.EndDate,
			&i.Terms,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContractStatus = `-- name: UpdateContractStatus :one
UPDATE contracts SET status = $2, updated_at = NOW() WHERE id = $1 RETURNING id, provider_id, start_date, end_date, terms, status, created_by, created_at, updated_at
`

type UpdateContractStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateContractStatus(ctx context.Context, arg UpdateContractStatusParams) (Contract, error) {
	row := q.db.QueryRow(ctx, updateContractStatus, arg.ID, arg.Status)
	var i Contract
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.StartDate,
		&i.EndDate,
		&i.Terms,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
