// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: document.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (entity_type, entity_id, document_type, status, file_name, file_size, mime_type, s3_key, uploaded_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING id, entity_type, entity_id, document_type, status, file_name, file_size, mime_type, s3_key, uploaded_by, confirmed_at, deleted_at, created_at, updated_at
`

type CreateDocumentParams struct {
	EntityType   string    `json:"entity_type"`
	EntityID     uuid.UUID `json:"entity_id"`
	DocumentType string    `json:"document_type"`
	Status       string    `json:"status"`
	FileName     string    `json:"file_name"`
	FileSize     int64     `json:"file_size"`
	MimeType     string    `json:"mime_type"`
	S3Key        string    `json:"s3_key"`
	UploadedBy   uuid.UUID `json:"uploaded_by"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, createDocument,
		arg.EntityType,
		arg.EntityID,
		arg.DocumentType,
		arg.Status,
		arg.FileName,
		arg.FileSize,
		arg.MimeType,
		arg.S3Key,
		arg.UploadedBy,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.EntityID,
		&i.DocumentType,
		&i.Status,
		&i.FileName,
		&i.FileSize,
		&i.MimeType,
		&i.S3Key,
		&i.UploadedBy,
		&i.ConfirmedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDocumentByID = `-- name: GetDocumentByID :one
SELECT id, entity_type, entity_id, document_type, status, file_name, file_size, mime_type, s3_key, uploaded_by, confirmed_at, deleted_at, created_at, updated_at FROM documents WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetDocumentByID(ctx context.Context, id uuid.UUID) (Document, error) {
	row := q.db.QueryRow(ctx, getDocumentByID, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.EntityID,
		&i.DocumentType,
		&i.Status,
		&i.FileName,
		&i.FileSize,
		&i.MimeType,
		&i.S3Key,
		&i.UploadedBy,
		&i.ConfirmedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDocumentsByEntity = `-- name: ListDocumentsByEntity :many
SELECT id, entity_type, entity_id, document_type, status, file_name, file_size, mime_type, s3_key, uploaded_by, confirmed_at, deleted_at, created_at, updated_at FROM documents WHERE entity_type = $1 AND entity_id = $2 AND deleted_at IS NULL ORDER BY created_at DESC
`

type ListDocumentsByEntityParams struct {
	EntityType string    `json:"entity_type"`
	EntityID   uuid.UUID `json:"entity_id"`
}

func (q *Queries) ListDocumentsByEntity(ctx context.Context, arg ListDocumentsByEntityParams) ([]Document, error) {
	rows, err := q.db.Query(ctx, listDocumentsByEntity, arg.EntityType, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityID,
			&i.DocumentType,
			&i.Status,
			&i.FileName,
			&i.FileSize,
			&i.MimeType,
			&i.S3Key,
			&i.UploadedBy,
			&i.ConfirmedAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteDocument = `-- name: SoftDeleteDocument :exec
UPDATE documents SET status = 'DELETED', deleted_at = $2, updated_at = NOW() WHERE id = $1
`

type SoftDeleteDocumentParams struct {
	ID        uuid.UUID          `json:"id"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) SoftDeleteDocument(ctx context.Context, arg SoftDeleteDocumentParams) error {
	_, err := q.db.Exec(ctx, softDeleteDocument, arg.ID, arg.DeletedAt)
	return err
}

const updateDocumentStatus = `-- name: UpdateDocumentStatus :exec
UPDATE documents SET status = $2, confirmed_at = $3, updated_at = NOW() WHERE id = $1
`

type UpdateDocumentStatusParams struct {
	ID          uuid.UUID          `json:"id"`
	Status      string             `json:"status"`
	ConfirmedAt pgtype.Timestamptz `json:"confirmed_at"`
}

func (q *Queries) UpdateDocumentStatus(ctx context.Context, arg UpdateDocumentStatusParams) error {
	_, err := q.db.Exec(ctx, updateDocumentStatus, arg.ID, arg.Status, arg.ConfirmedAt)
	return err
}
