// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: endorsement.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createEndorsement = `-- name: CreateEndorsement :one
INSERT INTO endorsements (policy_id, endorsement_type, status, effective_date, changes, reason, premium_adjustment, requested_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING id, policy_id, endorsement_type, status, effective_date, changes, reason, premium_adjustment, requested_by, approved_by, approved_at, applied_at, created_at, updated_at
`

type CreateEndorsementParams struct {
	PolicyID          uuid.UUID       `json:"policy_id"`
	EndorsementType   string          `json:"endorsement_type"`
	Status            string          `json:"status"`
	EffectiveDate     time.Time       `json:"effective_date"`
	Changes           json.RawMessage `json:"changes"`
	Reason            pgtype.Text     `json:"reason"`
	PremiumAdjustment pgtype.Int8     `json:"premium_adjustment"`
	RequestedBy       uuid.UUID       `json:"requested_by"`
}

func (q *Queries) CreateEndorsement(ctx context.Context, arg CreateEndorsementParams) (Endorsement, error) {
	row := q.db.QueryRow(ctx, createEndorsement,
		arg.PolicyID,
		arg.EndorsementType,
		arg.Status,
		arg.EffectiveDate,
		arg.Changes,
		arg.Reason,
		arg.PremiumAdjustment,
		arg.RequestedBy,
	)
	var i Endorsement
	err := row.Scan(
		&i.ID,
		&i.PolicyID,
		&i.EndorsementType,
		&i.Status,
		&i.EffectiveDate,
		&i.Changes,
		&i.Reason,
		&i.PremiumAdjustment,
		&i.RequestedBy,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.AppliedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEndorsementByID = `-- name: GetEndorsementByID :one
SELECT id, policy_id, endorsement_type, status, effective_date, changes, reason, premium_adjustment, requested_by, approved_by, approved_at, applied_at, created_at, updated_at FROM endorsements WHERE id = $1
`

func (q *Queries) GetEndorsementByID(ctx context.Context, id uuid.UUID) (Endorsement, error) {
	row := q.db.QueryRow(ctx, getEndorsementByID, id)
	var i Endorsement
	err := row.Scan(
		&i.ID,
		&i.PolicyID,
		&i.EndorsementType,
		&i.Status,
		&i.EffectiveDate,
		&i.Changes,
		&i.Reason,
		&i.PremiumAdjustment,
		&i.RequestedBy,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.AppliedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEndorsementsByPolicy = `-- name: ListEndorsementsByPolicy :many
SELECT id, policy_id, endorsement_type, status, effective_date, changes, reason, premium_adjustment, requested_by, approved_by, approved_at, applied_at, created_at, updated_at FROM endorsements WHERE policy_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListEndorsementsByPolicy(ctx context.Context, policyID uuid.UUID) ([]Endorsement, error) {
	rows, err := q.db.Query(ctx, listEndorsementsByPolicy, policyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Endorsement{}
	for rows.Next() {
		var i Endorsement
		if err := rows.Scan(
			&i.ID,
			&i.PolicyID,
			&i.EndorsementType,
			&i.Status,
			&i.EffectiveDate,
			&i.Changes,
			&i.Reason,
			&i.PremiumAdjustment,
			&i.RequestedBy,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.AppliedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEndorsement = `-- name: UpdateEndorsement :one
UPDATE endorsements SET
    status = COALESCE($1, status),
    approved_by = COALESCE($2, approved_by),
    approved_at = COALESCE($3, approved_at),
    applied_at = COALESCE($4, applied_at),
    reason = COALESCE($5, reason),
    updated_at = NOW()
WHERE id = $6 RETURNING id, policy_id, endorsement_type, status, effective_date, changes, reason, premium_adjustment, requested_by, approved_by, approved_at, applied_at, created_at, updated_at
`

type UpdateEndorsementParams struct {
	Status     pgtype.Text        `json:"status"`
	ApprovedBy pgtype.UUID        `json:"approved_by"`
	ApprovedAt pgtype.Timestamptz `json:"approved_at"`
	AppliedAt  pgtype.Timestamptz `json:"applied_at"`
	Reason     pgtype.Text        `json:"reason"`
	ID         uuid.UUID          `json:"id"`
}

func (q *Queries) UpdateEndorsement(ctx context.Context, arg UpdateEndorsementParams) (Endorsement, error) {
	row := q.db.QueryRow(ctx, updateEndorsement,
		arg.Status,
		arg.ApprovedBy,
		arg.ApprovedAt,
		arg.AppliedAt,
		arg.Reason,
		arg.ID,
	)
	var i Endorsement
	err := row.Scan(
		&i.ID,
		&i.PolicyID,
		&i.EndorsementType,
		&i.Status,
		&i.EffectiveDate,
		&i.Changes,
		&i.Reason,
		&i.PremiumAdjustment,
		&i.RequestedBy,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.AppliedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEndorsementStatus = `-- name: UpdateEndorsementStatus :one
UPDATE endorsements SET status = $2, updated_at = NOW() WHERE id = $1 RETURNING id, policy_id, endorsement_type, status, effective_date, changes, reason, premium_adjustment, requested_by, approved_by, approved_at, applied_at, created_at, updated_at
`

type UpdateEndorsementStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateEndorsementStatus(ctx context.Context, arg UpdateEndorsementStatusParams) (Endorsement, error) {
	row := q.db.QueryRow(ctx, updateEndorsementStatus, arg.ID, arg.Status)
	var i Endorsement
	err := row.Scan(
		&i.ID,
		&i.PolicyID,
		&i.EndorsementType,
		&i.Status,
		&i.EffectiveDate,
		&i.Changes,
		&i.Reason,
		&i.PremiumAdjustment,
		&i.RequestedBy,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.AppliedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
