// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: installment.sql

package db

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createInstallment = `-- name: CreateInstallment :one
INSERT INTO installments (schedule_id, installment_number, due_date, amount, status)
VALUES ($1, $2, $3, $4, $5) RETURNING id, schedule_id, installment_number, due_date, amount, status, paid_at, invoice_id, created_at, updated_at
`

type CreateInstallmentParams struct {
	ScheduleID        uuid.UUID `json:"schedule_id"`
	InstallmentNumber int32     `json:"installment_number"`
	DueDate           time.Time `json:"due_date"`
	Amount            int64     `json:"amount"`
	Status            string    `json:"status"`
}

func (q *Queries) CreateInstallment(ctx context.Context, arg CreateInstallmentParams) (Installment, error) {
	row := q.db.QueryRow(ctx, createInstallment,
		arg.ScheduleID,
		arg.InstallmentNumber,
		arg.DueDate,
		arg.Amount,
		arg.Status,
	)
	var i Installment
	err := row.Scan(
		&i.ID,
		&i.ScheduleID,
		&i.InstallmentNumber,
		&i.DueDate,
		&i.Amount,
		&i.Status,
		&i.PaidAt,
		&i.InvoiceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInstallmentByID = `-- name: GetInstallmentByID :one
SELECT id, schedule_id, installment_number, due_date, amount, status, paid_at, invoice_id, created_at, updated_at FROM installments WHERE id = $1
`

func (q *Queries) GetInstallmentByID(ctx context.Context, id uuid.UUID) (Installment, error) {
	row := q.db.QueryRow(ctx, getInstallmentByID, id)
	var i Installment
	err := row.Scan(
		&i.ID,
		&i.ScheduleID,
		&i.InstallmentNumber,
		&i.DueDate,
		&i.Amount,
		&i.Status,
		&i.PaidAt,
		&i.InvoiceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listInstallmentsBySchedule = `-- name: ListInstallmentsBySchedule :many
SELECT id, schedule_id, installment_number, due_date, amount, status, paid_at, invoice_id, created_at, updated_at FROM installments WHERE schedule_id = $1 ORDER BY installment_number
`

func (q *Queries) ListInstallmentsBySchedule(ctx context.Context, scheduleID uuid.UUID) ([]Installment, error) {
	rows, err := q.db.Query(ctx, listInstallmentsBySchedule, scheduleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Installment{}
	for rows.Next() {
		var i Installment
		if err := rows.Scan(
			&i.ID,
			&i.ScheduleID,
			&i.InstallmentNumber,
			&i.DueDate,
			&i.Amount,
			&i.Status,
			&i.PaidAt,
			&i.InvoiceID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOverdueInstallments = `-- name: ListOverdueInstallments :many
SELECT id, schedule_id, installment_number, due_date, amount, status, paid_at, invoice_id, created_at, updated_at FROM installments WHERE status = 'PENDING' AND due_date < NOW() ORDER BY due_date
`

func (q *Queries) ListOverdueInstallments(ctx context.Context) ([]Installment, error) {
	rows, err := q.db.Query(ctx, listOverdueInstallments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Installment{}
	for rows.Next() {
		var i Installment
		if err := rows.Scan(
			&i.ID,
			&i.ScheduleID,
			&i.InstallmentNumber,
			&i.DueDate,
			&i.Amount,
			&i.Status,
			&i.PaidAt,
			&i.InvoiceID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInstallmentPaid = `-- name: MarkInstallmentPaid :one
UPDATE installments SET status = 'PAID', paid_at = NOW(), invoice_id = $2, updated_at = NOW() WHERE id = $1 RETURNING id, schedule_id, installment_number, due_date, amount, status, paid_at, invoice_id, created_at, updated_at
`

type MarkInstallmentPaidParams struct {
	ID        uuid.UUID   `json:"id"`
	InvoiceID pgtype.UUID `json:"invoice_id"`
}

func (q *Queries) MarkInstallmentPaid(ctx context.Context, arg MarkInstallmentPaidParams) (Installment, error) {
	row := q.db.QueryRow(ctx, markInstallmentPaid, arg.ID, arg.InvoiceID)
	var i Installment
	err := row.Scan(
		&i.ID,
		&i.ScheduleID,
		&i.InstallmentNumber,
		&i.DueDate,
		&i.Amount,
		&i.Status,
		&i.PaidAt,
		&i.InvoiceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateInstallmentStatus = `-- name: UpdateInstallmentStatus :one
UPDATE installments SET status = $2, updated_at = NOW() WHERE id = $1 RETURNING id, schedule_id, installment_number, due_date, amount, status, paid_at, invoice_id, created_at, updated_at
`

type UpdateInstallmentStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateInstallmentStatus(ctx context.Context, arg UpdateInstallmentStatusParams) (Installment, error) {
	row := q.db.QueryRow(ctx, updateInstallmentStatus, arg.ID, arg.Status)
	var i Installment
	err := row.Scan(
		&i.ID,
		&i.ScheduleID,
		&i.InstallmentNumber,
		&i.DueDate,
		&i.Amount,
		&i.Status,
		&i.PaidAt,
		&i.InvoiceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
