// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: installment_schedule.sql

package db

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createInstallmentSchedule = `-- name: CreateInstallmentSchedule :one
INSERT INTO installment_schedules (policy_id, frequency, total_installments, amount_per_installment, start_date, status, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, policy_id, frequency, total_installments, amount_per_installment, start_date, status, created_by, created_at, updated_at
`

type CreateInstallmentScheduleParams struct {
	PolicyID             uuid.UUID   `json:"policy_id"`
	Frequency            string      `json:"frequency"`
	TotalInstallments    int32       `json:"total_installments"`
	AmountPerInstallment int64       `json:"amount_per_installment"`
	StartDate            time.Time   `json:"start_date"`
	Status               string      `json:"status"`
	CreatedBy            pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateInstallmentSchedule(ctx context.Context, arg CreateInstallmentScheduleParams) (InstallmentSchedule, error) {
	row := q.db.QueryRow(ctx, createInstallmentSchedule,
		arg.PolicyID,
		arg.Frequency,
		arg.TotalInstallments,
		arg.AmountPerInstallment,
		arg.StartDate,
		arg.Status,
		arg.CreatedBy,
	)
	var i InstallmentSchedule
	err := row.Scan(
		&i.ID,
		&i.PolicyID,
		&i.Frequency,
		&i.TotalInstallments,
		&i.AmountPerInstallment,
		&i.StartDate,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInstallmentScheduleByID = `-- name: GetInstallmentScheduleByID :one
SELECT id, policy_id, frequency, total_installments, amount_per_installment, start_date, status, created_by, created_at, updated_at FROM installment_schedules WHERE id = $1
`

func (q *Queries) GetInstallmentScheduleByID(ctx context.Context, id uuid.UUID) (InstallmentSchedule, error) {
	row := q.db.QueryRow(ctx, getInstallmentScheduleByID, id)
	var i InstallmentSchedule
	err := row.Scan(
		&i.ID,
		&i.PolicyID,
		&i.Frequency,
		&i.TotalInstallments,
		&i.AmountPerInstallment,
		&i.StartDate,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInstallmentScheduleByPolicy = `-- name: GetInstallmentScheduleByPolicy :many
SELECT id, policy_id, frequency, total_installments, amount_per_installment, start_date, status, created_by, created_at, updated_at FROM installment_schedules WHERE policy_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetInstallmentScheduleByPolicy(ctx context.Context, policyID uuid.UUID) ([]InstallmentSchedule, error) {
	rows, err := q.db.Query(ctx, getInstallmentScheduleByPolicy, policyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InstallmentSchedule{}
	for rows.Next() {
		var i InstallmentSchedule
		if err := rows.Scan(
			&i.ID,
			&i.PolicyID,
			&i.Frequency,
			&i.TotalInstallments,
			&i.AmountPerInstallment,
			&i.StartDate,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInstallmentScheduleStatus = `-- name: UpdateInstallmentScheduleStatus :one
UPDATE installment_schedules SET status = $2, updated_at = NOW() WHERE id = $1 RETURNING id, policy_id, frequency, total_installments, amount_per_installment, start_date, status, created_by, created_at, updated_at
`

type UpdateInstallmentScheduleStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateInstallmentScheduleStatus(ctx context.Context, arg UpdateInstallmentScheduleStatusParams) (InstallmentSchedule, error) {
	row := q.db.QueryRow(ctx, updateInstallmentScheduleStatus, arg.ID, arg.Status)
	var i InstallmentSchedule
	err := row.Scan(
		&i.ID,
		&i.PolicyID,
		&i.Frequency,
		&i.TotalInstallments,
		&i.AmountPerInstallment,
		&i.StartDate,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
