// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: invoice.sql

package db

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countInvoices = `-- name: CountInvoices :one
SELECT COUNT(*) FROM invoices
`

func (q *Queries) CountInvoices(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countInvoices)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInvoice = `-- name: CreateInvoice :one
INSERT INTO invoices (policy_id, invoice_number, amount, currency, due_date, status, billing_period_start, billing_period_end, notes, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) RETURNING id, policy_id, invoice_number, amount, currency, due_date, status, billing_period_start, billing_period_end, notes, created_by, created_at, updated_at
`

type CreateInvoiceParams struct {
	PolicyID           uuid.UUID   `json:"policy_id"`
	InvoiceNumber      string      `json:"invoice_number"`
	Amount             int64       `json:"amount"`
	Currency           string      `json:"currency"`
	DueDate            time.Time   `json:"due_date"`
	Status             string      `json:"status"`
	BillingPeriodStart time.Time   `json:"billing_period_start"`
	BillingPeriodEnd   time.Time   `json:"billing_period_end"`
	Notes              string      `json:"notes"`
	CreatedBy          pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, createInvoice,
		arg.PolicyID,
		arg.InvoiceNumber,
		arg.Amount,
		arg.Currency,
		arg.DueDate,
		arg.Status,
		arg.BillingPeriodStart,
		arg.BillingPeriodEnd,
		arg.Notes,
		arg.CreatedBy,
	)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.PolicyID,
		&i.InvoiceNumber,
		&i.Amount,
		&i.Currency,
		&i.DueDate,
		&i.Status,
		&i.BillingPeriodStart,
		&i.BillingPeriodEnd,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInvoiceByID = `-- name: GetInvoiceByID :one
SELECT id, policy_id, invoice_number, amount, currency, due_date, status, billing_period_start, billing_period_end, notes, created_by, created_at, updated_at FROM invoices WHERE id = $1
`

func (q *Queries) GetInvoiceByID(ctx context.Context, id uuid.UUID) (Invoice, error) {
	row := q.db.QueryRow(ctx, getInvoiceByID, id)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.PolicyID,
		&i.InvoiceNumber,
		&i.Amount,
		&i.Currency,
		&i.DueDate,
		&i.Status,
		&i.BillingPeriodStart,
		&i.BillingPeriodEnd,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInvoiceByNumber = `-- name: GetInvoiceByNumber :one
SELECT id, policy_id, invoice_number, amount, currency, due_date, status, billing_period_start, billing_period_end, notes, created_by, created_at, updated_at FROM invoices WHERE invoice_number = $1
`

func (q *Queries) GetInvoiceByNumber(ctx context.Context, invoiceNumber string) (Invoice, error) {
	row := q.db.QueryRow(ctx, getInvoiceByNumber, invoiceNumber)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.PolicyID,
		&i.InvoiceNumber,
		&i.Amount,
		&i.Currency,
		&i.DueDate,
		&i.Status,
		&i.BillingPeriodStart,
		&i.BillingPeriodEnd,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listInvoices = `-- name: ListInvoices :many
SELECT id, policy_id, invoice_number, amount, currency, due_date, status, billing_period_start, billing_period_end, notes, created_by, created_at, updated_at FROM invoices ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListInvoicesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListInvoices(ctx context.Context, arg ListInvoicesParams) ([]Invoice, error) {
	rows, err := q.db.Query(ctx, listInvoices, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invoice{}
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.ID,
			&i.PolicyID,
			&i.InvoiceNumber,
			&i.Amount,
			&i.Currency,
			&i.DueDate,
			&i.Status,
			&i.BillingPeriodStart,
			&i.BillingPeriodEnd,
			&i.Notes,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoicesByPolicy = `-- name: ListInvoicesByPolicy :many
SELECT id, policy_id, invoice_number, amount, currency, due_date, status, billing_period_start, billing_period_end, notes, created_by, created_at, updated_at FROM invoices WHERE policy_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListInvoicesByPolicyParams struct {
	PolicyID uuid.UUID `json:"policy_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListInvoicesByPolicy(ctx context.Context, arg ListInvoicesByPolicyParams) ([]Invoice, error) {
	rows, err := q.db.Query(ctx, listInvoicesByPolicy, arg.PolicyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invoice{}
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.ID,
			&i.PolicyID,
			&i.InvoiceNumber,
			&i.Amount,
			&i.Currency,
			&i.DueDate,
			&i.Status,
			&i.BillingPeriodStart,
			&i.BillingPeriodEnd,
			&i.Notes,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoicesByStatus = `-- name: ListInvoicesByStatus :many
SELECT id, policy_id, invoice_number, amount, currency, due_date, status, billing_period_start, billing_period_end, notes, created_by, created_at, updated_at FROM invoices WHERE status = $1 ORDER BY due_date ASC LIMIT $2 OFFSET $3
`

type ListInvoicesByStatusParams struct {
	Status string `json:"status"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListInvoicesByStatus(ctx context.Context, arg ListInvoicesByStatusParams) ([]Invoice, error) {
	rows, err := q.db.Query(ctx, listInvoicesByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invoice{}
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.ID,
			&i.PolicyID,
			&i.InvoiceNumber,
			&i.Amount,
			&i.Currency,
			&i.DueDate,
			&i.Status,
			&i.BillingPeriodStart,
			&i.BillingPeriodEnd,
			&i.Notes,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOverdueInvoices = `-- name: ListOverdueInvoices :many
SELECT id, policy_id, invoice_number, amount, currency, due_date, status, billing_period_start, billing_period_end, notes, created_by, created_at, updated_at FROM invoices WHERE status = 'PENDING' AND due_date < NOW() ORDER BY due_date ASC
`

func (q *Queries) ListOverdueInvoices(ctx context.Context) ([]Invoice, error) {
	rows, err := q.db.Query(ctx, listOverdueInvoices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invoice{}
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.ID,
			&i.PolicyID,
			&i.InvoiceNumber,
			&i.Amount,
			&i.Currency,
			&i.DueDate,
			&i.Status,
			&i.BillingPeriodStart,
			&i.BillingPeriodEnd,
			&i.Notes,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInvoiceStatus = `-- name: UpdateInvoiceStatus :one
UPDATE invoices SET status = $2, updated_at = NOW() WHERE id = $1 RETURNING id, policy_id, invoice_number, amount, currency, due_date, status, billing_period_start, billing_period_end, notes, created_by, created_at, updated_at
`

type UpdateInvoiceStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateInvoiceStatus(ctx context.Context, arg UpdateInvoiceStatusParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, updateInvoiceStatus, arg.ID, arg.Status)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.PolicyID,
		&i.InvoiceNumber,
		&i.Amount,
		&i.Currency,
		&i.DueDate,
		&i.Status,
		&i.BillingPeriodStart,
		&i.BillingPeriodEnd,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
