// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: lead.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countLeads = `-- name: CountLeads :one
SELECT COUNT(*) FROM leads
`

func (q *Queries) CountLeads(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countLeads)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLeadsByStatus = `-- name: CountLeadsByStatus :one
SELECT COUNT(*) FROM leads WHERE status = $1
`

func (q *Queries) CountLeadsByStatus(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRow(ctx, countLeadsByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLead = `-- name: CreateLead :one
INSERT INTO leads (lead_number, contact_name, contact_email, contact_phone, company_name, source, segment, plan_type, estimated_members, expected_premium, closure_probability, currency, status, assigned_to, next_follow_up_date, notes, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17) RETURNING id, lead_number, contact_name, contact_email, contact_phone, company_name, source, segment, plan_type, estimated_members, expected_premium, closure_probability, currency, status, assigned_to, next_follow_up_date, notes, created_by, created_at, updated_at
`

type CreateLeadParams struct {
	LeadNumber         string             `json:"lead_number"`
	ContactName        string             `json:"contact_name"`
	ContactEmail       pgtype.Text        `json:"contact_email"`
	ContactPhone       pgtype.Text        `json:"contact_phone"`
	CompanyName        pgtype.Text        `json:"company_name"`
	Source             string             `json:"source"`
	Segment            string             `json:"segment"`
	PlanType           string             `json:"plan_type"`
	EstimatedMembers   int32              `json:"estimated_members"`
	ExpectedPremium    int64              `json:"expected_premium"`
	ClosureProbability int32              `json:"closure_probability"`
	Currency           string             `json:"currency"`
	Status             string             `json:"status"`
	AssignedTo         pgtype.UUID        `json:"assigned_to"`
	NextFollowUpDate   pgtype.Timestamptz `json:"next_follow_up_date"`
	Notes              pgtype.Text        `json:"notes"`
	CreatedBy          pgtype.UUID        `json:"created_by"`
}

func (q *Queries) CreateLead(ctx context.Context, arg CreateLeadParams) (Lead, error) {
	row := q.db.QueryRow(ctx, createLead,
		arg.LeadNumber,
		arg.ContactName,
		arg.ContactEmail,
		arg.ContactPhone,
		arg.CompanyName,
		arg.Source,
		arg.Segment,
		arg.PlanType,
		arg.EstimatedMembers,
		arg.ExpectedPremium,
		arg.ClosureProbability,
		arg.Currency,
		arg.Status,
		arg.AssignedTo,
		arg.NextFollowUpDate,
		arg.Notes,
		arg.CreatedBy,
	)
	var i Lead
	err := row.Scan(
		&i.ID,
		&i.LeadNumber,
		&i.ContactName,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.CompanyName,
		&i.Source,
		&i.Segment,
		&i.PlanType,
		&i.EstimatedMembers,
		&i.ExpectedPremium,
		&i.ClosureProbability,
		&i.Currency,
		&i.Status,
		&i.AssignedTo,
		&i.NextFollowUpDate,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLeadByID = `-- name: GetLeadByID :one
SELECT id, lead_number, contact_name, contact_email, contact_phone, company_name, source, segment, plan_type, estimated_members, expected_premium, closure_probability, currency, status, assigned_to, next_follow_up_date, notes, created_by, created_at, updated_at FROM leads WHERE id = $1
`

func (q *Queries) GetLeadByID(ctx context.Context, id uuid.UUID) (Lead, error) {
	row := q.db.QueryRow(ctx, getLeadByID, id)
	var i Lead
	err := row.Scan(
		&i.ID,
		&i.LeadNumber,
		&i.ContactName,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.CompanyName,
		&i.Source,
		&i.Segment,
		&i.PlanType,
		&i.EstimatedMembers,
		&i.ExpectedPremium,
		&i.ClosureProbability,
		&i.Currency,
		&i.Status,
		&i.AssignedTo,
		&i.NextFollowUpDate,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLeadByNumber = `-- name: GetLeadByNumber :one
SELECT id, lead_number, contact_name, contact_email, contact_phone, company_name, source, segment, plan_type, estimated_members, expected_premium, closure_probability, currency, status, assigned_to, next_follow_up_date, notes, created_by, created_at, updated_at FROM leads WHERE lead_number = $1
`

func (q *Queries) GetLeadByNumber(ctx context.Context, leadNumber string) (Lead, error) {
	row := q.db.QueryRow(ctx, getLeadByNumber, leadNumber)
	var i Lead
	err := row.Scan(
		&i.ID,
		&i.LeadNumber,
		&i.ContactName,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.CompanyName,
		&i.Source,
		&i.Segment,
		&i.PlanType,
		&i.EstimatedMembers,
		&i.ExpectedPremium,
		&i.ClosureProbability,
		&i.Currency,
		&i.Status,
		&i.AssignedTo,
		&i.NextFollowUpDate,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDueFollowUps = `-- name: ListDueFollowUps :many
SELECT id, lead_number, contact_name, contact_email, contact_phone, company_name, source, segment, plan_type, estimated_members, expected_premium, closure_probability, currency, status, assigned_to, next_follow_up_date, notes, created_by, created_at, updated_at FROM leads
WHERE next_follow_up_date <= NOW()
  AND status NOT IN ('WON', 'LOST', 'DORMANT')
ORDER BY next_follow_up_date ASC
LIMIT $1 OFFSET $2
`

type ListDueFollowUpsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListDueFollowUps(ctx context.Context, arg ListDueFollowUpsParams) ([]Lead, error) {
	rows, err := q.db.Query(ctx, listDueFollowUps, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Lead{}
	for rows.Next() {
		var i Lead
		if err := rows.Scan(
			&i.ID,
			&i.LeadNumber,
			&i.ContactName,
			&i.ContactEmail,
			&i.ContactPhone,
			&i.CompanyName,
			&i.Source,
			&i.Segment,
			&i.PlanType,
			&i.EstimatedMembers,
			&i.ExpectedPremium,
			&i.ClosureProbability,
			&i.Currency,
			&i.Status,
			&i.AssignedTo,
			&i.NextFollowUpDate,
			&i.Notes,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeads = `-- name: ListLeads :many
SELECT id, lead_number, contact_name, contact_email, contact_phone, company_name, source, segment, plan_type, estimated_members, expected_premium, closure_probability, currency, status, assigned_to, next_follow_up_date, notes, created_by, created_at, updated_at FROM leads ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListLeadsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListLeads(ctx context.Context, arg ListLeadsParams) ([]Lead, error) {
	rows, err := q.db.Query(ctx, listLeads, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Lead{}
	for rows.Next() {
		var i Lead
		if err := rows.Scan(
			&i.ID,
			&i.LeadNumber,
			&i.ContactName,
			&i.ContactEmail,
			&i.ContactPhone,
			&i.CompanyName,
			&i.Source,
			&i.Segment,
			&i.PlanType,
			&i.EstimatedMembers,
			&i.ExpectedPremium,
			&i.ClosureProbability,
			&i.Currency,
			&i.Status,
			&i.AssignedTo,
			&i.NextFollowUpDate,
			&i.Notes,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeadsByAssignedTo = `-- name: ListLeadsByAssignedTo :many
SELECT id, lead_number, contact_name, contact_email, contact_phone, company_name, source, segment, plan_type, estimated_members, expected_premium, closure_probability, currency, status, assigned_to, next_follow_up_date, notes, created_by, created_at, updated_at FROM leads WHERE assigned_to = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListLeadsByAssignedToParams struct {
	AssignedTo pgtype.UUID `json:"assigned_to"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
}

func (q *Queries) ListLeadsByAssignedTo(ctx context.Context, arg ListLeadsByAssignedToParams) ([]Lead, error) {
	rows, err := q.db.Query(ctx, listLeadsByAssignedTo, arg.AssignedTo, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Lead{}
	for rows.Next() {
		var i Lead
		if err := rows.Scan(
			&i.ID,
			&i.LeadNumber,
			&i.ContactName,
			&i.ContactEmail,
			&i.ContactPhone,
			&i.CompanyName,
			&i.Source,
			&i.Segment,
			&i.PlanType,
			&i.EstimatedMembers,
			&i.ExpectedPremium,
			&i.ClosureProbability,
			&i.Currency,
			&i.Status,
			&i.AssignedTo,
			&i.NextFollowUpDate,
			&i.Notes,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeadsByStatus = `-- name: ListLeadsByStatus :many
SELECT id, lead_number, contact_name, contact_email, contact_phone, company_name, source, segment, plan_type, estimated_members, expected_premium, closure_probability, currency, status, assigned_to, next_follow_up_date, notes, created_by, created_at, updated_at FROM leads WHERE status = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListLeadsByStatusParams struct {
	Status string `json:"status"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListLeadsByStatus(ctx context.Context, arg ListLeadsByStatusParams) ([]Lead, error) {
	rows, err := q.db.Query(ctx, listLeadsByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Lead{}
	for rows.Next() {
		var i Lead
		if err := rows.Scan(
			&i.ID,
			&i.LeadNumber,
			&i.ContactName,
			&i.ContactEmail,
			&i.ContactPhone,
			&i.CompanyName,
			&i.Source,
			&i.Segment,
			&i.PlanType,
			&i.EstimatedMembers,
			&i.ExpectedPremium,
			&i.ClosureProbability,
			&i.Currency,
			&i.Status,
			&i.AssignedTo,
			&i.NextFollowUpDate,
			&i.Notes,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLead = `-- name: UpdateLead :one
UPDATE leads SET
    contact_name = COALESCE(NULLIF($2, ''), contact_name),
    contact_email = COALESCE(NULLIF($3, ''), contact_email),
    contact_phone = COALESCE(NULLIF($4, ''), contact_phone),
    company_name = COALESCE(NULLIF($5, ''), company_name),
    source = COALESCE(NULLIF($6, ''), source),
    segment = COALESCE(NULLIF($7, ''), segment),
    plan_type = COALESCE(NULLIF($8, ''), plan_type),
    estimated_members = COALESCE($9, estimated_members),
    expected_premium = COALESCE($10, expected_premium),
    closure_probability = COALESCE($11, closure_probability),
    assigned_to = COALESCE($12, assigned_to),
    next_follow_up_date = COALESCE($13, next_follow_up_date),
    notes = COALESCE(NULLIF($14, ''), notes),
    updated_at = NOW()
WHERE id = $1 RETURNING id, lead_number, contact_name, contact_email, contact_phone, company_name, source, segment, plan_type, estimated_members, expected_premium, closure_probability, currency, status, assigned_to, next_follow_up_date, notes, created_by, created_at, updated_at
`

type UpdateLeadParams struct {
	ID                 uuid.UUID          `json:"id"`
	Column2            interface{}        `json:"column_2"`
	Column3            interface{}        `json:"column_3"`
	Column4            interface{}        `json:"column_4"`
	Column5            interface{}        `json:"column_5"`
	Column6            interface{}        `json:"column_6"`
	Column7            interface{}        `json:"column_7"`
	Column8            interface{}        `json:"column_8"`
	EstimatedMembers   int32              `json:"estimated_members"`
	ExpectedPremium    int64              `json:"expected_premium"`
	ClosureProbability int32              `json:"closure_probability"`
	AssignedTo         pgtype.UUID        `json:"assigned_to"`
	NextFollowUpDate   pgtype.Timestamptz `json:"next_follow_up_date"`
	Column14           interface{}        `json:"column_14"`
}

func (q *Queries) UpdateLead(ctx context.Context, arg UpdateLeadParams) (Lead, error) {
	row := q.db.QueryRow(ctx, updateLead,
		arg.ID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Column8,
		arg.EstimatedMembers,
		arg.ExpectedPremium,
		arg.ClosureProbability,
		arg.AssignedTo,
		arg.NextFollowUpDate,
		arg.Column14,
	)
	var i Lead
	err := row.Scan(
		&i.ID,
		&i.LeadNumber,
		&i.ContactName,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.CompanyName,
		&i.Source,
		&i.Segment,
		&i.PlanType,
		&i.EstimatedMembers,
		&i.ExpectedPremium,
		&i.ClosureProbability,
		&i.Currency,
		&i.Status,
		&i.AssignedTo,
		&i.NextFollowUpDate,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLeadStatus = `-- name: UpdateLeadStatus :one
UPDATE leads SET status = $2, updated_at = NOW() WHERE id = $1 RETURNING id, lead_number, contact_name, contact_email, contact_phone, company_name, source, segment, plan_type, estimated_members, expected_premium, closure_probability, currency, status, assigned_to, next_follow_up_date, notes, created_by, created_at, updated_at
`

type UpdateLeadStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateLeadStatus(ctx context.Context, arg UpdateLeadStatusParams) (Lead, error) {
	row := q.db.QueryRow(ctx, updateLeadStatus, arg.ID, arg.Status)
	var i Lead
	err := row.Scan(
		&i.ID,
		&i.LeadNumber,
		&i.ContactName,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.CompanyName,
		&i.Source,
		&i.Segment,
		&i.PlanType,
		&i.EstimatedMembers,
		&i.ExpectedPremium,
		&i.ClosureProbability,
		&i.Currency,
		&i.Status,
		&i.AssignedTo,
		&i.NextFollowUpDate,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
