// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: lead_activity.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createLeadActivity = `-- name: CreateLeadActivity :one
INSERT INTO lead_activities (lead_id, activity_type, description, scheduled_at, completed_at, created_by)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, lead_id, activity_type, description, scheduled_at, completed_at, created_by, created_at
`

type CreateLeadActivityParams struct {
	LeadID       uuid.UUID          `json:"lead_id"`
	ActivityType string             `json:"activity_type"`
	Description  pgtype.Text        `json:"description"`
	ScheduledAt  pgtype.Timestamptz `json:"scheduled_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
	CreatedBy    pgtype.UUID        `json:"created_by"`
}

func (q *Queries) CreateLeadActivity(ctx context.Context, arg CreateLeadActivityParams) (LeadActivity, error) {
	row := q.db.QueryRow(ctx, createLeadActivity,
		arg.LeadID,
		arg.ActivityType,
		arg.Description,
		arg.ScheduledAt,
		arg.CompletedAt,
		arg.CreatedBy,
	)
	var i LeadActivity
	err := row.Scan(
		&i.ID,
		&i.LeadID,
		&i.ActivityType,
		&i.Description,
		&i.ScheduledAt,
		&i.CompletedAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listLeadActivitiesByLead = `-- name: ListLeadActivitiesByLead :many
SELECT id, lead_id, activity_type, description, scheduled_at, completed_at, created_by, created_at FROM lead_activities WHERE lead_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListLeadActivitiesByLead(ctx context.Context, leadID uuid.UUID) ([]LeadActivity, error) {
	rows, err := q.db.Query(ctx, listLeadActivitiesByLead, leadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LeadActivity{}
	for rows.Next() {
		var i LeadActivity
		if err := rows.Scan(
			&i.ID,
			&i.LeadID,
			&i.ActivityType,
			&i.Description,
			&i.ScheduledAt,
			&i.CompletedAt,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
