// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: member.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countMembersByPolicy = `-- name: CountMembersByPolicy :one
SELECT COUNT(*) FROM members WHERE policy_id = $1
`

func (q *Queries) CountMembersByPolicy(ctx context.Context, policyID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMembersByPolicy, policyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMember = `-- name: CreateMember :one
INSERT INTO members (policy_id, national_id, name, date_of_birth, gender, relationship, member_number, phone, email)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING id, policy_id, national_id, name, date_of_birth, gender, relationship, member_number, phone, email, verified, verified_at, created_at, updated_at
`

type CreateMemberParams struct {
	PolicyID     uuid.UUID   `json:"policy_id"`
	NationalID   pgtype.Text `json:"national_id"`
	Name         string      `json:"name"`
	DateOfBirth  pgtype.Date `json:"date_of_birth"`
	Gender       string      `json:"gender"`
	Relationship string      `json:"relationship"`
	MemberNumber string      `json:"member_number"`
	Phone        pgtype.Text `json:"phone"`
	Email        pgtype.Text `json:"email"`
}

func (q *Queries) CreateMember(ctx context.Context, arg CreateMemberParams) (Member, error) {
	row := q.db.QueryRow(ctx, createMember,
		arg.PolicyID,
		arg.NationalID,
		arg.Name,
		arg.DateOfBirth,
		arg.Gender,
		arg.Relationship,
		arg.MemberNumber,
		arg.Phone,
		arg.Email,
	)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.PolicyID,
		&i.NationalID,
		&i.Name,
		&i.DateOfBirth,
		&i.Gender,
		&i.Relationship,
		&i.MemberNumber,
		&i.Phone,
		&i.Email,
		&i.Verified,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMember = `-- name: DeleteMember :exec
DELETE FROM members WHERE id = $1
`

func (q *Queries) DeleteMember(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMember, id)
	return err
}

const getMemberByID = `-- name: GetMemberByID :one
SELECT id, policy_id, national_id, name, date_of_birth, gender, relationship, member_number, phone, email, verified, verified_at, created_at, updated_at FROM members WHERE id = $1
`

func (q *Queries) GetMemberByID(ctx context.Context, id uuid.UUID) (Member, error) {
	row := q.db.QueryRow(ctx, getMemberByID, id)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.PolicyID,
		&i.NationalID,
		&i.Name,
		&i.DateOfBirth,
		&i.Gender,
		&i.Relationship,
		&i.MemberNumber,
		&i.Phone,
		&i.Email,
		&i.Verified,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMemberByNationalID = `-- name: GetMemberByNationalID :one
SELECT id, policy_id, national_id, name, date_of_birth, gender, relationship, member_number, phone, email, verified, verified_at, created_at, updated_at FROM members WHERE national_id = $1
`

func (q *Queries) GetMemberByNationalID(ctx context.Context, nationalID pgtype.Text) (Member, error) {
	row := q.db.QueryRow(ctx, getMemberByNationalID, nationalID)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.PolicyID,
		&i.NationalID,
		&i.Name,
		&i.DateOfBirth,
		&i.Gender,
		&i.Relationship,
		&i.MemberNumber,
		&i.Phone,
		&i.Email,
		&i.Verified,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMemberByNumber = `-- name: GetMemberByNumber :one
SELECT id, policy_id, national_id, name, date_of_birth, gender, relationship, member_number, phone, email, verified, verified_at, created_at, updated_at FROM members WHERE member_number = $1
`

func (q *Queries) GetMemberByNumber(ctx context.Context, memberNumber string) (Member, error) {
	row := q.db.QueryRow(ctx, getMemberByNumber, memberNumber)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.PolicyID,
		&i.NationalID,
		&i.Name,
		&i.DateOfBirth,
		&i.Gender,
		&i.Relationship,
		&i.MemberNumber,
		&i.Phone,
		&i.Email,
		&i.Verified,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMembersByPolicy = `-- name: ListMembersByPolicy :many
SELECT id, policy_id, national_id, name, date_of_birth, gender, relationship, member_number, phone, email, verified, verified_at, created_at, updated_at FROM members WHERE policy_id = $1 ORDER BY relationship, name
`

func (q *Queries) ListMembersByPolicy(ctx context.Context, policyID uuid.UUID) ([]Member, error) {
	rows, err := q.db.Query(ctx, listMembersByPolicy, policyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Member{}
	for rows.Next() {
		var i Member
		if err := rows.Scan(
			&i.ID,
			&i.PolicyID,
			&i.NationalID,
			&i.Name,
			&i.DateOfBirth,
			&i.Gender,
			&i.Relationship,
			&i.MemberNumber,
			&i.Phone,
			&i.Email,
			&i.Verified,
			&i.VerifiedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMember = `-- name: UpdateMember :one
UPDATE members SET
    name = COALESCE($1, name),
    phone = COALESCE($2, phone),
    email = COALESCE($3, email),
    updated_at = NOW()
WHERE id = $4 RETURNING id, policy_id, national_id, name, date_of_birth, gender, relationship, member_number, phone, email, verified, verified_at, created_at, updated_at
`

type UpdateMemberParams struct {
	Name  pgtype.Text `json:"name"`
	Phone pgtype.Text `json:"phone"`
	Email pgtype.Text `json:"email"`
	ID    uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateMember(ctx context.Context, arg UpdateMemberParams) (Member, error) {
	row := q.db.QueryRow(ctx, updateMember,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.ID,
	)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.PolicyID,
		&i.NationalID,
		&i.Name,
		&i.DateOfBirth,
		&i.Gender,
		&i.Relationship,
		&i.MemberNumber,
		&i.Phone,
		&i.Email,
		&i.Verified,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const verifyMember = `-- name: VerifyMember :one
UPDATE members SET verified = TRUE, verified_at = NOW(), updated_at = NOW() WHERE id = $1 RETURNING id, policy_id, national_id, name, date_of_birth, gender, relationship, member_number, phone, email, verified, verified_at, created_at, updated_at
`

func (q *Queries) VerifyMember(ctx context.Context, id uuid.UUID) (Member, error) {
	row := q.db.QueryRow(ctx, verifyMember, id)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.PolicyID,
		&i.NationalID,
		&i.Name,
		&i.DateOfBirth,
		&i.Gender,
		&i.Relationship,
		&i.MemberNumber,
		&i.Phone,
		&i.Email,
		&i.Verified,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
