// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: member.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const activatePendingMembersByPolicy = `-- name: ActivatePendingMembersByPolicy :exec
UPDATE members SET status = 'ACTIVE', updated_at = NOW()
WHERE policy_id = $1 AND status = 'PENDING'
`

func (q *Queries) ActivatePendingMembersByPolicy(ctx context.Context, policyID uuid.UUID) error {
	_, err := q.db.Exec(ctx, activatePendingMembersByPolicy, policyID)
	return err
}

const countActiveMembersByPolicy = `-- name: CountActiveMembersByPolicy :one
SELECT COUNT(*) FROM members WHERE policy_id = $1 AND status = 'ACTIVE'
`

func (q *Queries) CountActiveMembersByPolicy(ctx context.Context, policyID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveMembersByPolicy, policyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMembersByPolicy = `-- name: CountMembersByPolicy :one
SELECT COUNT(*) FROM members WHERE policy_id = $1
`

func (q *Queries) CountMembersByPolicy(ctx context.Context, policyID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMembersByPolicy, policyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMembersFiltered = `-- name: CountMembersFiltered :one
SELECT COUNT(*) FROM members
WHERE ($1::text = '' OR (name ILIKE '%' || $1 || '%' OR national_id ILIKE '%' || $1 || '%' OR email ILIKE '%' || $1 || '%' OR phone ILIKE '%' || $1 || '%'))
`

func (q *Queries) CountMembersFiltered(ctx context.Context, dollar_1 string) (int64, error) {
	row := q.db.QueryRow(ctx, countMembersFiltered, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMember = `-- name: CreateMember :one
INSERT INTO members (policy_id, national_id, name, date_of_birth, gender, relationship, member_number, phone, email, kra_pin, county, city, country, address)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14) RETURNING id, policy_id, national_id, name, date_of_birth, gender, relationship, member_number, phone, email, kra_pin, county, address, verified, verified_at, created_at, updated_at, status, coverage_start_date, coverage_end_date, city, country
`

type CreateMemberParams struct {
	PolicyID     uuid.UUID   `json:"policy_id"`
	NationalID   pgtype.Text `json:"national_id"`
	Name         string      `json:"name"`
	DateOfBirth  pgtype.Date `json:"date_of_birth"`
	Gender       string      `json:"gender"`
	Relationship string      `json:"relationship"`
	MemberNumber string      `json:"member_number"`
	Phone        pgtype.Text `json:"phone"`
	Email        pgtype.Text `json:"email"`
	KraPin       pgtype.Text `json:"kra_pin"`
	County       pgtype.Text `json:"county"`
	City         string      `json:"city"`
	Country      string      `json:"country"`
	Address      pgtype.Text `json:"address"`
}

func (q *Queries) CreateMember(ctx context.Context, arg CreateMemberParams) (Member, error) {
	row := q.db.QueryRow(ctx, createMember,
		arg.PolicyID,
		arg.NationalID,
		arg.Name,
		arg.DateOfBirth,
		arg.Gender,
		arg.Relationship,
		arg.MemberNumber,
		arg.Phone,
		arg.Email,
		arg.KraPin,
		arg.County,
		arg.City,
		arg.Country,
		arg.Address,
	)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.PolicyID,
		&i.NationalID,
		&i.Name,
		&i.DateOfBirth,
		&i.Gender,
		&i.Relationship,
		&i.MemberNumber,
		&i.Phone,
		&i.Email,
		&i.KraPin,
		&i.County,
		&i.Address,
		&i.Verified,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.CoverageStartDate,
		&i.CoverageEndDate,
		&i.City,
		&i.Country,
	)
	return i, err
}

const deleteMember = `-- name: DeleteMember :exec
DELETE FROM members WHERE id = $1
`

func (q *Queries) DeleteMember(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMember, id)
	return err
}

const getMemberByID = `-- name: GetMemberByID :one
SELECT id, policy_id, national_id, name, date_of_birth, gender, relationship, member_number, phone, email, kra_pin, county, address, verified, verified_at, created_at, updated_at, status, coverage_start_date, coverage_end_date, city, country FROM members WHERE id = $1
`

func (q *Queries) GetMemberByID(ctx context.Context, id uuid.UUID) (Member, error) {
	row := q.db.QueryRow(ctx, getMemberByID, id)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.PolicyID,
		&i.NationalID,
		&i.Name,
		&i.DateOfBirth,
		&i.Gender,
		&i.Relationship,
		&i.MemberNumber,
		&i.Phone,
		&i.Email,
		&i.KraPin,
		&i.County,
		&i.Address,
		&i.Verified,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.CoverageStartDate,
		&i.CoverageEndDate,
		&i.City,
		&i.Country,
	)
	return i, err
}

const getMemberByNationalID = `-- name: GetMemberByNationalID :one
SELECT id, policy_id, national_id, name, date_of_birth, gender, relationship, member_number, phone, email, kra_pin, county, address, verified, verified_at, created_at, updated_at, status, coverage_start_date, coverage_end_date, city, country FROM members WHERE national_id = $1
`

func (q *Queries) GetMemberByNationalID(ctx context.Context, nationalID pgtype.Text) (Member, error) {
	row := q.db.QueryRow(ctx, getMemberByNationalID, nationalID)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.PolicyID,
		&i.NationalID,
		&i.Name,
		&i.DateOfBirth,
		&i.Gender,
		&i.Relationship,
		&i.MemberNumber,
		&i.Phone,
		&i.Email,
		&i.KraPin,
		&i.County,
		&i.Address,
		&i.Verified,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.CoverageStartDate,
		&i.CoverageEndDate,
		&i.City,
		&i.Country,
	)
	return i, err
}

const getMemberByNumber = `-- name: GetMemberByNumber :one
SELECT id, policy_id, national_id, name, date_of_birth, gender, relationship, member_number, phone, email, kra_pin, county, address, verified, verified_at, created_at, updated_at, status, coverage_start_date, coverage_end_date, city, country FROM members WHERE member_number = $1
`

func (q *Queries) GetMemberByNumber(ctx context.Context, memberNumber string) (Member, error) {
	row := q.db.QueryRow(ctx, getMemberByNumber, memberNumber)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.PolicyID,
		&i.NationalID,
		&i.Name,
		&i.DateOfBirth,
		&i.Gender,
		&i.Relationship,
		&i.MemberNumber,
		&i.Phone,
		&i.Email,
		&i.KraPin,
		&i.County,
		&i.Address,
		&i.Verified,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.CoverageStartDate,
		&i.CoverageEndDate,
		&i.City,
		&i.Country,
	)
	return i, err
}

const listActiveMembersByPolicy = `-- name: ListActiveMembersByPolicy :many
SELECT id, policy_id, national_id, name, date_of_birth, gender, relationship, member_number, phone, email, kra_pin, county, address, verified, verified_at, created_at, updated_at, status, coverage_start_date, coverage_end_date, city, country FROM members WHERE policy_id = $1 AND status = 'ACTIVE' ORDER BY relationship, name
`

func (q *Queries) ListActiveMembersByPolicy(ctx context.Context, policyID uuid.UUID) ([]Member, error) {
	rows, err := q.db.Query(ctx, listActiveMembersByPolicy, policyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Member{}
	for rows.Next() {
		var i Member
		if err := rows.Scan(
			&i.ID,
			&i.PolicyID,
			&i.NationalID,
			&i.Name,
			&i.DateOfBirth,
			&i.Gender,
			&i.Relationship,
			&i.MemberNumber,
			&i.Phone,
			&i.Email,
			&i.KraPin,
			&i.County,
			&i.Address,
			&i.Verified,
			&i.VerifiedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
			&i.CoverageStartDate,
			&i.CoverageEndDate,
			&i.City,
			&i.Country,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembersByPolicy = `-- name: ListMembersByPolicy :many
SELECT id, policy_id, national_id, name, date_of_birth, gender, relationship, member_number, phone, email, kra_pin, county, address, verified, verified_at, created_at, updated_at, status, coverage_start_date, coverage_end_date, city, country FROM members WHERE policy_id = $1 ORDER BY relationship, name
`

func (q *Queries) ListMembersByPolicy(ctx context.Context, policyID uuid.UUID) ([]Member, error) {
	rows, err := q.db.Query(ctx, listMembersByPolicy, policyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Member{}
	for rows.Next() {
		var i Member
		if err := rows.Scan(
			&i.ID,
			&i.PolicyID,
			&i.NationalID,
			&i.Name,
			&i.DateOfBirth,
			&i.Gender,
			&i.Relationship,
			&i.MemberNumber,
			&i.Phone,
			&i.Email,
			&i.KraPin,
			&i.County,
			&i.Address,
			&i.Verified,
			&i.VerifiedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
			&i.CoverageStartDate,
			&i.CoverageEndDate,
			&i.City,
			&i.Country,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembersFiltered = `-- name: ListMembersFiltered :many
SELECT id, policy_id, national_id, name, date_of_birth, gender, relationship, member_number, phone, email, kra_pin, county, address, verified, verified_at, created_at, updated_at, status, coverage_start_date, coverage_end_date, city, country FROM members
WHERE ($1::text = '' OR (name ILIKE '%' || $1 || '%' OR national_id ILIKE '%' || $1 || '%' OR email ILIKE '%' || $1 || '%' OR phone ILIKE '%' || $1 || '%'))
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListMembersFilteredParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) ListMembersFiltered(ctx context.Context, arg ListMembersFilteredParams) ([]Member, error) {
	rows, err := q.db.Query(ctx, listMembersFiltered, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Member{}
	for rows.Next() {
		var i Member
		if err := rows.Scan(
			&i.ID,
			&i.PolicyID,
			&i.NationalID,
			&i.Name,
			&i.DateOfBirth,
			&i.Gender,
			&i.Relationship,
			&i.MemberNumber,
			&i.Phone,
			&i.Email,
			&i.KraPin,
			&i.County,
			&i.Address,
			&i.Verified,
			&i.VerifiedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
			&i.CoverageStartDate,
			&i.CoverageEndDate,
			&i.City,
			&i.Country,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingMembersByPolicy = `-- name: ListPendingMembersByPolicy :many
SELECT id, policy_id, national_id, name, date_of_birth, gender, relationship, member_number, phone, email, kra_pin, county, address, verified, verified_at, created_at, updated_at, status, coverage_start_date, coverage_end_date, city, country FROM members WHERE policy_id = $1 AND status = 'PENDING'
`

func (q *Queries) ListPendingMembersByPolicy(ctx context.Context, policyID uuid.UUID) ([]Member, error) {
	rows, err := q.db.Query(ctx, listPendingMembersByPolicy, policyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Member{}
	for rows.Next() {
		var i Member
		if err := rows.Scan(
			&i.ID,
			&i.PolicyID,
			&i.NationalID,
			&i.Name,
			&i.DateOfBirth,
			&i.Gender,
			&i.Relationship,
			&i.MemberNumber,
			&i.Phone,
			&i.Email,
			&i.KraPin,
			&i.County,
			&i.Address,
			&i.Verified,
			&i.VerifiedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
			&i.CoverageStartDate,
			&i.CoverageEndDate,
			&i.City,
			&i.Country,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMember = `-- name: UpdateMember :one
UPDATE members SET
    name = COALESCE($1, name),
    phone = COALESCE($2, phone),
    email = COALESCE($3, email),
    kra_pin = COALESCE($4, kra_pin),
    county = COALESCE($5, county),
    city = COALESCE($6, city),
    country = COALESCE($7, country),
    address = COALESCE($8, address),
    updated_at = NOW()
WHERE id = $9 RETURNING id, policy_id, national_id, name, date_of_birth, gender, relationship, member_number, phone, email, kra_pin, county, address, verified, verified_at, created_at, updated_at, status, coverage_start_date, coverage_end_date, city, country
`

type UpdateMemberParams struct {
	Name    pgtype.Text `json:"name"`
	Phone   pgtype.Text `json:"phone"`
	Email   pgtype.Text `json:"email"`
	KraPin  pgtype.Text `json:"kra_pin"`
	County  pgtype.Text `json:"county"`
	City    pgtype.Text `json:"city"`
	Country pgtype.Text `json:"country"`
	Address pgtype.Text `json:"address"`
	ID      uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateMember(ctx context.Context, arg UpdateMemberParams) (Member, error) {
	row := q.db.QueryRow(ctx, updateMember,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.KraPin,
		arg.County,
		arg.City,
		arg.Country,
		arg.Address,
		arg.ID,
	)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.PolicyID,
		&i.NationalID,
		&i.Name,
		&i.DateOfBirth,
		&i.Gender,
		&i.Relationship,
		&i.MemberNumber,
		&i.Phone,
		&i.Email,
		&i.KraPin,
		&i.County,
		&i.Address,
		&i.Verified,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.CoverageStartDate,
		&i.CoverageEndDate,
		&i.City,
		&i.Country,
	)
	return i, err
}

const updateMemberCoverageDates = `-- name: UpdateMemberCoverageDates :one
UPDATE members SET
    coverage_start_date = COALESCE($1, coverage_start_date),
    coverage_end_date = COALESCE($2, coverage_end_date),
    updated_at = NOW()
WHERE id = $3 RETURNING id, policy_id, national_id, name, date_of_birth, gender, relationship, member_number, phone, email, kra_pin, county, address, verified, verified_at, created_at, updated_at, status, coverage_start_date, coverage_end_date, city, country
`

type UpdateMemberCoverageDatesParams struct {
	CoverageStartDate pgtype.Timestamptz `json:"coverage_start_date"`
	CoverageEndDate   pgtype.Timestamptz `json:"coverage_end_date"`
	ID                uuid.UUID          `json:"id"`
}

func (q *Queries) UpdateMemberCoverageDates(ctx context.Context, arg UpdateMemberCoverageDatesParams) (Member, error) {
	row := q.db.QueryRow(ctx, updateMemberCoverageDates, arg.CoverageStartDate, arg.CoverageEndDate, arg.ID)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.PolicyID,
		&i.NationalID,
		&i.Name,
		&i.DateOfBirth,
		&i.Gender,
		&i.Relationship,
		&i.MemberNumber,
		&i.Phone,
		&i.Email,
		&i.KraPin,
		&i.County,
		&i.Address,
		&i.Verified,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.CoverageStartDate,
		&i.CoverageEndDate,
		&i.City,
		&i.Country,
	)
	return i, err
}

const updateMemberStatus = `-- name: UpdateMemberStatus :one
UPDATE members SET status = $2, updated_at = NOW() WHERE id = $1 RETURNING id, policy_id, national_id, name, date_of_birth, gender, relationship, member_number, phone, email, kra_pin, county, address, verified, verified_at, created_at, updated_at, status, coverage_start_date, coverage_end_date, city, country
`

type UpdateMemberStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateMemberStatus(ctx context.Context, arg UpdateMemberStatusParams) (Member, error) {
	row := q.db.QueryRow(ctx, updateMemberStatus, arg.ID, arg.Status)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.PolicyID,
		&i.NationalID,
		&i.Name,
		&i.DateOfBirth,
		&i.Gender,
		&i.Relationship,
		&i.MemberNumber,
		&i.Phone,
		&i.Email,
		&i.KraPin,
		&i.County,
		&i.Address,
		&i.Verified,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.CoverageStartDate,
		&i.CoverageEndDate,
		&i.City,
		&i.Country,
	)
	return i, err
}

const verifyMember = `-- name: VerifyMember :one
UPDATE members SET verified = TRUE, verified_at = NOW(), updated_at = NOW() WHERE id = $1 RETURNING id, policy_id, national_id, name, date_of_birth, gender, relationship, member_number, phone, email, kra_pin, county, address, verified, verified_at, created_at, updated_at, status, coverage_start_date, coverage_end_date, city, country
`

func (q *Queries) VerifyMember(ctx context.Context, id uuid.UUID) (Member, error) {
	row := q.db.QueryRow(ctx, verifyMember, id)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.PolicyID,
		&i.NationalID,
		&i.Name,
		&i.DateOfBirth,
		&i.Gender,
		&i.Relationship,
		&i.MemberNumber,
		&i.Phone,
		&i.Email,
		&i.KraPin,
		&i.County,
		&i.Address,
		&i.Verified,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.CoverageStartDate,
		&i.CoverageEndDate,
		&i.City,
		&i.Country,
	)
	return i, err
}
