// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"encoding/json"
	"time"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AdjudicationDecision struct {
	ID                   uuid.UUID       `json:"id"`
	ClaimID              uuid.UUID       `json:"claim_id"`
	Decision             string          `json:"decision"`
	PayableAmount        int64           `json:"payable_amount"`
	MemberResponsibility int64           `json:"member_responsibility"`
	Reasons              json.RawMessage `json:"reasons"`
	RuleResults          json.RawMessage `json:"rule_results"`
	AdjudicatedBy        pgtype.UUID     `json:"adjudicated_by"`
	AdjudicatedAt        time.Time       `json:"adjudicated_at"`
	CreatedAt            time.Time       `json:"created_at"`
	UpdatedAt            time.Time       `json:"updated_at"`
}

type AuditEvent struct {
	ID         uuid.UUID   `json:"id"`
	UserID     pgtype.UUID `json:"user_id"`
	EntityType string      `json:"entity_type"`
	EntityID   uuid.UUID   `json:"entity_id"`
	Action     string      `json:"action"`
	OldValue   []byte      `json:"old_value"`
	NewValue   []byte      `json:"new_value"`
	IpAddress  pgtype.Text `json:"ip_address"`
	UserAgent  pgtype.Text `json:"user_agent"`
	CreatedAt  time.Time   `json:"created_at"`
}

type Benefit struct {
	ID                uuid.UUID `json:"id"`
	PlanID            uuid.UUID `json:"plan_id"`
	Name              string    `json:"name"`
	Category          string    `json:"category"`
	AnnualLimit       int64     `json:"annual_limit"`
	CoPayType         string    `json:"co_pay_type"`
	CoPayValue        int64     `json:"co_pay_value"`
	WaitingPeriodDays int32     `json:"waiting_period_days"`
	SubLimitType      string    `json:"sub_limit_type"`
	SubLimitValue     int64     `json:"sub_limit_value"`
	MinAge            int32     `json:"min_age"`
	MaxAge            int32     `json:"max_age"`
	WaitingPeriodType string    `json:"waiting_period_type"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
}

type Claim struct {
	ID                   uuid.UUID          `json:"id"`
	ClaimNumber          string             `json:"claim_number"`
	PolicyID             uuid.UUID          `json:"policy_id"`
	MemberID             uuid.UUID          `json:"member_id"`
	ProviderID           uuid.UUID          `json:"provider_id"`
	PreauthID            pgtype.UUID        `json:"preauth_id"`
	Status               string             `json:"status"`
	TotalAmount          int64              `json:"total_amount"`
	ApprovedAmount       int64              `json:"approved_amount"`
	CoPayAmount          int64              `json:"co_pay_amount"`
	MemberResponsibility int64              `json:"member_responsibility"`
	DiagnosisCodes       json.RawMessage    `json:"diagnosis_codes"`
	ServiceDate          time.Time          `json:"service_date"`
	AdmissionDate        pgtype.Timestamptz `json:"admission_date"`
	DischargeDate        pgtype.Timestamptz `json:"discharge_date"`
	Notes                string             `json:"notes"`
	RejectionReason      pgtype.Text        `json:"rejection_reason"`
	CreatedBy            pgtype.UUID        `json:"created_by"`
	CreatedAt            time.Time          `json:"created_at"`
	UpdatedAt            time.Time          `json:"updated_at"`
}

type ClaimLineItem struct {
	ID             uuid.UUID   `json:"id"`
	ClaimID        uuid.UUID   `json:"claim_id"`
	ProcedureCode  string      `json:"procedure_code"`
	ProcedureName  string      `json:"procedure_name"`
	DiagnosisCode  pgtype.Text `json:"diagnosis_code"`
	Quantity       int32       `json:"quantity"`
	UnitPrice      int64       `json:"unit_price"`
	TotalPrice     int64       `json:"total_price"`
	ApprovedAmount int64       `json:"approved_amount"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
}

type Contract struct {
	ID         uuid.UUID   `json:"id"`
	ProviderID uuid.UUID   `json:"provider_id"`
	StartDate  time.Time   `json:"start_date"`
	EndDate    time.Time   `json:"end_date"`
	Terms      string      `json:"terms"`
	Status     string      `json:"status"`
	CreatedBy  pgtype.UUID `json:"created_by"`
	CreatedAt  time.Time   `json:"created_at"`
	UpdatedAt  time.Time   `json:"updated_at"`
}

type Exclusion struct {
	ID          uuid.UUID       `json:"id"`
	PlanID      uuid.UUID       `json:"plan_id"`
	Description string          `json:"description"`
	Type        string          `json:"type"`
	IcdCodes    json.RawMessage `json:"icd_codes"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

type FraudFlag struct {
	ID               uuid.UUID          `json:"id"`
	ClaimID          uuid.UUID          `json:"claim_id"`
	FlagType         string             `json:"flag_type"`
	Severity         string             `json:"severity"`
	Details          string             `json:"details"`
	Resolved         bool               `json:"resolved"`
	ResolvedBy       pgtype.UUID        `json:"resolved_by"`
	ResolvedAt       pgtype.Timestamptz `json:"resolved_at"`
	ReferenceClaimID pgtype.UUID        `json:"reference_claim_id"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
}

type Installment struct {
	ID                uuid.UUID          `json:"id"`
	ScheduleID        uuid.UUID          `json:"schedule_id"`
	InstallmentNumber int32              `json:"installment_number"`
	DueDate           time.Time          `json:"due_date"`
	Amount            int64              `json:"amount"`
	Status            string             `json:"status"`
	PaidAt            pgtype.Timestamptz `json:"paid_at"`
	InvoiceID         pgtype.UUID        `json:"invoice_id"`
	CreatedAt         time.Time          `json:"created_at"`
	UpdatedAt         time.Time          `json:"updated_at"`
}

type InstallmentSchedule struct {
	ID                   uuid.UUID   `json:"id"`
	PolicyID             uuid.UUID   `json:"policy_id"`
	Frequency            string      `json:"frequency"`
	TotalInstallments    int32       `json:"total_installments"`
	AmountPerInstallment int64       `json:"amount_per_installment"`
	StartDate            time.Time   `json:"start_date"`
	Status               string      `json:"status"`
	CreatedBy            pgtype.UUID `json:"created_by"`
	CreatedAt            time.Time   `json:"created_at"`
	UpdatedAt            time.Time   `json:"updated_at"`
}

type Invoice struct {
	ID                 uuid.UUID   `json:"id"`
	PolicyID           uuid.UUID   `json:"policy_id"`
	InvoiceNumber      string      `json:"invoice_number"`
	Amount             int64       `json:"amount"`
	Currency           string      `json:"currency"`
	DueDate            time.Time   `json:"due_date"`
	Status             string      `json:"status"`
	BillingPeriodStart time.Time   `json:"billing_period_start"`
	BillingPeriodEnd   time.Time   `json:"billing_period_end"`
	Notes              string      `json:"notes"`
	CreatedBy          pgtype.UUID `json:"created_by"`
	CreatedAt          time.Time   `json:"created_at"`
	UpdatedAt          time.Time   `json:"updated_at"`
}

type Member struct {
	ID           uuid.UUID          `json:"id"`
	PolicyID     uuid.UUID          `json:"policy_id"`
	NationalID   pgtype.Text        `json:"national_id"`
	Name         string             `json:"name"`
	DateOfBirth  pgtype.Date        `json:"date_of_birth"`
	Gender       string             `json:"gender"`
	Relationship string             `json:"relationship"`
	MemberNumber string             `json:"member_number"`
	Phone        pgtype.Text        `json:"phone"`
	Email        pgtype.Text        `json:"email"`
	KraPin       pgtype.Text        `json:"kra_pin"`
	County       pgtype.Text        `json:"county"`
	Address      pgtype.Text        `json:"address"`
	Verified     bool               `json:"verified"`
	VerifiedAt   pgtype.Timestamptz `json:"verified_at"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
}

type Notification struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	Channel    string             `json:"channel"`
	Type       string             `json:"type"`
	Subject    string             `json:"subject"`
	Body       string             `json:"body"`
	Metadata   []byte             `json:"metadata"`
	Status     string             `json:"status"`
	RetryCount int32              `json:"retry_count"`
	MaxRetries int32              `json:"max_retries"`
	SentAt     pgtype.Timestamptz `json:"sent_at"`
	ReadAt     pgtype.Timestamptz `json:"read_at"`
	CreatedAt  time.Time          `json:"created_at"`
	UpdatedAt  time.Time          `json:"updated_at"`
}

type Payment struct {
	ID              uuid.UUID          `json:"id"`
	InvoiceID       pgtype.UUID        `json:"invoice_id"`
	ClaimID         pgtype.UUID        `json:"claim_id"`
	Type            string             `json:"type"`
	Amount          int64              `json:"amount"`
	Currency        string             `json:"currency"`
	Method          string             `json:"method"`
	ReferenceNumber pgtype.Text        `json:"reference_number"`
	Status          string             `json:"status"`
	RetryCount      int32              `json:"retry_count"`
	MaxRetries      int32              `json:"max_retries"`
	GatewayResponse []byte             `json:"gateway_response"`
	PaidAt          pgtype.Timestamptz `json:"paid_at"`
	ReconciledAt    pgtype.Timestamptz `json:"reconciled_at"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
}

type Permission struct {
	ID          uuid.UUID `json:"id"`
	Resource    string    `json:"resource"`
	Action      string    `json:"action"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Plan struct {
	ID          uuid.UUID   `json:"id"`
	Name        string      `json:"name"`
	Type        string      `json:"type"`
	Segment     string      `json:"segment"`
	BasePremium int64       `json:"base_premium"`
	Currency    string      `json:"currency"`
	Status      string      `json:"status"`
	Description string      `json:"description"`
	CreatedBy   pgtype.UUID `json:"created_by"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
}

type Policy struct {
	ID                uuid.UUID          `json:"id"`
	PlanID            uuid.UUID          `json:"plan_id"`
	PolicyholderName  string             `json:"policyholder_name"`
	PolicyholderEmail string             `json:"policyholder_email"`
	PolicyholderPhone string             `json:"policyholder_phone"`
	PolicyNumber      string             `json:"policy_number"`
	Status            string             `json:"status"`
	StartDate         pgtype.Timestamptz `json:"start_date"`
	EndDate           pgtype.Timestamptz `json:"end_date"`
	PremiumAmount     int64              `json:"premium_amount"`
	Currency          string             `json:"currency"`
	CreatedBy         pgtype.UUID        `json:"created_by"`
	CreatedAt         time.Time          `json:"created_at"`
	UpdatedAt         time.Time          `json:"updated_at"`
}

type Preauthorization struct {
	ID             uuid.UUID          `json:"id"`
	PolicyID       uuid.UUID          `json:"policy_id"`
	MemberID       uuid.UUID          `json:"member_id"`
	ProviderID     uuid.UUID          `json:"provider_id"`
	AuthCode       pgtype.Text        `json:"auth_code"`
	ProcedureCodes json.RawMessage    `json:"procedure_codes"`
	DiagnosisCodes json.RawMessage    `json:"diagnosis_codes"`
	EstimatedCost  int64              `json:"estimated_cost"`
	ApprovedAmount int64              `json:"approved_amount"`
	Status         string             `json:"status"`
	ValidityStart  pgtype.Timestamptz `json:"validity_start"`
	ValidityEnd    pgtype.Timestamptz `json:"validity_end"`
	Notes          string             `json:"notes"`
	DenialReason   pgtype.Text        `json:"denial_reason"`
	ReviewedBy     pgtype.UUID        `json:"reviewed_by"`
	ReviewedAt     pgtype.Timestamptz `json:"reviewed_at"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
}

type PremiumRule struct {
	ID              uuid.UUID   `json:"id"`
	PlanID          uuid.UUID   `json:"plan_id"`
	CalculationType string      `json:"calculation_type"`
	Relationship    pgtype.Text `json:"relationship"`
	RateAmount      int64       `json:"rate_amount"`
	DiscountType    pgtype.Text `json:"discount_type"`
	DiscountValue   int64       `json:"discount_value"`
	MinMembers      int32       `json:"min_members"`
	CreatedAt       time.Time   `json:"created_at"`
	UpdatedAt       time.Time   `json:"updated_at"`
}

type Provider struct {
	ID            uuid.UUID   `json:"id"`
	Name          string      `json:"name"`
	Type          string      `json:"type"`
	LicenseNumber string      `json:"license_number"`
	Status        string      `json:"status"`
	County        pgtype.Text `json:"county"`
	Address       pgtype.Text `json:"address"`
	Phone         pgtype.Text `json:"phone"`
	Email         pgtype.Text `json:"email"`
	ContactPerson pgtype.Text `json:"contact_person"`
	UserID        pgtype.UUID `json:"user_id"`
	CreatedBy     pgtype.UUID `json:"created_by"`
	CreatedAt     time.Time   `json:"created_at"`
	UpdatedAt     time.Time   `json:"updated_at"`
}

type ProviderNetwork struct {
	ID              uuid.UUID   `json:"id"`
	PlanID          uuid.UUID   `json:"plan_id"`
	ProviderID      uuid.UUID   `json:"provider_id"`
	BenefitCategory pgtype.Text `json:"benefit_category"`
	Status          string      `json:"status"`
	CreatedAt       time.Time   `json:"created_at"`
	UpdatedAt       time.Time   `json:"updated_at"`
}

type RateCard struct {
	ID            uuid.UUID   `json:"id"`
	ProviderID    uuid.UUID   `json:"provider_id"`
	ProcedureCode string      `json:"procedure_code"`
	ProcedureName string      `json:"procedure_name"`
	RateAmount    int64       `json:"rate_amount"`
	EffectiveDate time.Time   `json:"effective_date"`
	AgeFrom       int32       `json:"age_from"`
	AgeTo         int32       `json:"age_to"`
	Gender        pgtype.Text `json:"gender"`
	Relationship  pgtype.Text `json:"relationship"`
	CreatedAt     time.Time   `json:"created_at"`
	UpdatedAt     time.Time   `json:"updated_at"`
}

type Remittance struct {
	ID                   uuid.UUID       `json:"id"`
	ProviderID           uuid.UUID       `json:"provider_id"`
	ClaimIds             json.RawMessage `json:"claim_ids"`
	TotalAmount          int64           `json:"total_amount"`
	Currency             string          `json:"currency"`
	Status               string          `json:"status"`
	RemittanceAdviceSent bool            `json:"remittance_advice_sent"`
	PeriodStart          time.Time       `json:"period_start"`
	PeriodEnd            time.Time       `json:"period_end"`
	PaymentID            pgtype.UUID     `json:"payment_id"`
	CreatedBy            pgtype.UUID     `json:"created_by"`
	CreatedAt            time.Time       `json:"created_at"`
	UpdatedAt            time.Time       `json:"updated_at"`
}

type Role struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type RolePermission struct {
	ID           uuid.UUID `json:"id"`
	RoleID       uuid.UUID `json:"role_id"`
	PermissionID uuid.UUID `json:"permission_id"`
	CreatedAt    time.Time `json:"created_at"`
}

type User struct {
	ID           uuid.UUID   `json:"id"`
	CognitoSub   pgtype.Text `json:"cognito_sub"`
	Email        string      `json:"email"`
	Name         string      `json:"name"`
	Phone        pgtype.Text `json:"phone"`
	NationalID   pgtype.Text `json:"national_id"`
	RoleID       uuid.UUID   `json:"role_id"`
	Status       string      `json:"status"`
	CreatedBy    pgtype.UUID `json:"created_by"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
	PasswordHash string      `json:"password_hash"`
}
