// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: payment.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const confirmPayment = `-- name: ConfirmPayment :one
UPDATE payments SET status = 'CONFIRMED', paid_at = NOW(), gateway_response = $2, updated_at = NOW() WHERE id = $1 RETURNING id, invoice_id, claim_id, type, amount, currency, method, reference_number, status, retry_count, max_retries, gateway_response, paid_at, reconciled_at, created_by, created_at, updated_at
`

type ConfirmPaymentParams struct {
	ID              uuid.UUID `json:"id"`
	GatewayResponse []byte    `json:"gateway_response"`
}

func (q *Queries) ConfirmPayment(ctx context.Context, arg ConfirmPaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, confirmPayment, arg.ID, arg.GatewayResponse)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.ClaimID,
		&i.Type,
		&i.Amount,
		&i.Currency,
		&i.Method,
		&i.ReferenceNumber,
		&i.Status,
		&i.RetryCount,
		&i.MaxRetries,
		&i.GatewayResponse,
		&i.PaidAt,
		&i.ReconciledAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countPayments = `-- name: CountPayments :one
SELECT COUNT(*) FROM payments
`

func (q *Queries) CountPayments(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPayments)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (invoice_id, claim_id, type, amount, currency, method, reference_number, status, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING id, invoice_id, claim_id, type, amount, currency, method, reference_number, status, retry_count, max_retries, gateway_response, paid_at, reconciled_at, created_by, created_at, updated_at
`

type CreatePaymentParams struct {
	InvoiceID       pgtype.UUID `json:"invoice_id"`
	ClaimID         pgtype.UUID `json:"claim_id"`
	Type            string      `json:"type"`
	Amount          int64       `json:"amount"`
	Currency        string      `json:"currency"`
	Method          string      `json:"method"`
	ReferenceNumber pgtype.Text `json:"reference_number"`
	Status          string      `json:"status"`
	CreatedBy       pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.InvoiceID,
		arg.ClaimID,
		arg.Type,
		arg.Amount,
		arg.Currency,
		arg.Method,
		arg.ReferenceNumber,
		arg.Status,
		arg.CreatedBy,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.ClaimID,
		&i.Type,
		&i.Amount,
		&i.Currency,
		&i.Method,
		&i.ReferenceNumber,
		&i.Status,
		&i.RetryCount,
		&i.MaxRetries,
		&i.GatewayResponse,
		&i.PaidAt,
		&i.ReconciledAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFailedPaymentsForRetry = `-- name: GetFailedPaymentsForRetry :many
SELECT id, invoice_id, claim_id, type, amount, currency, method, reference_number, status, retry_count, max_retries, gateway_response, paid_at, reconciled_at, created_by, created_at, updated_at FROM payments WHERE status = 'FAILED' AND retry_count < max_retries ORDER BY created_at ASC LIMIT $1
`

func (q *Queries) GetFailedPaymentsForRetry(ctx context.Context, limit int32) ([]Payment, error) {
	rows, err := q.db.Query(ctx, getFailedPaymentsForRetry, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceID,
			&i.ClaimID,
			&i.Type,
			&i.Amount,
			&i.Currency,
			&i.Method,
			&i.ReferenceNumber,
			&i.Status,
			&i.RetryCount,
			&i.MaxRetries,
			&i.GatewayResponse,
			&i.PaidAt,
			&i.ReconciledAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT id, invoice_id, claim_id, type, amount, currency, method, reference_number, status, retry_count, max_retries, gateway_response, paid_at, reconciled_at, created_by, created_at, updated_at FROM payments WHERE id = $1
`

func (q *Queries) GetPaymentByID(ctx context.Context, id uuid.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByID, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.ClaimID,
		&i.Type,
		&i.Amount,
		&i.Currency,
		&i.Method,
		&i.ReferenceNumber,
		&i.Status,
		&i.RetryCount,
		&i.MaxRetries,
		&i.GatewayResponse,
		&i.PaidAt,
		&i.ReconciledAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByReference = `-- name: GetPaymentByReference :one
SELECT id, invoice_id, claim_id, type, amount, currency, method, reference_number, status, retry_count, max_retries, gateway_response, paid_at, reconciled_at, created_by, created_at, updated_at FROM payments WHERE reference_number = $1
`

func (q *Queries) GetPaymentByReference(ctx context.Context, referenceNumber pgtype.Text) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByReference, referenceNumber)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.ClaimID,
		&i.Type,
		&i.Amount,
		&i.Currency,
		&i.Method,
		&i.ReferenceNumber,
		&i.Status,
		&i.RetryCount,
		&i.MaxRetries,
		&i.GatewayResponse,
		&i.PaidAt,
		&i.ReconciledAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementPaymentRetry = `-- name: IncrementPaymentRetry :one
UPDATE payments SET retry_count = retry_count + 1, status = 'PROCESSING', updated_at = NOW() WHERE id = $1 RETURNING id, invoice_id, claim_id, type, amount, currency, method, reference_number, status, retry_count, max_retries, gateway_response, paid_at, reconciled_at, created_by, created_at, updated_at
`

func (q *Queries) IncrementPaymentRetry(ctx context.Context, id uuid.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, incrementPaymentRetry, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.ClaimID,
		&i.Type,
		&i.Amount,
		&i.Currency,
		&i.Method,
		&i.ReferenceNumber,
		&i.Status,
		&i.RetryCount,
		&i.MaxRetries,
		&i.GatewayResponse,
		&i.PaidAt,
		&i.ReconciledAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPayments = `-- name: ListPayments :many
SELECT id, invoice_id, claim_id, type, amount, currency, method, reference_number, status, retry_count, max_retries, gateway_response, paid_at, reconciled_at, created_by, created_at, updated_at FROM payments ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListPaymentsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPayments(ctx context.Context, arg ListPaymentsParams) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPayments, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceID,
			&i.ClaimID,
			&i.Type,
			&i.Amount,
			&i.Currency,
			&i.Method,
			&i.ReferenceNumber,
			&i.Status,
			&i.RetryCount,
			&i.MaxRetries,
			&i.GatewayResponse,
			&i.PaidAt,
			&i.ReconciledAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentsByInvoice = `-- name: ListPaymentsByInvoice :many
SELECT id, invoice_id, claim_id, type, amount, currency, method, reference_number, status, retry_count, max_retries, gateway_response, paid_at, reconciled_at, created_by, created_at, updated_at FROM payments WHERE invoice_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListPaymentsByInvoice(ctx context.Context, invoiceID pgtype.UUID) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsByInvoice, invoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceID,
			&i.ClaimID,
			&i.Type,
			&i.Amount,
			&i.Currency,
			&i.Method,
			&i.ReferenceNumber,
			&i.Status,
			&i.RetryCount,
			&i.MaxRetries,
			&i.GatewayResponse,
			&i.PaidAt,
			&i.ReconciledAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentsByStatus = `-- name: ListPaymentsByStatus :many
SELECT id, invoice_id, claim_id, type, amount, currency, method, reference_number, status, retry_count, max_retries, gateway_response, paid_at, reconciled_at, created_by, created_at, updated_at FROM payments WHERE status = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListPaymentsByStatusParams struct {
	Status string `json:"status"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListPaymentsByStatus(ctx context.Context, arg ListPaymentsByStatusParams) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceID,
			&i.ClaimID,
			&i.Type,
			&i.Amount,
			&i.Currency,
			&i.Method,
			&i.ReferenceNumber,
			&i.Status,
			&i.RetryCount,
			&i.MaxRetries,
			&i.GatewayResponse,
			&i.PaidAt,
			&i.ReconciledAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reconcilePayment = `-- name: ReconcilePayment :one
UPDATE payments SET status = 'RECONCILED', reconciled_at = NOW(), updated_at = NOW() WHERE id = $1 RETURNING id, invoice_id, claim_id, type, amount, currency, method, reference_number, status, retry_count, max_retries, gateway_response, paid_at, reconciled_at, created_by, created_at, updated_at
`

func (q *Queries) ReconcilePayment(ctx context.Context, id uuid.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, reconcilePayment, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.ClaimID,
		&i.Type,
		&i.Amount,
		&i.Currency,
		&i.Method,
		&i.ReferenceNumber,
		&i.Status,
		&i.RetryCount,
		&i.MaxRetries,
		&i.GatewayResponse,
		&i.PaidAt,
		&i.ReconciledAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :one
UPDATE payments SET status = $2, updated_at = NOW() WHERE id = $1 RETURNING id, invoice_id, claim_id, type, amount, currency, method, reference_number, status, retry_count, max_retries, gateway_response, paid_at, reconciled_at, created_by, created_at, updated_at
`

type UpdatePaymentStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (Payment, error) {
	row := q.db.QueryRow(ctx, updatePaymentStatus, arg.ID, arg.Status)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.ClaimID,
		&i.Type,
		&i.Amount,
		&i.Currency,
		&i.Method,
		&i.ReferenceNumber,
		&i.Status,
		&i.RetryCount,
		&i.MaxRetries,
		&i.GatewayResponse,
		&i.PaidAt,
		&i.ReconciledAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
