// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: plan.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countPlans = `-- name: CountPlans :one
SELECT COUNT(*) FROM plans
`

func (q *Queries) CountPlans(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPlans)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPlan = `-- name: CreatePlan :one
INSERT INTO plans (name, type, base_premium, currency, status, description, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, name, type, base_premium, currency, status, description, created_by, created_at, updated_at
`

type CreatePlanParams struct {
	Name        string      `json:"name"`
	Type        string      `json:"type"`
	BasePremium int64       `json:"base_premium"`
	Currency    string      `json:"currency"`
	Status      string      `json:"status"`
	Description string      `json:"description"`
	CreatedBy   pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreatePlan(ctx context.Context, arg CreatePlanParams) (Plan, error) {
	row := q.db.QueryRow(ctx, createPlan,
		arg.Name,
		arg.Type,
		arg.BasePremium,
		arg.Currency,
		arg.Status,
		arg.Description,
		arg.CreatedBy,
	)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.BasePremium,
		&i.Currency,
		&i.Status,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlanByID = `-- name: GetPlanByID :one
SELECT id, name, type, base_premium, currency, status, description, created_by, created_at, updated_at FROM plans WHERE id = $1
`

func (q *Queries) GetPlanByID(ctx context.Context, id uuid.UUID) (Plan, error) {
	row := q.db.QueryRow(ctx, getPlanByID, id)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.BasePremium,
		&i.Currency,
		&i.Status,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPlans = `-- name: ListPlans :many
SELECT id, name, type, base_premium, currency, status, description, created_by, created_at, updated_at FROM plans ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListPlansParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPlans(ctx context.Context, arg ListPlansParams) ([]Plan, error) {
	rows, err := q.db.Query(ctx, listPlans, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Plan{}
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.BasePremium,
			&i.Currency,
			&i.Status,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlansByStatus = `-- name: ListPlansByStatus :many
SELECT id, name, type, base_premium, currency, status, description, created_by, created_at, updated_at FROM plans WHERE status = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListPlansByStatusParams struct {
	Status string `json:"status"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListPlansByStatus(ctx context.Context, arg ListPlansByStatusParams) ([]Plan, error) {
	rows, err := q.db.Query(ctx, listPlansByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Plan{}
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.BasePremium,
			&i.Currency,
			&i.Status,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlan = `-- name: UpdatePlan :one
UPDATE plans SET
    name = COALESCE($1, name),
    type = COALESCE($2, type),
    base_premium = COALESCE($3, base_premium),
    description = COALESCE($4, description),
    status = COALESCE($5, status),
    updated_at = NOW()
WHERE id = $6 RETURNING id, name, type, base_premium, currency, status, description, created_by, created_at, updated_at
`

type UpdatePlanParams struct {
	Name        pgtype.Text `json:"name"`
	Type        pgtype.Text `json:"type"`
	BasePremium pgtype.Int8 `json:"base_premium"`
	Description pgtype.Text `json:"description"`
	Status      pgtype.Text `json:"status"`
	ID          uuid.UUID   `json:"id"`
}

func (q *Queries) UpdatePlan(ctx context.Context, arg UpdatePlanParams) (Plan, error) {
	row := q.db.QueryRow(ctx, updatePlan,
		arg.Name,
		arg.Type,
		arg.BasePremium,
		arg.Description,
		arg.Status,
		arg.ID,
	)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.BasePremium,
		&i.Currency,
		&i.Status,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
