// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: policy_renewal.sql

package db

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPolicyRenewal = `-- name: CreatePolicyRenewal :one
INSERT INTO policy_renewals (policy_id, status, renewal_date, new_premium, premium_change_reason, new_plan_id, expires_at, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING id, policy_id, renewed_policy_id, status, renewal_date, new_premium, premium_change_reason, new_plan_id, approved_by, approved_at, completed_at, expires_at, created_by, created_at, updated_at
`

type CreatePolicyRenewalParams struct {
	PolicyID            uuid.UUID          `json:"policy_id"`
	Status              string             `json:"status"`
	RenewalDate         time.Time          `json:"renewal_date"`
	NewPremium          pgtype.Int8        `json:"new_premium"`
	PremiumChangeReason pgtype.Text        `json:"premium_change_reason"`
	NewPlanID           pgtype.UUID        `json:"new_plan_id"`
	ExpiresAt           pgtype.Timestamptz `json:"expires_at"`
	CreatedBy           uuid.UUID          `json:"created_by"`
}

func (q *Queries) CreatePolicyRenewal(ctx context.Context, arg CreatePolicyRenewalParams) (PolicyRenewal, error) {
	row := q.db.QueryRow(ctx, createPolicyRenewal,
		arg.PolicyID,
		arg.Status,
		arg.RenewalDate,
		arg.NewPremium,
		arg.PremiumChangeReason,
		arg.NewPlanID,
		arg.ExpiresAt,
		arg.CreatedBy,
	)
	var i PolicyRenewal
	err := row.Scan(
		&i.ID,
		&i.PolicyID,
		&i.RenewedPolicyID,
		&i.Status,
		&i.RenewalDate,
		&i.NewPremium,
		&i.PremiumChangeReason,
		&i.NewPlanID,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPolicyRenewalByID = `-- name: GetPolicyRenewalByID :one
SELECT id, policy_id, renewed_policy_id, status, renewal_date, new_premium, premium_change_reason, new_plan_id, approved_by, approved_at, completed_at, expires_at, created_by, created_at, updated_at FROM policy_renewals WHERE id = $1
`

func (q *Queries) GetPolicyRenewalByID(ctx context.Context, id uuid.UUID) (PolicyRenewal, error) {
	row := q.db.QueryRow(ctx, getPolicyRenewalByID, id)
	var i PolicyRenewal
	err := row.Scan(
		&i.ID,
		&i.PolicyID,
		&i.RenewedPolicyID,
		&i.Status,
		&i.RenewalDate,
		&i.NewPremium,
		&i.PremiumChangeReason,
		&i.NewPlanID,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPolicyRenewalByPolicyID = `-- name: GetPolicyRenewalByPolicyID :one
SELECT id, policy_id, renewed_policy_id, status, renewal_date, new_premium, premium_change_reason, new_plan_id, approved_by, approved_at, completed_at, expires_at, created_by, created_at, updated_at FROM policy_renewals WHERE policy_id = $1 ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetPolicyRenewalByPolicyID(ctx context.Context, policyID uuid.UUID) (PolicyRenewal, error) {
	row := q.db.QueryRow(ctx, getPolicyRenewalByPolicyID, policyID)
	var i PolicyRenewal
	err := row.Scan(
		&i.ID,
		&i.PolicyID,
		&i.RenewedPolicyID,
		&i.Status,
		&i.RenewalDate,
		&i.NewPremium,
		&i.PremiumChangeReason,
		&i.NewPlanID,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listExpiredRenewals = `-- name: ListExpiredRenewals :many
SELECT id, policy_id, renewed_policy_id, status, renewal_date, new_premium, premium_change_reason, new_plan_id, approved_by, approved_at, completed_at, expires_at, created_by, created_at, updated_at FROM policy_renewals WHERE status = 'PENDING' AND expires_at IS NOT NULL AND expires_at < NOW()
`

func (q *Queries) ListExpiredRenewals(ctx context.Context) ([]PolicyRenewal, error) {
	rows, err := q.db.Query(ctx, listExpiredRenewals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PolicyRenewal{}
	for rows.Next() {
		var i PolicyRenewal
		if err := rows.Scan(
			&i.ID,
			&i.PolicyID,
			&i.RenewedPolicyID,
			&i.Status,
			&i.RenewalDate,
			&i.NewPremium,
			&i.PremiumChangeReason,
			&i.NewPlanID,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.CompletedAt,
			&i.ExpiresAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingRenewals = `-- name: ListPendingRenewals :many
SELECT id, policy_id, renewed_policy_id, status, renewal_date, new_premium, premium_change_reason, new_plan_id, approved_by, approved_at, completed_at, expires_at, created_by, created_at, updated_at FROM policy_renewals WHERE status = 'PENDING' ORDER BY renewal_date ASC
`

func (q *Queries) ListPendingRenewals(ctx context.Context) ([]PolicyRenewal, error) {
	rows, err := q.db.Query(ctx, listPendingRenewals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PolicyRenewal{}
	for rows.Next() {
		var i PolicyRenewal
		if err := rows.Scan(
			&i.ID,
			&i.PolicyID,
			&i.RenewedPolicyID,
			&i.Status,
			&i.RenewalDate,
			&i.NewPremium,
			&i.PremiumChangeReason,
			&i.NewPlanID,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.CompletedAt,
			&i.ExpiresAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePolicyRenewal = `-- name: UpdatePolicyRenewal :one
UPDATE policy_renewals SET
    status = COALESCE($1, status),
    renewed_policy_id = COALESCE($2, renewed_policy_id),
    new_premium = COALESCE($3, new_premium),
    premium_change_reason = COALESCE($4, premium_change_reason),
    approved_by = COALESCE($5, approved_by),
    approved_at = COALESCE($6, approved_at),
    completed_at = COALESCE($7, completed_at),
    updated_at = NOW()
WHERE id = $8 RETURNING id, policy_id, renewed_policy_id, status, renewal_date, new_premium, premium_change_reason, new_plan_id, approved_by, approved_at, completed_at, expires_at, created_by, created_at, updated_at
`

type UpdatePolicyRenewalParams struct {
	Status              pgtype.Text        `json:"status"`
	RenewedPolicyID     pgtype.UUID        `json:"renewed_policy_id"`
	NewPremium          pgtype.Int8        `json:"new_premium"`
	PremiumChangeReason pgtype.Text        `json:"premium_change_reason"`
	ApprovedBy          pgtype.UUID        `json:"approved_by"`
	ApprovedAt          pgtype.Timestamptz `json:"approved_at"`
	CompletedAt         pgtype.Timestamptz `json:"completed_at"`
	ID                  uuid.UUID          `json:"id"`
}

func (q *Queries) UpdatePolicyRenewal(ctx context.Context, arg UpdatePolicyRenewalParams) (PolicyRenewal, error) {
	row := q.db.QueryRow(ctx, updatePolicyRenewal,
		arg.Status,
		arg.RenewedPolicyID,
		arg.NewPremium,
		arg.PremiumChangeReason,
		arg.ApprovedBy,
		arg.ApprovedAt,
		arg.CompletedAt,
		arg.ID,
	)
	var i PolicyRenewal
	err := row.Scan(
		&i.ID,
		&i.PolicyID,
		&i.RenewedPolicyID,
		&i.Status,
		&i.RenewalDate,
		&i.NewPremium,
		&i.PremiumChangeReason,
		&i.NewPlanID,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePolicyRenewalStatus = `-- name: UpdatePolicyRenewalStatus :one
UPDATE policy_renewals SET status = $2, updated_at = NOW() WHERE id = $1 RETURNING id, policy_id, renewed_policy_id, status, renewal_date, new_premium, premium_change_reason, new_plan_id, approved_by, approved_at, completed_at, expires_at, created_by, created_at, updated_at
`

type UpdatePolicyRenewalStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdatePolicyRenewalStatus(ctx context.Context, arg UpdatePolicyRenewalStatusParams) (PolicyRenewal, error) {
	row := q.db.QueryRow(ctx, updatePolicyRenewalStatus, arg.ID, arg.Status)
	var i PolicyRenewal
	err := row.Scan(
		&i.ID,
		&i.PolicyID,
		&i.RenewedPolicyID,
		&i.Status,
		&i.RenewalDate,
		&i.NewPremium,
		&i.PremiumChangeReason,
		&i.NewPlanID,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
