// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: policy.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countPolicies = `-- name: CountPolicies :one
SELECT COUNT(*) FROM policies
`

func (q *Queries) CountPolicies(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPolicies)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPoliciesByStatus = `-- name: CountPoliciesByStatus :one
SELECT COUNT(*) FROM policies WHERE status = $1
`

func (q *Queries) CountPoliciesByStatus(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRow(ctx, countPoliciesByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPolicy = `-- name: CreatePolicy :one
INSERT INTO policies (plan_id, policyholder_name, policyholder_email, policyholder_phone, policy_number, status, start_date, end_date, premium_amount, currency, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11) RETURNING id, plan_id, policyholder_name, policyholder_email, policyholder_phone, policy_number, status, start_date, end_date, premium_amount, currency, created_by, created_at, updated_at
`

type CreatePolicyParams struct {
	PlanID            uuid.UUID          `json:"plan_id"`
	PolicyholderName  string             `json:"policyholder_name"`
	PolicyholderEmail string             `json:"policyholder_email"`
	PolicyholderPhone string             `json:"policyholder_phone"`
	PolicyNumber      string             `json:"policy_number"`
	Status            string             `json:"status"`
	StartDate         pgtype.Timestamptz `json:"start_date"`
	EndDate           pgtype.Timestamptz `json:"end_date"`
	PremiumAmount     int64              `json:"premium_amount"`
	Currency          string             `json:"currency"`
	CreatedBy         pgtype.UUID        `json:"created_by"`
}

func (q *Queries) CreatePolicy(ctx context.Context, arg CreatePolicyParams) (Policy, error) {
	row := q.db.QueryRow(ctx, createPolicy,
		arg.PlanID,
		arg.PolicyholderName,
		arg.PolicyholderEmail,
		arg.PolicyholderPhone,
		arg.PolicyNumber,
		arg.Status,
		arg.StartDate,
		arg.EndDate,
		arg.PremiumAmount,
		arg.Currency,
		arg.CreatedBy,
	)
	var i Policy
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.PolicyholderName,
		&i.PolicyholderEmail,
		&i.PolicyholderPhone,
		&i.PolicyNumber,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.PremiumAmount,
		&i.Currency,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActivePoliciesForBilling = `-- name: GetActivePoliciesForBilling :many
SELECT id, plan_id, policyholder_name, policyholder_email, policyholder_phone, policy_number, status, start_date, end_date, premium_amount, currency, created_by, created_at, updated_at FROM policies WHERE status = 'ACTIVE' AND end_date > NOW()
`

func (q *Queries) GetActivePoliciesForBilling(ctx context.Context) ([]Policy, error) {
	rows, err := q.db.Query(ctx, getActivePoliciesForBilling)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Policy{}
	for rows.Next() {
		var i Policy
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.PolicyholderName,
			&i.PolicyholderEmail,
			&i.PolicyholderPhone,
			&i.PolicyNumber,
			&i.Status,
			&i.StartDate,
			&i.EndDate,
			&i.PremiumAmount,
			&i.Currency,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLapsedPoliciesForTermination = `-- name: GetLapsedPoliciesForTermination :many
SELECT id, plan_id, policyholder_name, policyholder_email, policyholder_phone, policy_number, status, start_date, end_date, premium_amount, currency, created_by, created_at, updated_at FROM policies WHERE status = 'LAPSED' AND updated_at < NOW() - INTERVAL '90 days'
`

func (q *Queries) GetLapsedPoliciesForTermination(ctx context.Context) ([]Policy, error) {
	rows, err := q.db.Query(ctx, getLapsedPoliciesForTermination)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Policy{}
	for rows.Next() {
		var i Policy
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.PolicyholderName,
			&i.PolicyholderEmail,
			&i.PolicyholderPhone,
			&i.PolicyNumber,
			&i.Status,
			&i.StartDate,
			&i.EndDate,
			&i.PremiumAmount,
			&i.Currency,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOverduePoliciesForLapse = `-- name: GetOverduePoliciesForLapse :many
SELECT p.id, p.plan_id, p.policyholder_name, p.policyholder_email, p.policyholder_phone, p.policy_number, p.status, p.start_date, p.end_date, p.premium_amount, p.currency, p.created_by, p.created_at, p.updated_at FROM policies p
JOIN invoices i ON i.policy_id = p.id
WHERE p.status = 'ACTIVE' AND i.status = 'OVERDUE' AND i.due_date < NOW() - INTERVAL '30 days'
`

func (q *Queries) GetOverduePoliciesForLapse(ctx context.Context) ([]Policy, error) {
	rows, err := q.db.Query(ctx, getOverduePoliciesForLapse)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Policy{}
	for rows.Next() {
		var i Policy
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.PolicyholderName,
			&i.PolicyholderEmail,
			&i.PolicyholderPhone,
			&i.PolicyNumber,
			&i.Status,
			&i.StartDate,
			&i.EndDate,
			&i.PremiumAmount,
			&i.Currency,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPolicyByID = `-- name: GetPolicyByID :one
SELECT id, plan_id, policyholder_name, policyholder_email, policyholder_phone, policy_number, status, start_date, end_date, premium_amount, currency, created_by, created_at, updated_at FROM policies WHERE id = $1
`

func (q *Queries) GetPolicyByID(ctx context.Context, id uuid.UUID) (Policy, error) {
	row := q.db.QueryRow(ctx, getPolicyByID, id)
	var i Policy
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.PolicyholderName,
		&i.PolicyholderEmail,
		&i.PolicyholderPhone,
		&i.PolicyNumber,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.PremiumAmount,
		&i.Currency,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPolicyByNumber = `-- name: GetPolicyByNumber :one
SELECT id, plan_id, policyholder_name, policyholder_email, policyholder_phone, policy_number, status, start_date, end_date, premium_amount, currency, created_by, created_at, updated_at FROM policies WHERE policy_number = $1
`

func (q *Queries) GetPolicyByNumber(ctx context.Context, policyNumber string) (Policy, error) {
	row := q.db.QueryRow(ctx, getPolicyByNumber, policyNumber)
	var i Policy
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.PolicyholderName,
		&i.PolicyholderEmail,
		&i.PolicyholderPhone,
		&i.PolicyNumber,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.PremiumAmount,
		&i.Currency,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPolicies = `-- name: ListPolicies :many
SELECT id, plan_id, policyholder_name, policyholder_email, policyholder_phone, policy_number, status, start_date, end_date, premium_amount, currency, created_by, created_at, updated_at FROM policies ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListPoliciesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPolicies(ctx context.Context, arg ListPoliciesParams) ([]Policy, error) {
	rows, err := q.db.Query(ctx, listPolicies, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Policy{}
	for rows.Next() {
		var i Policy
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.PolicyholderName,
			&i.PolicyholderEmail,
			&i.PolicyholderPhone,
			&i.PolicyNumber,
			&i.Status,
			&i.StartDate,
			&i.EndDate,
			&i.PremiumAmount,
			&i.Currency,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPoliciesByStatus = `-- name: ListPoliciesByStatus :many
SELECT id, plan_id, policyholder_name, policyholder_email, policyholder_phone, policy_number, status, start_date, end_date, premium_amount, currency, created_by, created_at, updated_at FROM policies WHERE status = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListPoliciesByStatusParams struct {
	Status string `json:"status"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListPoliciesByStatus(ctx context.Context, arg ListPoliciesByStatusParams) ([]Policy, error) {
	rows, err := q.db.Query(ctx, listPoliciesByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Policy{}
	for rows.Next() {
		var i Policy
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.PolicyholderName,
			&i.PolicyholderEmail,
			&i.PolicyholderPhone,
			&i.PolicyNumber,
			&i.Status,
			&i.StartDate,
			&i.EndDate,
			&i.PremiumAmount,
			&i.Currency,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePolicy = `-- name: UpdatePolicy :one
UPDATE policies SET
    policyholder_name = COALESCE($1, policyholder_name),
    policyholder_email = COALESCE($2, policyholder_email),
    policyholder_phone = COALESCE($3, policyholder_phone),
    start_date = COALESCE($4, start_date),
    end_date = COALESCE($5, end_date),
    premium_amount = COALESCE($6, premium_amount),
    updated_at = NOW()
WHERE id = $7 RETURNING id, plan_id, policyholder_name, policyholder_email, policyholder_phone, policy_number, status, start_date, end_date, premium_amount, currency, created_by, created_at, updated_at
`

type UpdatePolicyParams struct {
	PolicyholderName  pgtype.Text        `json:"policyholder_name"`
	PolicyholderEmail pgtype.Text        `json:"policyholder_email"`
	PolicyholderPhone pgtype.Text        `json:"policyholder_phone"`
	StartDate         pgtype.Timestamptz `json:"start_date"`
	EndDate           pgtype.Timestamptz `json:"end_date"`
	PremiumAmount     pgtype.Int8        `json:"premium_amount"`
	ID                uuid.UUID          `json:"id"`
}

func (q *Queries) UpdatePolicy(ctx context.Context, arg UpdatePolicyParams) (Policy, error) {
	row := q.db.QueryRow(ctx, updatePolicy,
		arg.PolicyholderName,
		arg.PolicyholderEmail,
		arg.PolicyholderPhone,
		arg.StartDate,
		arg.EndDate,
		arg.PremiumAmount,
		arg.ID,
	)
	var i Policy
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.PolicyholderName,
		&i.PolicyholderEmail,
		&i.PolicyholderPhone,
		&i.PolicyNumber,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.PremiumAmount,
		&i.Currency,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePolicyStatus = `-- name: UpdatePolicyStatus :one
UPDATE policies SET status = $2, updated_at = NOW() WHERE id = $1 RETURNING id, plan_id, policyholder_name, policyholder_email, policyholder_phone, policy_number, status, start_date, end_date, premium_amount, currency, created_by, created_at, updated_at
`

type UpdatePolicyStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdatePolicyStatus(ctx context.Context, arg UpdatePolicyStatusParams) (Policy, error) {
	row := q.db.QueryRow(ctx, updatePolicyStatus, arg.ID, arg.Status)
	var i Policy
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.PolicyholderName,
		&i.PolicyholderEmail,
		&i.PolicyholderPhone,
		&i.PolicyNumber,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.PremiumAmount,
		&i.Currency,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
