// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: policy.sql

package db

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const activatePolicyWithTimestamp = `-- name: ActivatePolicyWithTimestamp :one
UPDATE policies SET status = 'ACTIVE', activated_at = NOW(), updated_at = NOW()
WHERE id = $1 RETURNING id, plan_id, policyholder_name, policyholder_email, policyholder_phone, policy_number, status, start_date, end_date, premium_amount, currency, created_by, created_at, updated_at, renewed_from_id, activated_at, underwriting_status
`

func (q *Queries) ActivatePolicyWithTimestamp(ctx context.Context, id uuid.UUID) (Policy, error) {
	row := q.db.QueryRow(ctx, activatePolicyWithTimestamp, id)
	var i Policy
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.PolicyholderName,
		&i.PolicyholderEmail,
		&i.PolicyholderPhone,
		&i.PolicyNumber,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.PremiumAmount,
		&i.Currency,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RenewedFromID,
		&i.ActivatedAt,
		&i.UnderwritingStatus,
	)
	return i, err
}

const countPolicies = `-- name: CountPolicies :one
SELECT COUNT(*) FROM policies
`

func (q *Queries) CountPolicies(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPolicies)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPoliciesByStatus = `-- name: CountPoliciesByStatus :one
SELECT COUNT(*) FROM policies WHERE status = $1
`

func (q *Queries) CountPoliciesByStatus(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRow(ctx, countPoliciesByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPoliciesFiltered = `-- name: CountPoliciesFiltered :one
SELECT COUNT(*) FROM policies
WHERE ($1::timestamptz IS NULL OR created_at >= $1)
  AND ($2::timestamptz IS NULL OR created_at <= $2)
  AND ($3::text = '' OR (policy_number ILIKE '%' || $3 || '%' OR policyholder_name ILIKE '%' || $3 || '%' OR policyholder_email ILIKE '%' || $3 || '%'))
`

type CountPoliciesFilteredParams struct {
	DateFrom pgtype.Timestamptz `json:"date_from"`
	DateTo   pgtype.Timestamptz `json:"date_to"`
	Search   string             `json:"search"`
}

func (q *Queries) CountPoliciesFiltered(ctx context.Context, arg CountPoliciesFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPoliciesFiltered, arg.DateFrom, arg.DateTo, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPolicy = `-- name: CreatePolicy :one
INSERT INTO policies (plan_id, policyholder_name, policyholder_email, policyholder_phone, policy_number, status, start_date, end_date, premium_amount, currency, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11) RETURNING id, plan_id, policyholder_name, policyholder_email, policyholder_phone, policy_number, status, start_date, end_date, premium_amount, currency, created_by, created_at, updated_at, renewed_from_id, activated_at, underwriting_status
`

type CreatePolicyParams struct {
	PlanID            uuid.UUID          `json:"plan_id"`
	PolicyholderName  string             `json:"policyholder_name"`
	PolicyholderEmail string             `json:"policyholder_email"`
	PolicyholderPhone string             `json:"policyholder_phone"`
	PolicyNumber      string             `json:"policy_number"`
	Status            string             `json:"status"`
	StartDate         pgtype.Timestamptz `json:"start_date"`
	EndDate           pgtype.Timestamptz `json:"end_date"`
	PremiumAmount     int64              `json:"premium_amount"`
	Currency          string             `json:"currency"`
	CreatedBy         pgtype.UUID        `json:"created_by"`
}

func (q *Queries) CreatePolicy(ctx context.Context, arg CreatePolicyParams) (Policy, error) {
	row := q.db.QueryRow(ctx, createPolicy,
		arg.PlanID,
		arg.PolicyholderName,
		arg.PolicyholderEmail,
		arg.PolicyholderPhone,
		arg.PolicyNumber,
		arg.Status,
		arg.StartDate,
		arg.EndDate,
		arg.PremiumAmount,
		arg.Currency,
		arg.CreatedBy,
	)
	var i Policy
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.PolicyholderName,
		&i.PolicyholderEmail,
		&i.PolicyholderPhone,
		&i.PolicyNumber,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.PremiumAmount,
		&i.Currency,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RenewedFromID,
		&i.ActivatedAt,
		&i.UnderwritingStatus,
	)
	return i, err
}

const getActivePoliciesForBilling = `-- name: GetActivePoliciesForBilling :many
SELECT id, plan_id, policyholder_name, policyholder_email, policyholder_phone, policy_number, status, start_date, end_date, premium_amount, currency, created_by, created_at, updated_at, renewed_from_id, activated_at, underwriting_status FROM policies WHERE status = 'ACTIVE' AND end_date > NOW()
`

func (q *Queries) GetActivePoliciesForBilling(ctx context.Context) ([]Policy, error) {
	rows, err := q.db.Query(ctx, getActivePoliciesForBilling)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Policy{}
	for rows.Next() {
		var i Policy
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.PolicyholderName,
			&i.PolicyholderEmail,
			&i.PolicyholderPhone,
			&i.PolicyNumber,
			&i.Status,
			&i.StartDate,
			&i.EndDate,
			&i.PremiumAmount,
			&i.Currency,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RenewedFromID,
			&i.ActivatedAt,
			&i.UnderwritingStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActivePolicyCount = `-- name: GetActivePolicyCount :one
SELECT COUNT(*) FROM policies WHERE status = 'ACTIVE' AND created_at BETWEEN $1 AND $2
`

type GetActivePolicyCountParams struct {
	StartDate time.Time `json:"start_date"`
	EndDate   time.Time `json:"end_date"`
}

func (q *Queries) GetActivePolicyCount(ctx context.Context, arg GetActivePolicyCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, getActivePolicyCount, arg.StartDate, arg.EndDate)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getLapsedPoliciesForTermination = `-- name: GetLapsedPoliciesForTermination :many
SELECT id, plan_id, policyholder_name, policyholder_email, policyholder_phone, policy_number, status, start_date, end_date, premium_amount, currency, created_by, created_at, updated_at, renewed_from_id, activated_at, underwriting_status FROM policies WHERE status = 'LAPSED' AND updated_at < NOW() - INTERVAL '90 days'
`

func (q *Queries) GetLapsedPoliciesForTermination(ctx context.Context) ([]Policy, error) {
	rows, err := q.db.Query(ctx, getLapsedPoliciesForTermination)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Policy{}
	for rows.Next() {
		var i Policy
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.PolicyholderName,
			&i.PolicyholderEmail,
			&i.PolicyholderPhone,
			&i.PolicyNumber,
			&i.Status,
			&i.StartDate,
			&i.EndDate,
			&i.PremiumAmount,
			&i.Currency,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RenewedFromID,
			&i.ActivatedAt,
			&i.UnderwritingStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLapsedPolicyCount = `-- name: GetLapsedPolicyCount :one
SELECT COUNT(*) FROM policies WHERE status = 'LAPSED' AND created_at BETWEEN $1 AND $2
`

type GetLapsedPolicyCountParams struct {
	StartDate time.Time `json:"start_date"`
	EndDate   time.Time `json:"end_date"`
}

func (q *Queries) GetLapsedPolicyCount(ctx context.Context, arg GetLapsedPolicyCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, getLapsedPolicyCount, arg.StartDate, arg.EndDate)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getOverduePoliciesForLapse = `-- name: GetOverduePoliciesForLapse :many
SELECT p.id, p.plan_id, p.policyholder_name, p.policyholder_email, p.policyholder_phone, p.policy_number, p.status, p.start_date, p.end_date, p.premium_amount, p.currency, p.created_by, p.created_at, p.updated_at, p.renewed_from_id, p.activated_at, p.underwriting_status FROM policies p
JOIN invoices i ON i.policy_id = p.id
WHERE p.status = 'ACTIVE' AND i.status = 'OVERDUE' AND i.due_date < NOW() - INTERVAL '30 days'
`

func (q *Queries) GetOverduePoliciesForLapse(ctx context.Context) ([]Policy, error) {
	rows, err := q.db.Query(ctx, getOverduePoliciesForLapse)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Policy{}
	for rows.Next() {
		var i Policy
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.PolicyholderName,
			&i.PolicyholderEmail,
			&i.PolicyholderPhone,
			&i.PolicyNumber,
			&i.Status,
			&i.StartDate,
			&i.EndDate,
			&i.PremiumAmount,
			&i.Currency,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RenewedFromID,
			&i.ActivatedAt,
			&i.UnderwritingStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPolicyByID = `-- name: GetPolicyByID :one
SELECT p.id, p.plan_id, p.policyholder_name, p.policyholder_email, p.policyholder_phone, p.policy_number, p.status, p.start_date, p.end_date, p.premium_amount, p.currency, p.created_by, p.created_at, p.updated_at, p.renewed_from_id, p.activated_at, p.underwriting_status, COALESCE(pl.name, '') AS plan_name FROM policies p
LEFT JOIN plans pl ON pl.id = p.plan_id
WHERE p.id = $1
`

type GetPolicyByIDRow struct {
	ID                 uuid.UUID          `json:"id"`
	PlanID             uuid.UUID          `json:"plan_id"`
	PolicyholderName   string             `json:"policyholder_name"`
	PolicyholderEmail  string             `json:"policyholder_email"`
	PolicyholderPhone  string             `json:"policyholder_phone"`
	PolicyNumber       string             `json:"policy_number"`
	Status             string             `json:"status"`
	StartDate          pgtype.Timestamptz `json:"start_date"`
	EndDate            pgtype.Timestamptz `json:"end_date"`
	PremiumAmount      int64              `json:"premium_amount"`
	Currency           string             `json:"currency"`
	CreatedBy          pgtype.UUID        `json:"created_by"`
	CreatedAt          time.Time          `json:"created_at"`
	UpdatedAt          time.Time          `json:"updated_at"`
	RenewedFromID      pgtype.UUID        `json:"renewed_from_id"`
	ActivatedAt        pgtype.Timestamptz `json:"activated_at"`
	UnderwritingStatus string             `json:"underwriting_status"`
	PlanName           string             `json:"plan_name"`
}

func (q *Queries) GetPolicyByID(ctx context.Context, id uuid.UUID) (GetPolicyByIDRow, error) {
	row := q.db.QueryRow(ctx, getPolicyByID, id)
	var i GetPolicyByIDRow
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.PolicyholderName,
		&i.PolicyholderEmail,
		&i.PolicyholderPhone,
		&i.PolicyNumber,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.PremiumAmount,
		&i.Currency,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RenewedFromID,
		&i.ActivatedAt,
		&i.UnderwritingStatus,
		&i.PlanName,
	)
	return i, err
}

const getPolicyByNumber = `-- name: GetPolicyByNumber :one
SELECT p.id, p.plan_id, p.policyholder_name, p.policyholder_email, p.policyholder_phone, p.policy_number, p.status, p.start_date, p.end_date, p.premium_amount, p.currency, p.created_by, p.created_at, p.updated_at, p.renewed_from_id, p.activated_at, p.underwriting_status, COALESCE(pl.name, '') AS plan_name FROM policies p
LEFT JOIN plans pl ON pl.id = p.plan_id
WHERE p.policy_number = $1
`

type GetPolicyByNumberRow struct {
	ID                 uuid.UUID          `json:"id"`
	PlanID             uuid.UUID          `json:"plan_id"`
	PolicyholderName   string             `json:"policyholder_name"`
	PolicyholderEmail  string             `json:"policyholder_email"`
	PolicyholderPhone  string             `json:"policyholder_phone"`
	PolicyNumber       string             `json:"policy_number"`
	Status             string             `json:"status"`
	StartDate          pgtype.Timestamptz `json:"start_date"`
	EndDate            pgtype.Timestamptz `json:"end_date"`
	PremiumAmount      int64              `json:"premium_amount"`
	Currency           string             `json:"currency"`
	CreatedBy          pgtype.UUID        `json:"created_by"`
	CreatedAt          time.Time          `json:"created_at"`
	UpdatedAt          time.Time          `json:"updated_at"`
	RenewedFromID      pgtype.UUID        `json:"renewed_from_id"`
	ActivatedAt        pgtype.Timestamptz `json:"activated_at"`
	UnderwritingStatus string             `json:"underwriting_status"`
	PlanName           string             `json:"plan_name"`
}

func (q *Queries) GetPolicyByNumber(ctx context.Context, policyNumber string) (GetPolicyByNumberRow, error) {
	row := q.db.QueryRow(ctx, getPolicyByNumber, policyNumber)
	var i GetPolicyByNumberRow
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.PolicyholderName,
		&i.PolicyholderEmail,
		&i.PolicyholderPhone,
		&i.PolicyNumber,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.PremiumAmount,
		&i.Currency,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RenewedFromID,
		&i.ActivatedAt,
		&i.UnderwritingStatus,
		&i.PlanName,
	)
	return i, err
}

const getRenewalRate = `-- name: GetRenewalRate :one
SELECT CASE WHEN COUNT(*) = 0 THEN 0 ELSE
    ROUND(COUNT(CASE WHEN pr.status = 'COMPLETED' THEN 1 END)::numeric / COUNT(*)::numeric * 100, 2)
END FROM policy_renewals pr WHERE pr.created_at BETWEEN $1 AND $2
`

type GetRenewalRateParams struct {
	StartDate time.Time `json:"start_date"`
	EndDate   time.Time `json:"end_date"`
}

func (q *Queries) GetRenewalRate(ctx context.Context, arg GetRenewalRateParams) (interface{}, error) {
	row := q.db.QueryRow(ctx, getRenewalRate, arg.StartDate, arg.EndDate)
	var column_1 interface{}
	err := row.Scan(&column_1)
	return column_1, err
}

const getTotalActiveMemberCount = `-- name: GetTotalActiveMemberCount :one
SELECT COUNT(*) FROM members WHERE status = 'ACTIVE' AND created_at BETWEEN $1 AND $2
`

type GetTotalActiveMemberCountParams struct {
	StartDate time.Time `json:"start_date"`
	EndDate   time.Time `json:"end_date"`
}

func (q *Queries) GetTotalActiveMemberCount(ctx context.Context, arg GetTotalActiveMemberCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalActiveMemberCount, arg.StartDate, arg.EndDate)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listPolicies = `-- name: ListPolicies :many
SELECT p.id, p.plan_id, p.policyholder_name, p.policyholder_email, p.policyholder_phone, p.policy_number, p.status, p.start_date, p.end_date, p.premium_amount, p.currency, p.created_by, p.created_at, p.updated_at, p.renewed_from_id, p.activated_at, p.underwriting_status, COALESCE(pl.name, '') AS plan_name FROM policies p
LEFT JOIN plans pl ON pl.id = p.plan_id
ORDER BY p.created_at DESC LIMIT $1 OFFSET $2
`

type ListPoliciesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListPoliciesRow struct {
	ID                 uuid.UUID          `json:"id"`
	PlanID             uuid.UUID          `json:"plan_id"`
	PolicyholderName   string             `json:"policyholder_name"`
	PolicyholderEmail  string             `json:"policyholder_email"`
	PolicyholderPhone  string             `json:"policyholder_phone"`
	PolicyNumber       string             `json:"policy_number"`
	Status             string             `json:"status"`
	StartDate          pgtype.Timestamptz `json:"start_date"`
	EndDate            pgtype.Timestamptz `json:"end_date"`
	PremiumAmount      int64              `json:"premium_amount"`
	Currency           string             `json:"currency"`
	CreatedBy          pgtype.UUID        `json:"created_by"`
	CreatedAt          time.Time          `json:"created_at"`
	UpdatedAt          time.Time          `json:"updated_at"`
	RenewedFromID      pgtype.UUID        `json:"renewed_from_id"`
	ActivatedAt        pgtype.Timestamptz `json:"activated_at"`
	UnderwritingStatus string             `json:"underwriting_status"`
	PlanName           string             `json:"plan_name"`
}

func (q *Queries) ListPolicies(ctx context.Context, arg ListPoliciesParams) ([]ListPoliciesRow, error) {
	rows, err := q.db.Query(ctx, listPolicies, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPoliciesRow{}
	for rows.Next() {
		var i ListPoliciesRow
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.PolicyholderName,
			&i.PolicyholderEmail,
			&i.PolicyholderPhone,
			&i.PolicyNumber,
			&i.Status,
			&i.StartDate,
			&i.EndDate,
			&i.PremiumAmount,
			&i.Currency,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RenewedFromID,
			&i.ActivatedAt,
			&i.UnderwritingStatus,
			&i.PlanName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPoliciesByStatus = `-- name: ListPoliciesByStatus :many
SELECT p.id, p.plan_id, p.policyholder_name, p.policyholder_email, p.policyholder_phone, p.policy_number, p.status, p.start_date, p.end_date, p.premium_amount, p.currency, p.created_by, p.created_at, p.updated_at, p.renewed_from_id, p.activated_at, p.underwriting_status, COALESCE(pl.name, '') AS plan_name FROM policies p
LEFT JOIN plans pl ON pl.id = p.plan_id
WHERE p.status = $1 ORDER BY p.created_at DESC LIMIT $2 OFFSET $3
`

type ListPoliciesByStatusParams struct {
	Status string `json:"status"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type ListPoliciesByStatusRow struct {
	ID                 uuid.UUID          `json:"id"`
	PlanID             uuid.UUID          `json:"plan_id"`
	PolicyholderName   string             `json:"policyholder_name"`
	PolicyholderEmail  string             `json:"policyholder_email"`
	PolicyholderPhone  string             `json:"policyholder_phone"`
	PolicyNumber       string             `json:"policy_number"`
	Status             string             `json:"status"`
	StartDate          pgtype.Timestamptz `json:"start_date"`
	EndDate            pgtype.Timestamptz `json:"end_date"`
	PremiumAmount      int64              `json:"premium_amount"`
	Currency           string             `json:"currency"`
	CreatedBy          pgtype.UUID        `json:"created_by"`
	CreatedAt          time.Time          `json:"created_at"`
	UpdatedAt          time.Time          `json:"updated_at"`
	RenewedFromID      pgtype.UUID        `json:"renewed_from_id"`
	ActivatedAt        pgtype.Timestamptz `json:"activated_at"`
	UnderwritingStatus string             `json:"underwriting_status"`
	PlanName           string             `json:"plan_name"`
}

func (q *Queries) ListPoliciesByStatus(ctx context.Context, arg ListPoliciesByStatusParams) ([]ListPoliciesByStatusRow, error) {
	rows, err := q.db.Query(ctx, listPoliciesByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPoliciesByStatusRow{}
	for rows.Next() {
		var i ListPoliciesByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.PolicyholderName,
			&i.PolicyholderEmail,
			&i.PolicyholderPhone,
			&i.PolicyNumber,
			&i.Status,
			&i.StartDate,
			&i.EndDate,
			&i.PremiumAmount,
			&i.Currency,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RenewedFromID,
			&i.ActivatedAt,
			&i.UnderwritingStatus,
			&i.PlanName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPoliciesExpiringSoon = `-- name: ListPoliciesExpiringSoon :many
SELECT id, plan_id, policyholder_name, policyholder_email, policyholder_phone, policy_number, status, start_date, end_date, premium_amount, currency, created_by, created_at, updated_at, renewed_from_id, activated_at, underwriting_status FROM policies WHERE status = 'ACTIVE' AND end_date BETWEEN NOW() AND NOW() + make_interval(days => $1::int) ORDER BY end_date ASC
`

func (q *Queries) ListPoliciesExpiringSoon(ctx context.Context, days int32) ([]Policy, error) {
	rows, err := q.db.Query(ctx, listPoliciesExpiringSoon, days)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Policy{}
	for rows.Next() {
		var i Policy
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.PolicyholderName,
			&i.PolicyholderEmail,
			&i.PolicyholderPhone,
			&i.PolicyNumber,
			&i.Status,
			&i.StartDate,
			&i.EndDate,
			&i.PremiumAmount,
			&i.Currency,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RenewedFromID,
			&i.ActivatedAt,
			&i.UnderwritingStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPoliciesFiltered = `-- name: ListPoliciesFiltered :many
SELECT p.id, p.plan_id, p.policyholder_name, p.policyholder_email, p.policyholder_phone, p.policy_number, p.status, p.start_date, p.end_date, p.premium_amount, p.currency, p.created_by, p.created_at, p.updated_at, p.renewed_from_id, p.activated_at, p.underwriting_status, COALESCE(pl.name, '') AS plan_name FROM policies p
LEFT JOIN plans pl ON pl.id = p.plan_id
WHERE ($1::timestamptz IS NULL OR p.created_at >= $1)
  AND ($2::timestamptz IS NULL OR p.created_at <= $2)
  AND ($3::text = '' OR (p.policy_number ILIKE '%' || $3 || '%' OR p.policyholder_name ILIKE '%' || $3 || '%' OR p.policyholder_email ILIKE '%' || $3 || '%'))
ORDER BY p.created_at DESC
LIMIT $5 OFFSET $4
`

type ListPoliciesFilteredParams struct {
	DateFrom    pgtype.Timestamptz `json:"date_from"`
	DateTo      pgtype.Timestamptz `json:"date_to"`
	Search      string             `json:"search"`
	QueryOffset int32              `json:"query_offset"`
	QueryLimit  int32              `json:"query_limit"`
}

type ListPoliciesFilteredRow struct {
	ID                 uuid.UUID          `json:"id"`
	PlanID             uuid.UUID          `json:"plan_id"`
	PolicyholderName   string             `json:"policyholder_name"`
	PolicyholderEmail  string             `json:"policyholder_email"`
	PolicyholderPhone  string             `json:"policyholder_phone"`
	PolicyNumber       string             `json:"policy_number"`
	Status             string             `json:"status"`
	StartDate          pgtype.Timestamptz `json:"start_date"`
	EndDate            pgtype.Timestamptz `json:"end_date"`
	PremiumAmount      int64              `json:"premium_amount"`
	Currency           string             `json:"currency"`
	CreatedBy          pgtype.UUID        `json:"created_by"`
	CreatedAt          time.Time          `json:"created_at"`
	UpdatedAt          time.Time          `json:"updated_at"`
	RenewedFromID      pgtype.UUID        `json:"renewed_from_id"`
	ActivatedAt        pgtype.Timestamptz `json:"activated_at"`
	UnderwritingStatus string             `json:"underwriting_status"`
	PlanName           string             `json:"plan_name"`
}

func (q *Queries) ListPoliciesFiltered(ctx context.Context, arg ListPoliciesFilteredParams) ([]ListPoliciesFilteredRow, error) {
	rows, err := q.db.Query(ctx, listPoliciesFiltered,
		arg.DateFrom,
		arg.DateTo,
		arg.Search,
		arg.QueryOffset,
		arg.QueryLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPoliciesFilteredRow{}
	for rows.Next() {
		var i ListPoliciesFilteredRow
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.PolicyholderName,
			&i.PolicyholderEmail,
			&i.PolicyholderPhone,
			&i.PolicyNumber,
			&i.Status,
			&i.StartDate,
			&i.EndDate,
			&i.PremiumAmount,
			&i.Currency,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RenewedFromID,
			&i.ActivatedAt,
			&i.UnderwritingStatus,
			&i.PlanName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePolicy = `-- name: UpdatePolicy :one
UPDATE policies SET
    policyholder_name = COALESCE($1, policyholder_name),
    policyholder_email = COALESCE($2, policyholder_email),
    policyholder_phone = COALESCE($3, policyholder_phone),
    start_date = COALESCE($4, start_date),
    end_date = COALESCE($5, end_date),
    premium_amount = COALESCE($6, premium_amount),
    updated_at = NOW()
WHERE id = $7 RETURNING id, plan_id, policyholder_name, policyholder_email, policyholder_phone, policy_number, status, start_date, end_date, premium_amount, currency, created_by, created_at, updated_at, renewed_from_id, activated_at, underwriting_status
`

type UpdatePolicyParams struct {
	PolicyholderName  pgtype.Text        `json:"policyholder_name"`
	PolicyholderEmail pgtype.Text        `json:"policyholder_email"`
	PolicyholderPhone pgtype.Text        `json:"policyholder_phone"`
	StartDate         pgtype.Timestamptz `json:"start_date"`
	EndDate           pgtype.Timestamptz `json:"end_date"`
	PremiumAmount     pgtype.Int8        `json:"premium_amount"`
	ID                uuid.UUID          `json:"id"`
}

func (q *Queries) UpdatePolicy(ctx context.Context, arg UpdatePolicyParams) (Policy, error) {
	row := q.db.QueryRow(ctx, updatePolicy,
		arg.PolicyholderName,
		arg.PolicyholderEmail,
		arg.PolicyholderPhone,
		arg.StartDate,
		arg.EndDate,
		arg.PremiumAmount,
		arg.ID,
	)
	var i Policy
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.PolicyholderName,
		&i.PolicyholderEmail,
		&i.PolicyholderPhone,
		&i.PolicyNumber,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.PremiumAmount,
		&i.Currency,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RenewedFromID,
		&i.ActivatedAt,
		&i.UnderwritingStatus,
	)
	return i, err
}

const updatePolicyPlanAndPremium = `-- name: UpdatePolicyPlanAndPremium :one
UPDATE policies SET plan_id = $2, premium_amount = $3, updated_at = NOW() WHERE id = $1 RETURNING id, plan_id, policyholder_name, policyholder_email, policyholder_phone, policy_number, status, start_date, end_date, premium_amount, currency, created_by, created_at, updated_at, renewed_from_id, activated_at, underwriting_status
`

type UpdatePolicyPlanAndPremiumParams struct {
	ID            uuid.UUID `json:"id"`
	PlanID        uuid.UUID `json:"plan_id"`
	PremiumAmount int64     `json:"premium_amount"`
}

func (q *Queries) UpdatePolicyPlanAndPremium(ctx context.Context, arg UpdatePolicyPlanAndPremiumParams) (Policy, error) {
	row := q.db.QueryRow(ctx, updatePolicyPlanAndPremium, arg.ID, arg.PlanID, arg.PremiumAmount)
	var i Policy
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.PolicyholderName,
		&i.PolicyholderEmail,
		&i.PolicyholderPhone,
		&i.PolicyNumber,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.PremiumAmount,
		&i.Currency,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RenewedFromID,
		&i.ActivatedAt,
		&i.UnderwritingStatus,
	)
	return i, err
}

const updatePolicyStatus = `-- name: UpdatePolicyStatus :one
UPDATE policies SET status = $2, updated_at = NOW() WHERE id = $1 RETURNING id, plan_id, policyholder_name, policyholder_email, policyholder_phone, policy_number, status, start_date, end_date, premium_amount, currency, created_by, created_at, updated_at, renewed_from_id, activated_at, underwriting_status
`

type UpdatePolicyStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdatePolicyStatus(ctx context.Context, arg UpdatePolicyStatusParams) (Policy, error) {
	row := q.db.QueryRow(ctx, updatePolicyStatus, arg.ID, arg.Status)
	var i Policy
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.PolicyholderName,
		&i.PolicyholderEmail,
		&i.PolicyholderPhone,
		&i.PolicyNumber,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.PremiumAmount,
		&i.Currency,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RenewedFromID,
		&i.ActivatedAt,
		&i.UnderwritingStatus,
	)
	return i, err
}

const updatePolicyUnderwritingStatus = `-- name: UpdatePolicyUnderwritingStatus :one
UPDATE policies SET underwriting_status = $2, updated_at = NOW() WHERE id = $1 RETURNING id, plan_id, policyholder_name, policyholder_email, policyholder_phone, policy_number, status, start_date, end_date, premium_amount, currency, created_by, created_at, updated_at, renewed_from_id, activated_at, underwriting_status
`

type UpdatePolicyUnderwritingStatusParams struct {
	ID                 uuid.UUID `json:"id"`
	UnderwritingStatus string    `json:"underwriting_status"`
}

func (q *Queries) UpdatePolicyUnderwritingStatus(ctx context.Context, arg UpdatePolicyUnderwritingStatusParams) (Policy, error) {
	row := q.db.QueryRow(ctx, updatePolicyUnderwritingStatus, arg.ID, arg.UnderwritingStatus)
	var i Policy
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.PolicyholderName,
		&i.PolicyholderEmail,
		&i.PolicyholderPhone,
		&i.PolicyNumber,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.PremiumAmount,
		&i.Currency,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RenewedFromID,
		&i.ActivatedAt,
		&i.UnderwritingStatus,
	)
	return i, err
}
