// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: policy_document.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPolicyDocument = `-- name: CreatePolicyDocument :one
INSERT INTO policy_documents (policy_id, member_id, document_type, file_name, file_size, s3_key, generated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, policy_id, member_id, document_type, file_name, file_size, s3_key, generated_by, created_at
`

type CreatePolicyDocumentParams struct {
	PolicyID     uuid.UUID   `json:"policy_id"`
	MemberID     pgtype.UUID `json:"member_id"`
	DocumentType string      `json:"document_type"`
	FileName     string      `json:"file_name"`
	FileSize     pgtype.Int8 `json:"file_size"`
	S3Key        string      `json:"s3_key"`
	GeneratedBy  uuid.UUID   `json:"generated_by"`
}

func (q *Queries) CreatePolicyDocument(ctx context.Context, arg CreatePolicyDocumentParams) (PolicyDocument, error) {
	row := q.db.QueryRow(ctx, createPolicyDocument,
		arg.PolicyID,
		arg.MemberID,
		arg.DocumentType,
		arg.FileName,
		arg.FileSize,
		arg.S3Key,
		arg.GeneratedBy,
	)
	var i PolicyDocument
	err := row.Scan(
		&i.ID,
		&i.PolicyID,
		&i.MemberID,
		&i.DocumentType,
		&i.FileName,
		&i.FileSize,
		&i.S3Key,
		&i.GeneratedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deletePolicyDocument = `-- name: DeletePolicyDocument :exec
DELETE FROM policy_documents WHERE id = $1
`

func (q *Queries) DeletePolicyDocument(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePolicyDocument, id)
	return err
}

const getPolicyDocumentByID = `-- name: GetPolicyDocumentByID :one
SELECT id, policy_id, member_id, document_type, file_name, file_size, s3_key, generated_by, created_at FROM policy_documents WHERE id = $1
`

func (q *Queries) GetPolicyDocumentByID(ctx context.Context, id uuid.UUID) (PolicyDocument, error) {
	row := q.db.QueryRow(ctx, getPolicyDocumentByID, id)
	var i PolicyDocument
	err := row.Scan(
		&i.ID,
		&i.PolicyID,
		&i.MemberID,
		&i.DocumentType,
		&i.FileName,
		&i.FileSize,
		&i.S3Key,
		&i.GeneratedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listPolicyDocumentsByMember = `-- name: ListPolicyDocumentsByMember :many
SELECT id, policy_id, member_id, document_type, file_name, file_size, s3_key, generated_by, created_at FROM policy_documents WHERE member_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListPolicyDocumentsByMember(ctx context.Context, memberID pgtype.UUID) ([]PolicyDocument, error) {
	rows, err := q.db.Query(ctx, listPolicyDocumentsByMember, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PolicyDocument{}
	for rows.Next() {
		var i PolicyDocument
		if err := rows.Scan(
			&i.ID,
			&i.PolicyID,
			&i.MemberID,
			&i.DocumentType,
			&i.FileName,
			&i.FileSize,
			&i.S3Key,
			&i.GeneratedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPolicyDocumentsByPolicy = `-- name: ListPolicyDocumentsByPolicy :many
SELECT id, policy_id, member_id, document_type, file_name, file_size, s3_key, generated_by, created_at FROM policy_documents WHERE policy_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListPolicyDocumentsByPolicy(ctx context.Context, policyID uuid.UUID) ([]PolicyDocument, error) {
	rows, err := q.db.Query(ctx, listPolicyDocumentsByPolicy, policyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PolicyDocument{}
	for rows.Next() {
		var i PolicyDocument
		if err := rows.Scan(
			&i.ID,
			&i.PolicyID,
			&i.MemberID,
			&i.DocumentType,
			&i.FileName,
			&i.FileSize,
			&i.S3Key,
			&i.GeneratedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
