// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: preauth.sql

package db

import (
	"context"
	"encoding/json"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const approvePreAuth = `-- name: ApprovePreAuth :one
UPDATE preauthorizations SET
    status = 'APPROVED',
    auth_code = $2,
    approved_amount = $3,
    validity_start = $4,
    validity_end = $5,
    reviewed_by = $6,
    reviewed_at = NOW(),
    updated_at = NOW()
WHERE id = $1 RETURNING id, policy_id, member_id, provider_id, auth_code, procedure_codes, diagnosis_codes, estimated_cost, approved_amount, status, validity_start, validity_end, notes, denial_reason, reviewed_by, reviewed_at, created_by, created_at, updated_at
`

type ApprovePreAuthParams struct {
	ID             uuid.UUID          `json:"id"`
	AuthCode       pgtype.Text        `json:"auth_code"`
	ApprovedAmount int64              `json:"approved_amount"`
	ValidityStart  pgtype.Timestamptz `json:"validity_start"`
	ValidityEnd    pgtype.Timestamptz `json:"validity_end"`
	ReviewedBy     pgtype.UUID        `json:"reviewed_by"`
}

func (q *Queries) ApprovePreAuth(ctx context.Context, arg ApprovePreAuthParams) (Preauthorization, error) {
	row := q.db.QueryRow(ctx, approvePreAuth,
		arg.ID,
		arg.AuthCode,
		arg.ApprovedAmount,
		arg.ValidityStart,
		arg.ValidityEnd,
		arg.ReviewedBy,
	)
	var i Preauthorization
	err := row.Scan(
		&i.ID,
		&i.PolicyID,
		&i.MemberID,
		&i.ProviderID,
		&i.AuthCode,
		&i.ProcedureCodes,
		&i.DiagnosisCodes,
		&i.EstimatedCost,
		&i.ApprovedAmount,
		&i.Status,
		&i.ValidityStart,
		&i.ValidityEnd,
		&i.Notes,
		&i.DenialReason,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countPreAuths = `-- name: CountPreAuths :one
SELECT COUNT(*) FROM preauthorizations
`

func (q *Queries) CountPreAuths(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPreAuths)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPreAuth = `-- name: CreatePreAuth :one
INSERT INTO preauthorizations (policy_id, member_id, provider_id, procedure_codes, diagnosis_codes, estimated_cost, status, notes, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING id, policy_id, member_id, provider_id, auth_code, procedure_codes, diagnosis_codes, estimated_cost, approved_amount, status, validity_start, validity_end, notes, denial_reason, reviewed_by, reviewed_at, created_by, created_at, updated_at
`

type CreatePreAuthParams struct {
	PolicyID       uuid.UUID       `json:"policy_id"`
	MemberID       uuid.UUID       `json:"member_id"`
	ProviderID     uuid.UUID       `json:"provider_id"`
	ProcedureCodes json.RawMessage `json:"procedure_codes"`
	DiagnosisCodes json.RawMessage `json:"diagnosis_codes"`
	EstimatedCost  int64           `json:"estimated_cost"`
	Status         string          `json:"status"`
	Notes          string          `json:"notes"`
	CreatedBy      pgtype.UUID     `json:"created_by"`
}

func (q *Queries) CreatePreAuth(ctx context.Context, arg CreatePreAuthParams) (Preauthorization, error) {
	row := q.db.QueryRow(ctx, createPreAuth,
		arg.PolicyID,
		arg.MemberID,
		arg.ProviderID,
		arg.ProcedureCodes,
		arg.DiagnosisCodes,
		arg.EstimatedCost,
		arg.Status,
		arg.Notes,
		arg.CreatedBy,
	)
	var i Preauthorization
	err := row.Scan(
		&i.ID,
		&i.PolicyID,
		&i.MemberID,
		&i.ProviderID,
		&i.AuthCode,
		&i.ProcedureCodes,
		&i.DiagnosisCodes,
		&i.EstimatedCost,
		&i.ApprovedAmount,
		&i.Status,
		&i.ValidityStart,
		&i.ValidityEnd,
		&i.Notes,
		&i.DenialReason,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const denyPreAuth = `-- name: DenyPreAuth :one
UPDATE preauthorizations SET
    status = 'DENIED',
    denial_reason = $2,
    reviewed_by = $3,
    reviewed_at = NOW(),
    updated_at = NOW()
WHERE id = $1 RETURNING id, policy_id, member_id, provider_id, auth_code, procedure_codes, diagnosis_codes, estimated_cost, approved_amount, status, validity_start, validity_end, notes, denial_reason, reviewed_by, reviewed_at, created_by, created_at, updated_at
`

type DenyPreAuthParams struct {
	ID           uuid.UUID   `json:"id"`
	DenialReason pgtype.Text `json:"denial_reason"`
	ReviewedBy   pgtype.UUID `json:"reviewed_by"`
}

func (q *Queries) DenyPreAuth(ctx context.Context, arg DenyPreAuthParams) (Preauthorization, error) {
	row := q.db.QueryRow(ctx, denyPreAuth, arg.ID, arg.DenialReason, arg.ReviewedBy)
	var i Preauthorization
	err := row.Scan(
		&i.ID,
		&i.PolicyID,
		&i.MemberID,
		&i.ProviderID,
		&i.AuthCode,
		&i.ProcedureCodes,
		&i.DiagnosisCodes,
		&i.EstimatedCost,
		&i.ApprovedAmount,
		&i.Status,
		&i.ValidityStart,
		&i.ValidityEnd,
		&i.Notes,
		&i.DenialReason,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExpiringPreAuths = `-- name: GetExpiringPreAuths :many
SELECT id, policy_id, member_id, provider_id, auth_code, procedure_codes, diagnosis_codes, estimated_cost, approved_amount, status, validity_start, validity_end, notes, denial_reason, reviewed_by, reviewed_at, created_by, created_at, updated_at FROM preauthorizations WHERE status = 'APPROVED' AND validity_end < NOW()
`

func (q *Queries) GetExpiringPreAuths(ctx context.Context) ([]Preauthorization, error) {
	rows, err := q.db.Query(ctx, getExpiringPreAuths)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Preauthorization{}
	for rows.Next() {
		var i Preauthorization
		if err := rows.Scan(
			&i.ID,
			&i.PolicyID,
			&i.MemberID,
			&i.ProviderID,
			&i.AuthCode,
			&i.ProcedureCodes,
			&i.DiagnosisCodes,
			&i.EstimatedCost,
			&i.ApprovedAmount,
			&i.Status,
			&i.ValidityStart,
			&i.ValidityEnd,
			&i.Notes,
			&i.DenialReason,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPreAuthByAuthCode = `-- name: GetPreAuthByAuthCode :one
SELECT id, policy_id, member_id, provider_id, auth_code, procedure_codes, diagnosis_codes, estimated_cost, approved_amount, status, validity_start, validity_end, notes, denial_reason, reviewed_by, reviewed_at, created_by, created_at, updated_at FROM preauthorizations WHERE auth_code = $1
`

func (q *Queries) GetPreAuthByAuthCode(ctx context.Context, authCode pgtype.Text) (Preauthorization, error) {
	row := q.db.QueryRow(ctx, getPreAuthByAuthCode, authCode)
	var i Preauthorization
	err := row.Scan(
		&i.ID,
		&i.PolicyID,
		&i.MemberID,
		&i.ProviderID,
		&i.AuthCode,
		&i.ProcedureCodes,
		&i.DiagnosisCodes,
		&i.EstimatedCost,
		&i.ApprovedAmount,
		&i.Status,
		&i.ValidityStart,
		&i.ValidityEnd,
		&i.Notes,
		&i.DenialReason,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPreAuthByID = `-- name: GetPreAuthByID :one
SELECT id, policy_id, member_id, provider_id, auth_code, procedure_codes, diagnosis_codes, estimated_cost, approved_amount, status, validity_start, validity_end, notes, denial_reason, reviewed_by, reviewed_at, created_by, created_at, updated_at FROM preauthorizations WHERE id = $1
`

func (q *Queries) GetPreAuthByID(ctx context.Context, id uuid.UUID) (Preauthorization, error) {
	row := q.db.QueryRow(ctx, getPreAuthByID, id)
	var i Preauthorization
	err := row.Scan(
		&i.ID,
		&i.PolicyID,
		&i.MemberID,
		&i.ProviderID,
		&i.AuthCode,
		&i.ProcedureCodes,
		&i.DiagnosisCodes,
		&i.EstimatedCost,
		&i.ApprovedAmount,
		&i.Status,
		&i.ValidityStart,
		&i.ValidityEnd,
		&i.Notes,
		&i.DenialReason,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPreAuths = `-- name: ListPreAuths :many
SELECT id, policy_id, member_id, provider_id, auth_code, procedure_codes, diagnosis_codes, estimated_cost, approved_amount, status, validity_start, validity_end, notes, denial_reason, reviewed_by, reviewed_at, created_by, created_at, updated_at FROM preauthorizations ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListPreAuthsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPreAuths(ctx context.Context, arg ListPreAuthsParams) ([]Preauthorization, error) {
	rows, err := q.db.Query(ctx, listPreAuths, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Preauthorization{}
	for rows.Next() {
		var i Preauthorization
		if err := rows.Scan(
			&i.ID,
			&i.PolicyID,
			&i.MemberID,
			&i.ProviderID,
			&i.AuthCode,
			&i.ProcedureCodes,
			&i.DiagnosisCodes,
			&i.EstimatedCost,
			&i.ApprovedAmount,
			&i.Status,
			&i.ValidityStart,
			&i.ValidityEnd,
			&i.Notes,
			&i.DenialReason,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPreAuthsByMember = `-- name: ListPreAuthsByMember :many
SELECT id, policy_id, member_id, provider_id, auth_code, procedure_codes, diagnosis_codes, estimated_cost, approved_amount, status, validity_start, validity_end, notes, denial_reason, reviewed_by, reviewed_at, created_by, created_at, updated_at FROM preauthorizations WHERE member_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListPreAuthsByMemberParams struct {
	MemberID uuid.UUID `json:"member_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListPreAuthsByMember(ctx context.Context, arg ListPreAuthsByMemberParams) ([]Preauthorization, error) {
	rows, err := q.db.Query(ctx, listPreAuthsByMember, arg.MemberID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Preauthorization{}
	for rows.Next() {
		var i Preauthorization
		if err := rows.Scan(
			&i.ID,
			&i.PolicyID,
			&i.MemberID,
			&i.ProviderID,
			&i.AuthCode,
			&i.ProcedureCodes,
			&i.DiagnosisCodes,
			&i.EstimatedCost,
			&i.ApprovedAmount,
			&i.Status,
			&i.ValidityStart,
			&i.ValidityEnd,
			&i.Notes,
			&i.DenialReason,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPreAuthsByProvider = `-- name: ListPreAuthsByProvider :many
SELECT id, policy_id, member_id, provider_id, auth_code, procedure_codes, diagnosis_codes, estimated_cost, approved_amount, status, validity_start, validity_end, notes, denial_reason, reviewed_by, reviewed_at, created_by, created_at, updated_at FROM preauthorizations WHERE provider_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListPreAuthsByProviderParams struct {
	ProviderID uuid.UUID `json:"provider_id"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

func (q *Queries) ListPreAuthsByProvider(ctx context.Context, arg ListPreAuthsByProviderParams) ([]Preauthorization, error) {
	rows, err := q.db.Query(ctx, listPreAuthsByProvider, arg.ProviderID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Preauthorization{}
	for rows.Next() {
		var i Preauthorization
		if err := rows.Scan(
			&i.ID,
			&i.PolicyID,
			&i.MemberID,
			&i.ProviderID,
			&i.AuthCode,
			&i.ProcedureCodes,
			&i.DiagnosisCodes,
			&i.EstimatedCost,
			&i.ApprovedAmount,
			&i.Status,
			&i.ValidityStart,
			&i.ValidityEnd,
			&i.Notes,
			&i.DenialReason,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPreAuthsByStatus = `-- name: ListPreAuthsByStatus :many
SELECT id, policy_id, member_id, provider_id, auth_code, procedure_codes, diagnosis_codes, estimated_cost, approved_amount, status, validity_start, validity_end, notes, denial_reason, reviewed_by, reviewed_at, created_by, created_at, updated_at FROM preauthorizations WHERE status = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListPreAuthsByStatusParams struct {
	Status string `json:"status"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListPreAuthsByStatus(ctx context.Context, arg ListPreAuthsByStatusParams) ([]Preauthorization, error) {
	rows, err := q.db.Query(ctx, listPreAuthsByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Preauthorization{}
	for rows.Next() {
		var i Preauthorization
		if err := rows.Scan(
			&i.ID,
			&i.PolicyID,
			&i.MemberID,
			&i.ProviderID,
			&i.AuthCode,
			&i.ProcedureCodes,
			&i.DiagnosisCodes,
			&i.EstimatedCost,
			&i.ApprovedAmount,
			&i.Status,
			&i.ValidityStart,
			&i.ValidityEnd,
			&i.Notes,
			&i.DenialReason,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePreAuthStatus = `-- name: UpdatePreAuthStatus :one
UPDATE preauthorizations SET status = $2, updated_at = NOW() WHERE id = $1 RETURNING id, policy_id, member_id, provider_id, auth_code, procedure_codes, diagnosis_codes, estimated_cost, approved_amount, status, validity_start, validity_end, notes, denial_reason, reviewed_by, reviewed_at, created_by, created_at, updated_at
`

type UpdatePreAuthStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdatePreAuthStatus(ctx context.Context, arg UpdatePreAuthStatusParams) (Preauthorization, error) {
	row := q.db.QueryRow(ctx, updatePreAuthStatus, arg.ID, arg.Status)
	var i Preauthorization
	err := row.Scan(
		&i.ID,
		&i.PolicyID,
		&i.MemberID,
		&i.ProviderID,
		&i.AuthCode,
		&i.ProcedureCodes,
		&i.DiagnosisCodes,
		&i.EstimatedCost,
		&i.ApprovedAmount,
		&i.Status,
		&i.ValidityStart,
		&i.ValidityEnd,
		&i.Notes,
		&i.DenialReason,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
