// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: premium_rule.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPremiumRule = `-- name: CreatePremiumRule :one
INSERT INTO premium_rules (plan_id, calculation_type, relationship, rate_amount, discount_type, discount_value, min_members, min_age, max_age)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING id, plan_id, calculation_type, relationship, rate_amount, discount_type, discount_value, min_members, created_at, updated_at, min_age, max_age
`

type CreatePremiumRuleParams struct {
	PlanID          uuid.UUID   `json:"plan_id"`
	CalculationType string      `json:"calculation_type"`
	Relationship    pgtype.Text `json:"relationship"`
	RateAmount      int64       `json:"rate_amount"`
	DiscountType    pgtype.Text `json:"discount_type"`
	DiscountValue   int64       `json:"discount_value"`
	MinMembers      int32       `json:"min_members"`
	MinAge          int32       `json:"min_age"`
	MaxAge          int32       `json:"max_age"`
}

func (q *Queries) CreatePremiumRule(ctx context.Context, arg CreatePremiumRuleParams) (PremiumRule, error) {
	row := q.db.QueryRow(ctx, createPremiumRule,
		arg.PlanID,
		arg.CalculationType,
		arg.Relationship,
		arg.RateAmount,
		arg.DiscountType,
		arg.DiscountValue,
		arg.MinMembers,
		arg.MinAge,
		arg.MaxAge,
	)
	var i PremiumRule
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.CalculationType,
		&i.Relationship,
		&i.RateAmount,
		&i.DiscountType,
		&i.DiscountValue,
		&i.MinMembers,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MinAge,
		&i.MaxAge,
	)
	return i, err
}

const deletePremiumRule = `-- name: DeletePremiumRule :exec
DELETE FROM premium_rules WHERE id = $1
`

func (q *Queries) DeletePremiumRule(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePremiumRule, id)
	return err
}

const getPremiumRuleByID = `-- name: GetPremiumRuleByID :one
SELECT id, plan_id, calculation_type, relationship, rate_amount, discount_type, discount_value, min_members, created_at, updated_at, min_age, max_age FROM premium_rules WHERE id = $1
`

func (q *Queries) GetPremiumRuleByID(ctx context.Context, id uuid.UUID) (PremiumRule, error) {
	row := q.db.QueryRow(ctx, getPremiumRuleByID, id)
	var i PremiumRule
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.CalculationType,
		&i.Relationship,
		&i.RateAmount,
		&i.DiscountType,
		&i.DiscountValue,
		&i.MinMembers,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MinAge,
		&i.MaxAge,
	)
	return i, err
}

const listPremiumRulesByPlan = `-- name: ListPremiumRulesByPlan :many
SELECT id, plan_id, calculation_type, relationship, rate_amount, discount_type, discount_value, min_members, created_at, updated_at, min_age, max_age FROM premium_rules WHERE plan_id = $1 ORDER BY created_at
`

func (q *Queries) ListPremiumRulesByPlan(ctx context.Context, planID uuid.UUID) ([]PremiumRule, error) {
	rows, err := q.db.Query(ctx, listPremiumRulesByPlan, planID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PremiumRule{}
	for rows.Next() {
		var i PremiumRule
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.CalculationType,
			&i.Relationship,
			&i.RateAmount,
			&i.DiscountType,
			&i.DiscountValue,
			&i.MinMembers,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MinAge,
			&i.MaxAge,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePremiumRule = `-- name: UpdatePremiumRule :one
UPDATE premium_rules SET
    calculation_type = COALESCE($1, calculation_type),
    relationship = COALESCE($2, relationship),
    rate_amount = COALESCE($3, rate_amount),
    discount_type = COALESCE($4, discount_type),
    discount_value = COALESCE($5, discount_value),
    min_members = COALESCE($6, min_members),
    min_age = COALESCE($7, min_age),
    max_age = COALESCE($8, max_age),
    updated_at = NOW()
WHERE id = $9 RETURNING id, plan_id, calculation_type, relationship, rate_amount, discount_type, discount_value, min_members, created_at, updated_at, min_age, max_age
`

type UpdatePremiumRuleParams struct {
	CalculationType pgtype.Text `json:"calculation_type"`
	Relationship    pgtype.Text `json:"relationship"`
	RateAmount      pgtype.Int8 `json:"rate_amount"`
	DiscountType    pgtype.Text `json:"discount_type"`
	DiscountValue   pgtype.Int8 `json:"discount_value"`
	MinMembers      pgtype.Int4 `json:"min_members"`
	MinAge          pgtype.Int4 `json:"min_age"`
	MaxAge          pgtype.Int4 `json:"max_age"`
	ID              uuid.UUID   `json:"id"`
}

func (q *Queries) UpdatePremiumRule(ctx context.Context, arg UpdatePremiumRuleParams) (PremiumRule, error) {
	row := q.db.QueryRow(ctx, updatePremiumRule,
		arg.CalculationType,
		arg.Relationship,
		arg.RateAmount,
		arg.DiscountType,
		arg.DiscountValue,
		arg.MinMembers,
		arg.MinAge,
		arg.MaxAge,
		arg.ID,
	)
	var i PremiumRule
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.CalculationType,
		&i.Relationship,
		&i.RateAmount,
		&i.DiscountType,
		&i.DiscountValue,
		&i.MinMembers,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MinAge,
		&i.MaxAge,
	)
	return i, err
}
