// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: premium_ledger.sql

package db

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPremiumLedgerEntry = `-- name: CreatePremiumLedgerEntry :one
INSERT INTO premium_ledger_entries (policy_id, entry_type, amount, description, reference_number, effective_date, balance_after, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, policy_id, entry_type, amount, description, reference_number, effective_date, balance_after, created_by, created_at, updated_at
`

type CreatePremiumLedgerEntryParams struct {
	PolicyID        uuid.UUID   `json:"policy_id"`
	EntryType       string      `json:"entry_type"`
	Amount          int64       `json:"amount"`
	Description     string      `json:"description"`
	ReferenceNumber string      `json:"reference_number"`
	EffectiveDate   time.Time   `json:"effective_date"`
	BalanceAfter    int64       `json:"balance_after"`
	CreatedBy       pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreatePremiumLedgerEntry(ctx context.Context, arg CreatePremiumLedgerEntryParams) (PremiumLedgerEntry, error) {
	row := q.db.QueryRow(ctx, createPremiumLedgerEntry,
		arg.PolicyID,
		arg.EntryType,
		arg.Amount,
		arg.Description,
		arg.ReferenceNumber,
		arg.EffectiveDate,
		arg.BalanceAfter,
		arg.CreatedBy,
	)
	var i PremiumLedgerEntry
	err := row.Scan(
		&i.ID,
		&i.PolicyID,
		&i.EntryType,
		&i.Amount,
		&i.Description,
		&i.ReferenceNumber,
		&i.EffectiveDate,
		&i.BalanceAfter,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPremiumBalanceByPolicy = `-- name: GetPremiumBalanceByPolicy :one
SELECT COALESCE(
    SUM(CASE WHEN entry_type = 'CREDIT' THEN amount ELSE -amount END), 0
)::bigint AS balance
FROM premium_ledger_entries WHERE policy_id = $1
`

func (q *Queries) GetPremiumBalanceByPolicy(ctx context.Context, policyID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getPremiumBalanceByPolicy, policyID)
	var balance int64
	err := row.Scan(&balance)
	return balance, err
}

const listPremiumLedgerByPolicy = `-- name: ListPremiumLedgerByPolicy :many
SELECT id, policy_id, entry_type, amount, description, reference_number, effective_date, balance_after, created_by, created_at, updated_at FROM premium_ledger_entries WHERE policy_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListPremiumLedgerByPolicyParams struct {
	PolicyID uuid.UUID `json:"policy_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListPremiumLedgerByPolicy(ctx context.Context, arg ListPremiumLedgerByPolicyParams) ([]PremiumLedgerEntry, error) {
	rows, err := q.db.Query(ctx, listPremiumLedgerByPolicy, arg.PolicyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PremiumLedgerEntry{}
	for rows.Next() {
		var i PremiumLedgerEntry
		if err := rows.Scan(
			&i.ID,
			&i.PolicyID,
			&i.EntryType,
			&i.Amount,
			&i.Description,
			&i.ReferenceNumber,
			&i.EffectiveDate,
			&i.BalanceAfter,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
