// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: profit_commission.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProfitCommission = `-- name: CreateProfitCommission :one
INSERT INTO profit_commissions (treaty_id, commission_type, loss_ratio_from, loss_ratio_to, commission_rate, carry_forward_years, carry_forward_balance, period_start, period_end, calculated_amount)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) RETURNING id, treaty_id, commission_type, loss_ratio_from, loss_ratio_to, commission_rate, carry_forward_years, carry_forward_balance, period_start, period_end, calculated_amount, created_at, updated_at
`

type CreateProfitCommissionParams struct {
	TreatyID            uuid.UUID      `json:"treaty_id"`
	CommissionType      string         `json:"commission_type"`
	LossRatioFrom       pgtype.Numeric `json:"loss_ratio_from"`
	LossRatioTo         pgtype.Numeric `json:"loss_ratio_to"`
	CommissionRate      pgtype.Numeric `json:"commission_rate"`
	CarryForwardYears   int32          `json:"carry_forward_years"`
	CarryForwardBalance int64          `json:"carry_forward_balance"`
	PeriodStart         pgtype.Date    `json:"period_start"`
	PeriodEnd           pgtype.Date    `json:"period_end"`
	CalculatedAmount    int64          `json:"calculated_amount"`
}

func (q *Queries) CreateProfitCommission(ctx context.Context, arg CreateProfitCommissionParams) (ProfitCommission, error) {
	row := q.db.QueryRow(ctx, createProfitCommission,
		arg.TreatyID,
		arg.CommissionType,
		arg.LossRatioFrom,
		arg.LossRatioTo,
		arg.CommissionRate,
		arg.CarryForwardYears,
		arg.CarryForwardBalance,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.CalculatedAmount,
	)
	var i ProfitCommission
	err := row.Scan(
		&i.ID,
		&i.TreatyID,
		&i.CommissionType,
		&i.LossRatioFrom,
		&i.LossRatioTo,
		&i.CommissionRate,
		&i.CarryForwardYears,
		&i.CarryForwardBalance,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.CalculatedAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProfitCommission = `-- name: DeleteProfitCommission :exec
DELETE FROM profit_commissions WHERE id = $1
`

func (q *Queries) DeleteProfitCommission(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProfitCommission, id)
	return err
}

const getProfitCommissionByID = `-- name: GetProfitCommissionByID :one
SELECT id, treaty_id, commission_type, loss_ratio_from, loss_ratio_to, commission_rate, carry_forward_years, carry_forward_balance, period_start, period_end, calculated_amount, created_at, updated_at FROM profit_commissions WHERE id = $1
`

func (q *Queries) GetProfitCommissionByID(ctx context.Context, id uuid.UUID) (ProfitCommission, error) {
	row := q.db.QueryRow(ctx, getProfitCommissionByID, id)
	var i ProfitCommission
	err := row.Scan(
		&i.ID,
		&i.TreatyID,
		&i.CommissionType,
		&i.LossRatioFrom,
		&i.LossRatioTo,
		&i.CommissionRate,
		&i.CarryForwardYears,
		&i.CarryForwardBalance,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.CalculatedAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProfitCommissionsByTreaty = `-- name: ListProfitCommissionsByTreaty :many
SELECT id, treaty_id, commission_type, loss_ratio_from, loss_ratio_to, commission_rate, carry_forward_years, carry_forward_balance, period_start, period_end, calculated_amount, created_at, updated_at FROM profit_commissions WHERE treaty_id = $1 ORDER BY loss_ratio_from ASC
`

func (q *Queries) ListProfitCommissionsByTreaty(ctx context.Context, treatyID uuid.UUID) ([]ProfitCommission, error) {
	rows, err := q.db.Query(ctx, listProfitCommissionsByTreaty, treatyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProfitCommission{}
	for rows.Next() {
		var i ProfitCommission
		if err := rows.Scan(
			&i.ID,
			&i.TreatyID,
			&i.CommissionType,
			&i.LossRatioFrom,
			&i.LossRatioTo,
			&i.CommissionRate,
			&i.CarryForwardYears,
			&i.CarryForwardBalance,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.CalculatedAmount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProfitCommission = `-- name: UpdateProfitCommission :one
UPDATE profit_commissions SET
    commission_type = $2, loss_ratio_from = $3, loss_ratio_to = $4,
    commission_rate = $5, carry_forward_years = $6, carry_forward_balance = $7,
    period_start = $8, period_end = $9, calculated_amount = $10, updated_at = NOW()
WHERE id = $1 RETURNING id, treaty_id, commission_type, loss_ratio_from, loss_ratio_to, commission_rate, carry_forward_years, carry_forward_balance, period_start, period_end, calculated_amount, created_at, updated_at
`

type UpdateProfitCommissionParams struct {
	ID                  uuid.UUID      `json:"id"`
	CommissionType      string         `json:"commission_type"`
	LossRatioFrom       pgtype.Numeric `json:"loss_ratio_from"`
	LossRatioTo         pgtype.Numeric `json:"loss_ratio_to"`
	CommissionRate      pgtype.Numeric `json:"commission_rate"`
	CarryForwardYears   int32          `json:"carry_forward_years"`
	CarryForwardBalance int64          `json:"carry_forward_balance"`
	PeriodStart         pgtype.Date    `json:"period_start"`
	PeriodEnd           pgtype.Date    `json:"period_end"`
	CalculatedAmount    int64          `json:"calculated_amount"`
}

func (q *Queries) UpdateProfitCommission(ctx context.Context, arg UpdateProfitCommissionParams) (ProfitCommission, error) {
	row := q.db.QueryRow(ctx, updateProfitCommission,
		arg.ID,
		arg.CommissionType,
		arg.LossRatioFrom,
		arg.LossRatioTo,
		arg.CommissionRate,
		arg.CarryForwardYears,
		arg.CarryForwardBalance,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.CalculatedAmount,
	)
	var i ProfitCommission
	err := row.Scan(
		&i.ID,
		&i.TreatyID,
		&i.CommissionType,
		&i.LossRatioFrom,
		&i.LossRatioTo,
		&i.CommissionRate,
		&i.CarryForwardYears,
		&i.CarryForwardBalance,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.CalculatedAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
