// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: provider.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countProviders = `-- name: CountProviders :one
SELECT COUNT(*) FROM providers
`

func (q *Queries) CountProviders(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countProviders)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProvidersFiltered = `-- name: CountProvidersFiltered :one
SELECT COUNT(*) FROM providers
WHERE ($1::text = '' OR (name ILIKE '%' || $1 || '%' OR license_number ILIKE '%' || $1 || '%' OR email ILIKE '%' || $1 || '%'))
`

func (q *Queries) CountProvidersFiltered(ctx context.Context, dollar_1 string) (int64, error) {
	row := q.db.QueryRow(ctx, countProvidersFiltered, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProvider = `-- name: CreateProvider :one
INSERT INTO providers (name, type, license_number, status, county, address, phone, email, contact_person, user_id, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11) RETURNING id, name, type, license_number, status, county, address, phone, email, contact_person, user_id, created_by, created_at, updated_at, tier, accreditation_status, accreditation_expiry, accreditation_body
`

type CreateProviderParams struct {
	Name          string      `json:"name"`
	Type          string      `json:"type"`
	LicenseNumber string      `json:"license_number"`
	Status        string      `json:"status"`
	County        pgtype.Text `json:"county"`
	Address       pgtype.Text `json:"address"`
	Phone         pgtype.Text `json:"phone"`
	Email         pgtype.Text `json:"email"`
	ContactPerson pgtype.Text `json:"contact_person"`
	UserID        pgtype.UUID `json:"user_id"`
	CreatedBy     pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateProvider(ctx context.Context, arg CreateProviderParams) (Provider, error) {
	row := q.db.QueryRow(ctx, createProvider,
		arg.Name,
		arg.Type,
		arg.LicenseNumber,
		arg.Status,
		arg.County,
		arg.Address,
		arg.Phone,
		arg.Email,
		arg.ContactPerson,
		arg.UserID,
		arg.CreatedBy,
	)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.LicenseNumber,
		&i.Status,
		&i.County,
		&i.Address,
		&i.Phone,
		&i.Email,
		&i.ContactPerson,
		&i.UserID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Tier,
		&i.AccreditationStatus,
		&i.AccreditationExpiry,
		&i.AccreditationBody,
	)
	return i, err
}

const getProviderByID = `-- name: GetProviderByID :one
SELECT id, name, type, license_number, status, county, address, phone, email, contact_person, user_id, created_by, created_at, updated_at, tier, accreditation_status, accreditation_expiry, accreditation_body FROM providers WHERE id = $1
`

func (q *Queries) GetProviderByID(ctx context.Context, id uuid.UUID) (Provider, error) {
	row := q.db.QueryRow(ctx, getProviderByID, id)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.LicenseNumber,
		&i.Status,
		&i.County,
		&i.Address,
		&i.Phone,
		&i.Email,
		&i.ContactPerson,
		&i.UserID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Tier,
		&i.AccreditationStatus,
		&i.AccreditationExpiry,
		&i.AccreditationBody,
	)
	return i, err
}

const getProviderByLicense = `-- name: GetProviderByLicense :one
SELECT id, name, type, license_number, status, county, address, phone, email, contact_person, user_id, created_by, created_at, updated_at, tier, accreditation_status, accreditation_expiry, accreditation_body FROM providers WHERE license_number = $1
`

func (q *Queries) GetProviderByLicense(ctx context.Context, licenseNumber string) (Provider, error) {
	row := q.db.QueryRow(ctx, getProviderByLicense, licenseNumber)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.LicenseNumber,
		&i.Status,
		&i.County,
		&i.Address,
		&i.Phone,
		&i.Email,
		&i.ContactPerson,
		&i.UserID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Tier,
		&i.AccreditationStatus,
		&i.AccreditationExpiry,
		&i.AccreditationBody,
	)
	return i, err
}

const getProviderByUserID = `-- name: GetProviderByUserID :one
SELECT id, name, type, license_number, status, county, address, phone, email, contact_person, user_id, created_by, created_at, updated_at, tier, accreditation_status, accreditation_expiry, accreditation_body FROM providers WHERE user_id = $1
`

func (q *Queries) GetProviderByUserID(ctx context.Context, userID pgtype.UUID) (Provider, error) {
	row := q.db.QueryRow(ctx, getProviderByUserID, userID)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.LicenseNumber,
		&i.Status,
		&i.County,
		&i.Address,
		&i.Phone,
		&i.Email,
		&i.ContactPerson,
		&i.UserID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Tier,
		&i.AccreditationStatus,
		&i.AccreditationExpiry,
		&i.AccreditationBody,
	)
	return i, err
}

const listExpiringAccreditations = `-- name: ListExpiringAccreditations :many
SELECT id, name, type, license_number, status, county, address, phone, email, contact_person, user_id, created_by, created_at, updated_at, tier, accreditation_status, accreditation_expiry, accreditation_body FROM providers WHERE accreditation_status = 'ACCREDITED'
AND accreditation_expiry <= NOW() + make_interval(days => $1)
ORDER BY accreditation_expiry LIMIT $2 OFFSET $3
`

type ListExpiringAccreditationsParams struct {
	Days   int32 `json:"days"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListExpiringAccreditations(ctx context.Context, arg ListExpiringAccreditationsParams) ([]Provider, error) {
	rows, err := q.db.Query(ctx, listExpiringAccreditations, arg.Days, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Provider{}
	for rows.Next() {
		var i Provider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.LicenseNumber,
			&i.Status,
			&i.County,
			&i.Address,
			&i.Phone,
			&i.Email,
			&i.ContactPerson,
			&i.UserID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Tier,
			&i.AccreditationStatus,
			&i.AccreditationExpiry,
			&i.AccreditationBody,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProviders = `-- name: ListProviders :many
SELECT id, name, type, license_number, status, county, address, phone, email, contact_person, user_id, created_by, created_at, updated_at, tier, accreditation_status, accreditation_expiry, accreditation_body FROM providers ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListProvidersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListProviders(ctx context.Context, arg ListProvidersParams) ([]Provider, error) {
	rows, err := q.db.Query(ctx, listProviders, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Provider{}
	for rows.Next() {
		var i Provider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.LicenseNumber,
			&i.Status,
			&i.County,
			&i.Address,
			&i.Phone,
			&i.Email,
			&i.ContactPerson,
			&i.UserID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Tier,
			&i.AccreditationStatus,
			&i.AccreditationExpiry,
			&i.AccreditationBody,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProvidersByAccreditationStatus = `-- name: ListProvidersByAccreditationStatus :many
SELECT id, name, type, license_number, status, county, address, phone, email, contact_person, user_id, created_by, created_at, updated_at, tier, accreditation_status, accreditation_expiry, accreditation_body FROM providers WHERE accreditation_status = $1 ORDER BY name LIMIT $2 OFFSET $3
`

type ListProvidersByAccreditationStatusParams struct {
	AccreditationStatus pgtype.Text `json:"accreditation_status"`
	Limit               int32       `json:"limit"`
	Offset              int32       `json:"offset"`
}

func (q *Queries) ListProvidersByAccreditationStatus(ctx context.Context, arg ListProvidersByAccreditationStatusParams) ([]Provider, error) {
	rows, err := q.db.Query(ctx, listProvidersByAccreditationStatus, arg.AccreditationStatus, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Provider{}
	for rows.Next() {
		var i Provider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.LicenseNumber,
			&i.Status,
			&i.County,
			&i.Address,
			&i.Phone,
			&i.Email,
			&i.ContactPerson,
			&i.UserID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Tier,
			&i.AccreditationStatus,
			&i.AccreditationExpiry,
			&i.AccreditationBody,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProvidersByStatus = `-- name: ListProvidersByStatus :many
SELECT id, name, type, license_number, status, county, address, phone, email, contact_person, user_id, created_by, created_at, updated_at, tier, accreditation_status, accreditation_expiry, accreditation_body FROM providers WHERE status = $1 ORDER BY name LIMIT $2 OFFSET $3
`

type ListProvidersByStatusParams struct {
	Status string `json:"status"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListProvidersByStatus(ctx context.Context, arg ListProvidersByStatusParams) ([]Provider, error) {
	rows, err := q.db.Query(ctx, listProvidersByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Provider{}
	for rows.Next() {
		var i Provider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.LicenseNumber,
			&i.Status,
			&i.County,
			&i.Address,
			&i.Phone,
			&i.Email,
			&i.ContactPerson,
			&i.UserID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Tier,
			&i.AccreditationStatus,
			&i.AccreditationExpiry,
			&i.AccreditationBody,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProvidersByTier = `-- name: ListProvidersByTier :many
SELECT id, name, type, license_number, status, county, address, phone, email, contact_person, user_id, created_by, created_at, updated_at, tier, accreditation_status, accreditation_expiry, accreditation_body FROM providers WHERE tier = $1 ORDER BY name LIMIT $2 OFFSET $3
`

type ListProvidersByTierParams struct {
	Tier   string `json:"tier"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListProvidersByTier(ctx context.Context, arg ListProvidersByTierParams) ([]Provider, error) {
	rows, err := q.db.Query(ctx, listProvidersByTier, arg.Tier, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Provider{}
	for rows.Next() {
		var i Provider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.LicenseNumber,
			&i.Status,
			&i.County,
			&i.Address,
			&i.Phone,
			&i.Email,
			&i.ContactPerson,
			&i.UserID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Tier,
			&i.AccreditationStatus,
			&i.AccreditationExpiry,
			&i.AccreditationBody,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProvidersFiltered = `-- name: ListProvidersFiltered :many
SELECT id, name, type, license_number, status, county, address, phone, email, contact_person, user_id, created_by, created_at, updated_at, tier, accreditation_status, accreditation_expiry, accreditation_body FROM providers
WHERE ($1::text = '' OR (name ILIKE '%' || $1 || '%' OR license_number ILIKE '%' || $1 || '%' OR email ILIKE '%' || $1 || '%'))
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListProvidersFilteredParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) ListProvidersFiltered(ctx context.Context, arg ListProvidersFilteredParams) ([]Provider, error) {
	rows, err := q.db.Query(ctx, listProvidersFiltered, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Provider{}
	for rows.Next() {
		var i Provider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.LicenseNumber,
			&i.Status,
			&i.County,
			&i.Address,
			&i.Phone,
			&i.Email,
			&i.ContactPerson,
			&i.UserID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Tier,
			&i.AccreditationStatus,
			&i.AccreditationExpiry,
			&i.AccreditationBody,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccreditation = `-- name: UpdateAccreditation :one
UPDATE providers SET
    accreditation_status = $2,
    accreditation_expiry = $3,
    accreditation_body = $4,
    updated_at = NOW()
WHERE id = $1 RETURNING id, name, type, license_number, status, county, address, phone, email, contact_person, user_id, created_by, created_at, updated_at, tier, accreditation_status, accreditation_expiry, accreditation_body
`

type UpdateAccreditationParams struct {
	ID                  uuid.UUID          `json:"id"`
	AccreditationStatus pgtype.Text        `json:"accreditation_status"`
	AccreditationExpiry pgtype.Timestamptz `json:"accreditation_expiry"`
	AccreditationBody   pgtype.Text        `json:"accreditation_body"`
}

func (q *Queries) UpdateAccreditation(ctx context.Context, arg UpdateAccreditationParams) (Provider, error) {
	row := q.db.QueryRow(ctx, updateAccreditation,
		arg.ID,
		arg.AccreditationStatus,
		arg.AccreditationExpiry,
		arg.AccreditationBody,
	)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.LicenseNumber,
		&i.Status,
		&i.County,
		&i.Address,
		&i.Phone,
		&i.Email,
		&i.ContactPerson,
		&i.UserID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Tier,
		&i.AccreditationStatus,
		&i.AccreditationExpiry,
		&i.AccreditationBody,
	)
	return i, err
}

const updateProvider = `-- name: UpdateProvider :one
UPDATE providers SET
    name = COALESCE($1, name),
    county = COALESCE($2, county),
    address = COALESCE($3, address),
    phone = COALESCE($4, phone),
    email = COALESCE($5, email),
    contact_person = COALESCE($6, contact_person),
    updated_at = NOW()
WHERE id = $7 RETURNING id, name, type, license_number, status, county, address, phone, email, contact_person, user_id, created_by, created_at, updated_at, tier, accreditation_status, accreditation_expiry, accreditation_body
`

type UpdateProviderParams struct {
	Name          pgtype.Text `json:"name"`
	County        pgtype.Text `json:"county"`
	Address       pgtype.Text `json:"address"`
	Phone         pgtype.Text `json:"phone"`
	Email         pgtype.Text `json:"email"`
	ContactPerson pgtype.Text `json:"contact_person"`
	ID            uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateProvider(ctx context.Context, arg UpdateProviderParams) (Provider, error) {
	row := q.db.QueryRow(ctx, updateProvider,
		arg.Name,
		arg.County,
		arg.Address,
		arg.Phone,
		arg.Email,
		arg.ContactPerson,
		arg.ID,
	)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.LicenseNumber,
		&i.Status,
		&i.County,
		&i.Address,
		&i.Phone,
		&i.Email,
		&i.ContactPerson,
		&i.UserID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Tier,
		&i.AccreditationStatus,
		&i.AccreditationExpiry,
		&i.AccreditationBody,
	)
	return i, err
}

const updateProviderStatus = `-- name: UpdateProviderStatus :one
UPDATE providers SET status = $2, updated_at = NOW() WHERE id = $1 RETURNING id, name, type, license_number, status, county, address, phone, email, contact_person, user_id, created_by, created_at, updated_at, tier, accreditation_status, accreditation_expiry, accreditation_body
`

type UpdateProviderStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateProviderStatus(ctx context.Context, arg UpdateProviderStatusParams) (Provider, error) {
	row := q.db.QueryRow(ctx, updateProviderStatus, arg.ID, arg.Status)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.LicenseNumber,
		&i.Status,
		&i.County,
		&i.Address,
		&i.Phone,
		&i.Email,
		&i.ContactPerson,
		&i.UserID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Tier,
		&i.AccreditationStatus,
		&i.AccreditationExpiry,
		&i.AccreditationBody,
	)
	return i, err
}

const updateProviderTier = `-- name: UpdateProviderTier :one
UPDATE providers SET tier = $2, updated_at = NOW() WHERE id = $1 RETURNING id, name, type, license_number, status, county, address, phone, email, contact_person, user_id, created_by, created_at, updated_at, tier, accreditation_status, accreditation_expiry, accreditation_body
`

type UpdateProviderTierParams struct {
	ID   uuid.UUID `json:"id"`
	Tier string    `json:"tier"`
}

func (q *Queries) UpdateProviderTier(ctx context.Context, arg UpdateProviderTierParams) (Provider, error) {
	row := q.db.QueryRow(ctx, updateProviderTier, arg.ID, arg.Tier)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.LicenseNumber,
		&i.Status,
		&i.County,
		&i.Address,
		&i.Phone,
		&i.Email,
		&i.ContactPerson,
		&i.UserID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Tier,
		&i.AccreditationStatus,
		&i.AccreditationExpiry,
		&i.AccreditationBody,
	)
	return i, err
}
