// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: provider_statement.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProviderStatement = `-- name: CreateProviderStatement :one
INSERT INTO provider_statements (provider_id, statement_number, period_start, period_end, total_claimed, status, file_name, s3_key, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING id, provider_id, statement_number, period_start, period_end, total_claimed, total_matched, total_discrepancy, matched_count, unmatched_count, status, file_name, s3_key, reconciled_by, reconciled_at, created_by, created_at, updated_at
`

type CreateProviderStatementParams struct {
	ProviderID      uuid.UUID   `json:"provider_id"`
	StatementNumber string      `json:"statement_number"`
	PeriodStart     pgtype.Date `json:"period_start"`
	PeriodEnd       pgtype.Date `json:"period_end"`
	TotalClaimed    int64       `json:"total_claimed"`
	Status          string      `json:"status"`
	FileName        pgtype.Text `json:"file_name"`
	S3Key           pgtype.Text `json:"s3_key"`
	CreatedBy       uuid.UUID   `json:"created_by"`
}

func (q *Queries) CreateProviderStatement(ctx context.Context, arg CreateProviderStatementParams) (ProviderStatement, error) {
	row := q.db.QueryRow(ctx, createProviderStatement,
		arg.ProviderID,
		arg.StatementNumber,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.TotalClaimed,
		arg.Status,
		arg.FileName,
		arg.S3Key,
		arg.CreatedBy,
	)
	var i ProviderStatement
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.StatementNumber,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.TotalClaimed,
		&i.TotalMatched,
		&i.TotalDiscrepancy,
		&i.MatchedCount,
		&i.UnmatchedCount,
		&i.Status,
		&i.FileName,
		&i.S3Key,
		&i.ReconciledBy,
		&i.ReconciledAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProviderStatementByID = `-- name: GetProviderStatementByID :one
SELECT id, provider_id, statement_number, period_start, period_end, total_claimed, total_matched, total_discrepancy, matched_count, unmatched_count, status, file_name, s3_key, reconciled_by, reconciled_at, created_by, created_at, updated_at FROM provider_statements WHERE id = $1
`

func (q *Queries) GetProviderStatementByID(ctx context.Context, id uuid.UUID) (ProviderStatement, error) {
	row := q.db.QueryRow(ctx, getProviderStatementByID, id)
	var i ProviderStatement
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.StatementNumber,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.TotalClaimed,
		&i.TotalMatched,
		&i.TotalDiscrepancy,
		&i.MatchedCount,
		&i.UnmatchedCount,
		&i.Status,
		&i.FileName,
		&i.S3Key,
		&i.ReconciledBy,
		&i.ReconciledAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProviderStatementsByProvider = `-- name: ListProviderStatementsByProvider :many
SELECT id, provider_id, statement_number, period_start, period_end, total_claimed, total_matched, total_discrepancy, matched_count, unmatched_count, status, file_name, s3_key, reconciled_by, reconciled_at, created_by, created_at, updated_at FROM provider_statements WHERE provider_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListProviderStatementsByProviderParams struct {
	ProviderID uuid.UUID `json:"provider_id"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

func (q *Queries) ListProviderStatementsByProvider(ctx context.Context, arg ListProviderStatementsByProviderParams) ([]ProviderStatement, error) {
	rows, err := q.db.Query(ctx, listProviderStatementsByProvider, arg.ProviderID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProviderStatement{}
	for rows.Next() {
		var i ProviderStatement
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.StatementNumber,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.TotalClaimed,
			&i.TotalMatched,
			&i.TotalDiscrepancy,
			&i.MatchedCount,
			&i.UnmatchedCount,
			&i.Status,
			&i.FileName,
			&i.S3Key,
			&i.ReconciledBy,
			&i.ReconciledAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reconcileProviderStatement = `-- name: ReconcileProviderStatement :one
UPDATE provider_statements SET
    total_matched = $2,
    total_discrepancy = $3,
    matched_count = $4,
    unmatched_count = $5,
    status = 'RECONCILED',
    reconciled_by = $6,
    reconciled_at = NOW(),
    updated_at = NOW()
WHERE id = $1 RETURNING id, provider_id, statement_number, period_start, period_end, total_claimed, total_matched, total_discrepancy, matched_count, unmatched_count, status, file_name, s3_key, reconciled_by, reconciled_at, created_by, created_at, updated_at
`

type ReconcileProviderStatementParams struct {
	ID               uuid.UUID   `json:"id"`
	TotalMatched     int64       `json:"total_matched"`
	TotalDiscrepancy int64       `json:"total_discrepancy"`
	MatchedCount     int32       `json:"matched_count"`
	UnmatchedCount   int32       `json:"unmatched_count"`
	ReconciledBy     pgtype.UUID `json:"reconciled_by"`
}

func (q *Queries) ReconcileProviderStatement(ctx context.Context, arg ReconcileProviderStatementParams) (ProviderStatement, error) {
	row := q.db.QueryRow(ctx, reconcileProviderStatement,
		arg.ID,
		arg.TotalMatched,
		arg.TotalDiscrepancy,
		arg.MatchedCount,
		arg.UnmatchedCount,
		arg.ReconciledBy,
	)
	var i ProviderStatement
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.StatementNumber,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.TotalClaimed,
		&i.TotalMatched,
		&i.TotalDiscrepancy,
		&i.MatchedCount,
		&i.UnmatchedCount,
		&i.Status,
		&i.FileName,
		&i.S3Key,
		&i.ReconciledBy,
		&i.ReconciledAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
