// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: provider_network.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const checkProviderNetworkEligibility = `-- name: CheckProviderNetworkEligibility :one
SELECT COUNT(*) FROM provider_networks
WHERE plan_id = $1 AND provider_id = $2 AND status = 'ACTIVE'
AND (benefit_category IS NULL OR benefit_category = $3)
`

type CheckProviderNetworkEligibilityParams struct {
	PlanID          uuid.UUID   `json:"plan_id"`
	ProviderID      uuid.UUID   `json:"provider_id"`
	BenefitCategory pgtype.Text `json:"benefit_category"`
}

func (q *Queries) CheckProviderNetworkEligibility(ctx context.Context, arg CheckProviderNetworkEligibilityParams) (int64, error) {
	row := q.db.QueryRow(ctx, checkProviderNetworkEligibility, arg.PlanID, arg.ProviderID, arg.BenefitCategory)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProviderNetwork = `-- name: CreateProviderNetwork :one
INSERT INTO provider_networks (plan_id, provider_id, benefit_category, status)
VALUES ($1, $2, $3, $4) RETURNING id, plan_id, provider_id, benefit_category, status, created_at, updated_at
`

type CreateProviderNetworkParams struct {
	PlanID          uuid.UUID   `json:"plan_id"`
	ProviderID      uuid.UUID   `json:"provider_id"`
	BenefitCategory pgtype.Text `json:"benefit_category"`
	Status          string      `json:"status"`
}

func (q *Queries) CreateProviderNetwork(ctx context.Context, arg CreateProviderNetworkParams) (ProviderNetwork, error) {
	row := q.db.QueryRow(ctx, createProviderNetwork,
		arg.PlanID,
		arg.ProviderID,
		arg.BenefitCategory,
		arg.Status,
	)
	var i ProviderNetwork
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.ProviderID,
		&i.BenefitCategory,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProviderNetwork = `-- name: DeleteProviderNetwork :exec
DELETE FROM provider_networks WHERE id = $1
`

func (q *Queries) DeleteProviderNetwork(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProviderNetwork, id)
	return err
}

const getProviderNetworkByID = `-- name: GetProviderNetworkByID :one
SELECT id, plan_id, provider_id, benefit_category, status, created_at, updated_at FROM provider_networks WHERE id = $1
`

func (q *Queries) GetProviderNetworkByID(ctx context.Context, id uuid.UUID) (ProviderNetwork, error) {
	row := q.db.QueryRow(ctx, getProviderNetworkByID, id)
	var i ProviderNetwork
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.ProviderID,
		&i.BenefitCategory,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProviderNetworksByPlan = `-- name: ListProviderNetworksByPlan :many
SELECT id, plan_id, provider_id, benefit_category, status, created_at, updated_at FROM provider_networks WHERE plan_id = $1 ORDER BY created_at
`

func (q *Queries) ListProviderNetworksByPlan(ctx context.Context, planID uuid.UUID) ([]ProviderNetwork, error) {
	rows, err := q.db.Query(ctx, listProviderNetworksByPlan, planID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProviderNetwork{}
	for rows.Next() {
		var i ProviderNetwork
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.ProviderID,
			&i.BenefitCategory,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProviderNetworksByProvider = `-- name: ListProviderNetworksByProvider :many
SELECT id, plan_id, provider_id, benefit_category, status, created_at, updated_at FROM provider_networks WHERE provider_id = $1 ORDER BY created_at
`

func (q *Queries) ListProviderNetworksByProvider(ctx context.Context, providerID uuid.UUID) ([]ProviderNetwork, error) {
	rows, err := q.db.Query(ctx, listProviderNetworksByProvider, providerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProviderNetwork{}
	for rows.Next() {
		var i ProviderNetwork
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.ProviderID,
			&i.BenefitCategory,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProviderNetworkStatus = `-- name: UpdateProviderNetworkStatus :one
UPDATE provider_networks SET status = $2, updated_at = NOW() WHERE id = $1 RETURNING id, plan_id, provider_id, benefit_category, status, created_at, updated_at
`

type UpdateProviderNetworkStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateProviderNetworkStatus(ctx context.Context, arg UpdateProviderNetworkStatusParams) (ProviderNetwork, error) {
	row := q.db.QueryRow(ctx, updateProviderNetworkStatus, arg.ID, arg.Status)
	var i ProviderNetwork
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.ProviderID,
		&i.BenefitCategory,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
