// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: quotation_version.sql

package db

import (
	"context"
	"encoding/json"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createQuotationVersion = `-- name: CreateQuotationVersion :one
INSERT INTO quotation_versions (quotation_id, version_number, base_premium, discount_type, discount_value, discount_reason, loading_type, loading_value, loading_reason, final_premium, member_count, proposed_members, billing_frequency, requires_approval, approval_status, pricing_breakdown, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17) RETURNING id, quotation_id, version_number, base_premium, discount_type, discount_value, discount_reason, loading_type, loading_value, loading_reason, final_premium, member_count, proposed_members, billing_frequency, requires_approval, approval_status, approved_by, approved_at, rejection_reason, pricing_breakdown, created_by, created_at, updated_at
`

type CreateQuotationVersionParams struct {
	QuotationID      uuid.UUID       `json:"quotation_id"`
	VersionNumber    int32           `json:"version_number"`
	BasePremium      int64           `json:"base_premium"`
	DiscountType     string          `json:"discount_type"`
	DiscountValue    int64           `json:"discount_value"`
	DiscountReason   pgtype.Text     `json:"discount_reason"`
	LoadingType      string          `json:"loading_type"`
	LoadingValue     int64           `json:"loading_value"`
	LoadingReason    pgtype.Text     `json:"loading_reason"`
	FinalPremium     int64           `json:"final_premium"`
	MemberCount      int32           `json:"member_count"`
	ProposedMembers  json.RawMessage `json:"proposed_members"`
	BillingFrequency string          `json:"billing_frequency"`
	RequiresApproval bool            `json:"requires_approval"`
	ApprovalStatus   string          `json:"approval_status"`
	PricingBreakdown json.RawMessage `json:"pricing_breakdown"`
	CreatedBy        pgtype.UUID     `json:"created_by"`
}

func (q *Queries) CreateQuotationVersion(ctx context.Context, arg CreateQuotationVersionParams) (QuotationVersion, error) {
	row := q.db.QueryRow(ctx, createQuotationVersion,
		arg.QuotationID,
		arg.VersionNumber,
		arg.BasePremium,
		arg.DiscountType,
		arg.DiscountValue,
		arg.DiscountReason,
		arg.LoadingType,
		arg.LoadingValue,
		arg.LoadingReason,
		arg.FinalPremium,
		arg.MemberCount,
		arg.ProposedMembers,
		arg.BillingFrequency,
		arg.RequiresApproval,
		arg.ApprovalStatus,
		arg.PricingBreakdown,
		arg.CreatedBy,
	)
	var i QuotationVersion
	err := row.Scan(
		&i.ID,
		&i.QuotationID,
		&i.VersionNumber,
		&i.BasePremium,
		&i.DiscountType,
		&i.DiscountValue,
		&i.DiscountReason,
		&i.LoadingType,
		&i.LoadingValue,
		&i.LoadingReason,
		&i.FinalPremium,
		&i.MemberCount,
		&i.ProposedMembers,
		&i.BillingFrequency,
		&i.RequiresApproval,
		&i.ApprovalStatus,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.RejectionReason,
		&i.PricingBreakdown,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestQuotationVersion = `-- name: GetLatestQuotationVersion :one
SELECT id, quotation_id, version_number, base_premium, discount_type, discount_value, discount_reason, loading_type, loading_value, loading_reason, final_premium, member_count, proposed_members, billing_frequency, requires_approval, approval_status, approved_by, approved_at, rejection_reason, pricing_breakdown, created_by, created_at, updated_at FROM quotation_versions WHERE quotation_id = $1 ORDER BY version_number DESC LIMIT 1
`

func (q *Queries) GetLatestQuotationVersion(ctx context.Context, quotationID uuid.UUID) (QuotationVersion, error) {
	row := q.db.QueryRow(ctx, getLatestQuotationVersion, quotationID)
	var i QuotationVersion
	err := row.Scan(
		&i.ID,
		&i.QuotationID,
		&i.VersionNumber,
		&i.BasePremium,
		&i.DiscountType,
		&i.DiscountValue,
		&i.DiscountReason,
		&i.LoadingType,
		&i.LoadingValue,
		&i.LoadingReason,
		&i.FinalPremium,
		&i.MemberCount,
		&i.ProposedMembers,
		&i.BillingFrequency,
		&i.RequiresApproval,
		&i.ApprovalStatus,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.RejectionReason,
		&i.PricingBreakdown,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getQuotationVersionByID = `-- name: GetQuotationVersionByID :one
SELECT id, quotation_id, version_number, base_premium, discount_type, discount_value, discount_reason, loading_type, loading_value, loading_reason, final_premium, member_count, proposed_members, billing_frequency, requires_approval, approval_status, approved_by, approved_at, rejection_reason, pricing_breakdown, created_by, created_at, updated_at FROM quotation_versions WHERE id = $1
`

func (q *Queries) GetQuotationVersionByID(ctx context.Context, id uuid.UUID) (QuotationVersion, error) {
	row := q.db.QueryRow(ctx, getQuotationVersionByID, id)
	var i QuotationVersion
	err := row.Scan(
		&i.ID,
		&i.QuotationID,
		&i.VersionNumber,
		&i.BasePremium,
		&i.DiscountType,
		&i.DiscountValue,
		&i.DiscountReason,
		&i.LoadingType,
		&i.LoadingValue,
		&i.LoadingReason,
		&i.FinalPremium,
		&i.MemberCount,
		&i.ProposedMembers,
		&i.BillingFrequency,
		&i.RequiresApproval,
		&i.ApprovalStatus,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.RejectionReason,
		&i.PricingBreakdown,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getQuotationVersionByNumber = `-- name: GetQuotationVersionByNumber :one
SELECT id, quotation_id, version_number, base_premium, discount_type, discount_value, discount_reason, loading_type, loading_value, loading_reason, final_premium, member_count, proposed_members, billing_frequency, requires_approval, approval_status, approved_by, approved_at, rejection_reason, pricing_breakdown, created_by, created_at, updated_at FROM quotation_versions WHERE quotation_id = $1 AND version_number = $2
`

type GetQuotationVersionByNumberParams struct {
	QuotationID   uuid.UUID `json:"quotation_id"`
	VersionNumber int32     `json:"version_number"`
}

func (q *Queries) GetQuotationVersionByNumber(ctx context.Context, arg GetQuotationVersionByNumberParams) (QuotationVersion, error) {
	row := q.db.QueryRow(ctx, getQuotationVersionByNumber, arg.QuotationID, arg.VersionNumber)
	var i QuotationVersion
	err := row.Scan(
		&i.ID,
		&i.QuotationID,
		&i.VersionNumber,
		&i.BasePremium,
		&i.DiscountType,
		&i.DiscountValue,
		&i.DiscountReason,
		&i.LoadingType,
		&i.LoadingValue,
		&i.LoadingReason,
		&i.FinalPremium,
		&i.MemberCount,
		&i.ProposedMembers,
		&i.BillingFrequency,
		&i.RequiresApproval,
		&i.ApprovalStatus,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.RejectionReason,
		&i.PricingBreakdown,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listQuotationVersionsByQuotation = `-- name: ListQuotationVersionsByQuotation :many
SELECT id, quotation_id, version_number, base_premium, discount_type, discount_value, discount_reason, loading_type, loading_value, loading_reason, final_premium, member_count, proposed_members, billing_frequency, requires_approval, approval_status, approved_by, approved_at, rejection_reason, pricing_breakdown, created_by, created_at, updated_at FROM quotation_versions WHERE quotation_id = $1 ORDER BY version_number ASC
`

func (q *Queries) ListQuotationVersionsByQuotation(ctx context.Context, quotationID uuid.UUID) ([]QuotationVersion, error) {
	rows, err := q.db.Query(ctx, listQuotationVersionsByQuotation, quotationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QuotationVersion{}
	for rows.Next() {
		var i QuotationVersion
		if err := rows.Scan(
			&i.ID,
			&i.QuotationID,
			&i.VersionNumber,
			&i.BasePremium,
			&i.DiscountType,
			&i.DiscountValue,
			&i.DiscountReason,
			&i.LoadingType,
			&i.LoadingValue,
			&i.LoadingReason,
			&i.FinalPremium,
			&i.MemberCount,
			&i.ProposedMembers,
			&i.BillingFrequency,
			&i.RequiresApproval,
			&i.ApprovalStatus,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.RejectionReason,
			&i.PricingBreakdown,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectQuotationVersion = `-- name: RejectQuotationVersion :one
UPDATE quotation_versions SET approval_status = 'REJECTED', rejection_reason = $2, approved_by = $3, approved_at = NOW(), updated_at = NOW() WHERE id = $1 RETURNING id, quotation_id, version_number, base_premium, discount_type, discount_value, discount_reason, loading_type, loading_value, loading_reason, final_premium, member_count, proposed_members, billing_frequency, requires_approval, approval_status, approved_by, approved_at, rejection_reason, pricing_breakdown, created_by, created_at, updated_at
`

type RejectQuotationVersionParams struct {
	ID              uuid.UUID   `json:"id"`
	RejectionReason pgtype.Text `json:"rejection_reason"`
	ApprovedBy      pgtype.UUID `json:"approved_by"`
}

func (q *Queries) RejectQuotationVersion(ctx context.Context, arg RejectQuotationVersionParams) (QuotationVersion, error) {
	row := q.db.QueryRow(ctx, rejectQuotationVersion, arg.ID, arg.RejectionReason, arg.ApprovedBy)
	var i QuotationVersion
	err := row.Scan(
		&i.ID,
		&i.QuotationID,
		&i.VersionNumber,
		&i.BasePremium,
		&i.DiscountType,
		&i.DiscountValue,
		&i.DiscountReason,
		&i.LoadingType,
		&i.LoadingValue,
		&i.LoadingReason,
		&i.FinalPremium,
		&i.MemberCount,
		&i.ProposedMembers,
		&i.BillingFrequency,
		&i.RequiresApproval,
		&i.ApprovalStatus,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.RejectionReason,
		&i.PricingBreakdown,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateQuotationVersionApproval = `-- name: UpdateQuotationVersionApproval :one
UPDATE quotation_versions SET approval_status = $2, approved_by = $3, approved_at = NOW(), updated_at = NOW() WHERE id = $1 RETURNING id, quotation_id, version_number, base_premium, discount_type, discount_value, discount_reason, loading_type, loading_value, loading_reason, final_premium, member_count, proposed_members, billing_frequency, requires_approval, approval_status, approved_by, approved_at, rejection_reason, pricing_breakdown, created_by, created_at, updated_at
`

type UpdateQuotationVersionApprovalParams struct {
	ID             uuid.UUID   `json:"id"`
	ApprovalStatus string      `json:"approval_status"`
	ApprovedBy     pgtype.UUID `json:"approved_by"`
}

func (q *Queries) UpdateQuotationVersionApproval(ctx context.Context, arg UpdateQuotationVersionApprovalParams) (QuotationVersion, error) {
	row := q.db.QueryRow(ctx, updateQuotationVersionApproval, arg.ID, arg.ApprovalStatus, arg.ApprovedBy)
	var i QuotationVersion
	err := row.Scan(
		&i.ID,
		&i.QuotationID,
		&i.VersionNumber,
		&i.BasePremium,
		&i.DiscountType,
		&i.DiscountValue,
		&i.DiscountReason,
		&i.LoadingType,
		&i.LoadingValue,
		&i.LoadingReason,
		&i.FinalPremium,
		&i.MemberCount,
		&i.ProposedMembers,
		&i.BillingFrequency,
		&i.RequiresApproval,
		&i.ApprovalStatus,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.RejectionReason,
		&i.PricingBreakdown,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
