// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: quotation_document.sql

package db

import (
	"context"
	"encoding/json"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createQuotationDocument = `-- name: CreateQuotationDocument :one
INSERT INTO quotation_documents (quotation_id, version_number, file_name, file_type, file_size, s3_key, uploaded_by, can_edit_roles, can_delete_roles)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING id, quotation_id, version_number, file_name, file_type, file_size, s3_key, uploaded_by, can_edit_roles, can_delete_roles, is_deleted, created_at, updated_at
`

type CreateQuotationDocumentParams struct {
	QuotationID    uuid.UUID       `json:"quotation_id"`
	VersionNumber  pgtype.Int4     `json:"version_number"`
	FileName       string          `json:"file_name"`
	FileType       string          `json:"file_type"`
	FileSize       int64           `json:"file_size"`
	S3Key          string          `json:"s3_key"`
	UploadedBy     pgtype.UUID     `json:"uploaded_by"`
	CanEditRoles   json.RawMessage `json:"can_edit_roles"`
	CanDeleteRoles json.RawMessage `json:"can_delete_roles"`
}

func (q *Queries) CreateQuotationDocument(ctx context.Context, arg CreateQuotationDocumentParams) (QuotationDocument, error) {
	row := q.db.QueryRow(ctx, createQuotationDocument,
		arg.QuotationID,
		arg.VersionNumber,
		arg.FileName,
		arg.FileType,
		arg.FileSize,
		arg.S3Key,
		arg.UploadedBy,
		arg.CanEditRoles,
		arg.CanDeleteRoles,
	)
	var i QuotationDocument
	err := row.Scan(
		&i.ID,
		&i.QuotationID,
		&i.VersionNumber,
		&i.FileName,
		&i.FileType,
		&i.FileSize,
		&i.S3Key,
		&i.UploadedBy,
		&i.CanEditRoles,
		&i.CanDeleteRoles,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getQuotationDocumentByID = `-- name: GetQuotationDocumentByID :one
SELECT id, quotation_id, version_number, file_name, file_type, file_size, s3_key, uploaded_by, can_edit_roles, can_delete_roles, is_deleted, created_at, updated_at FROM quotation_documents WHERE id = $1 AND is_deleted = false
`

func (q *Queries) GetQuotationDocumentByID(ctx context.Context, id uuid.UUID) (QuotationDocument, error) {
	row := q.db.QueryRow(ctx, getQuotationDocumentByID, id)
	var i QuotationDocument
	err := row.Scan(
		&i.ID,
		&i.QuotationID,
		&i.VersionNumber,
		&i.FileName,
		&i.FileType,
		&i.FileSize,
		&i.S3Key,
		&i.UploadedBy,
		&i.CanEditRoles,
		&i.CanDeleteRoles,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listQuotationDocumentsByQuotation = `-- name: ListQuotationDocumentsByQuotation :many
SELECT id, quotation_id, version_number, file_name, file_type, file_size, s3_key, uploaded_by, can_edit_roles, can_delete_roles, is_deleted, created_at, updated_at FROM quotation_documents WHERE quotation_id = $1 AND is_deleted = false ORDER BY created_at DESC
`

func (q *Queries) ListQuotationDocumentsByQuotation(ctx context.Context, quotationID uuid.UUID) ([]QuotationDocument, error) {
	rows, err := q.db.Query(ctx, listQuotationDocumentsByQuotation, quotationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QuotationDocument{}
	for rows.Next() {
		var i QuotationDocument
		if err := rows.Scan(
			&i.ID,
			&i.QuotationID,
			&i.VersionNumber,
			&i.FileName,
			&i.FileType,
			&i.FileSize,
			&i.S3Key,
			&i.UploadedBy,
			&i.CanEditRoles,
			&i.CanDeleteRoles,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteQuotationDocument = `-- name: SoftDeleteQuotationDocument :exec
UPDATE quotation_documents SET is_deleted = true, updated_at = NOW() WHERE id = $1
`

func (q *Queries) SoftDeleteQuotationDocument(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteQuotationDocument, id)
	return err
}

const updateQuotationDocument = `-- name: UpdateQuotationDocument :one
UPDATE quotation_documents SET
    file_name = COALESCE(NULLIF($1::text, ''), file_name),
    can_edit_roles = COALESCE($2, can_edit_roles),
    can_delete_roles = COALESCE($3, can_delete_roles),
    updated_at = NOW()
WHERE id = $4 RETURNING id, quotation_id, version_number, file_name, file_type, file_size, s3_key, uploaded_by, can_edit_roles, can_delete_roles, is_deleted, created_at, updated_at
`

type UpdateQuotationDocumentParams struct {
	FileName       string    `json:"file_name"`
	CanEditRoles   []byte    `json:"can_edit_roles"`
	CanDeleteRoles []byte    `json:"can_delete_roles"`
	ID             uuid.UUID `json:"id"`
}

func (q *Queries) UpdateQuotationDocument(ctx context.Context, arg UpdateQuotationDocumentParams) (QuotationDocument, error) {
	row := q.db.QueryRow(ctx, updateQuotationDocument,
		arg.FileName,
		arg.CanEditRoles,
		arg.CanDeleteRoles,
		arg.ID,
	)
	var i QuotationDocument
	err := row.Scan(
		&i.ID,
		&i.QuotationID,
		&i.VersionNumber,
		&i.FileName,
		&i.FileType,
		&i.FileSize,
		&i.S3Key,
		&i.UploadedBy,
		&i.CanEditRoles,
		&i.CanDeleteRoles,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
