// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: quotation.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countQuotations = `-- name: CountQuotations :one
SELECT COUNT(*) FROM quotations
`

func (q *Queries) CountQuotations(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countQuotations)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createQuotation = `-- name: CreateQuotation :one
INSERT INTO quotations (quotation_number, lead_id, plan_id, quotation_type, status, current_version, valid_from, valid_until, client_name, client_email, client_phone, currency, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13) RETURNING id, quotation_number, lead_id, plan_id, quotation_type, status, current_version, policy_id, valid_from, valid_until, client_name, client_email, client_phone, currency, created_by, created_at, updated_at
`

type CreateQuotationParams struct {
	QuotationNumber string             `json:"quotation_number"`
	LeadID          uuid.UUID          `json:"lead_id"`
	PlanID          uuid.UUID          `json:"plan_id"`
	QuotationType   string             `json:"quotation_type"`
	Status          string             `json:"status"`
	CurrentVersion  int32              `json:"current_version"`
	ValidFrom       pgtype.Timestamptz `json:"valid_from"`
	ValidUntil      pgtype.Timestamptz `json:"valid_until"`
	ClientName      string             `json:"client_name"`
	ClientEmail     pgtype.Text        `json:"client_email"`
	ClientPhone     pgtype.Text        `json:"client_phone"`
	Currency        string             `json:"currency"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
}

func (q *Queries) CreateQuotation(ctx context.Context, arg CreateQuotationParams) (Quotation, error) {
	row := q.db.QueryRow(ctx, createQuotation,
		arg.QuotationNumber,
		arg.LeadID,
		arg.PlanID,
		arg.QuotationType,
		arg.Status,
		arg.CurrentVersion,
		arg.ValidFrom,
		arg.ValidUntil,
		arg.ClientName,
		arg.ClientEmail,
		arg.ClientPhone,
		arg.Currency,
		arg.CreatedBy,
	)
	var i Quotation
	err := row.Scan(
		&i.ID,
		&i.QuotationNumber,
		&i.LeadID,
		&i.PlanID,
		&i.QuotationType,
		&i.Status,
		&i.CurrentVersion,
		&i.PolicyID,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.ClientName,
		&i.ClientEmail,
		&i.ClientPhone,
		&i.Currency,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getQuotationByID = `-- name: GetQuotationByID :one
SELECT id, quotation_number, lead_id, plan_id, quotation_type, status, current_version, policy_id, valid_from, valid_until, client_name, client_email, client_phone, currency, created_by, created_at, updated_at FROM quotations WHERE id = $1
`

func (q *Queries) GetQuotationByID(ctx context.Context, id uuid.UUID) (Quotation, error) {
	row := q.db.QueryRow(ctx, getQuotationByID, id)
	var i Quotation
	err := row.Scan(
		&i.ID,
		&i.QuotationNumber,
		&i.LeadID,
		&i.PlanID,
		&i.QuotationType,
		&i.Status,
		&i.CurrentVersion,
		&i.PolicyID,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.ClientName,
		&i.ClientEmail,
		&i.ClientPhone,
		&i.Currency,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getQuotationByNumber = `-- name: GetQuotationByNumber :one
SELECT id, quotation_number, lead_id, plan_id, quotation_type, status, current_version, policy_id, valid_from, valid_until, client_name, client_email, client_phone, currency, created_by, created_at, updated_at FROM quotations WHERE quotation_number = $1
`

func (q *Queries) GetQuotationByNumber(ctx context.Context, quotationNumber string) (Quotation, error) {
	row := q.db.QueryRow(ctx, getQuotationByNumber, quotationNumber)
	var i Quotation
	err := row.Scan(
		&i.ID,
		&i.QuotationNumber,
		&i.LeadID,
		&i.PlanID,
		&i.QuotationType,
		&i.Status,
		&i.CurrentVersion,
		&i.PolicyID,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.ClientName,
		&i.ClientEmail,
		&i.ClientPhone,
		&i.Currency,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listExpiredQuotations = `-- name: ListExpiredQuotations :many
SELECT id, quotation_number, lead_id, plan_id, quotation_type, status, current_version, policy_id, valid_from, valid_until, client_name, client_email, client_phone, currency, created_by, created_at, updated_at FROM quotations
WHERE status IN ('ISSUED', 'PENDING_DECISION')
  AND valid_until < NOW()
`

func (q *Queries) ListExpiredQuotations(ctx context.Context) ([]Quotation, error) {
	rows, err := q.db.Query(ctx, listExpiredQuotations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Quotation{}
	for rows.Next() {
		var i Quotation
		if err := rows.Scan(
			&i.ID,
			&i.QuotationNumber,
			&i.LeadID,
			&i.PlanID,
			&i.QuotationType,
			&i.Status,
			&i.CurrentVersion,
			&i.PolicyID,
			&i.ValidFrom,
			&i.ValidUntil,
			&i.ClientName,
			&i.ClientEmail,
			&i.ClientPhone,
			&i.Currency,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuotations = `-- name: ListQuotations :many
SELECT id, quotation_number, lead_id, plan_id, quotation_type, status, current_version, policy_id, valid_from, valid_until, client_name, client_email, client_phone, currency, created_by, created_at, updated_at FROM quotations ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListQuotationsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListQuotations(ctx context.Context, arg ListQuotationsParams) ([]Quotation, error) {
	rows, err := q.db.Query(ctx, listQuotations, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Quotation{}
	for rows.Next() {
		var i Quotation
		if err := rows.Scan(
			&i.ID,
			&i.QuotationNumber,
			&i.LeadID,
			&i.PlanID,
			&i.QuotationType,
			&i.Status,
			&i.CurrentVersion,
			&i.PolicyID,
			&i.ValidFrom,
			&i.ValidUntil,
			&i.ClientName,
			&i.ClientEmail,
			&i.ClientPhone,
			&i.Currency,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuotationsByLead = `-- name: ListQuotationsByLead :many
SELECT id, quotation_number, lead_id, plan_id, quotation_type, status, current_version, policy_id, valid_from, valid_until, client_name, client_email, client_phone, currency, created_by, created_at, updated_at FROM quotations WHERE lead_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListQuotationsByLeadParams struct {
	LeadID uuid.UUID `json:"lead_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListQuotationsByLead(ctx context.Context, arg ListQuotationsByLeadParams) ([]Quotation, error) {
	rows, err := q.db.Query(ctx, listQuotationsByLead, arg.LeadID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Quotation{}
	for rows.Next() {
		var i Quotation
		if err := rows.Scan(
			&i.ID,
			&i.QuotationNumber,
			&i.LeadID,
			&i.PlanID,
			&i.QuotationType,
			&i.Status,
			&i.CurrentVersion,
			&i.PolicyID,
			&i.ValidFrom,
			&i.ValidUntil,
			&i.ClientName,
			&i.ClientEmail,
			&i.ClientPhone,
			&i.Currency,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuotationsByStatus = `-- name: ListQuotationsByStatus :many
SELECT id, quotation_number, lead_id, plan_id, quotation_type, status, current_version, policy_id, valid_from, valid_until, client_name, client_email, client_phone, currency, created_by, created_at, updated_at FROM quotations WHERE status = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListQuotationsByStatusParams struct {
	Status string `json:"status"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListQuotationsByStatus(ctx context.Context, arg ListQuotationsByStatusParams) ([]Quotation, error) {
	rows, err := q.db.Query(ctx, listQuotationsByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Quotation{}
	for rows.Next() {
		var i Quotation
		if err := rows.Scan(
			&i.ID,
			&i.QuotationNumber,
			&i.LeadID,
			&i.PlanID,
			&i.QuotationType,
			&i.Status,
			&i.CurrentVersion,
			&i.PolicyID,
			&i.ValidFrom,
			&i.ValidUntil,
			&i.ClientName,
			&i.ClientEmail,
			&i.ClientPhone,
			&i.Currency,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setQuotationPolicyID = `-- name: SetQuotationPolicyID :one
UPDATE quotations SET policy_id = $2, status = 'CONVERTED', updated_at = NOW() WHERE id = $1 RETURNING id, quotation_number, lead_id, plan_id, quotation_type, status, current_version, policy_id, valid_from, valid_until, client_name, client_email, client_phone, currency, created_by, created_at, updated_at
`

type SetQuotationPolicyIDParams struct {
	ID       uuid.UUID   `json:"id"`
	PolicyID pgtype.UUID `json:"policy_id"`
}

func (q *Queries) SetQuotationPolicyID(ctx context.Context, arg SetQuotationPolicyIDParams) (Quotation, error) {
	row := q.db.QueryRow(ctx, setQuotationPolicyID, arg.ID, arg.PolicyID)
	var i Quotation
	err := row.Scan(
		&i.ID,
		&i.QuotationNumber,
		&i.LeadID,
		&i.PlanID,
		&i.QuotationType,
		&i.Status,
		&i.CurrentVersion,
		&i.PolicyID,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.ClientName,
		&i.ClientEmail,
		&i.ClientPhone,
		&i.Currency,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateQuotationCurrentVersion = `-- name: UpdateQuotationCurrentVersion :one
UPDATE quotations SET current_version = $2, updated_at = NOW() WHERE id = $1 RETURNING id, quotation_number, lead_id, plan_id, quotation_type, status, current_version, policy_id, valid_from, valid_until, client_name, client_email, client_phone, currency, created_by, created_at, updated_at
`

type UpdateQuotationCurrentVersionParams struct {
	ID             uuid.UUID `json:"id"`
	CurrentVersion int32     `json:"current_version"`
}

func (q *Queries) UpdateQuotationCurrentVersion(ctx context.Context, arg UpdateQuotationCurrentVersionParams) (Quotation, error) {
	row := q.db.QueryRow(ctx, updateQuotationCurrentVersion, arg.ID, arg.CurrentVersion)
	var i Quotation
	err := row.Scan(
		&i.ID,
		&i.QuotationNumber,
		&i.LeadID,
		&i.PlanID,
		&i.QuotationType,
		&i.Status,
		&i.CurrentVersion,
		&i.PolicyID,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.ClientName,
		&i.ClientEmail,
		&i.ClientPhone,
		&i.Currency,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateQuotationStatus = `-- name: UpdateQuotationStatus :one
UPDATE quotations SET status = $2, updated_at = NOW() WHERE id = $1 RETURNING id, quotation_number, lead_id, plan_id, quotation_type, status, current_version, policy_id, valid_from, valid_until, client_name, client_email, client_phone, currency, created_by, created_at, updated_at
`

type UpdateQuotationStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateQuotationStatus(ctx context.Context, arg UpdateQuotationStatusParams) (Quotation, error) {
	row := q.db.QueryRow(ctx, updateQuotationStatus, arg.ID, arg.Status)
	var i Quotation
	err := row.Scan(
		&i.ID,
		&i.QuotationNumber,
		&i.LeadID,
		&i.PlanID,
		&i.QuotationType,
		&i.Status,
		&i.CurrentVersion,
		&i.PolicyID,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.ClientName,
		&i.ClientEmail,
		&i.ClientPhone,
		&i.Currency,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
