// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: recovery_workflow_event.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createRecoveryWorkflowEvent = `-- name: CreateRecoveryWorkflowEvent :one
INSERT INTO recovery_workflow_events (recovery_id, from_status, to_status, event_type, notes, performed_by)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, recovery_id, from_status, to_status, event_type, notes, performed_by, created_at
`

type CreateRecoveryWorkflowEventParams struct {
	RecoveryID  uuid.UUID   `json:"recovery_id"`
	FromStatus  string      `json:"from_status"`
	ToStatus    string      `json:"to_status"`
	EventType   string      `json:"event_type"`
	Notes       pgtype.Text `json:"notes"`
	PerformedBy uuid.UUID   `json:"performed_by"`
}

func (q *Queries) CreateRecoveryWorkflowEvent(ctx context.Context, arg CreateRecoveryWorkflowEventParams) (RecoveryWorkflowEvent, error) {
	row := q.db.QueryRow(ctx, createRecoveryWorkflowEvent,
		arg.RecoveryID,
		arg.FromStatus,
		arg.ToStatus,
		arg.EventType,
		arg.Notes,
		arg.PerformedBy,
	)
	var i RecoveryWorkflowEvent
	err := row.Scan(
		&i.ID,
		&i.RecoveryID,
		&i.FromStatus,
		&i.ToStatus,
		&i.EventType,
		&i.Notes,
		&i.PerformedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listRecoveryWorkflowEventsByRecovery = `-- name: ListRecoveryWorkflowEventsByRecovery :many
SELECT id, recovery_id, from_status, to_status, event_type, notes, performed_by, created_at FROM recovery_workflow_events WHERE recovery_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListRecoveryWorkflowEventsByRecovery(ctx context.Context, recoveryID uuid.UUID) ([]RecoveryWorkflowEvent, error) {
	rows, err := q.db.Query(ctx, listRecoveryWorkflowEventsByRecovery, recoveryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecoveryWorkflowEvent{}
	for rows.Next() {
		var i RecoveryWorkflowEvent
		if err := rows.Scan(
			&i.ID,
			&i.RecoveryID,
			&i.FromStatus,
			&i.ToStatus,
			&i.EventType,
			&i.Notes,
			&i.PerformedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
