// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: reinsurer_statement.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countReinsurerStatements = `-- name: CountReinsurerStatements :one
SELECT COUNT(*) FROM reinsurer_statements
`

func (q *Queries) CountReinsurerStatements(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countReinsurerStatements)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createReinsurerStatement = `-- name: CreateReinsurerStatement :one
INSERT INTO reinsurer_statements (statement_number, treaty_id, participant_id, period_start, period_end, premium_ceded, claims_recovered, commission_due, profit_commission, net_balance, status, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12) RETURNING id, statement_number, treaty_id, participant_id, period_start, period_end, premium_ceded, claims_recovered, commission_due, profit_commission, net_balance, status, created_by, created_at, updated_at
`

type CreateReinsurerStatementParams struct {
	StatementNumber  string      `json:"statement_number"`
	TreatyID         uuid.UUID   `json:"treaty_id"`
	ParticipantID    uuid.UUID   `json:"participant_id"`
	PeriodStart      pgtype.Date `json:"period_start"`
	PeriodEnd        pgtype.Date `json:"period_end"`
	PremiumCeded     int64       `json:"premium_ceded"`
	ClaimsRecovered  int64       `json:"claims_recovered"`
	CommissionDue    int64       `json:"commission_due"`
	ProfitCommission int64       `json:"profit_commission"`
	NetBalance       int64       `json:"net_balance"`
	Status           string      `json:"status"`
	CreatedBy        uuid.UUID   `json:"created_by"`
}

func (q *Queries) CreateReinsurerStatement(ctx context.Context, arg CreateReinsurerStatementParams) (ReinsurerStatement, error) {
	row := q.db.QueryRow(ctx, createReinsurerStatement,
		arg.StatementNumber,
		arg.TreatyID,
		arg.ParticipantID,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.PremiumCeded,
		arg.ClaimsRecovered,
		arg.CommissionDue,
		arg.ProfitCommission,
		arg.NetBalance,
		arg.Status,
		arg.CreatedBy,
	)
	var i ReinsurerStatement
	err := row.Scan(
		&i.ID,
		&i.StatementNumber,
		&i.TreatyID,
		&i.ParticipantID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.PremiumCeded,
		&i.ClaimsRecovered,
		&i.CommissionDue,
		&i.ProfitCommission,
		&i.NetBalance,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReinsurerStatementByID = `-- name: GetReinsurerStatementByID :one
SELECT id, statement_number, treaty_id, participant_id, period_start, period_end, premium_ceded, claims_recovered, commission_due, profit_commission, net_balance, status, created_by, created_at, updated_at FROM reinsurer_statements WHERE id = $1
`

func (q *Queries) GetReinsurerStatementByID(ctx context.Context, id uuid.UUID) (ReinsurerStatement, error) {
	row := q.db.QueryRow(ctx, getReinsurerStatementByID, id)
	var i ReinsurerStatement
	err := row.Scan(
		&i.ID,
		&i.StatementNumber,
		&i.TreatyID,
		&i.ParticipantID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.PremiumCeded,
		&i.ClaimsRecovered,
		&i.CommissionDue,
		&i.ProfitCommission,
		&i.NetBalance,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReinsurerStatementByNumber = `-- name: GetReinsurerStatementByNumber :one
SELECT id, statement_number, treaty_id, participant_id, period_start, period_end, premium_ceded, claims_recovered, commission_due, profit_commission, net_balance, status, created_by, created_at, updated_at FROM reinsurer_statements WHERE statement_number = $1
`

func (q *Queries) GetReinsurerStatementByNumber(ctx context.Context, statementNumber string) (ReinsurerStatement, error) {
	row := q.db.QueryRow(ctx, getReinsurerStatementByNumber, statementNumber)
	var i ReinsurerStatement
	err := row.Scan(
		&i.ID,
		&i.StatementNumber,
		&i.TreatyID,
		&i.ParticipantID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.PremiumCeded,
		&i.ClaimsRecovered,
		&i.CommissionDue,
		&i.ProfitCommission,
		&i.NetBalance,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listReinsurerStatementsByTreaty = `-- name: ListReinsurerStatementsByTreaty :many
SELECT id, statement_number, treaty_id, participant_id, period_start, period_end, premium_ceded, claims_recovered, commission_due, profit_commission, net_balance, status, created_by, created_at, updated_at FROM reinsurer_statements WHERE treaty_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListReinsurerStatementsByTreatyParams struct {
	TreatyID uuid.UUID `json:"treaty_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListReinsurerStatementsByTreaty(ctx context.Context, arg ListReinsurerStatementsByTreatyParams) ([]ReinsurerStatement, error) {
	rows, err := q.db.Query(ctx, listReinsurerStatementsByTreaty, arg.TreatyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReinsurerStatement{}
	for rows.Next() {
		var i ReinsurerStatement
		if err := rows.Scan(
			&i.ID,
			&i.StatementNumber,
			&i.TreatyID,
			&i.ParticipantID,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.PremiumCeded,
			&i.ClaimsRecovered,
			&i.CommissionDue,
			&i.ProfitCommission,
			&i.NetBalance,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReinsurerStatement = `-- name: UpdateReinsurerStatement :one
UPDATE reinsurer_statements SET
    premium_ceded = $2, claims_recovered = $3, commission_due = $4,
    profit_commission = $5, net_balance = $6, updated_at = NOW()
WHERE id = $1 RETURNING id, statement_number, treaty_id, participant_id, period_start, period_end, premium_ceded, claims_recovered, commission_due, profit_commission, net_balance, status, created_by, created_at, updated_at
`

type UpdateReinsurerStatementParams struct {
	ID               uuid.UUID `json:"id"`
	PremiumCeded     int64     `json:"premium_ceded"`
	ClaimsRecovered  int64     `json:"claims_recovered"`
	CommissionDue    int64     `json:"commission_due"`
	ProfitCommission int64     `json:"profit_commission"`
	NetBalance       int64     `json:"net_balance"`
}

func (q *Queries) UpdateReinsurerStatement(ctx context.Context, arg UpdateReinsurerStatementParams) (ReinsurerStatement, error) {
	row := q.db.QueryRow(ctx, updateReinsurerStatement,
		arg.ID,
		arg.PremiumCeded,
		arg.ClaimsRecovered,
		arg.CommissionDue,
		arg.ProfitCommission,
		arg.NetBalance,
	)
	var i ReinsurerStatement
	err := row.Scan(
		&i.ID,
		&i.StatementNumber,
		&i.TreatyID,
		&i.ParticipantID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.PremiumCeded,
		&i.ClaimsRecovered,
		&i.CommissionDue,
		&i.ProfitCommission,
		&i.NetBalance,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateReinsurerStatementStatus = `-- name: UpdateReinsurerStatementStatus :one
UPDATE reinsurer_statements SET status = $2, updated_at = NOW() WHERE id = $1 RETURNING id, statement_number, treaty_id, participant_id, period_start, period_end, premium_ceded, claims_recovered, commission_due, profit_commission, net_balance, status, created_by, created_at, updated_at
`

type UpdateReinsurerStatementStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateReinsurerStatementStatus(ctx context.Context, arg UpdateReinsurerStatementStatusParams) (ReinsurerStatement, error) {
	row := q.db.QueryRow(ctx, updateReinsurerStatementStatus, arg.ID, arg.Status)
	var i ReinsurerStatement
	err := row.Scan(
		&i.ID,
		&i.StatementNumber,
		&i.TreatyID,
		&i.ParticipantID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.PremiumCeded,
		&i.ClaimsRecovered,
		&i.CommissionDue,
		&i.ProfitCommission,
		&i.NetBalance,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
