// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: remittance.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countRemittances = `-- name: CountRemittances :one
SELECT COUNT(*) FROM remittances
`

func (q *Queries) CountRemittances(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countRemittances)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRemittance = `-- name: CreateRemittance :one
INSERT INTO remittances (provider_id, claim_ids, total_amount, currency, status, period_start, period_end, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING id, provider_id, claim_ids, total_amount, currency, status, remittance_advice_sent, period_start, period_end, payment_id, created_by, created_at, updated_at
`

type CreateRemittanceParams struct {
	ProviderID  uuid.UUID       `json:"provider_id"`
	ClaimIds    json.RawMessage `json:"claim_ids"`
	TotalAmount int64           `json:"total_amount"`
	Currency    string          `json:"currency"`
	Status      string          `json:"status"`
	PeriodStart time.Time       `json:"period_start"`
	PeriodEnd   time.Time       `json:"period_end"`
	CreatedBy   pgtype.UUID     `json:"created_by"`
}

func (q *Queries) CreateRemittance(ctx context.Context, arg CreateRemittanceParams) (Remittance, error) {
	row := q.db.QueryRow(ctx, createRemittance,
		arg.ProviderID,
		arg.ClaimIds,
		arg.TotalAmount,
		arg.Currency,
		arg.Status,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.CreatedBy,
	)
	var i Remittance
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.ClaimIds,
		&i.TotalAmount,
		&i.Currency,
		&i.Status,
		&i.RemittanceAdviceSent,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.PaymentID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRemittanceByID = `-- name: GetRemittanceByID :one
SELECT id, provider_id, claim_ids, total_amount, currency, status, remittance_advice_sent, period_start, period_end, payment_id, created_by, created_at, updated_at FROM remittances WHERE id = $1
`

func (q *Queries) GetRemittanceByID(ctx context.Context, id uuid.UUID) (Remittance, error) {
	row := q.db.QueryRow(ctx, getRemittanceByID, id)
	var i Remittance
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.ClaimIds,
		&i.TotalAmount,
		&i.Currency,
		&i.Status,
		&i.RemittanceAdviceSent,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.PaymentID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRemittances = `-- name: ListRemittances :many
SELECT id, provider_id, claim_ids, total_amount, currency, status, remittance_advice_sent, period_start, period_end, payment_id, created_by, created_at, updated_at FROM remittances ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListRemittancesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListRemittances(ctx context.Context, arg ListRemittancesParams) ([]Remittance, error) {
	rows, err := q.db.Query(ctx, listRemittances, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Remittance{}
	for rows.Next() {
		var i Remittance
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.ClaimIds,
			&i.TotalAmount,
			&i.Currency,
			&i.Status,
			&i.RemittanceAdviceSent,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.PaymentID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRemittancesByProvider = `-- name: ListRemittancesByProvider :many
SELECT id, provider_id, claim_ids, total_amount, currency, status, remittance_advice_sent, period_start, period_end, payment_id, created_by, created_at, updated_at FROM remittances WHERE provider_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListRemittancesByProviderParams struct {
	ProviderID uuid.UUID `json:"provider_id"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

func (q *Queries) ListRemittancesByProvider(ctx context.Context, arg ListRemittancesByProviderParams) ([]Remittance, error) {
	rows, err := q.db.Query(ctx, listRemittancesByProvider, arg.ProviderID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Remittance{}
	for rows.Next() {
		var i Remittance
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.ClaimIds,
			&i.TotalAmount,
			&i.Currency,
			&i.Status,
			&i.RemittanceAdviceSent,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.PaymentID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRemittancesByStatus = `-- name: ListRemittancesByStatus :many
SELECT id, provider_id, claim_ids, total_amount, currency, status, remittance_advice_sent, period_start, period_end, payment_id, created_by, created_at, updated_at FROM remittances WHERE status = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListRemittancesByStatusParams struct {
	Status string `json:"status"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListRemittancesByStatus(ctx context.Context, arg ListRemittancesByStatusParams) ([]Remittance, error) {
	rows, err := q.db.Query(ctx, listRemittancesByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Remittance{}
	for rows.Next() {
		var i Remittance
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.ClaimIds,
			&i.TotalAmount,
			&i.Currency,
			&i.Status,
			&i.RemittanceAdviceSent,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.PaymentID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRemittanceAdviceSent = `-- name: MarkRemittanceAdviceSent :one
UPDATE remittances SET remittance_advice_sent = TRUE, updated_at = NOW() WHERE id = $1 RETURNING id, provider_id, claim_ids, total_amount, currency, status, remittance_advice_sent, period_start, period_end, payment_id, created_by, created_at, updated_at
`

func (q *Queries) MarkRemittanceAdviceSent(ctx context.Context, id uuid.UUID) (Remittance, error) {
	row := q.db.QueryRow(ctx, markRemittanceAdviceSent, id)
	var i Remittance
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.ClaimIds,
		&i.TotalAmount,
		&i.Currency,
		&i.Status,
		&i.RemittanceAdviceSent,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.PaymentID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setRemittancePayment = `-- name: SetRemittancePayment :one
UPDATE remittances SET payment_id = $2, updated_at = NOW() WHERE id = $1 RETURNING id, provider_id, claim_ids, total_amount, currency, status, remittance_advice_sent, period_start, period_end, payment_id, created_by, created_at, updated_at
`

type SetRemittancePaymentParams struct {
	ID        uuid.UUID   `json:"id"`
	PaymentID pgtype.UUID `json:"payment_id"`
}

func (q *Queries) SetRemittancePayment(ctx context.Context, arg SetRemittancePaymentParams) (Remittance, error) {
	row := q.db.QueryRow(ctx, setRemittancePayment, arg.ID, arg.PaymentID)
	var i Remittance
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.ClaimIds,
		&i.TotalAmount,
		&i.Currency,
		&i.Status,
		&i.RemittanceAdviceSent,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.PaymentID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRemittanceStatus = `-- name: UpdateRemittanceStatus :one
UPDATE remittances SET status = $2, updated_at = NOW() WHERE id = $1 RETURNING id, provider_id, claim_ids, total_amount, currency, status, remittance_advice_sent, period_start, period_end, payment_id, created_by, created_at, updated_at
`

type UpdateRemittanceStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateRemittanceStatus(ctx context.Context, arg UpdateRemittanceStatusParams) (Remittance, error) {
	row := q.db.QueryRow(ctx, updateRemittanceStatus, arg.ID, arg.Status)
	var i Remittance
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.ClaimIds,
		&i.TotalAmount,
		&i.Currency,
		&i.Status,
		&i.RemittanceAdviceSent,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.PaymentID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
