// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: standalone_documents.sql

package db

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const countStandaloneDocuments = `-- name: CountStandaloneDocuments :one
SELECT (
    (SELECT COUNT(*) FROM policy_documents) +
    (SELECT COUNT(*) FROM claim_documents WHERE is_deleted = false) +
    (SELECT COUNT(*) FROM quotation_documents WHERE is_deleted = false) +
    (SELECT COUNT(*) FROM documents WHERE status = 'ACTIVE' AND deleted_at IS NULL)
)::bigint AS total
`

func (q *Queries) CountStandaloneDocuments(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countStandaloneDocuments)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const findDocumentS3Key = `-- name: FindDocumentS3Key :one
SELECT doc_id, s3_key, source_type FROM (
    SELECT pd.id AS doc_id, pd.s3_key, 'policy' AS source_type FROM policy_documents pd WHERE pd.id = $1
    UNION ALL
    SELECT cd.id AS doc_id, cd.s3_key, 'claim' AS source_type FROM claim_documents cd WHERE cd.id = $1 AND cd.is_deleted = false
    UNION ALL
    SELECT qd.id AS doc_id, qd.s3_key, 'quotation' AS source_type FROM quotation_documents qd WHERE qd.id = $1 AND qd.is_deleted = false
    UNION ALL
    SELECT d.id AS doc_id, d.s3_key, d.entity_type AS source_type FROM documents d WHERE d.id = $1 AND d.status = 'ACTIVE' AND d.deleted_at IS NULL
) docs
LIMIT 1
`

type FindDocumentS3KeyRow struct {
	DocID      uuid.UUID `json:"doc_id"`
	S3Key      string    `json:"s3_key"`
	SourceType string    `json:"source_type"`
}

func (q *Queries) FindDocumentS3Key(ctx context.Context, id uuid.UUID) (FindDocumentS3KeyRow, error) {
	row := q.db.QueryRow(ctx, findDocumentS3Key, id)
	var i FindDocumentS3KeyRow
	err := row.Scan(&i.DocID, &i.S3Key, &i.SourceType)
	return i, err
}

const listStandaloneDocuments = `-- name: ListStandaloneDocuments :many
SELECT id, source_type, source_id, document_type, file_name, file_size, s3_key, created_by, created_at FROM (
    SELECT
        id,
        'policy' AS source_type,
        policy_id AS source_id,
        document_type,
        file_name,
        COALESCE(file_size, 0) AS file_size,
        s3_key,
        generated_by AS created_by,
        created_at
    FROM policy_documents
    UNION ALL
    SELECT
        id,
        'claim' AS source_type,
        claim_id AS source_id,
        file_type AS document_type,
        file_name,
        COALESCE(file_size, 0) AS file_size,
        s3_key,
        uploaded_by AS created_by,
        created_at
    FROM claim_documents WHERE is_deleted = false
    UNION ALL
    SELECT
        id,
        'quotation' AS source_type,
        quotation_id AS source_id,
        file_type AS document_type,
        file_name,
        COALESCE(file_size, 0) AS file_size,
        s3_key,
        COALESCE(uploaded_by, '00000000-0000-0000-0000-000000000000'::uuid) AS created_by,
        created_at
    FROM quotation_documents WHERE is_deleted = false
    UNION ALL
    SELECT
        id,
        entity_type AS source_type,
        entity_id AS source_id,
        document_type,
        file_name,
        COALESCE(file_size, 0) AS file_size,
        s3_key,
        uploaded_by AS created_by,
        created_at
    FROM documents WHERE status = 'ACTIVE' AND deleted_at IS NULL
) docs
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListStandaloneDocumentsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListStandaloneDocumentsRow struct {
	ID           uuid.UUID `json:"id"`
	SourceType   string    `json:"source_type"`
	SourceID     uuid.UUID `json:"source_id"`
	DocumentType string    `json:"document_type"`
	FileName     string    `json:"file_name"`
	FileSize     int64     `json:"file_size"`
	S3Key        string    `json:"s3_key"`
	CreatedBy    uuid.UUID `json:"created_by"`
	CreatedAt    time.Time `json:"created_at"`
}

func (q *Queries) ListStandaloneDocuments(ctx context.Context, arg ListStandaloneDocumentsParams) ([]ListStandaloneDocumentsRow, error) {
	rows, err := q.db.Query(ctx, listStandaloneDocuments, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStandaloneDocumentsRow{}
	for rows.Next() {
		var i ListStandaloneDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceType,
			&i.SourceID,
			&i.DocumentType,
			&i.FileName,
			&i.FileSize,
			&i.S3Key,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
