// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: treaty_layer.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTreatyLayer = `-- name: CreateTreatyLayer :one
INSERT INTO treaty_layers (treaty_id, layer_number, attachment_point, layer_limit, deductible_amount, premium_rate, aggregate_limit)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, treaty_id, layer_number, attachment_point, layer_limit, deductible_amount, premium_rate, aggregate_limit, aggregate_used, created_at, updated_at
`

type CreateTreatyLayerParams struct {
	TreatyID         uuid.UUID      `json:"treaty_id"`
	LayerNumber      int32          `json:"layer_number"`
	AttachmentPoint  int64          `json:"attachment_point"`
	LayerLimit       int64          `json:"layer_limit"`
	DeductibleAmount int64          `json:"deductible_amount"`
	PremiumRate      pgtype.Numeric `json:"premium_rate"`
	AggregateLimit   pgtype.Int8    `json:"aggregate_limit"`
}

func (q *Queries) CreateTreatyLayer(ctx context.Context, arg CreateTreatyLayerParams) (TreatyLayer, error) {
	row := q.db.QueryRow(ctx, createTreatyLayer,
		arg.TreatyID,
		arg.LayerNumber,
		arg.AttachmentPoint,
		arg.LayerLimit,
		arg.DeductibleAmount,
		arg.PremiumRate,
		arg.AggregateLimit,
	)
	var i TreatyLayer
	err := row.Scan(
		&i.ID,
		&i.TreatyID,
		&i.LayerNumber,
		&i.AttachmentPoint,
		&i.LayerLimit,
		&i.DeductibleAmount,
		&i.PremiumRate,
		&i.AggregateLimit,
		&i.AggregateUsed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTreatyLayer = `-- name: DeleteTreatyLayer :exec
DELETE FROM treaty_layers WHERE id = $1
`

func (q *Queries) DeleteTreatyLayer(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTreatyLayer, id)
	return err
}

const getTreatyLayerByID = `-- name: GetTreatyLayerByID :one
SELECT id, treaty_id, layer_number, attachment_point, layer_limit, deductible_amount, premium_rate, aggregate_limit, aggregate_used, created_at, updated_at FROM treaty_layers WHERE id = $1
`

func (q *Queries) GetTreatyLayerByID(ctx context.Context, id uuid.UUID) (TreatyLayer, error) {
	row := q.db.QueryRow(ctx, getTreatyLayerByID, id)
	var i TreatyLayer
	err := row.Scan(
		&i.ID,
		&i.TreatyID,
		&i.LayerNumber,
		&i.AttachmentPoint,
		&i.LayerLimit,
		&i.DeductibleAmount,
		&i.PremiumRate,
		&i.AggregateLimit,
		&i.AggregateUsed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTreatyLayersByTreaty = `-- name: ListTreatyLayersByTreaty :many
SELECT id, treaty_id, layer_number, attachment_point, layer_limit, deductible_amount, premium_rate, aggregate_limit, aggregate_used, created_at, updated_at FROM treaty_layers WHERE treaty_id = $1 ORDER BY layer_number ASC
`

func (q *Queries) ListTreatyLayersByTreaty(ctx context.Context, treatyID uuid.UUID) ([]TreatyLayer, error) {
	rows, err := q.db.Query(ctx, listTreatyLayersByTreaty, treatyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TreatyLayer{}
	for rows.Next() {
		var i TreatyLayer
		if err := rows.Scan(
			&i.ID,
			&i.TreatyID,
			&i.LayerNumber,
			&i.AttachmentPoint,
			&i.LayerLimit,
			&i.DeductibleAmount,
			&i.PremiumRate,
			&i.AggregateLimit,
			&i.AggregateUsed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTreatyLayer = `-- name: UpdateTreatyLayer :one
UPDATE treaty_layers SET
    attachment_point = $2, layer_limit = $3, deductible_amount = $4,
    premium_rate = $5, aggregate_limit = $6, updated_at = NOW()
WHERE id = $1 RETURNING id, treaty_id, layer_number, attachment_point, layer_limit, deductible_amount, premium_rate, aggregate_limit, aggregate_used, created_at, updated_at
`

type UpdateTreatyLayerParams struct {
	ID               uuid.UUID      `json:"id"`
	AttachmentPoint  int64          `json:"attachment_point"`
	LayerLimit       int64          `json:"layer_limit"`
	DeductibleAmount int64          `json:"deductible_amount"`
	PremiumRate      pgtype.Numeric `json:"premium_rate"`
	AggregateLimit   pgtype.Int8    `json:"aggregate_limit"`
}

func (q *Queries) UpdateTreatyLayer(ctx context.Context, arg UpdateTreatyLayerParams) (TreatyLayer, error) {
	row := q.db.QueryRow(ctx, updateTreatyLayer,
		arg.ID,
		arg.AttachmentPoint,
		arg.LayerLimit,
		arg.DeductibleAmount,
		arg.PremiumRate,
		arg.AggregateLimit,
	)
	var i TreatyLayer
	err := row.Scan(
		&i.ID,
		&i.TreatyID,
		&i.LayerNumber,
		&i.AttachmentPoint,
		&i.LayerLimit,
		&i.DeductibleAmount,
		&i.PremiumRate,
		&i.AggregateLimit,
		&i.AggregateUsed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTreatyLayerAggregateUsed = `-- name: UpdateTreatyLayerAggregateUsed :one
UPDATE treaty_layers SET aggregate_used = $2, updated_at = NOW() WHERE id = $1 RETURNING id, treaty_id, layer_number, attachment_point, layer_limit, deductible_amount, premium_rate, aggregate_limit, aggregate_used, created_at, updated_at
`

type UpdateTreatyLayerAggregateUsedParams struct {
	ID            uuid.UUID `json:"id"`
	AggregateUsed int64     `json:"aggregate_used"`
}

func (q *Queries) UpdateTreatyLayerAggregateUsed(ctx context.Context, arg UpdateTreatyLayerAggregateUsedParams) (TreatyLayer, error) {
	row := q.db.QueryRow(ctx, updateTreatyLayerAggregateUsed, arg.ID, arg.AggregateUsed)
	var i TreatyLayer
	err := row.Scan(
		&i.ID,
		&i.TreatyID,
		&i.LayerNumber,
		&i.AttachmentPoint,
		&i.LayerLimit,
		&i.DeductibleAmount,
		&i.PremiumRate,
		&i.AggregateLimit,
		&i.AggregateUsed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
