// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: underwriting_rule.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUnderwritingRule = `-- name: CreateUnderwritingRule :one
INSERT INTO underwriting_rules (plan_id, rule_type, relationship, parameter_key, parameter_value, severity, risk_score_weight, is_blocking, is_active, description)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) RETURNING id, plan_id, rule_type, relationship, parameter_key, parameter_value, severity, risk_score_weight, is_blocking, is_active, description, created_at, updated_at
`

type CreateUnderwritingRuleParams struct {
	PlanID          uuid.UUID   `json:"plan_id"`
	RuleType        string      `json:"rule_type"`
	Relationship    pgtype.Text `json:"relationship"`
	ParameterKey    string      `json:"parameter_key"`
	ParameterValue  string      `json:"parameter_value"`
	Severity        string      `json:"severity"`
	RiskScoreWeight int32       `json:"risk_score_weight"`
	IsBlocking      bool        `json:"is_blocking"`
	IsActive        bool        `json:"is_active"`
	Description     pgtype.Text `json:"description"`
}

func (q *Queries) CreateUnderwritingRule(ctx context.Context, arg CreateUnderwritingRuleParams) (UnderwritingRule, error) {
	row := q.db.QueryRow(ctx, createUnderwritingRule,
		arg.PlanID,
		arg.RuleType,
		arg.Relationship,
		arg.ParameterKey,
		arg.ParameterValue,
		arg.Severity,
		arg.RiskScoreWeight,
		arg.IsBlocking,
		arg.IsActive,
		arg.Description,
	)
	var i UnderwritingRule
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.RuleType,
		&i.Relationship,
		&i.ParameterKey,
		&i.ParameterValue,
		&i.Severity,
		&i.RiskScoreWeight,
		&i.IsBlocking,
		&i.IsActive,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUnderwritingRule = `-- name: DeleteUnderwritingRule :exec
DELETE FROM underwriting_rules WHERE id = $1
`

func (q *Queries) DeleteUnderwritingRule(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUnderwritingRule, id)
	return err
}

const getUnderwritingRuleByID = `-- name: GetUnderwritingRuleByID :one
SELECT id, plan_id, rule_type, relationship, parameter_key, parameter_value, severity, risk_score_weight, is_blocking, is_active, description, created_at, updated_at FROM underwriting_rules WHERE id = $1
`

func (q *Queries) GetUnderwritingRuleByID(ctx context.Context, id uuid.UUID) (UnderwritingRule, error) {
	row := q.db.QueryRow(ctx, getUnderwritingRuleByID, id)
	var i UnderwritingRule
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.RuleType,
		&i.Relationship,
		&i.ParameterKey,
		&i.ParameterValue,
		&i.Severity,
		&i.RiskScoreWeight,
		&i.IsBlocking,
		&i.IsActive,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveUnderwritingRulesByPlan = `-- name: ListActiveUnderwritingRulesByPlan :many
SELECT id, plan_id, rule_type, relationship, parameter_key, parameter_value, severity, risk_score_weight, is_blocking, is_active, description, created_at, updated_at FROM underwriting_rules WHERE plan_id = $1 AND is_active = true ORDER BY rule_type
`

func (q *Queries) ListActiveUnderwritingRulesByPlan(ctx context.Context, planID uuid.UUID) ([]UnderwritingRule, error) {
	rows, err := q.db.Query(ctx, listActiveUnderwritingRulesByPlan, planID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UnderwritingRule{}
	for rows.Next() {
		var i UnderwritingRule
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.RuleType,
			&i.Relationship,
			&i.ParameterKey,
			&i.ParameterValue,
			&i.Severity,
			&i.RiskScoreWeight,
			&i.IsBlocking,
			&i.IsActive,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnderwritingRulesByPlan = `-- name: ListUnderwritingRulesByPlan :many
SELECT id, plan_id, rule_type, relationship, parameter_key, parameter_value, severity, risk_score_weight, is_blocking, is_active, description, created_at, updated_at FROM underwriting_rules WHERE plan_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListUnderwritingRulesByPlan(ctx context.Context, planID uuid.UUID) ([]UnderwritingRule, error) {
	rows, err := q.db.Query(ctx, listUnderwritingRulesByPlan, planID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UnderwritingRule{}
	for rows.Next() {
		var i UnderwritingRule
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.RuleType,
			&i.Relationship,
			&i.ParameterKey,
			&i.ParameterValue,
			&i.Severity,
			&i.RiskScoreWeight,
			&i.IsBlocking,
			&i.IsActive,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUnderwritingRule = `-- name: UpdateUnderwritingRule :one
UPDATE underwriting_rules SET
    rule_type = COALESCE($1, rule_type),
    relationship = COALESCE($2, relationship),
    parameter_key = COALESCE($3, parameter_key),
    parameter_value = COALESCE($4, parameter_value),
    severity = COALESCE($5, severity),
    risk_score_weight = COALESCE($6, risk_score_weight),
    is_blocking = COALESCE($7, is_blocking),
    is_active = COALESCE($8, is_active),
    description = COALESCE($9, description),
    updated_at = NOW()
WHERE id = $10 RETURNING id, plan_id, rule_type, relationship, parameter_key, parameter_value, severity, risk_score_weight, is_blocking, is_active, description, created_at, updated_at
`

type UpdateUnderwritingRuleParams struct {
	RuleType        pgtype.Text `json:"rule_type"`
	Relationship    pgtype.Text `json:"relationship"`
	ParameterKey    pgtype.Text `json:"parameter_key"`
	ParameterValue  pgtype.Text `json:"parameter_value"`
	Severity        pgtype.Text `json:"severity"`
	RiskScoreWeight pgtype.Int4 `json:"risk_score_weight"`
	IsBlocking      pgtype.Bool `json:"is_blocking"`
	IsActive        pgtype.Bool `json:"is_active"`
	Description     pgtype.Text `json:"description"`
	ID              uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateUnderwritingRule(ctx context.Context, arg UpdateUnderwritingRuleParams) (UnderwritingRule, error) {
	row := q.db.QueryRow(ctx, updateUnderwritingRule,
		arg.RuleType,
		arg.Relationship,
		arg.ParameterKey,
		arg.ParameterValue,
		arg.Severity,
		arg.RiskScoreWeight,
		arg.IsBlocking,
		arg.IsActive,
		arg.Description,
		arg.ID,
	)
	var i UnderwritingRule
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.RuleType,
		&i.Relationship,
		&i.ParameterKey,
		&i.ParameterValue,
		&i.Severity,
		&i.RiskScoreWeight,
		&i.IsBlocking,
		&i.IsActive,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
