// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: underwriting_flag.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countOpenUnderwritingFlags = `-- name: CountOpenUnderwritingFlags :one
SELECT COUNT(*) FROM underwriting_flags WHERE status = 'OPEN'
`

func (q *Queries) CountOpenUnderwritingFlags(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenUnderwritingFlags)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUnderwritingFlag = `-- name: CreateUnderwritingFlag :one
INSERT INTO underwriting_flags (assessment_id, policy_id, member_id, flag_type, severity, details, status)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, assessment_id, policy_id, member_id, flag_type, severity, details, status, resolved_by, resolved_at, resolution, created_at, updated_at
`

type CreateUnderwritingFlagParams struct {
	AssessmentID pgtype.UUID `json:"assessment_id"`
	PolicyID     uuid.UUID   `json:"policy_id"`
	MemberID     pgtype.UUID `json:"member_id"`
	FlagType     string      `json:"flag_type"`
	Severity     string      `json:"severity"`
	Details      string      `json:"details"`
	Status       string      `json:"status"`
}

func (q *Queries) CreateUnderwritingFlag(ctx context.Context, arg CreateUnderwritingFlagParams) (UnderwritingFlag, error) {
	row := q.db.QueryRow(ctx, createUnderwritingFlag,
		arg.AssessmentID,
		arg.PolicyID,
		arg.MemberID,
		arg.FlagType,
		arg.Severity,
		arg.Details,
		arg.Status,
	)
	var i UnderwritingFlag
	err := row.Scan(
		&i.ID,
		&i.AssessmentID,
		&i.PolicyID,
		&i.MemberID,
		&i.FlagType,
		&i.Severity,
		&i.Details,
		&i.Status,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.Resolution,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUnderwritingFlagByID = `-- name: GetUnderwritingFlagByID :one
SELECT id, assessment_id, policy_id, member_id, flag_type, severity, details, status, resolved_by, resolved_at, resolution, created_at, updated_at FROM underwriting_flags WHERE id = $1
`

func (q *Queries) GetUnderwritingFlagByID(ctx context.Context, id uuid.UUID) (UnderwritingFlag, error) {
	row := q.db.QueryRow(ctx, getUnderwritingFlagByID, id)
	var i UnderwritingFlag
	err := row.Scan(
		&i.ID,
		&i.AssessmentID,
		&i.PolicyID,
		&i.MemberID,
		&i.FlagType,
		&i.Severity,
		&i.Details,
		&i.Status,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.Resolution,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOpenUnderwritingFlags = `-- name: ListOpenUnderwritingFlags :many
SELECT id, assessment_id, policy_id, member_id, flag_type, severity, details, status, resolved_by, resolved_at, resolution, created_at, updated_at FROM underwriting_flags WHERE status = 'OPEN' ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListOpenUnderwritingFlagsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListOpenUnderwritingFlags(ctx context.Context, arg ListOpenUnderwritingFlagsParams) ([]UnderwritingFlag, error) {
	rows, err := q.db.Query(ctx, listOpenUnderwritingFlags, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UnderwritingFlag{}
	for rows.Next() {
		var i UnderwritingFlag
		if err := rows.Scan(
			&i.ID,
			&i.AssessmentID,
			&i.PolicyID,
			&i.MemberID,
			&i.FlagType,
			&i.Severity,
			&i.Details,
			&i.Status,
			&i.ResolvedBy,
			&i.ResolvedAt,
			&i.Resolution,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnderwritingFlagsByAssessment = `-- name: ListUnderwritingFlagsByAssessment :many
SELECT id, assessment_id, policy_id, member_id, flag_type, severity, details, status, resolved_by, resolved_at, resolution, created_at, updated_at FROM underwriting_flags WHERE assessment_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListUnderwritingFlagsByAssessment(ctx context.Context, assessmentID pgtype.UUID) ([]UnderwritingFlag, error) {
	rows, err := q.db.Query(ctx, listUnderwritingFlagsByAssessment, assessmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UnderwritingFlag{}
	for rows.Next() {
		var i UnderwritingFlag
		if err := rows.Scan(
			&i.ID,
			&i.AssessmentID,
			&i.PolicyID,
			&i.MemberID,
			&i.FlagType,
			&i.Severity,
			&i.Details,
			&i.Status,
			&i.ResolvedBy,
			&i.ResolvedAt,
			&i.Resolution,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnderwritingFlagsByMember = `-- name: ListUnderwritingFlagsByMember :many
SELECT id, assessment_id, policy_id, member_id, flag_type, severity, details, status, resolved_by, resolved_at, resolution, created_at, updated_at FROM underwriting_flags WHERE member_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListUnderwritingFlagsByMember(ctx context.Context, memberID pgtype.UUID) ([]UnderwritingFlag, error) {
	rows, err := q.db.Query(ctx, listUnderwritingFlagsByMember, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UnderwritingFlag{}
	for rows.Next() {
		var i UnderwritingFlag
		if err := rows.Scan(
			&i.ID,
			&i.AssessmentID,
			&i.PolicyID,
			&i.MemberID,
			&i.FlagType,
			&i.Severity,
			&i.Details,
			&i.Status,
			&i.ResolvedBy,
			&i.ResolvedAt,
			&i.Resolution,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnderwritingFlagsByPolicy = `-- name: ListUnderwritingFlagsByPolicy :many
SELECT id, assessment_id, policy_id, member_id, flag_type, severity, details, status, resolved_by, resolved_at, resolution, created_at, updated_at FROM underwriting_flags WHERE policy_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListUnderwritingFlagsByPolicy(ctx context.Context, policyID uuid.UUID) ([]UnderwritingFlag, error) {
	rows, err := q.db.Query(ctx, listUnderwritingFlagsByPolicy, policyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UnderwritingFlag{}
	for rows.Next() {
		var i UnderwritingFlag
		if err := rows.Scan(
			&i.ID,
			&i.AssessmentID,
			&i.PolicyID,
			&i.MemberID,
			&i.FlagType,
			&i.Severity,
			&i.Details,
			&i.Status,
			&i.ResolvedBy,
			&i.ResolvedAt,
			&i.Resolution,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const overrideUnderwritingFlag = `-- name: OverrideUnderwritingFlag :one
UPDATE underwriting_flags SET
    status = 'OVERRIDDEN',
    resolved_by = $1,
    resolved_at = NOW(),
    resolution = $2,
    updated_at = NOW()
WHERE id = $3 RETURNING id, assessment_id, policy_id, member_id, flag_type, severity, details, status, resolved_by, resolved_at, resolution, created_at, updated_at
`

type OverrideUnderwritingFlagParams struct {
	ResolvedBy pgtype.UUID `json:"resolved_by"`
	Resolution pgtype.Text `json:"resolution"`
	ID         uuid.UUID   `json:"id"`
}

func (q *Queries) OverrideUnderwritingFlag(ctx context.Context, arg OverrideUnderwritingFlagParams) (UnderwritingFlag, error) {
	row := q.db.QueryRow(ctx, overrideUnderwritingFlag, arg.ResolvedBy, arg.Resolution, arg.ID)
	var i UnderwritingFlag
	err := row.Scan(
		&i.ID,
		&i.AssessmentID,
		&i.PolicyID,
		&i.MemberID,
		&i.FlagType,
		&i.Severity,
		&i.Details,
		&i.Status,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.Resolution,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resolveUnderwritingFlag = `-- name: ResolveUnderwritingFlag :one
UPDATE underwriting_flags SET
    status = 'RESOLVED',
    resolved_by = $1,
    resolved_at = NOW(),
    resolution = $2,
    updated_at = NOW()
WHERE id = $3 RETURNING id, assessment_id, policy_id, member_id, flag_type, severity, details, status, resolved_by, resolved_at, resolution, created_at, updated_at
`

type ResolveUnderwritingFlagParams struct {
	ResolvedBy pgtype.UUID `json:"resolved_by"`
	Resolution pgtype.Text `json:"resolution"`
	ID         uuid.UUID   `json:"id"`
}

func (q *Queries) ResolveUnderwritingFlag(ctx context.Context, arg ResolveUnderwritingFlagParams) (UnderwritingFlag, error) {
	row := q.db.QueryRow(ctx, resolveUnderwritingFlag, arg.ResolvedBy, arg.Resolution, arg.ID)
	var i UnderwritingFlag
	err := row.Scan(
		&i.ID,
		&i.AssessmentID,
		&i.PolicyID,
		&i.MemberID,
		&i.FlagType,
		&i.Severity,
		&i.Details,
		&i.Status,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.Resolution,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
