// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: underwriting_assessment.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUnderwritingAssessment = `-- name: CreateUnderwritingAssessment :one
INSERT INTO underwriting_assessments (policy_id, member_id, status, questionnaire, medical_declarations, created_by)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, policy_id, member_id, status, questionnaire, medical_declarations, risk_score, risk_flags, decision_reason, assessed_by, assessed_at, created_by, created_at, updated_at
`

type CreateUnderwritingAssessmentParams struct {
	PolicyID            uuid.UUID       `json:"policy_id"`
	MemberID            pgtype.UUID     `json:"member_id"`
	Status              string          `json:"status"`
	Questionnaire       json.RawMessage `json:"questionnaire"`
	MedicalDeclarations []byte          `json:"medical_declarations"`
	CreatedBy           uuid.UUID       `json:"created_by"`
}

func (q *Queries) CreateUnderwritingAssessment(ctx context.Context, arg CreateUnderwritingAssessmentParams) (UnderwritingAssessment, error) {
	row := q.db.QueryRow(ctx, createUnderwritingAssessment,
		arg.PolicyID,
		arg.MemberID,
		arg.Status,
		arg.Questionnaire,
		arg.MedicalDeclarations,
		arg.CreatedBy,
	)
	var i UnderwritingAssessment
	err := row.Scan(
		&i.ID,
		&i.PolicyID,
		&i.MemberID,
		&i.Status,
		&i.Questionnaire,
		&i.MedicalDeclarations,
		&i.RiskScore,
		&i.RiskFlags,
		&i.DecisionReason,
		&i.AssessedBy,
		&i.AssessedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUnderwritingByID = `-- name: GetUnderwritingByID :one
SELECT ua.id, ua.policy_id, ua.member_id, ua.status, ua.questionnaire, ua.medical_declarations, ua.risk_score, ua.risk_flags, ua.decision_reason, ua.assessed_by, ua.assessed_at, ua.created_by, ua.created_at, ua.updated_at, COALESCE(u.name, '') AS assessed_by_name
FROM underwriting_assessments ua
LEFT JOIN users u ON u.id = ua.assessed_by
WHERE ua.id = $1
`

type GetUnderwritingByIDRow struct {
	ID                  uuid.UUID          `json:"id"`
	PolicyID            uuid.UUID          `json:"policy_id"`
	MemberID            pgtype.UUID        `json:"member_id"`
	Status              string             `json:"status"`
	Questionnaire       json.RawMessage    `json:"questionnaire"`
	MedicalDeclarations []byte             `json:"medical_declarations"`
	RiskScore           pgtype.Int4        `json:"risk_score"`
	RiskFlags           []byte             `json:"risk_flags"`
	DecisionReason      pgtype.Text        `json:"decision_reason"`
	AssessedBy          pgtype.UUID        `json:"assessed_by"`
	AssessedAt          pgtype.Timestamptz `json:"assessed_at"`
	CreatedBy           uuid.UUID          `json:"created_by"`
	CreatedAt           time.Time          `json:"created_at"`
	UpdatedAt           time.Time          `json:"updated_at"`
	AssessedByName      string             `json:"assessed_by_name"`
}

func (q *Queries) GetUnderwritingByID(ctx context.Context, id uuid.UUID) (GetUnderwritingByIDRow, error) {
	row := q.db.QueryRow(ctx, getUnderwritingByID, id)
	var i GetUnderwritingByIDRow
	err := row.Scan(
		&i.ID,
		&i.PolicyID,
		&i.MemberID,
		&i.Status,
		&i.Questionnaire,
		&i.MedicalDeclarations,
		&i.RiskScore,
		&i.RiskFlags,
		&i.DecisionReason,
		&i.AssessedBy,
		&i.AssessedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AssessedByName,
	)
	return i, err
}

const getUnderwritingByMember = `-- name: GetUnderwritingByMember :one
SELECT ua.id, ua.policy_id, ua.member_id, ua.status, ua.questionnaire, ua.medical_declarations, ua.risk_score, ua.risk_flags, ua.decision_reason, ua.assessed_by, ua.assessed_at, ua.created_by, ua.created_at, ua.updated_at, COALESCE(u.name, '') AS assessed_by_name
FROM underwriting_assessments ua
LEFT JOIN users u ON u.id = ua.assessed_by
WHERE ua.member_id = $1 ORDER BY ua.created_at DESC LIMIT 1
`

type GetUnderwritingByMemberRow struct {
	ID                  uuid.UUID          `json:"id"`
	PolicyID            uuid.UUID          `json:"policy_id"`
	MemberID            pgtype.UUID        `json:"member_id"`
	Status              string             `json:"status"`
	Questionnaire       json.RawMessage    `json:"questionnaire"`
	MedicalDeclarations []byte             `json:"medical_declarations"`
	RiskScore           pgtype.Int4        `json:"risk_score"`
	RiskFlags           []byte             `json:"risk_flags"`
	DecisionReason      pgtype.Text        `json:"decision_reason"`
	AssessedBy          pgtype.UUID        `json:"assessed_by"`
	AssessedAt          pgtype.Timestamptz `json:"assessed_at"`
	CreatedBy           uuid.UUID          `json:"created_by"`
	CreatedAt           time.Time          `json:"created_at"`
	UpdatedAt           time.Time          `json:"updated_at"`
	AssessedByName      string             `json:"assessed_by_name"`
}

func (q *Queries) GetUnderwritingByMember(ctx context.Context, memberID pgtype.UUID) (GetUnderwritingByMemberRow, error) {
	row := q.db.QueryRow(ctx, getUnderwritingByMember, memberID)
	var i GetUnderwritingByMemberRow
	err := row.Scan(
		&i.ID,
		&i.PolicyID,
		&i.MemberID,
		&i.Status,
		&i.Questionnaire,
		&i.MedicalDeclarations,
		&i.RiskScore,
		&i.RiskFlags,
		&i.DecisionReason,
		&i.AssessedBy,
		&i.AssessedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AssessedByName,
	)
	return i, err
}

const listUnderwritingByPolicy = `-- name: ListUnderwritingByPolicy :many
SELECT ua.id, ua.policy_id, ua.member_id, ua.status, ua.questionnaire, ua.medical_declarations, ua.risk_score, ua.risk_flags, ua.decision_reason, ua.assessed_by, ua.assessed_at, ua.created_by, ua.created_at, ua.updated_at, COALESCE(u.name, '') AS assessed_by_name
FROM underwriting_assessments ua
LEFT JOIN users u ON u.id = ua.assessed_by
WHERE ua.policy_id = $1 ORDER BY ua.created_at DESC
`

type ListUnderwritingByPolicyRow struct {
	ID                  uuid.UUID          `json:"id"`
	PolicyID            uuid.UUID          `json:"policy_id"`
	MemberID            pgtype.UUID        `json:"member_id"`
	Status              string             `json:"status"`
	Questionnaire       json.RawMessage    `json:"questionnaire"`
	MedicalDeclarations []byte             `json:"medical_declarations"`
	RiskScore           pgtype.Int4        `json:"risk_score"`
	RiskFlags           []byte             `json:"risk_flags"`
	DecisionReason      pgtype.Text        `json:"decision_reason"`
	AssessedBy          pgtype.UUID        `json:"assessed_by"`
	AssessedAt          pgtype.Timestamptz `json:"assessed_at"`
	CreatedBy           uuid.UUID          `json:"created_by"`
	CreatedAt           time.Time          `json:"created_at"`
	UpdatedAt           time.Time          `json:"updated_at"`
	AssessedByName      string             `json:"assessed_by_name"`
}

func (q *Queries) ListUnderwritingByPolicy(ctx context.Context, policyID uuid.UUID) ([]ListUnderwritingByPolicyRow, error) {
	rows, err := q.db.Query(ctx, listUnderwritingByPolicy, policyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnderwritingByPolicyRow{}
	for rows.Next() {
		var i ListUnderwritingByPolicyRow
		if err := rows.Scan(
			&i.ID,
			&i.PolicyID,
			&i.MemberID,
			&i.Status,
			&i.Questionnaire,
			&i.MedicalDeclarations,
			&i.RiskScore,
			&i.RiskFlags,
			&i.DecisionReason,
			&i.AssessedBy,
			&i.AssessedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AssessedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUnderwriting = `-- name: UpdateUnderwriting :one
UPDATE underwriting_assessments SET
    status = COALESCE($1, status),
    risk_score = COALESCE($2, risk_score),
    risk_flags = COALESCE($3, risk_flags),
    decision_reason = COALESCE($4, decision_reason),
    assessed_by = COALESCE($5, assessed_by),
    assessed_at = COALESCE($6, assessed_at),
    updated_at = NOW()
WHERE id = $7 RETURNING id, policy_id, member_id, status, questionnaire, medical_declarations, risk_score, risk_flags, decision_reason, assessed_by, assessed_at, created_by, created_at, updated_at
`

type UpdateUnderwritingParams struct {
	Status         pgtype.Text        `json:"status"`
	RiskScore      pgtype.Int4        `json:"risk_score"`
	RiskFlags      []byte             `json:"risk_flags"`
	DecisionReason pgtype.Text        `json:"decision_reason"`
	AssessedBy     pgtype.UUID        `json:"assessed_by"`
	AssessedAt     pgtype.Timestamptz `json:"assessed_at"`
	ID             uuid.UUID          `json:"id"`
}

func (q *Queries) UpdateUnderwriting(ctx context.Context, arg UpdateUnderwritingParams) (UnderwritingAssessment, error) {
	row := q.db.QueryRow(ctx, updateUnderwriting,
		arg.Status,
		arg.RiskScore,
		arg.RiskFlags,
		arg.DecisionReason,
		arg.AssessedBy,
		arg.AssessedAt,
		arg.ID,
	)
	var i UnderwritingAssessment
	err := row.Scan(
		&i.ID,
		&i.PolicyID,
		&i.MemberID,
		&i.Status,
		&i.Questionnaire,
		&i.MedicalDeclarations,
		&i.RiskScore,
		&i.RiskFlags,
		&i.DecisionReason,
		&i.AssessedBy,
		&i.AssessedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUnderwritingStatus = `-- name: UpdateUnderwritingStatus :one
UPDATE underwriting_assessments SET status = $2, updated_at = NOW() WHERE id = $1 RETURNING id, policy_id, member_id, status, questionnaire, medical_declarations, risk_score, risk_flags, decision_reason, assessed_by, assessed_at, created_by, created_at, updated_at
`

type UpdateUnderwritingStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateUnderwritingStatus(ctx context.Context, arg UpdateUnderwritingStatusParams) (UnderwritingAssessment, error) {
	row := q.db.QueryRow(ctx, updateUnderwritingStatus, arg.ID, arg.Status)
	var i UnderwritingAssessment
	err := row.Scan(
		&i.ID,
		&i.PolicyID,
		&i.MemberID,
		&i.Status,
		&i.Questionnaire,
		&i.MedicalDeclarations,
		&i.RiskScore,
		&i.RiskFlags,
		&i.DecisionReason,
		&i.AssessedBy,
		&i.AssessedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
