// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: user.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (cognito_sub, email, name, phone, national_id, role_id, status, created_by, password_hash)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING id, cognito_sub, email, name, phone, national_id, role_id, status, created_by, created_at, updated_at, password_hash
`

type CreateUserParams struct {
	CognitoSub   pgtype.Text `json:"cognito_sub"`
	Email        string      `json:"email"`
	Name         string      `json:"name"`
	Phone        pgtype.Text `json:"phone"`
	NationalID   pgtype.Text `json:"national_id"`
	RoleID       uuid.UUID   `json:"role_id"`
	Status       string      `json:"status"`
	CreatedBy    pgtype.UUID `json:"created_by"`
	PasswordHash string      `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.CognitoSub,
		arg.Email,
		arg.Name,
		arg.Phone,
		arg.NationalID,
		arg.RoleID,
		arg.Status,
		arg.CreatedBy,
		arg.PasswordHash,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CognitoSub,
		&i.Email,
		&i.Name,
		&i.Phone,
		&i.NationalID,
		&i.RoleID,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
	)
	return i, err
}

const getUserByCognitoSub = `-- name: GetUserByCognitoSub :one
SELECT id, cognito_sub, email, name, phone, national_id, role_id, status, created_by, created_at, updated_at, password_hash FROM users WHERE cognito_sub = $1
`

func (q *Queries) GetUserByCognitoSub(ctx context.Context, cognitoSub pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByCognitoSub, cognitoSub)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CognitoSub,
		&i.Email,
		&i.Name,
		&i.Phone,
		&i.NationalID,
		&i.RoleID,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, cognito_sub, email, name, phone, national_id, role_id, status, created_by, created_at, updated_at, password_hash FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CognitoSub,
		&i.Email,
		&i.Name,
		&i.Phone,
		&i.NationalID,
		&i.RoleID,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, cognito_sub, email, name, phone, national_id, role_id, status, created_by, created_at, updated_at, password_hash FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CognitoSub,
		&i.Email,
		&i.Name,
		&i.Phone,
		&i.NationalID,
		&i.RoleID,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
	)
	return i, err
}

const getUserByNationalID = `-- name: GetUserByNationalID :one
SELECT id, cognito_sub, email, name, phone, national_id, role_id, status, created_by, created_at, updated_at, password_hash FROM users WHERE national_id = $1
`

func (q *Queries) GetUserByNationalID(ctx context.Context, nationalID pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByNationalID, nationalID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CognitoSub,
		&i.Email,
		&i.Name,
		&i.Phone,
		&i.NationalID,
		&i.RoleID,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, cognito_sub, email, name, phone, national_id, role_id, status, created_by, created_at, updated_at, password_hash FROM users ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.CognitoSub,
			&i.Email,
			&i.Name,
			&i.Phone,
			&i.NationalID,
			&i.RoleID,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PasswordHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET
    name = COALESCE($1, name),
    phone = COALESCE($2, phone),
    national_id = COALESCE($3, national_id),
    updated_at = NOW()
WHERE id = $4 RETURNING id, cognito_sub, email, name, phone, national_id, role_id, status, created_by, created_at, updated_at, password_hash
`

type UpdateUserParams struct {
	Name       pgtype.Text `json:"name"`
	Phone      pgtype.Text `json:"phone"`
	NationalID pgtype.Text `json:"national_id"`
	ID         uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Name,
		arg.Phone,
		arg.NationalID,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CognitoSub,
		&i.Email,
		&i.Name,
		&i.Phone,
		&i.NationalID,
		&i.RoleID,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
	)
	return i, err
}

const updateUserCognitoSub = `-- name: UpdateUserCognitoSub :one
UPDATE users SET cognito_sub = $2, updated_at = NOW() WHERE id = $1 RETURNING id, cognito_sub, email, name, phone, national_id, role_id, status, created_by, created_at, updated_at, password_hash
`

type UpdateUserCognitoSubParams struct {
	ID         uuid.UUID   `json:"id"`
	CognitoSub pgtype.Text `json:"cognito_sub"`
}

func (q *Queries) UpdateUserCognitoSub(ctx context.Context, arg UpdateUserCognitoSubParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserCognitoSub, arg.ID, arg.CognitoSub)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CognitoSub,
		&i.Email,
		&i.Name,
		&i.Phone,
		&i.NationalID,
		&i.RoleID,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = $2, updated_at = NOW() WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUserRole = `-- name: UpdateUserRole :one
UPDATE users SET role_id = $2, updated_at = NOW() WHERE id = $1 RETURNING id, cognito_sub, email, name, phone, national_id, role_id, status, created_by, created_at, updated_at, password_hash
`

type UpdateUserRoleParams struct {
	ID     uuid.UUID `json:"id"`
	RoleID uuid.UUID `json:"role_id"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserRole, arg.ID, arg.RoleID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CognitoSub,
		&i.Email,
		&i.Name,
		&i.Phone,
		&i.NationalID,
		&i.RoleID,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
	)
	return i, err
}

const updateUserStatus = `-- name: UpdateUserStatus :one
UPDATE users SET status = $2, updated_at = NOW() WHERE id = $1 RETURNING id, cognito_sub, email, name, phone, national_id, role_id, status, created_by, created_at, updated_at, password_hash
`

type UpdateUserStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserStatus, arg.ID, arg.Status)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CognitoSub,
		&i.Email,
		&i.Name,
		&i.Phone,
		&i.NationalID,
		&i.RoleID,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
	)
	return i, err
}
